---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: 在設定Cisco Nexus 3232c 交換器之前，請先查看流程概述和命名規則。 
---
= 遷移要求
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 交換器可作為AFF或FAS叢集中的叢集交換器。叢集交換器可讓您建立具有兩個以上節點的ONTAP叢集。


NOTE: 流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

如有需要，請參考以下內容以了解更多資訊：

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== CN1610遷移要求

叢集交換器支援以下節點連線：

* NetApp CN1610：連接埠 0/1 至 0/12 (10 GbE)
* Cisco Nexus 3232C：連接埠 e1/1-30（40 或 100 或 4x10GbE）


叢集交換器使用下列交換器間連結 (ISL) 連接埠。

* NetApp CN1610：連接埠 0/13 至 0/16 (10 GbE)
* Cisco Nexus 3232C：連接埠 1/31-32 (100GbE)


[NOTE]
====
在Cisco Nexus 3232C 叢集交換器上必須使用 4x10G 分支電纜。

====
下表顯示了從NetApp CN1610 交換器過渡到Cisco Nexus 3232C 叢集交換器時，每個階段所需的佈線連接：

|===
| 階段 | 描述 | 所需電纜 


 a| 
最初的
 a| 
CN1610 至 CN1610（SFP+ 至 SFP+）
 a| 
4條SFP+光纖或銅纜直連電纜



 a| 
過渡
 a| 
CN1610 至 3232C（QSFP 至 SFP+）
 a| 
1條QSFP和4條SFP+光纖或銅纜分支電纜



 a| 
最終的
 a| 
3232C 至 3232C（QSFP 至 QSFP）
 a| 
2條QSFP光纖或銅纜直連電纜

|===
您必須已下載適用的參考設定檔（RCF）。  10 GbE 和 40/100 GbE 連接埠的數量在可用的 RCF 中定義。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集網路交換器參考設定檔下載"^] 。

此流程支援的ONTAP和 NX-OS 版本列於此。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 。

此流程支援的ONTAP和 FASTPATH 版本列於此處link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 交換機"^]。

.關於所使用的範例
遷移過程中的範例使用了四個節點：

* 兩個節點使用四個 10 GbE 叢集互連連接埠：*e0a*、*e0b*、*e0c* 和 *e0d*。
* 另外兩個節點使用兩條 40 GbE 群集互連光纖電纜：*e4a* 和 *e4e*。
+
這link:https://hwu.netapp.com/["硬體宇宙"^]包含您平台集群光纖電纜的資訊。



本流程中的範例使用以下開關和節點命名規則：

* 這些節點是 *n1*、*n2*、*n3* 和 *n4*。
* 命令輸出可能因ONTAP軟體版本不同而有所差異。
* 需要更換的 CN1610 交換器是 *CL1* 和 *CL2*。
* 用來取代 CN1610 交換器的 Nexus 3232C 交換器是 *C1* 和 *C2*。
* *n1_clus1* 是連接到節點 *n1* 的叢集交換器 1 (CL1 或 C1) 的第一個叢集邏輯介面 (LIF)。
* *n1_clus2* 是連接到節點 *n1* 的叢集交換器 2 (CL2 或 C2) 的第一個叢集 LIF。
* *n1_clus3* 是連接到節點 *n1* 的叢集交換器 2 (CL2 或 C2) 的第二個 LIF。
* *n1_clus4* 是連接到節點 *n1* 的叢集交換器 1 (CL1 或 C1) 的第二個 LIF。
* 10 GbE 和 40/100 GbE 連接埠的數量在參考設定檔 (RCF) 中定義，這些檔案可在以下網址取得：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集網路交換器參考設定檔下載"^] 。


.下一步是什麼？
link:cn1610-prepare-to-migrate.html["做好遷移準備"]。
