---
permalink: switch-cisco-3232c/cn1610-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 您可以在AFF或FAS叢集中使用Cisco Nexus 3232C 交換器作為叢集交換器。 
---
= 準備從 CN1610 交換器遷移到 3232C 交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟準備將 CN1610 交換器遷移到Cisco Nexus 3232C 交換器。

.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
此訊息通知技術支援部門此維護任務，以便在維護期間禁止自動建立案例。

====
. 顯示配置中設備的資訊：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了每個節點上每個叢集互連交換器配置的叢集互連連接口數量：

[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*

       Local  Discovered
Node   Port   Device       Interface   Platform
------ ------ ------------ ----------- ----------
n1     /cdp
        e0a   CL1          0/1         CN1610
        e0b   CL2          0/1         CN1610
        e0c   CL2          0/2         CN1610
        e0d   CL1          0/2         CN1610
n2     /cdp
        e0a   CL1          0/3         CN1610
        e0b   CL2          0/3         CN1610
        e0c   CL2          0/4         CN1610
        e0d   CL1          0/4         CN1610

8 entries were displayed.
----
====
. 確定每個叢集介面的管理或運作狀態。
+
.. 顯示集群網路連接埠屬性：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status Health Status
----- --------- ---------- ----- ----- ------------ ------ -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -
Node: n2
                Broadcast              Speed (Mbps) Health Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status Health Status
----- --------- ---------- ----- ----- ------------ ------ -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -

8 entries were displayed.
----
====
.. 顯示邏輯介面資訊：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

 8 entries were displayed.
----
====
.. 顯示已發現的群集交換器的相關資訊：
+
`system cluster-switch show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集已知的叢集交換器及其管理 IP 位址：

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP
CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP

2	entries displayed.
----
====


. 確認已根據您的要求在新 3232C 交換器上安裝了相應的 RCF 和映像，並進行任何必要的網站自訂。
+
此時您應該準備好這兩台交換器。如果需要升級 RCF 和鏡像，則必須完成以下步驟：

+
.. 看link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]在NetApp支援網站上。
.. 請記下您交換器的型號以及該頁表格中所需的軟體版本。
.. 下載相應版本的RCF。
.. 在“描述”頁面上選擇“繼續”，接受許可協議，然後按照“下載”頁面上的說明下載 RCF。
.. 請從以下網址下載對應版本的影像處理軟體：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集和管理網路交換器參考設定檔下載"^] 。


. 遷移與計畫替換的第二個 CN1610 交換器關聯的 LIF：
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_ destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須按照以下範例所示，逐一遷移每個 LIF：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node  n1  -destination-port  e0a*
cluster::*> *network interface migrate -vserver cluster -lif n1_clus3 -source-node n1
-destination-node  n1  -destination-port  e0d*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node  n2  -destination-port  e0a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus3 -source-node n2
-destination-node  n2  -destination-port  e0d*
----
====
. 驗證集群健康狀況：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network         Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask    Node     Port     Home
-------- ---------- ----------- --------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24    n1        e0a     true
         n1_clus2   up/up       10.10.0.2/24    n1        e0a     false
         n1_clus3   up/up       10.10.0.3/24    n1        e0d     false
         n1_clus4   up/up       10.10.0.4/24    n1        e0d     true
         n2_clus1   up/up       10.10.0.5/24    n2        e0a     true
         n2_clus2   up/up       10.10.0.6/24    n2        e0a     false
         n2_clus3   up/up       10.10.0.7/24    n2        e0d     false
         n2_clus4   up/up       10.10.0.8/24    n2        e0d     true

8 entries were displayed.
----
====


.下一步是什麼？
link:cn1610-replace-CL2.html["將 CN1610 交換器 CL2 更換為 3232C 交換器 C2"]。
