---
permalink: switch-cisco-3232c/install-upgrade-rcf-overview-3232c.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: '使用群集交換器健康監視器 (CSHM) 和日誌收集功能時需要 SSH。若要在Cisco 3232c 叢集交換器上啟用 SSH，您需要先生成 SSH 金鑰，然後啟用 SSH。' 
---
= 安裝或升級參考設定檔 (RCF) 概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次設定 Nexus 3232C 交換器後，安裝參考設定檔 (RCF)。當您的交換器上安裝了現有版本的 RCF 檔案時，您可以升級您的 RCF 版本。

請參閱知識庫文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除Cisco互連交換器上的配置"^]安裝或升級 RCF 時，有關更多信息，請參閱以下內容。

.可用的 RCF 配置
下表描述了不同配置可用的 RCF。選擇適用於您配置的 RCF。

有關具體連接埠和 VLAN 使用詳情，請參閱 RCF 中的橫幅和重要說明部分。

[cols="1,2"]
|===
| RCF 名稱 | 描述 


 a| 
2-集群-HA-突破
 a| 
支援至少八個節點的兩個ONTAP集群，包括使用共享 Cluster+HA 連接埠的節點。



 a| 
4-集群-HA-突破
 a| 
支援至少四個節點的四個ONTAP集群，包括使用共享 Cluster+HA 連接埠的節點。



 a| 
1-集群-HA
 a| 
所有連接埠均配置為 40/100GbE。支援連接埠上的共用叢集/高可用性流量。 AFF A320、 AFF A250和FAS500f系統需要此組件。此外，所有連接埠均可用作專用叢集連接埠。



 a| 
1-集群-HA-突破
 a| 
連接埠配置為 4x10GbE 分支、4x25GbE 分支（100GbE 交換器上的 RCF 1.6+）和 40/100GbE。支援使用共享叢集/HA連接埠的節點在連接埠上共用叢集/HA流量： AFF A320、 AFF A250和FAS500f系統。此外，所有連接埠均可用作專用叢集連接埠。



 a| 
叢集高可用性存儲
 a| 
連接埠配置為：叢集+HA 40/100GbE，叢集 4x10GbE 分支，叢集+HA 4x25GbE 分支，以及每個儲存 HA 對 100GbE。



 a| 
簇
 a| 
兩種 RCF 版本，分別分配了不同的 4x10GbE 連接埠（分支）和 40/100GbE 連接埠。除了AFF A320、 AFF A250和FAS500f系統之外，所有FAS/ AFF節點均受支援。



 a| 
儲存
 a| 
所有連接埠均配置為 100GbE NVMe 儲存連線。

|===
.建議的文檔
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換器（NSS）"^]
+
請參閱NetApp支援網站上的交換器相容性表格，以了解支援的ONTAP和 RCF 版本。請注意，RCF 中的命令語法與特定版本的 NX-OS 中的語法之間可能存在命令依賴關係。

* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["CiscoNexus 3000 系列交換機"^]
+
有關Cisco交換器升級和降級程序的完整文檔，請參閱Cisco網站上提供的相應軟體和升級指南。



.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩個Cisco交換器的名稱分別是 *cs1* 和 *cs2*。
* 節點名稱分別為 *cluster1-01*、*cluster1-02*、*cluster1-03* 和 *cluster1-04*。
* 群集 LIF 名稱稱為 *cluster1-01_clus1*、*cluster1-01_clus2*、*cluster1-02_clus1*、*cluster1-02_clus2*、*cluster1-03_clus1*、*cluster1-03_clus2*、*cluster1-03_clus1*、*cluster1-03_clus2*、*cluster1-03_clus1*、*cluster1-03_clus2*、*cluster1-03_clus1*、*cluster1-03_clus2*、*cluster1-03_clus1*、*cluster1-03_clus2*、*cluster1-04_cluster12
* 這 `cluster1::*>`prompt 指示叢集名稱。


本流程中的範例使用了四個節點。這些節點使用兩個 10GbE 叢集互連連接埠 *e0a* 和 *e0b*。參見 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]請確認您的平台上叢集連接埠是否正確。


NOTE: 命令輸出可能因ONTAP版本不同而有所差異。

有關可用 RCF 配置的詳細信息，請參閱link:configure-software-overview-3232c-cluster.html["軟體安裝工作流程"]。

.使用的命令
流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

.下一步是什麼？
在您查看安裝 RCF 或升級 RCF 程式後，您link:install-rcf-software-3232c.html["安裝 RCF"]或者link:upgrade-rcf-software-3232c.html["升級您的 RCF"]按要求。
