---
permalink: switch-cisco-3232c/migrate-from-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 設定連接埠，以便從雙節點無交換器式叢集移轉到 Cisco Nexus 3232C 叢集交換器。 
---
= 設定連接埠，以便從雙節點無交換器式叢集移轉到 Cisco Nexus 3232C 叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定連接埠，以便使用 Cisco Nexus 3232C 叢集交換器從雙節點無交換器式叢集移轉至雙節點交換式叢集。

.步驟
. 將 n1_clus1 和 n2_clus1 LIF 移轉至其目的地節點的實體連接埠：
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須對每個本機節點執行該命令，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====
. 驗證叢集介面是否已成功移轉：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
下列範例顯示，移轉完成後，n1_clus1 和 n2_clus1 LIF 的「Is Home」狀態已變為「false」：

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. 關閉在步驟 9 中移轉的 n1_clus1 和 n2_clus1 LIF 的叢集連接埠：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.顯示範例
[%collapsible]
====
您必須對每個連接埠執行該命令，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step5]] 從節點 n1 上的 e4a 拔除纜線。
+
您可以參考執行中的組態，並使用 Nexus 3232C 交換器支援的纜線，將交換器 C1 上的第一個 40 GbE 連接埠（本例中為連接埠 1/7）連接到 n1 上的 e4a。

. 拔除節點 n2 上 e4a 的纜線。
+
您可以參考執行中的組態，使用支援的纜線將 e4a 連接到 C1 上的下一個可用 40 GbE 連接埠（連接埠 1/8）。

. 啟用 C1 上所有面向節點的連接埠。
+
有關 Cisco 命令的更多資訊，請參閱 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令參考"^] 中列出的指南。

+
.顯示範例
[%collapsible]
====
以下範例顯示如何使用 RCF 中支援的組態在 Nexus 3232C 叢集交換器 C1 和 C2 上啟用連接埠 1 到 30 `NX3232_RCF_v1.0_24p10g_26p100g.txt`：

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 在每個節點上啟用第一個叢集連接埠 e4a：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 確認兩個節點上的叢集都已啟動：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 對於每個節點，回復所有已移轉的叢集互連 LIF：
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.顯示範例
[%collapsible]
====
您必須將每個 LIF 分別回復到其主連接埠，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. 請確認所有 LIF 都已回復至其主連接埠：
+
`network interface show -role cluster`

+
對於 `Current Port`欄中列出的所有連接埠， `Is Home`欄應顯示 `true`值。如果顯示的值為 `false`，則表示該連接埠尚未回復。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 顯示每個節點上的叢集連接埠連線情況：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 在每個節點的主控台上將 clus2 移轉至連接埠 e4a：
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須按照以下範例所示，將每個 LIF 單獨移轉到其主連接埠：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 關閉兩個節點上的叢集連接埠 clus2 LIF：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例顯示如何將指定的連接埠設定為 `false`，從而關閉兩個節點上的連接埠：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. 驗證叢集 LIF 狀態：
+
`network interface show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 拔除節點 n1 上 e4e 的纜線。
+
您可以參考執行中的組態，將交換器 C2 上的第一個 40 GbE 連接埠（本例中為連接埠 1/7）連接到節點 n1 上的 e4e，並使用適用於 Nexus 3232C 交換器型號的適當纜線。

. 拔除節點 n2 上 e4e 的纜線。
+
您可以參考執行中的組態，使用適用於 Nexus 3232C 交換器型號的適當纜線，將 e4e 連接到 C2 上下一個可用的 40 GbE 連接埠（連接埠 1/8）。

. 啟用 C2 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示如何使用 RCF 支援的組態在 Nexus 3132Q-V 叢集交換器 C1 和 C2 上啟用連接埠 1 到 30 `NX3232C_RCF_v1.0_24p10g_26p100g.txt`：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 在每個節點上啟用第二個叢集連接埠 e4e：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例展示了在每個節點上啟動第二個叢集連接埠 e4e 的過程：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 對於每個節點，回復所有已移轉的叢集互連 LIF：
+
`network interface revert`

+
.顯示範例
[%collapsible]
====
以下範例顯示已移轉的 LIF 回復至其主連接埠。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====


.下一步是什麼？
設定好連接埠後，您可以link:migrate-from-switchless-complete-migration.html["完成移轉"]。
