---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: 如果您有一個雙節點無交換器集群，您可以無中斷地遷移到包含Cisco Nexus 3232C 集群網路交換器的雙節點有交換器集群。 
---
= 將雙節點無交換器叢集遷移到使用Cisco Nexus 3232C 叢集交換器的叢集。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有一個雙節點無交換器集群，您可以遷移到包含Cisco Nexus 3232C 集群網路交換器的雙節點有交換器集群。這是一個非破壞性的過程。



== 審查要求

.開始之前
請核實以下安裝和連接：

* 連接埠可用於節點連接。叢集交換器使用交換器間連結 (ISL) 連接埠 e1/31-32。
* 您擁有適用於叢集連線的線纜：
+
** 具有 10 GbE 叢集連接的節點需要 QSFP 光模組和分支光纖纜線或 QSFP 轉 SFP+ 銅纜分支纜線。
** 具有 40/100 GbE 叢集連接的節點需要支援 QSFP/QSFP28 光模組，並配備光纖電纜或 QSFP/QSFP28 銅纜直連接纜線。
** 叢集交換器需要適當的 ISL 佈線：2 條 QSFP28 光纖或銅纜直連接纜線。


* 配置已正確設定並正常運作。
+
這兩個節點必須連接在一起，並在雙節點無交換器叢集環境中運作。

* 叢集所有連接埠均處於*開啟*狀態。
* 支援Cisco Nexus 3232C 集群交換器。
* 現有叢集網路配置如下：
+
** 兩台交換器上都配備了冗餘且功能齊全的 Nexus 3232C 叢集基礎設施。
** 交換器上的最新 RCF 和 NX-OS 版本
** 兩台交換器的管理連線功能
** 可透過控制台存取兩台交換機
** 所有處於*up*狀態但尚未遷移的叢集邏輯介面（LIF）
** 開關的初始定制
** 所有ISL連接埠均已啟用並連接線纜




.關於範例
本流程中的範例使用以下開關和節點命名規則：

* Nexus 3232C 集群交換機，C1 和 C2。
* 節點分別為 n1 和 n2。


本流程中的範例使用兩個節點，每個節點使用兩個 40 GbE 叢集互連連接埠 e4a 和 e4e。這link:https://hwu.netapp.com/["硬體宇宙"^]包含您平台上叢集連接埠的詳細資訊。

* n1_clus1 是連接到節點 n1 的叢集交換器 C1 的第一個叢集邏輯介面 (LIF)。
* n1_clus2 是第一個連接到節點 n1 的叢集交換器 C2 的叢集 LIF。
* n2_clus1 是第一個連接到節點 n2 的叢集交換器 C1 的叢集 LIF。
* n2_clus2 是第二個要連接到節點 n2 的叢集交換器 C2 的叢集 LIF。
* 10 GbE 和 40/100 GbE 連接埠的數量在參考設定檔 (RCF) 中定義，這些檔案可在以下網址取得：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集網路交換器參考設定檔下載"^] 。


[NOTE]
====
流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

====


== 步驟 1：顯示和遷移實體連接埠和邏輯端口

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 確定每個叢集介面的管理或運作狀態：
+
.. 顯示網路連接埠屬性：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 顯示有​​關邏輯介面及其指定歸屬節點的資訊：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. 使用進階權限命令驗證是否已啟用無交換器叢集偵測：
+
`network options detect-switchless-cluster show``

+
.顯示範例
[%collapsible]
====
以下範例的輸出表示已啟用無交換器叢集偵測：

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 確認新的 3232C 交換器上已安裝相應的 RCF 和映像，並進行任何必要的網站自訂，例如新增使用者、密碼和網路位址。
+
此時您必須準備好這兩個開關。如果需要升級 RCF 和鏡像軟體，必須按照以下步驟操作：

+
.. 請造訪NetApp支援網站上的 _Cisco 乙太網路交換器_ 頁面。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]

.. 請記下您交換器的型號以及該頁表格中所需的軟體版本。
.. 下載相應版本的RCF。
.. 在“描述”頁面上點擊“繼續”，接受許可協議，然後按照“下載”頁面上的說明下載 RCF。
.. 下載對應版本的影像處理軟體。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集和管理網路交換器參考設定檔下載"^]。



. 在“描述”頁面上點擊“繼續”，接受許可協議，然後按照“下載”頁面上的說明下載 RCF。
. 在 Nexus 3232C 交換器 C1 和 C2 上，停用所有面向節點的連接埠 C1 和 C2，但不要停用 ISL 連接埠 e1/31-32。
+
有關Cisco命令的更多信息，請參閱以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示如何使用 RCF 支援的配置，在 Nexus 3232C 叢集交換器 C1 和 C2 上停用連接埠 1 到 30。 `NX3232_RCF_v1.0_24p10g_24p100g.txt` ：

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 使用支援的電纜將 C1 上的連接埠 1/31 和 1/32 連接到 C2 上的相同連接埠。
. 請確認C1和C2上的ISL連接埠是否正常運作：
+
`show port-channel summary`

+
有關Cisco命令的更多信息，請參閱以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示了Cisco `show port-channel summary`用於驗證 C1 和 C2 上的 ISL 連接埠是否正常運作的命令：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 顯示交換器上相鄰設備的清單。
+
有關Cisco命令的更多信息，請參閱以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示了Cisco指令 `show cdp neighbors`用於顯示交換器上的鄰近設備：

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 顯示每個節點上的叢集連接埠連線情況：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了雙節點無交換器叢集配置的叢集連接埠連線情況：

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. 將 n1_clus1 和 n2_clus1 LIF 遷移到其目標節點的實體連接埠：
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須對每個本機節點執行該命令，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====




== 步驟 2：關閉重新分配的 LIF 並斷開電纜

. 驗證叢集介面是否已成功遷移：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
下列範例顯示，遷移完成後，n1_clus1 和 n2_clus1 LIF 的「Is Home」狀態已變為「false」：

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. 關閉在步驟 9 中遷移的 n1_clus1 和 n2_clus1 LIF 的叢集連接埠：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.顯示範例
[%collapsible]
====
您必須對每個連接埠執行該命令，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step4]] 斷開節點 n1 上 e4a 的電纜。
+
您可以參考運作配置，並將交換器 C1 上的第一個 40 GbE 連接埠（本例中為連接埠 1/7）連接到 n1 上的 e4a，使用 Nexus 3232C 交換器支援的電纜。





== 步驟 3：啟用叢集連接埠

. 斷開節點 n2 上 e4a 的電纜。
+
您可以參考運行配置，使用支援的電纜將 e4a 連接到 C1 上的下一個可用的 40 GbE 連接埠 1/8。

. 啟用 C1 上所有面向節點的連接埠。
+
有關Cisco命令的更多信息，請參閱以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示如何使用 RCF 中支援的配置，在 Nexus 3232C 叢集交換器 C1 和 C2 上啟用連接埠 1 到 30。 `NX3232_RCF_v1.0_24p10g_26p100g.txt` ：

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 在每個節點上啟用第一個叢集連接埠 e4a：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 確認兩個節點上的叢集都已啟動：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 對於每個節點，還原所有已遷移的叢集互連 LIF：
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.顯示範例
[%collapsible]
====
您必須將每個 LIF 分別恢復到其原始端口，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. 請確認所有 LIF 都已恢復到原始連接埠：
+
`network interface show -role cluster`

+
這 `Is Home`該列應顯示以下值： `true`對於列表中列出的所有端口 `Current Port`柱子。如果顯示的值為 `false`連接埠尚未恢復。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




== 步驟 4：啟用重新指派的 LIF

. 顯示每個節點上的叢集連接埠連線情況：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 將 clus2 遷移到每個節點控制台上的 e4a 連接埠：
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須按照以下範例所示，將每個 LIF 單獨遷移到其所屬連接埠：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 關閉兩個節點上的叢集連接埠 clus2 LIF：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例顯示如何設定指定的連接埠 `false`關閉兩個節點上的連接埠：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. 驗證叢集 LIF 狀態：
+
`network interface show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 斷開節點 n1 上 e4e 的電纜。
+
您可以參考運作配置，將交換器 C2 上的第一個 40 GbE 連接埠（本例中為連接埠 1/7）連接到節點 n1 上的 e4e，使用適用於 Nexus 3232C 交換器型號的適當電纜。

. 斷開節點 n2 上 e4e 的電纜。
+
您可以參考運行配置，使用適用於 Nexus 3232C 交換器型號的適當電纜，將 e4e 連接到 C2 上的下一個可用 40 GbE 連接埠（連接埠 1/8）。

. 啟用 C2 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例展示如何使用 RCF 支援的設定在 Nexus 3132Q-V 叢集交換器 C1 和 C2 上啟用連接埠 1 到 30。 `NX3232C_RCF_v1.0_24p10g_26p100g.txt` ：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 在每個節點上啟用第二個叢集連接埠 e4e：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例展示如何在每個節點上啟動第二個叢集連接埠 e4e：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 對於每個節點，還原所有已遷移的叢集互連 LIF： `network interface revert`
+
.顯示範例
[%collapsible]
====
以下範例顯示已移轉的 LIF 還原至其原始連接埠。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====
. 確認所有群集互連連接埠均已恢復為其原始連接埠：
+
`network interface show -role cluster`

+
這 `Is Home`該列應顯示以下值： `true`對於列表中列出的所有端口 `Current Port`柱子。如果顯示的值為 `false`連接埠尚未恢復。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 確認所有群集互連連接埠均已連線。 `up`狀態：
+
`network port show -role cluster`

. 顯示叢集交換器連接埠號，每個叢集連接埠透過這些連接埠連接到每個節點： `network device-discovery show`
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. 顯示已發現和監控的群集交換器：
+
`system cluster-switch show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. 確認無交換器叢集偵測已將無交換器叢集選項變更為停用：
+
`network options switchless-cluster show`

. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step16]] 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用此功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
