---
permalink: switch-cisco-3232c/migrate-from-switchless-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 您可以在AFF或FAS叢集中使用Cisco Nexus 3232C 交換器作為叢集交換器。 
---
= 做好從雙節點無交換器叢集遷移到雙節點有交換器叢集的準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟準備您的雙節點無交換器集群，以遷移到包含Cisco Nexus 3232C 集群網路交換器的雙節點交換集群。

.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 確定每個叢集介面的管理或運作狀態：
+
.. 顯示網路連接埠屬性：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 顯示有​​關邏輯介面及其指定歸屬節點的資訊：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. 使用進階權限命令驗證是否已啟用無交換器叢集偵測：
+
`network options detect-switchless-cluster show``

+
.顯示範例
[%collapsible]
====
以下範例的輸出表示已啟用無交換器叢集偵測：

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 確認新的 3232C 交換器上已安裝相應的 RCF 和映像，並進行任何必要的網站自訂，例如新增使用者、密碼和網路位址。
+
此時您必須準備好這兩個開關。如果需要升級 RCF 和鏡像軟體，必須按照以下步驟操作：

+
.. 請造訪NetApp支援網站上的 _Cisco 乙太網路交換器_ 頁面。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch/["Cisco乙太網路交換機"^]

.. 請記下您交換器的型號以及該頁表格中所需的軟體版本。
.. 下載相應版本的RCF。
.. 在“描述”頁面上選擇“繼續”，接受許可協議，然後按照“下載”頁面上的說明下載 RCF。
.. 下載對應版本的影像處理軟體。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集和管理網路交換器參考設定檔下載"^]



. 在“描述”頁面上選擇“繼續”，接受許可協議，然後按照“下載”頁面上的說明下載 RCF。
. 在 Nexus 3232C 交換器 C1 和 C2 上，停用所有面向節點的連接埠 C1 和 C2，但不要停用 ISL 連接埠 e1/31-32。
+
有關Cisco命令的更多信息，請參閱以下列表。 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示如何使用 RCF 支援的配置，在 Nexus 3232C 叢集交換器 C1 和 C2 上停用連接埠 1 到 30。 `NX3232_RCF_v1.0_24p10g_24p100g.txt` ：

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 使用支援的電纜將 C1 上的連接埠 1/31 和 1/32 連接到 C2 上的相同連接埠。
. 請確認C1和C2上的ISL連接埠是否正常運作：
+
`show port-channel summary`

+
有關Cisco命令的更多信息，請參閱以下列表。 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示了Cisco `show port-channel summary`用於驗證 C1 和 C2 上的 ISL 連接埠是否正常運作的命令：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 顯示交換器上相鄰設備的清單。
+
有關Cisco命令的更多信息，請參閱以下列表。 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^] 。

+
.顯示範例
[%collapsible]
====
以下範例展示了Cisco指令 `show cdp neighbors`用於顯示交換器上的鄰近設備：

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 顯示每個節點上的叢集連接埠連線情況：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了雙節點無交換器叢集配置的叢集連接埠連線情況：

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====


.下一步是什麼？
link:migrate-from-switchless-configure-ports.html["配置連接埠"]。
