---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: 當您以Cisco Nexus 3232C 叢集交換器取代 CN1610 叢集交換器時，您必須了解某些設定資訊、連接埠連線和佈線需求。 
---
= Cisco Nexus 3232C 叢集交換器的遷移需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在遷移至Cisco Nexus 3232C 叢集交換器之前，請先查看設定資訊、連接埠連線和佈線要求。



== CN1610遷移要求

叢集交換器支援以下節點連線：

* NetApp CN1610：連接埠 0/1 至 0/12 (10 GbE)
* Cisco Nexus 3232C：連接埠 e1/1-30（40 或 100 或 4x10GbE）


叢集交換器使用下列交換器間連結 (ISL) 連接埠。

* NetApp CN1610：連接埠 0/13 至 0/16 (10 GbE)
* Cisco Nexus 3232C：連接埠 1/31-32 (100GbE)


[NOTE]
====
在Cisco Nexus 3232C 叢集交換器上必須使用 4x10G 分支電纜。

====
下表顯示了從NetApp CN1610 交換器過渡到Cisco Nexus 3232C 叢集交換器時，每個階段所需的佈線連接：

|===
| 階段 | 描述 | 所需電纜 


 a| 
最初的
 a| 
CN1610 至 CN1610（SFP+ 至 SFP+）
 a| 
4條SFP+光纖或銅纜直連電纜



 a| 
過渡
 a| 
CN1610 至 3232C（QSFP 至 SFP+）
 a| 
1條QSFP和4條SFP+光纖或銅纜分支電纜



 a| 
最終的
 a| 
3232C 至 3232C（QSFP 至 QSFP）
 a| 
2條QSFP光纖或銅纜直連電纜

|===
您必須已下載適用的參考設定檔（RCF）。  10 GbE 和 40/100 GbE 連接埠的數量在 RCF 中定義。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集網路交換器參考設定檔下載"^] 。

此流程支援的ONTAP和 NX-OS 版本列於此。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 。

此流程支援的ONTAP和 FASTPATH 版本列於此處link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 交換機"^]。



== CN5596 要求

叢集交換器使用下列連接埠連接到節點：

* 埠 e1/1-40 (10 GbE)：Nexus 5596
* 連接埠 e1/1-30 (10/40/100 GbE)：Nexus 3232C
+
** 叢集交換器使用下列交換器間連結 (ISL) 連接埠：


* 埠 e1/41-48 (10 GbE)：Nexus 5596
* 連接埠 e1/31-32 (40/100 GbE)：Nexus 3232C
+
** 這link:https://hwu.netapp.com/["硬體宇宙"^]包含有關 Nexus 3232C 交換器支援的佈線資訊：


* 具有 10 GbE 叢集連接的節點需要 QSFP 轉 SFP+ 光纖分支電纜或 QSFP 轉 SFP+ 銅纜分支纜線。
* 具有 40/100 GbE 叢集連接的節點需要支援 QSFP/QSFP28 光模組，並配備光纖電纜或 QSFP/QSFP28 銅纜直連接纜線。
+
** 叢集交換器使用對應的ISL電纜：


* 起始端：Nexus 5596（SFP+ 至 SFP+）
+
** 8條SFP+光纖或銅纜直連接纜


* 過渡期：Nexus 5596 至 Nexus 3232C（QSFP 至 4xSFP+ 突破）
+
** 1條QSFP轉SFP+光纖分支線或銅纜分支線


* 最終版：Nexus 3232C 至 Nexus 3232C（QSFP28 至 QSFP28）
+
** 2條QSFP28光纖或銅纜直連接電纜
+
*** 在 Nexus 3232C 交換器上，您可以將 QSFP/QSFP28 連接埠操作為 40/100 千兆乙太網路或 4 x 10 千兆乙太網路模式。
+
預設情況下，40/100 千兆乙太網路模式下有 32 個連接埠。這 40 個千兆乙太網路連接埠採用二元組命名規則進行編號。例如，第二個 40 千兆乙太網路連接埠編號為 1/2。將 40 千兆乙太網路配置更改為 10 千兆乙太網路的過程稱為 _breakout_，將 10 千兆乙太網路配置更改為 40 千兆乙太網路的過程稱為 _breakin_。當您將 40/100 千兆乙太網路連接埠拆分為 10 千兆乙太網路連接埠時，產生的連接埠將使用三元組命名規則進行編號。例如，第二個 40/100 千兆乙太網路連接埠的分線連接埠編號為 1/2/1、1/2/2、1/2/3 和 1/2/4。

*** Nexus 3232C 交換器的左側有 2 個 SFP+ 端口，分別稱為 1/33 和 1/34。
*** 您已將 Nexus 3232C 交換器上的一些連接埠配置為以 10 GbE 或 40/100 GbE 運作。
+
[NOTE]
====
您可以使用下列方法將前六個連接埠配置為 4x10 GbE 模式： `interface breakout module 1 port 1-6 map 10g-4x`命令。同樣，您可以使用下列方法將前六個 QSFP+ 連接埠從分支配置中重新分組： `no interface breakout module 1 port 1-6 map 10g-4x`命令。

====
*** 您已完成規劃、遷移，並閱讀了有關從節點到 Nexus 3232C 叢集交換器的 10 GbE 和 40/100 GbE 連接的必要文件。
*** 此流程支援的ONTAP和 NX-OS 版本為：link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 。





