---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: 當您以 Cisco Nexus 3232C 叢集交換器取代 CN1610 叢集交換器時，您必須瞭解某些組態資訊、連接埠連線和佈線需求。 
---
= Cisco Nexus 3232C 叢集交換器的移轉需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在移轉至 Cisco Nexus 3232C 叢集交換器之前，請審查組態資訊、連接埠連線和佈線要求。



[[cn1610-migrate-requirements]]
== CN1610 移轉要求

叢集交換器支援以下節點連線：

* NetApp CN1610：連接埠 0/1 至 0/12（10 GbE）
* Cisco Nexus 3232C：連接埠 e1/1-30（40 或 100 或 4x10GbE）


叢集交換器使用下列交換器間連結 (ISL) 連接埠。

* NetApp CN1610：連接埠 0/13 至 0/16（10 GbE）
* Cisco Nexus 3232C：連接埠 1/31-32 (100GbE)


[NOTE]
====
在 Cisco Nexus 3232C 叢集交換器上必須使用 4x10G 分支電纜。

====
下表顯示從 NetApp CN1610 交換器移轉至 Cisco Nexus 3232C 叢集交換器時，每個階段所需的佈線連接：

|===
| 階段 | 描述 | 所需電纜 


 a| 
最初的
 a| 
CN1610 至 CN1610（SFP+ 至 SFP+）
 a| 
4 條 SFP+ 光纖或銅直連電纜



 a| 
過渡
 a| 
CN1610 至 3232C（QSFP 至 SFP+）
 a| 
1 條 QSFP 和 4 條 SFP+ 光纖或銅分支電纜



 a| 
最終的
 a| 
3232C 至 3232C（QSFP 至 QSFP）
 a| 
2 條 QSFP 光纖或銅直連電纜

|===
您必須已下載適用的參考組態檔 (RCF)。10 GbE 和 40/100 GbE 連接埠的數量在 RCF 中定義，可在以下位置取得link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 叢集網路交換器參考組態檔下載"^]。

此程序支援的 ONTAP 和 NX-OS 版本列於 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]。

此程序支援的 ONTAP 和 FASTPATH 版本列於 link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 交換器"^]。



[[cn5596-requirements]]
== CN5596 要求

叢集交換器使用下列連接埠連接到節點：

* 連接埠 e1/1-40 (10 GbE)：Nexus 5596
* 連接埠 e1/1-30 (10/40/100 GbE)：Nexus 3232C
+
** 叢集交換器使用下列交換器間連結 (ISL) 連接埠：


* 連接埠 e1/41-48 (10 GbE)：Nexus 5596
* 連接埠 e1/31-32 (40/100 GbE)：Nexus 3232C
+
** link:https://hwu.netapp.com/["Hardware Universe"^]包含有關 Nexus 3232C 交換器支援佈線的資訊：


* 具有 10 GbE 叢集連接的節點需要 QSFP 轉 SFP+ 光纖分支纜線或 QSFP 轉 SFP+ 銅分支纜線。
* 具有 40/100 GbE 叢集連接的節點需要支援的 QSFP/QSFP28 光模組（配備光纖電纜）或 QSFP/QSFP28 銅直連接纜線。
+
** 叢集交換器使用對應的ISL電纜：


* 起始端：Nexus 5596（SFP+ 至 SFP+）
+
** 8 條 SFP+ 光纖或銅直連接纜


* 過渡期：Nexus 5596 至 Nexus 3232C（QSFP 至 4xSFP+ 分支）
+
** 1 條 QSFP 轉 SFP+ 光纖分支線或銅分支線


* 最終版：Nexus 3232C 至 Nexus 3232C（QSFP28 至 QSFP28）
+
** 2 條 QSFP28 光纖或銅直連接電纜
+
*** 在 Nexus 3232C 交換器上，您可以將 QSFP/QSFP28 連接埠以 40/100 Gigabit Ethernet 或 4 x10 Gigabit Ethernet 模式運作。
+
預設情況下，40/100 Gigabit Ethernet 模式下有 32 個連接埠。這些 40 Gigabit Ethernet 連接埠採用二元組命名慣例進行編號。例如，第二個 40 Gigabit Ethernet 連接埠的編號為 1/2。將組態從 40 Gigabit Ethernet 變更為 10 Gigabit Ethernet 的程序稱為 _breakout_，將組態從 10 Gigabit Ethernet 變更為 40 Gigabit Ethernet 的程序稱為 _breakin_。當您將一個 40/100 Gigabit Ethernet 連接埠分出為 10 Gigabit Ethernet 連接埠時，產生的連接埠會採用三元組命名慣例進行編號。例如，第二個 40/100 Gigabit Ethernet 連接埠的分線連接埠編號為 1/2/1、1/2/2、1/2/3 和 1/2/4。

*** Nexus 3232C 交換器的左側有 2 個 SFP+ 連接埠，分別稱為 1/33 和 1/34。
*** 您已將 Nexus 3232C 交換器上的部分連接埠設定為以 10 GbE 或 40/100 GbE 運作。
+
[NOTE]
====
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x`命令將前六個連接埠拆分為 4x10 GbE 模式。同樣，您可以使用 `no interface breakout module 1 port 1-6 map 10g-4x`命令將前六個 QSFP+ 連接埠從分割組態重新組合。

====
*** 您已完成規劃、移轉，並閱讀了有關節點到 Nexus 3232C 叢集交換器的 10 GbE 和 40/100 GbE 連接的必要文件。
*** 此程序支援的 ONTAP 和 NX-OS 版本位於 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]。





