---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: 將雙節點無交換器式叢集移轉至使用 Cisco Nexus 3232C 叢集交換器的交換式叢集。這是不中斷營運的程序。 
---
= 將雙節點無交換器式叢集移轉至 Cisco Nexus 3232C 叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將雙節點無交換器式叢集移轉至使用 Cisco Nexus 3232C 叢集交換器的交換式叢集。這是不中斷營運的程序。



[[review-requirements]]
== 審查要求

.開始之前
請核實以下安裝和連接：

* 連接埠可供節點連線使用。叢集交換器使用交換器間連結 (ISL) 連接埠 e1/31-32。
* 您擁有適合叢集連線的纜線：
+
** 具有 10 GbE 叢集連接的節點需要 QSFP 光模組搭配分支光纖纜線，或 QSFP 轉 SFP+ 銅分支纜線。
** 具有 40/100 GbE 叢集連接的節點需要支援的 QSFP/QSFP28 光模組，並配備光纖電纜或 QSFP/QSFP28 銅直連接纜線。
** 叢集交換器需要適當的 ISL 佈線：2 條 QSFP28 光纖或銅直連接纜線。


* 組態已正確設定並正常運作。
+
這兩個節點必須連接在一起，並在雙節點無交換器式叢集環境中運作。

* 叢集所有連接埠均處於*開啟*狀態。
* 支援 Cisco Nexus 3232C 叢集交換器。
* 現有叢集網路配置如下：
+
** 兩台交換器上都具備備援且功能齊全的 Nexus 3232C 叢集基礎架構
** 交換器上的最新 RCF 和 NX-OS 版本
** 兩台交換器的管理連線功能
** 可透過控制台存取兩台交換器
** 所有處於 *up* 狀態但尚未移轉的叢集邏輯介面（LIF）
** 交換器的初始自訂
** 所有ISL連接埠均已啟用並連接線纜




.關於範例
本流程中的範例使用以下開關和節點命名規則：

* Nexus 3232C 叢集交換器，C1 和 C2。
* 節點分別為 n1 和 n2。


本流程中的範例使用兩個節點，每個節點使用兩個 40 GbE 叢集互連連接埠 e4a 和 e4e。link:https://hwu.netapp.com/["Hardware Universe"^]包含有關您平台上叢集連接埠的詳細資訊。

* n1_clus1 是節點 n1 連接到叢集交換器 C1 的第一個叢集邏輯介面 （LIF）。
* n1_clus2 是第一個連接到節點 n1 之叢集交換器 C2 的叢集 LIF。
* n2_clus1 是第一個連接到節點 n2 的叢集交換器 C1 的叢集 LIF。
* n2_clus2 是要連接到節點 n2 之叢集交換器 C2 的第二個叢集 LIF。
* 10 GbE 和 40/100 GbE 連接埠的數量在參考組態檔 （RCF） 中定義，可在以下網址取得：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 叢集網路交換器參考組態檔下載"^]


[NOTE]
====
流程需要同時使用 ONTAP 命令和 Cisco Nexus 3000 系列交換器命令；除非另有說明，否則使用 ONTAP 命令。

====


[[step-1-display-and-migrate-physical-and-logical-ports]]
== 步驟 1：顯示和移轉實體連接埠和邏輯介面

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 確定每個叢集介面的管理或運作狀態：
+
.. 顯示網路連接埠屬性：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 顯示有​​關邏輯介面及其指定歸屬節點的資訊：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. 使用進階權限命令驗證是否已啟用無交換器式叢集偵測：
+
`network options detect-switchless-cluster show``

+
.顯示範例
[%collapsible]
====
以下範例的輸出表示已啟用無交換器式叢集偵測：

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 確認新的 3232C 交換器上已安裝相應的 RCF 和"映像"，並進行任何必要的網站自訂，例如新增使用者、密碼和網路位址。
+
此時您必須準備好兩台交換器。如果需要升級 RCF 和映像軟體，請依照以下步驟操作：

+
.. 請前往 NetApp 支援網站上的 _Cisco Ethernet Switches_ 頁面。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]

.. 請記下您交換器的型號以及該頁表格中所需的軟體版本。
.. 下載適當版本的 RCF。
.. 在 *Description* 頁面上按一下 *CONTINUE*，接受授權合約，然後依照 *Download* 頁面上的說明下載 RCF。
.. 下載對應版本的映像軟體。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco 叢集和管理網路交換器參考組態檔下載"^]。



. 在 *Description* 頁面上按一下 *CONTINUE*，接受授權合約，然後依照 *Download* 頁面上的說明下載 RCF。
. 在 Nexus 3232C 交換器 C1 和 C2 上，停用所有面向節點的連接埠 C1 和 C2，但不要停用 ISL 連接埠 e1/31-32。
+
有關 Cisco 命令的更多資訊，請參閱 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令參考"^] 中列出的指南。

+
.顯示範例
[%collapsible]
====
以下範例展示如何使用 RCF 支援的組態停用 Nexus 3232C 叢集交換器 C1 和 C2 上的連接埠 1 到 30 `NX3232_RCF_v1.0_24p10g_24p100g.txt`：

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 使用支援的電纜將 C1 上的連接埠 1/31 和 1/32 連接到 C2 上的相同連接埠。
. 請確認 C1 和 C2 上的 ISL 連接埠是否正常運作：
+
`show port-channel summary`

+
有關 Cisco 命令的更多資訊，請參閱 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令參考"^] 中列出的指南。

+
.顯示範例
[%collapsible]
====
以下範例顯示如何使用 Cisco `show port-channel summary` 命令來驗證 C1 和 C2 上的 ISL 連接埠是否正常運作：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 顯示交換器上相鄰設備的清單。
+
有關 Cisco 命令的更多資訊，請參閱 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令參考"^] 中列出的指南。

+
.顯示範例
[%collapsible]
====
以下範例說明如何使用 Cisco 命令 `show cdp neighbors`顯示交換器上的鄰近設備：

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 顯示每個節點上的叢集連接埠連線情況：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了雙節點無交換器式叢集組態的叢集連接埠連線情況：

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. 將 n1_clus1 和 n2_clus1 LIF 移轉至其目的地節點的實體連接埠：
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須對每個本機節點執行該命令，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====




[[step-2-shut-down-the-reassigned-lifs-and-disconnect-the-cables]]
== 步驟 2：關閉重新指派的 LIF 並拔除纜線

. 驗證叢集介面是否已成功移轉：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
下列範例顯示，移轉完成後，n1_clus1 和 n2_clus1 LIF 的「Is Home」狀態已變為「false」：

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. 關閉在步驟 9 中移轉的 n1_clus1 和 n2_clus1 LIF 的叢集連接埠：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.顯示範例
[%collapsible]
====
您必須對每個連接埠執行該命令，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step4]] 拔除節點 n1 上 e4a 的纜線。
+
您可以參考執行中的組態，並使用 Nexus 3232C 交換器支援的纜線，將交換器 C1 上的第一個 40 GbE 連接埠（本例中為連接埠 1/7）連接到 n1 上的 e4a。





[[step-3-enable-the-cluster-ports]]
== 步驟 3：啟用叢集連接埠

. 拔除節點 n2 上 e4a 的纜線。
+
您可以參考執行中的組態，使用支援的纜線將 e4a 連接到 C1 上的下一個可用 40 GbE 連接埠（連接埠 1/8）。

. 啟用 C1 上所有面向節點的連接埠。
+
有關 Cisco 命令的更多資訊，請參閱 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令參考"^] 中列出的指南。

+
.顯示範例
[%collapsible]
====
以下範例顯示如何使用 RCF 中支援的組態在 Nexus 3232C 叢集交換器 C1 和 C2 上啟用連接埠 1 到 30 `NX3232_RCF_v1.0_24p10g_26p100g.txt`：

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 在每個節點上啟用第一個叢集連接埠 e4a：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 確認兩個節點上的叢集都已啟動：
+
`network port show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 對於每個節點，回復所有已移轉的叢集互連 LIF：
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.顯示範例
[%collapsible]
====
您必須將每個 LIF 分別回復到其主連接埠，如下例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. 請確認所有 LIF 都已回復至其主連接埠：
+
`network interface show -role cluster`

+
對於 `Current Port`欄中列出的所有連接埠， `Is Home`欄應顯示 `true`值。如果顯示的值為 `false`，則表示該連接埠尚未回復。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




[[step-4-enable-the-reassigned-lifs]]
== 步驟 4：啟用重新指派的 LIF

. 顯示每個節點上的叢集連接埠連線情況：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 在每個節點的主控台上將 clus2 移轉至連接埠 e4a：
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.顯示範例
[%collapsible]
====
您必須按照以下範例所示，將每個 LIF 單獨移轉到其主連接埠：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 關閉兩個節點上的叢集連接埠 clus2 LIF：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例顯示如何將指定的連接埠設定為 `false`，從而關閉兩個節點上的連接埠：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. 驗證叢集 LIF 狀態：
+
`network interface show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 拔除節點 n1 上 e4e 的纜線。
+
您可以參考執行中的組態，將交換器 C2 上的第一個 40 GbE 連接埠（本例中為連接埠 1/7）連接到節點 n1 上的 e4e，並使用適用於 Nexus 3232C 交換器型號的適當纜線。

. 拔除節點 n2 上 e4e 的纜線。
+
您可以參考執行中的組態，使用適用於 Nexus 3232C 交換器型號的適當纜線，將 e4e 連接到 C2 上下一個可用的 40 GbE 連接埠（連接埠 1/8）。

. 啟用 C2 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示如何使用 RCF 支援的組態在 Nexus 3132Q-V 叢集交換器 C1 和 C2 上啟用連接埠 1 到 30 `NX3232C_RCF_v1.0_24p10g_26p100g.txt`：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 在每個節點上啟用第二個叢集連接埠 e4e：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例展示了在每個節點上啟動第二個叢集連接埠 e4e 的過程：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 對於每個節點，回復所有已移轉的叢集互連 LIF： `network interface revert`
+
.顯示範例
[%collapsible]
====
以下範例顯示已移轉的 LIF 回復至其主連接埠。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====
. 確認所有叢集互連連接埠現在均已回復至其主連接埠：
+
`network interface show -role cluster`

+
對於 `Current Port`欄中列出的所有連接埠， `Is Home`欄應顯示 `true`值。如果顯示的值為 `false`，則表示該連接埠尚未回復。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 確認所有叢集互連連接埠均處於 `up`狀態：
+
`network port show -role cluster`

. 顯示每個叢集連接埠連接到每個節點的叢集交換器連接埠號碼： `network device-discovery show`
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. 顯示已探索和受監控的叢集交換器：
+
`system cluster-switch show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. 確認無交換器式叢集偵測已將無交換器式叢集選項變更為停用：
+
`network options switchless-cluster show`

. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step16]] 如果您已停用自動建立案例功能，請透過呼叫下列 AutoSupport 訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
