---
permalink: switch-cisco-3232c/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: 您可以按照特定步驟，在不中斷業務的情況下更換有缺陷的 Cisco Nexus 3232C 儲存設備交換器。 
---
= 更換 Cisco Nexus 3232C 儲存設備交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟更換有缺陷的 Cisco Nexus 3232C 儲存設備交換器。此程序不會造成中斷。



[[review-requirements]]
== 審查要求

現有網路配置必須具備以下特徵：

* Cisco乙太網路交換器頁麵包含交換器上最新的 RCF 和 NX-OS 版本。
* 兩台交換器都必須具備管理連線功能。
+
[NOTE]
====
請確保已完成所有故障排除步驟，以確認您的交換器需要更換。

====


更換用的 Cisco Nexus 3232C 交換器必須具備以下特性：

* 管理網路連線必須正常。
* 必須具備對更換開關的控制台存取權限。
* 必須將對應的 RCF 和 NX-OS 作業系統映像載入到交換器上。
* 交換器的初始自訂必須完成。




[[replace-the-switch]]
== 更換開關

此程序將第二個 Nexus 3232C 儲存設備交換器 S2 替換為新的 3232C 交換器 NS2。這兩個節點分別為 node1 和 node2。



[[step-1-confirm-the-switch-to-be-replaced-is-s2]]
=== 步驟 1：確認待更換的交換器是 S2

. 如果此叢集已啟用 AutoSupport，請透過叫用 AutoSupport 訊息來抑制自動建立案例：
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 檢查儲存節點連接埠的運作狀況，確保與儲存交換器S1有連接：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. 確認儲存交換器 S1 可用：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
====
. 在運作中的交換器上執行 `show lldp neighbors`命令，以確認可以看到兩個節點和所有機櫃：
+
`show lldp neighbors`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




[[step-2-configure-cabling]]
=== 步驟 2：設定纜線

. [[five]]檢查儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
====
. 拆下連接到儲存交換器 S2 的所有電纜。
. 將所有電纜重新連接到替換交換器 NS2。




[[step-3-verify-all-device-configurations-on-switch-ns2]]
=== 步驟 3：驗證交換器 NS2 上的所有裝置組態

. 驗證儲存節點連接埠的健全狀況：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 確認兩台交換器均可用：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
====
. 檢查儲存系統中的貨架連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
====
. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
link:../switch-cshm/config-overview.html["配置交換器健康監控"]
