---
permalink: switch-cisco-3232c/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: 您可以執行特定的工作順序、不中斷地更換故障的Cisco Nexus 3232C儲存交換器。 
---
= 更換Cisco Nexus 3232C儲存交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟更換故障的Cisco Nexus 3232C儲存交換器。這是不中斷營運的程序。



== 檢閱要求

現有的網路組態必須具有下列特性：

* 「Cisco乙太網路交換器」頁面提供您交換器上最新的RCF和NX-OS版本。
* 兩台交換器都必須具備管理連線能力。
+
[NOTE]
====
請確定已完成所有疑難排解步驟、以確認您的交換器需要更換。

====


更換的Cisco Nexus 3232C交換器必須具備下列特性：

* 管理網路連線功能必須正常。
* 更換交換器的主控台存取必須已就緒。
* 必須將適當的RCF和NX-OS作業系統映像載入交換器。
* 交換器的初始自訂必須完成。




== 更換交換器

此程序會以新的3232C交換器NS2取代第二個Nexus 3232C儲存交換器S2。這兩個節點分別是node1和node2。



=== 步驟1：確認要更換的交換器為S2

. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 下列訊息來抑制自動建立案例：「System Node AutoSupport 支援功能叫用節點*-type all - Message MAn=xh」
+
_x_是維護時段的持續時間（以小時為單位）。

+
[NOTE]
====
此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

====
. 檢查儲存節點連接埠的健全狀況、確定已連線至儲存交換器S1：
+
「torage port show -port-type ENET」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. 確認儲存交換器S1可用：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
====
. 執行 `show lldp neighbors` 在工作交換器上執行命令、確認您可以同時看到節點和所有磁碟櫃：
+
`show lldp neighbors`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== 步驟2：設定纜線

. [[五]驗證儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
====
. 拔下連接至儲存交換器S2的所有纜線。
. 將所有纜線重新連接至更換的交換器NS2。




=== 步驟3：檢查交換器NS2上的所有裝置組態

. 驗證儲存節點連接埠的健全狀況：
+
「torage port show -port-type ENET」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 確認兩個交換器都可用：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
====
. 驗證儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
====
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」


