---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: 完成 Cisco Nexus 3232C 叢集交換器的佈線工作表，以記錄連接埠連線及支援的平台組態。 
---
= 完成 Cisco Nexus 3232C 佈線工作表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
完成 Cisco Nexus 3232C 叢集交換器的佈線工作表，以記錄連接埠連線及支援的平台組態。

範例佈線工作表提供了從交換器到控制器的建議連接埠分配範例。空白工作表提供了一個模板，您可以在設定叢集時使用該模板。

每個交換器可設定為單一 100GbE 連接埠、40GbE 連接埠或 4 x 10GbE 連接埠。



[[sample-cabling-worksheet]]
== 佈線工作表範例

每對交換器上的範例連接埠定義如下：

[cols="1, 1, 1, 1"]
|===
2+| 集群開關 A 2+| 集群開關 B 


| 交換器埠 | 節點和連接埠使用情況 | 交換器埠 | 節點和連接埠使用情況 


 a| 
1
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
1
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
2
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
2
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
3
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
3
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
4
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
4
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
5
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
5
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
6
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
6
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
7
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
7
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
8
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
8
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
9
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
9
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
10
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
10
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
11
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
11
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
12
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
12
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
13
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
13
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
14
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
14
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
15
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
15
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
16
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
16
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
17
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
17
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
18
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點
 a| 
18
 a| 
4x10GbE/4x25GbE 或 40/100GbE 節點



 a| 
19
 a| 
40G/100GbE 節點 19
 a| 
19
 a| 
40G/100GbE 節點 19



 a| 
20
 a| 
40G/100GbE 節點 20
 a| 
20
 a| 
40G/100GbE 節點 20



 a| 
21
 a| 
40G/100GbE 節點 21
 a| 
21
 a| 
40G/100GbE 節點 21



 a| 
22
 a| 
40G/100GbE 節點 22
 a| 
22
 a| 
40G/100GbE 節點 22



 a| 
23
 a| 
40G/100GbE 節點 23
 a| 
23
 a| 
40G/100GbE 節點 23



 a| 
24
 a| 
40G/100GbE 節點 24
 a| 
24
 a| 
40G/100GbE 節點 24



 a| 
25至30
 a| 
預訂的
 a| 
25至30
 a| 
預訂的



 a| 
31
 a| 
100GbE ISL 連接至交換器 B 連接埠 31
 a| 
31
 a| 
100GbE ISL 連接至交換器 A 連接埠 31



 a| 
32
 a| 
100GbE ISL 連接至交換器 B 連接埠 32
 a| 
32
 a| 
100GbE ISL 連接至交換器 A 連接埠 32

|===


[[blank-cabling-worksheet]]
== 空白佈線工作表

您可以使用空白的佈線工作表來記錄叢集中支援的節點平台。  《支援的集群連結》部分 https://hwu.netapp.com["Hardware Universe"^]定義平台使用的叢集連接埠。

[cols="1, 1, 1, 1"]
|===
2+| 集群開關 A 2+| 集群開關 B 


| 交換器埠 | 節點/連接埠使用情況 | 交換器埠 | 節點/連接埠使用情況 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25至30
 a| 
預訂的
 a| 
25至30
 a| 
預訂的



 a| 
31
 a| 
100GbE ISL 連接至交換器 B 連接埠 31
 a| 
31
 a| 
100GbE ISL 連接至交換器 A 連接埠 31



 a| 
32
 a| 
100GbE ISL 連接至交換器 B 連接埠 32
 a| 
32
 a| 
100GbE ISL 連接至交換器 A 連接埠 32

|===
.下一步
完成佈線工作表後，您可以link:install-switch-3232c.html["安裝開關"]。
