---
permalink: switch-cisco-3232c/setup-switch.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 如果您還沒有必要的組態資訊和文件、則必須先收集這些資訊、再設定叢集和管理網路交換器。 
---
= 設定3232C叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請遵循此程序來設定及設定Cisco Nexus 3232C交換器。

.您需要的產品
* 存取安裝站台的HTTP、FTP或TFTP伺服器、下載適用的NX-OS和參考組態檔（RCF）版本。
* 適用的NX-OS版本、可從下載 https://["Cisco軟體下載"^] 頁面。
* 必要的叢集網路和管理網路交換器文件。
+
請參閱 link:required-documentation-3232c.html["必要文件"] 以取得更多資訊。

* 必要的控制器文件與ONTAP 資訊文件。
+
https://["NetApp文件"^]

* 適用的授權、網路與組態資訊、以及纜線。
* 完成佈線工作表。
* 適用的NetApp叢集網路和管理網路RCT、可從NetApp 支援網站 下列網址下載 http://["mysupport.netapp.com"^] 適用於您收到的交換器。所有Cisco叢集網路和管理網路交換器都會以標準Cisco原廠預設組態送達。這些交換器也有NX-OS軟體的最新版本、但未載入RCFs。


.步驟
. 將叢集網路和管理網路交換器與控制器架起。
+
[cols="1,2"]
|===
| 如果您要安裝... | 然後... 


 a| 
NetApp系統機櫃中的Cisco Nexus 3232C
 a| 
請參閱NetApp機櫃指南中的安裝Cisco Nexus 3232C叢集交換器與傳遞面板、以取得在NetApp機櫃中安裝交換器的指示。



 a| 
電信機架中的設備
 a| 
請參閱交換器硬體安裝指南中提供的程序、以及NetApp安裝與設定說明。

|===
. 使用完整的佈線工作表、將叢集網路和管理網路交換器連接至控制器。
. 開啟叢集網路和管理網路交換器和控制器的電源。
. 執行叢集網路交換器的初始組態。
+
在您第一次開機交換器時、針對下列初始設定問題提供適當的回應。您站台的安全性原則會定義要啟用的回應和服務。

+
[cols="1,2"]
|===
| 提示 | 回應 


 a| 
中止自動資源配置並繼續正常設定？（是/否）
 a| 
回應* yes *。預設值為「否」



 a| 
是否要強制執行安全密碼標準？（是/否）
 a| 
回應* yes *。預設值為yes。



 a| 
輸入admin的密碼。
 a| 
預設密碼為「admin」；您必須建立新的強式密碼。弱密碼可能會遭到拒絕。



 a| 
是否要進入基本組態對話方塊？（是/否）
 a| 
在交換器的初始組態中回應* yes *。



 a| 
建立另一個登入帳戶？（是/否）
 a| 
您的答案取決於您站台的原則、取決於替代系統管理員。預設值為*否*。



 a| 
設定唯讀SNMP社群字串？（是/否）
 a| 
回應*否*。預設值為「否」



 a| 
設定讀寫SNMP社群字串？（是/否）
 a| 
回應*否*。預設值為「否」



 a| 
輸入交換器名稱。
 a| 
交換器名稱上限為63個英數字元。



 a| 
是否繼續頻外（mgmt0）管理組態？（是/否）
 a| 
在該提示字元中以* yes *（預設值）回應。在mgmt0 ipv4位址：提示字元中、輸入您的IP位址：ip_address.



 a| 
設定預設閘道？（是/否）
 a| 
回應* yes *。在「Default-gateway:（預設閘道：）」提示字元的IPV4位址、輸入您的預設閘道。



 a| 
設定進階IP選項？（是/否）
 a| 
回應*否*。預設值為「否」



 a| 
啟用Telnet服務？（是/否）
 a| 
回應*否*。預設值為「否」



 a| 
啟用SSH服務？（是/否）
 a| 
回應* yes *。預設值為yes。


NOTE: 建議在使用叢集交換器健全狀況監視器（CSHM）進行記錄收集功能時使用SSH。我們也建議使用SSHv2來增強安全性。



 a| 
輸入您要產生的SSH金鑰類型（DSA/RSA/rsa1）。
 a| 
預設值為* RSA*。



 a| 
輸入金鑰位元數（1024-2048）。
 a| 
輸入1024-2048之間的金鑰位元數。



 a| 
設定NTP伺服器？（是/否）
 a| 
回應*否*。預設值為「否」



 a| 
設定預設介面層（L3/L2）：
 a| 
回應* L2*。預設值為L2。



 a| 
設定預設交換器連接埠介面狀態（關機/節點關機）：
 a| 
使用* noshut*回應。預設值為noshut。



 a| 
設定CoPP系統設定檔（嚴格/中等/輕度/高密度）：
 a| 
回應*嚴格*。預設為嚴格。



 a| 
是否要編輯組態？（是/否）
 a| 
此時您應該會看到新的組態。檢閱您剛輸入的組態、並進行必要的變更。如果您對組態感到滿意、請在提示字元中回應*否*。如果您要編輯組態設定、請使用* yes *回應。



 a| 
使用此組態並加以儲存？（是/否）
 a| 
回應* yes *以儲存組態。這會自動更新Kickstart和系統映像。


NOTE: 如果您在此階段未儲存組態、下次重新啟動交換器時、將不會有任何變更生效。

|===
. 確認您在設定結束時所顯示的顯示器上所做的組態選擇、並確定您已儲存組態。
. 檢查叢集網路交換器的版本、必要時可從將NetApp支援的軟體版本下載至交換器 https://["Cisco軟體下載"^] 頁面。


.接下來呢？
link:prepare-install-cisco-nexus-3232c.html["準備安裝NX-OS和RCF"]。
