---
permalink: switch-cisco-3232c/task-upgrade-nx-os-software-and-rcfs-on-cisco-nexus-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: Cisco NX-OS軟體與參考組態檔（RCT）可在Cisco Nexus 3232C儲存交換器上升級。 
---
= 升級Cisco Nexus 3232C儲存交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco NX-OS軟體與參考組態檔（RCT）可在Cisco Nexus 3232C儲存交換器上升級。

在升級儲存交換器上的NX-OS軟體和RCFs之前、必須符合下列條件：

* 交換器必須完全正常運作（記錄中不應有錯誤或類似問題）。
* 如果您只安裝NX-OS並保留目前的RCF版本、則必須在RCF中檢查或設定所需的開機變數、以反映所需的開機映像。
+
如果您需要變更開機變數以反映目前的開機映像、則必須在重新套用RCF之前執行此動作、以便在未來重新開機時產生正確的版本。

* 您必須參閱上提供的適當軟體與升級指南 http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Cisco Nexus 3000系列交換器"^] 頁面以取得Cisco儲存設備升級與降級程序的完整文件。
* 10 GbE和40/100 GbE連接埠的數量是在上可用的參考組態檔（RCFs）中定義 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco®乙太網路交換器"^] 頁面。


*程序摘要：*

* 我檢查交換器和連接埠的健全狀況（,步驟1- ,4.）*
* 二將RCF複製到Cisco交換器S2（,步驟5. - ,8.）*
* 三將NX-OS映像下載至Cisco交換器S2並重新開機（,步驟9. - ,12.）*
* 四重新檢查交換器和連接埠的健全狀況（,步驟13 - ,15）*
* 五重複 ,步驟1- ,17 適用於Cisco交換器S1.**


本程序中的範例使用兩個節點：節點1具有兩個儲存連接埠、節點2則有兩個儲存連接埠。請參閱 link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 驗證平台上的儲存連接埠是否正確。


NOTE: 命令輸出可能會因ONTAP 不同版本的不相同而有所差異。

本程序中的範例使用下列交換器和節點命名法：

* 這兩個儲存交換器的名稱分別為S1和S2。
* 節點是node1和node2。



NOTE: 此程序需要同時使用ONTAP 支援指令和Cisco Nexus 3000系列交換器的命令；ONTAP 除非另有說明、否則會使用支援指令。

.步驟
. [[step1_upgrade_3232c].如果AutoSupport 此叢集已啟用Section,請叫用AutoSupport 下列訊息來抑制自動建立個案：「System nodeeseXreoke AutoSupport -node*-type all - Message MAn=xh」
+
_x_是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

. 檢查儲存交換器是否可用：「System switches Ethernet show」
+
[listing]
----
storage::*> system switch ethernet show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
. 驗證節點連接埠是否正常運作：「torage port show -port-type ENET」
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. [[step4_upgrade_3232c]]檢查叢集是否有儲存交換器或纜線問題：「System health alerting show -instance」（系統健全狀況警示顯示-instance）
+
[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step5_upgrade_3232c]]使用下列傳輸協定之一、將交換器S2上的RCF複製到交換器bootflash：FTP、HTTP、TFTP、SFTP或scp。
+
如需Cisco命令的詳細資訊、請參閱中的適當指南 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000系列NX-OS命令參考資料"^]。

+
以下範例顯示HTTP用於將RCF複製到交換器S2上的bootflash：

+
[listing]
----
S2# copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:–   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
S2#
----
. 將先前下載的RCF套用至bootflash：「copy bootflash:」
+
以下範例顯示交換器S2上安裝的RCF檔案「Nexus _3232C_RCF-v1.6-Storage.txt'：

+
[listing]
----
S2# copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands
----
. 確認RCF檔案為正確的更新版本：「How RF-config」
+
當您檢查輸出以確認您擁有正確的RCF時、請確定下列資訊正確無誤：

+
** RCF橫幅
** 節點和連接埠設定
** 自訂輸出會根據您的站台組態而有所不同。請檢查連接埠設定、並參閱版本說明、以瞭解您安裝的RCF的任何特定變更。


+
[NOTE]
====
在「show banner motd」命令的橫幅輸出中、您必須閱讀並遵循「*重要附註*」一節中的指示、以確保交換器的組態和操作正確。

====
+
[listing]
----
S2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
S2#
----
+

NOTE: 第一次套用RCF時、預期會出現*錯誤：無法寫入VSH命令*訊息、因此可以忽略。

. [[step8_upgrade_3232c]驗證軟體版本和交換器設定是否正確之後、請將「執行組態」檔案複製到交換器S2上的「啟動組態」檔案。
+
如需Cisco命令的詳細資訊、請參閱中的適當指南 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000系列NX-OS命令參考資料"^]。

+
以下範例顯示「執行組態」檔案已成功複製到「儲存組態」檔案：

+
[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
----
. [step9_upgrade_3232c]將NX-OS映像下載至交換器S2。
. 安裝系統映像、以便下次重新啟動交換器S2時載入新版本。
+
交換器會在10秒內重新開機、並顯示新映像、如下面的輸出所示：

+
[listing]
----
S2# install all nxos bootflash:nxos.9.3.4.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n]  y
input string too long
Do you want to continue with the installation (y/n)?  [n] y

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
S2#
----
. 儲存組態。
+
如需Cisco命令的詳細資訊、請參閱中的適當指南 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000系列NX-OS命令參考資料"^]。

+
系統會提示您重新開機、如下例所示：

+
[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
S2# reload
This command will reboot the system. (y/n)?  [n] y
----
. [[step12_upgrade_3232c]]確認交換器上有新的NX-OS版本號：
+
[listing]
----
S2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

S2#
----
. [[step13_upgrade_3232c]]重新開機後、請檢查儲存交換器是否可用：「System switches Ethernet show」
+
[listing]
----
storage::*> system switch ethernet show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
. 重新開機後、請確認交換器連接埠正常運作：「torage port show -port-type ENET」
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. [[step15_upgrade_3232c]]重新檢查叢集是否有儲存交換器或纜線問題：「系統健全狀況警示顯示-instance」
+
[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. 重複此程序、升級交換器S1上的NX-OS軟體和RCF。
. [[step17_upgrade_3232c]]如果您禁止自動建立個案、請叫用AutoSupport 「System nodees/setoke AutoSupport -node*-type all -Message MAn=end」訊息來重新啟用此功能

