---
permalink: switch-cisco-3232c/task-install-nx-os-software-and-rcfs-on-cisco-nexus-3232-cluster-switches-running-ontap-9-4-and-later.html 
sidebar: sidebar 
keywords: nx-os software, install, cisco nexus cluster switches, 3232c, rcfs 
summary: Cisco NX-OS軟體和參考組態檔（RCT）必須安裝在Cisco Nexus 3232C叢集交換器上。 
---
= 在Cisco Nexus 3232C叢集交換器上安裝NX-OS軟體和RCT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco NX-OS軟體和參考組態檔（RCT）必須安裝在Cisco Nexus 3232C叢集交換器上。

在叢集交換器上安裝NX-OS軟體和參考組態檔（RCT）之前、必須符合下列條件：

* 叢集必須完全正常運作（記錄或類似的-sues不應有錯誤）。
* 如果您只安裝NX-OS並保留目前的RCF版本、則必須在RCF中檢查或設定所需的開機組態、以反映所需的開機映像。
* 如果您需要變更開機組態以反映目前的開機映像、則必須在重新套用RCF之前執行此動作、以便在未來重新開機時產生正確的版本。
* 安裝RCF時、您必須有與交換器的主控台連線。
* 您必須查閱上的交換器相容性表 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換器頁面"^] 支援ONTAP 的支援版本包括：支援的支援版、NX-OS和RCF。
* RCF中的命令語法與NX-OS版本中的命令語法之間可能存在相依性。
* 您必須參閱Cisco網站上提供的適當軟體與升級指南、以取得Cisco交換器升級與降級程序的完整文件 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000系列交換器"^]。
* 您必須擁有目前的RCF。


本程序中的範例使用兩個節點。這些節點使用兩個10GbE叢集互連連接埠「e0a」和「e0b」。

請參閱 link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 驗證平台上的叢集連接埠是否正確。

[NOTE]
====
命令輸出可能會因ONTAP 不同版本的不相同而有所差異。

====
本程序中的範例使用下列交換器和節點命名法：

* 兩個Cisco交換器的名稱分別為「CS1」和「CS2」。
* 節點名稱為「cluster1-01」和「cluster1-02」。
* 叢集LIF的名稱為「cluster1-01_clus1」、叢集式為「cluster1-01_clus2」、叢集式為「cluster1-02_clus1」、叢集式為「cluster1-02_clus2」。
* 「cluster1：*：>」提示會指出叢集的名稱。


[NOTE]
====
此程序需要同時使用ONTAP 支援指令和Cisco Nexus 3000系列交換器的命令；ONTAP 除非另有說明、否則會使用支援指令。

====
.步驟
. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 下列訊息來抑制自動建立案例：「System Node AutoSupport Rsepooke -Node *-type all -most MAn=x h」
+
其中_x_是維護時段的持續時間（以小時為單位）。

+
[NOTE]
====
此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

====
. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
"進階權限"

+
出現進階提示（「*>」）。

. 顯示每個叢集互連交換器的每個節點已設定多少個叢集互連介面：「network device-dDiscovery show -protocol cup」
+
[listing]
----
cluster1::*> network device-discovery show -protocol cdp

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e0a    cs1                       Eth1/2            N3K-C3232C
            e0b    cs2                       Eth1/2            N3K-C3232C
cluster1-01/cdp
            e0a    cs1                       Eth1/1            N3K-C3232C
            e0b    cs2                       Eth1/1            N3K-C3232C

4 entries were displayed.
----
. 檢查每個叢集介面的管理或作業狀態。
+
.. 顯示網路連接埠屬性：「network port show–IPSpace Cluster（網路連接埠顯示–IPSpace叢集）」
+
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: cluster1-02
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: cluster1-01
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
.. 顯示有關生命的資訊：「網路介面show -vserver叢集」
+
[listing]
----
cluster1::*> network interface show -vserver Cluster

            Logical            Status     Network            Current       Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node          Port    Home
----------- ------------------ ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01   e0a     true
            cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01   e0b     true
            cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02   e0a     true
            cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02   e0b     true

4 entries were displayed.
----


. Ping遠端叢集lifs：「cluster ping-cluster -node-node-name_」
+
[listing]
----

cluster1::*> **cluster ping-cluster -node cluster1-02**
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. 驗證是否已在所有叢集lifs上啟用「自動還原」命令：「network interface show -vserver cluster -Fields autover-f還原」
+
[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface           Auto-revert
--------- ––––––-------------- ------------
Cluster
          cluster1-01_clus1   true
          cluster1-01_clus2   true
          cluster1-02_clus1   true
          cluster1-02_clus2   true
4 entries were displayed.
----
. 針對《支援乙太網路》9.8及更新版本、請使用「系統交換器乙太網路記錄設定密碼」命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔ONTAP
+
「系統交換器乙太網路記錄啟用收集」

+
[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system  switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+
[NOTE]
====
如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

====
. 針對發行9.5P16、9.6P12和9.7P10及更新版本的修補程式、請使用「System叢集-交換器記錄設定密碼」命令、啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔ONTAP
+
「系統叢集交換器記錄啟用收集」

+
[listing]
----
cluster1::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+
[NOTE]
====
如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

====

