---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: 了解FAS和AFF系統的新型交換器。 
---
= 交換器有什麼新變化
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解FAS和AFF系統的新型交換器。有關交換機的更多信息，請參閱 https://hwu.netapp.com/Switch/Index["NetAppHardware Universe"^]。



== 新交換器支持

[cols="25h,~,~"]
|===
| 開關 | 描述 | 可開始 


 a| 
32 連接埠 400GbECisco交換器（X190300-CS-PI 和 X190300-PE）
 a| 
Cisco 9332D-GX2B 叢集內/HA/儲存交換器支援。
 a| 
ONTAP 9.17.1



 a| 
64埠400GbECisco交換器（X190310-CS-PI）
 a| 
Cisco 9364D-GX2A 叢集內/HA/儲存交換器支援。
 a| 
ONTAP 9.17.1



 a| 
12 連接埠 10/25/40/100GbE Cisco Nexus 9336C-FX2-T 叢集和儲存交換器（X190212-CS-PE 和 X190212-CS-PI）
 a| 
支援 10/25/40/100GbE 叢集配置和 100GbE 儲存（交換器連接儲存）配置。
 a| 
ONTAP 9.10.1



 a| 
12 連接埠 10/25/40/100GbE Cisco Nexus 9336C-FX2-T 叢集和儲存交換器（X190212-CS-PE 和 X190212-CS-PI）
 a| 
支援 10/25/40/100GbE 叢集配置和 100GbE 儲存（交換器連接儲存）配置。
 a| 
ONTAP 9.10.1



 a| 
16埠100GbE NVIDIA交換器（X190006-PE和X190006-PI）
 a| 
支援NVIDIA SN2100 叢集互連交換器和儲存交換機，包括支援MetroCluster IP 配置。
 a| 
ONTAP 9.10.1



 a| 
36埠100GbECisco交換器（X190200-CS-PE和X190200-CS-PI）
 a| 
支援在同一對Cisco Nexus 9336C-FX2 交換器上共用基礎架構（叢集、HA 和交換器附加儲存），包括對MetroCluster IP 配置的支援。
 a| 
ONTAP 9.9.1



 a| 
36埠100GbECisco交換器（X190200-CS-PE和X190200-CS-PI），（X190210-FE-PE和X190210-FE-PI）
 a| 
Cisco Nexus 9336C-FX2 叢集互連交換器和儲存交換器支援AFF和ASA儲存系統，以及前端資料連線。
 a| 
ONTAP 9.8



 a| 
博通 BES-53248 交換器（X190005 和 X190005R）
 a| 
Broadcom BES-53248 群集互連交換器支援AFF/ FAS控制器，具有 10/25GbE 和 40/100GbE 連接埠。
 a| 
ONTAP 9.8



 a| 
36埠100GbECisco交換器（X190200）及32埠100GbECisco交換器（X190100和X190100R）
 a| 
Cisco Nexus 3232C 儲存交換器支援連接 NS224 NVMe 磁碟機架AFF和ASA儲存系統：

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===