---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: 在設定NVIDIA SN2100交換器之前、請先檢閱下列資訊。 
---
= 檢閱纜線佈線和組態考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定NVIDIA SN2100交換器之前、請先檢閱下列考量事項。



== NVIDIA連接埠詳細資料

|===


| *交換器連接埠* | *連接埠使用率* 


 a| 
swp1s-3
 a| 
4個10GbE中斷叢集連接埠節點



 a| 
swp2s-3
 a| 
4個25GbE中斷叢集連接埠節點



 a| 
swp3-14
 a| 
40/100叢集連接埠節點



 a| 
swp15-16
 a| 
40/100交換器間連結（ISL）連接埠

|===
請參閱 https://hwu.netapp.com/Switch/Index["Hardware Universe"^] 如需交換器連接埠的詳細資訊、



== 光纖連線

對於CummUS Linux 4.4.2、只有具有X1151A NIC、X1146A NIC或內建100GbE連接埠的SN2100交換器才支援光纖連線。例如：

* 連接埠e0a和e0b上的SI-A800 AFF
* 連接埠e0g和e0h上的E320 AFF


對於CummUS Linux 4.4.3及更新版本、需要進行下列組態變更、才能修正此問題。

. 將下列兩行新增至 `/etc/cumulus/switchd.conf` 每個<n> 使用40/100GbE銅線的連接埠（swjpg）檔案：
+
** `interface.swp<n>.enable_media_depended_linkup_flow=TRUE`
** `interface.swp<n>.enable_short_tuning=TRUE`


. 重新啟動switchd精靈： `systemctl restart switchd`


請參閱下列內容 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric_Interconnect_and_Management_Switches/NVIDIA_SN2100_switch_fails_to_connect_using_40_100GbE_copper_cable["KB"^] 以取得更多詳細資料。

.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp3*
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp6*
interface.swp6.enable_media_depended_linkup_flow=TRUE
interface.swp6.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$
----
====


== QSA介面卡

當使用QSA介面卡連線至平台上的內建叢集連接埠時、可能不會出現連結。

若要解決此問題、請執行下列步驟：

* 若為10G、請手動將swp1s-3連結速度設為10000、並將自動交涉設為關。
* 若為25G、請手動將swp2s-3連結速度設為25000、並將自動交涉設為關。



NOTE: 使用10G/25G QSA時、請將其插入不中斷的40/100G連接埠。請勿將QSA介面卡插入設定為中斷的連接埠。



== 設定中斷連接埠的介面速度

視交換器連接埠中的收發器而定、您可能需要將交換器介面上的速度設定為固定速度。如果使用10G和25G離線連接埠、請確定自動交涉已關閉、並硬設定交換器的介面速度。例如：

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ net add int swp1s3 link autoneg off && net com
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
.接下來呢？
link:install-cable-shelves-sn2100-cluster.html["將NS224磁碟櫃纜線當作交換器附加儲存設備"]。
