---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-cluster.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: '當交換器運行 Cumulus Linux 或 ONIE 時，可以安裝 Cumulus Linux (CL) 作業系統。' 
---
= 以 ONIE 模式安裝 Cumulus Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當交換器運作在 ONIE 模式下時，請依照下列步驟安裝 Cumulus Linux (CL) 作業系統。


NOTE: Cumulus Linux (CL) 作業系統可以在交換器執行 ONIE 或 Cumulus Linux 時安裝（請參閱）。link:install-cumulus-mode-sn2100-cluster.html["以 Cumulus 模式安裝"] ）。

.關於此任務
您可以使用開放網路安裝環境 (ONIE) 安裝 Cumulus Linux，該環境允許自動發現網路安裝程式映像。這有助於實現透過作業系統選擇（例如 Cumulus Linux）來保護交換器的系統模型。使用 ONIE 安裝 Cumulus Linux 最簡單的方法是透過本機 HTTP 發現。


NOTE: 如果您的主機支援 IPv6，請確保它正在執行 Web 伺服器。如果您的主機支援 IPv4，請確保除了 Web 伺服器之外，它還執行 DHCP 服務。

本過程示範了管理員在 ONIE 啟動後如何升級 Cumulus Linux。

.步驟
[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. 將 Cumulus Linux 安裝檔下載到 Web 伺服器的根目錄。將此文件重新命名為： `onie-installer` 。
. 使用乙太網路線將主機連接到交換器的管理乙太網路連接埠。
. 打開開關電源。
+
交換器下載 ONIE 鏡像安裝程式並啟動。安裝完成後，終端機視窗中會出現 Cumulus Linux 登入提示字元。

+

NOTE: 每次安裝 Cumulus Linux 時，整個檔案系統結構都會被擦除並重建。

. 重啟SN2100交換器：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. 在 GNU GRUB 畫面上按 *Esc* 鍵中斷正常的啟動過程，選擇 *ONIE*，然後按 *Enter* 鍵。
. 在下一個畫面上，選擇 *ONIE：安裝作業系統*。
. ONIE 安裝程式發現程序會執行以搜尋自動安裝程式。按 *Enter* 鍵暫時停止該行程。
. 當發現過程停止時：
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. 如果您的網路正在執行 DHCP 服務，請驗證 IP 位址、子網路遮罩和預設閘道是否已正確指派：
+
`ifconfig eth0`

+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
. 如果 IP 位址方案是手動定義的，請執行下列操作：
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. 重複步驟 9 以驗證靜態資訊是否已正確輸入。
. 安裝 Cumulus Linux：
+
[listing]
----
# onie-nos-install http://<web-server>/<path>/cumulus-linux-4.4.3-mlx-amd64.bin
----
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. 安裝完成後，登入交換器。
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. 請驗證 Cumulus Linux 版本： `net show version`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----


--
.Cumulus Linux 5.x
--
. 將 Cumulus Linux 安裝檔下載到 Web 伺服器的根目錄。將此文件重新命名為： `onie-installer` 。
. 使用乙太網路線將主機連接到交換器的管理乙太網路連接埠。
. 打開開關電源。
+
交換器下載 ONIE 鏡像安裝程式並啟動。安裝完成後，終端機視窗中會出現 Cumulus Linux 登入提示字元。

+

NOTE: 每次安裝 Cumulus Linux 時，整個檔案系統結構都會被擦除並重建。

. 重啟SN2100交換器：
+
[listing]
----
cumulus@cumulus:mgmt:~$ sudo reboot
.
.
GNU GRUB version 2.06-3
+-------------------------------------------------------------------------+
| Cumulus-Linux GNU/Linux                                                 |
| Advanced options for Cumulus-Linux GNU/Linux                            |
| ONIE                                                                    |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
----
. 在 GNU GRUB 畫面上按 Esc 鍵中斷正常的啟動過程，選擇 ONIE，然後按 Enter 鍵。
+
[listing]
----
.
.
Loading ONIE ...

GNU GRUB version 2.02
+-------------------------------------------------------------------------+
| ONIE: Install OS                                                        |
| ONIE: Rescue                                                            |
| ONIE: Uninstall OS                                                      |
| ONIE: Update ONIE                                                       |
| ONIE: Embed ONIE                                                        |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
----
+
選擇 ONIE：*安裝作業系統*。

. ONIE 安裝程式發現程序會執行以搜尋自動安裝程式。按 *Enter* 鍵暫時停止該行程。
. 當發現過程停止時：
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. 配置IP位址、子網路遮罩和預設網關：
+
`ifconfig eth0`

+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ #
ONIE:/ # *ifconfig eth0 10.228.140.27 netmask 255.255.248.0*
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet HWaddr B8:CE:F6:5E:05:E6
       inet addr:10.228.140.27 Bcast:10.228.143.255 Mask:255.255.248.0
       inet6 addr: fd20:8b1e:b255:822b:bace:f6ff:fe5e:5e6/64 Scope:Global
       inet6 addr: fe80::bace:f6ff:fe5e:5e6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
       RX packets:18813 errors:0 dropped:1418 overruns:0 frame:0
       TX packets:491 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:1339596 (1.2 MiB) TX bytes:49379 (48.2 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ # *route add default gw 10.228.136.1*
ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.228.136.1    0.0.0.0         UG    0      0      0   eth0
10.228.136.1    *               255.255.248.0   U     0      0      0   eth0
----
. 安裝 Cumulus Linux 5.4：
+
`# onie-nos-install http://<web-server>/<path>/cumulus-linux-5.4-mlx-amd64.bin`

+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-5.4-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. 安裝完成後，登入交換器。
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. 請驗證 Cumulus Linux 版本： `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. 建立一個新用戶並將該用戶加入到 `sudo`團體。該使用者僅在控制台/SSH會話重新啟動後生效。
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. 新增其他使用者群組以供管理員使用者訪問 `nv`命令：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
看 https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIA使用者帳戶"^]了解更多。



--
====
.下一步是什麼？
在 ONIE 模式下安裝 Cumulus Linux 後，您可以…link:install-rcf-sn2100-cluster.html["安裝參考設定檔 (RCF) 腳本"] 。
