---
permalink: switch-nvidia-sn2100/migrate-cn1610-sn2100-cluster-switch.html 
sidebar: sidebar 
keywords: migrate cluster NVIDIA SN2100 cluster switches cn1610 
summary: 您可以將用於ONTAP叢集的NetApp CN1610 叢集交換器無中斷地移轉到NVIDIA SN2100 叢集網路交換器。 
---
= 將 CN1610 叢集交換器遷移到NVIDIA SN2100 叢集交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將用於ONTAP叢集的NetApp CN1610 叢集交換器移轉到NVIDIA SN2100 叢集交換器。這是一個非破壞性的過程。



== 審查要求

當您以NVIDIA SN2100 叢集交換器取代NetApp CN1610 叢集交換器時，您必須了解某些設定資訊、連接埠連線和佈線需求。看link:configure-overview-sn2100-cluster.html["NVIDIA SN2100交換器的安裝與設定概述"]。

.支援的交換機
支援以下集群交換器：

* NetApp CN1610
* NVIDIA SN2100


有關支援的連接埠及其配置的詳細信息，請參閱 https://hwu.netapp.com/["Hardware Universe"^]。

.開始之前
請確認您的配置符合以下要求：

* 現有叢集已正確設定並正常運作。
* 為確保運作不中斷，所有叢集連接埠均處於*開啟*狀態。
* NVIDIA SN2100 叢集交換器已設定並運行在正確版本的 Cumulus Linux 下，並應用了參考設定檔 (RCF)。
* 現有叢集網路配置如下：
+
** 使用 CN1610 交換器的冗餘且功能齊全的NetApp叢集。
** 對 CN1610 交換器和新交換器的管理連線和控制台存取。
** 所有群集 LIF 均處於啟動狀態，且群集 LIF 均位於其主連接埠上。
** ISL 連接埠已啟用，CN1610 交換器之間以及新交換器之間已連接電纜。


* NVIDIA SN2100 交換器上的一些連接埠配置為以 40GbE 或 100GbE 運作。
* 您已規劃、遷移並記錄了從節點到NVIDIA SN2100 叢集交換器的 40GbE 和 100GbE 連線。




== 遷移交換機

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 現有的 CN1610 叢集交換器是 _c1_ 和 _c2_。
* 新的NVIDIA SN2100 叢集交換器是 _sw1_ 和 _sw2_。
* 節點分別為 _node1_ 和 _node2_。
* 節點 1 上的叢集 LIF 分別為 _node1_clus1_ 和 _node1_clus2_，節點 2 上的叢集 LIF 分別為 _node2_clus1_ 和 _node2_clus2_。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 此過程中使用的叢集連接埠為 _e3a_ 和 _e3b_。
* 分支端口採用以下格式：swp[端口]s[分支端口 0-3]。例如，swp1 上的四個分支連接埠分別是 _swp1s0_、_swp1s1_、_swp1s2_ 和 _swp1s3_。


.關於此任務
本流程涵蓋以下情況：

* 首先將交換器 c2 替換為交換器 sw2。
+
** 關閉叢集節點的連接埠。為避免叢集不穩定，所有連接埠必須同時關閉。
** 然後斷開節點與 c2 之間的電纜與 c2 的連接，並重新連接到 sw2。


* 交換器 c1 被交換器 sw1 取代。
+
** 關閉叢集節點的連接埠。為避免叢集不穩定，所有連接埠必須同時關閉。
** 然後斷開節點與 c1 之間的電纜與 c1 的連接，並重新連接到 sw1。





NOTE: 在此過程中不需要任何可操作的交換器間連結 (ISL)。這是設計使然，因為 RCF 版本的變更可能會暫時影響 ISL 連線。為確保叢集運作不會中斷，以下步驟將所有叢集 LIF 遷移到運作夥伴交換機，同時在目標交換器上執行對應步驟。



=== 步驟 1：準備遷移

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 為維護視窗的持續時間（小時）。

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 停用叢集 LIF 的自動回滾功能：
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





=== 步驟二：設定埠和線纜

. 確定每個叢集介面的管理或運作狀態。
+
每個連接埠都應該顯示出來。 `Link`和 `healthy`為了 `Health Status`。

+
.. 顯示網路連接埠屬性：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. 顯示有​​關 LIF 及其指定歸屬節點的資訊：
+
`network interface show -vserver Cluster`

+
每個 LIF 都應顯示 `up/up`為了 `Status Admin/Oper`和 `true`為了 `Is Home`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. 從節點的角度來看，每個節點上的叢集連接埠透過以下命令以下列方式連接到現有的叢集交換器：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. 叢集連接埠和交換器透過以下命令連接（從交換器的角度來看）：
+
`show cdp neighbors`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124     H          AFF-A400         e3a
node2                 0/2           124     H          AFF-A400         e3a
c2                    0/13          179     S I s      CN1610           0/13
c2                    0/14          175     S I s      CN1610           0/14
c2                    0/15          179     S I s      CN1610           0/15
c2                    0/16          175     S I s      CN1610           0/16

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124    H           AFF-A400         e3b
node2                 0/2           124    H           AFF-A400         e3b
c1                    0/13          175    S I s       CN1610           0/13
c1                    0/14          175    S I s       CN1610           0/14
c1                    0/15          175    S I s       CN1610           0/15
c1                    0/16          175    S I s       CN1610           0/16
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step5]]在交換器 c2 上，關閉連接到節點集群端口的端口，以便集群 LIF 進行故障轉移。
+
[listing, subs="+quotes"]
----
(c2)# *configure*
(c2)(Config)# *interface 0/1-0/12*
(c2)(Interface 0/1-0/12)# *shutdown*
(c2)(Interface 0/1-0/12)# *exit*
(c2)(Config)# *exit*
(c2)#
----
. 將節點叢集連接埠從舊交換器 c2 移至新交換器 sw2，使用NVIDIA SN2100 支援的適當線纜。
. 顯示網路連接埠屬性：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 從節點的角度來看，每個節點上的叢集連接埠現在會以以下方式連接到叢集交換器：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/1               -
            e3b    sw2 (b8:ce:f6:19:1a:7e)   swp3              -
node2      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/2               -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4              -
----
====
. 在交換器 sw2 上，確認所有節點叢集連接埠均已啟動：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 在交換器 c1 上，關閉連接到節點集群端口的端口，以便集群 LIF 進行故障轉移。
+
[listing, subs="+quotes"]
----
(c1)# *configure*
(c1)(Config)# *interface 0/1-0/12*
(c1)(Interface 0/1-0/12)# *shutdown*
(c1)(Interface 0/1-0/12)# *exit*
(c1)(Config)# *exit*
(c1)#
----
. 將節點叢集連接埠從舊交換器 c1 移至新交換器 sw1，使用NVIDIA SN2100 支援的適當線纜。
. 驗證叢集的最終配置：
+
`network port show -ipspace Cluster`

+
每個連接埠應顯示 `up`為了 `Link`和 `healthy`為了 `Health Status`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 從節點的角度來看，每個節點上的叢集連接埠現在會以以下方式連接到叢集交換器：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3            -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4            -
----
====
. 在交換器 sw1 和 sw2 上，驗證所有節點叢集連接埠是否都已啟動：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw2 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw2 (swp16)       Master: cluster_isl(UP)


cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- -----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 確認兩個節點都分別與每個交換器建立了一個連線：
+
`net show lldp`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩種開關的正確結果：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3a
swp4       100G   Trunk/L2    node2               e3a
swp15      100G   BondMember  sw2                 swp15
swp16      100G   BondMember  sw2                 swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3b
swp4       100G   Trunk/L2    node2               e3b
swp15      100G   BondMember  sw1                 swp15
swp16      100G   BondMember  sw1                 swp16
----
====




=== 步驟 3：驗證配置

. 啟用叢集 LIF 的自動回滾功能：
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 在交換器 sw2 上，關閉並重新啟動所有叢集端口，以觸發所有不在它們所屬端口上的叢集 LIF 的自動恢復。


[role="tabbed-block"]
====
.積雲 4.4.3
--
[listing, subs="+quotes"]
----
cumulus@sw2:mgmt:~$ *net add interface swp1-14 link down*
cumulus@sw2:mgmt:~$ *net pending*
cumulus@sw2:mgmt:~$ *net commit*

(Wait for 5-10 seconds before re-enabling the ports)

cumulus@sw2:mgmt:~$ *net add interface swp1-14 link up*
cumulus@sw2:mgmt:~$ *net pending*
cumulus@sw2:mgmt:~$ *net commit*

(After executing the link state up command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)
----
--
.Cumulus 5.x
--
[listing, subs="+quotes"]
----
cumulus@sw2:mgmt:~$ *nv set interface swp1-14 link state down*
cumulus@sw2:mgmt:~$ *nv config apply*
cumulus@sw2:mgmt:~$ *nv show interface*

(Wait for 5-10 seconds before re-enabling the ports)

cumulus@sw2:mgmt:~$ *nv set interface swp1-14 link state up*
cumulus@sw2:mgmt:~$ *nv config apply*
cumulus@sw2:mgmt:~$ *nv show interface*

(After executing the link state up command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)
----
--
====
. [[步驟3]]驗證叢集 LIF 是否已恢復到其原始連接埠（這可能需要一分鐘）：
+
`network interface show -vserver Cluster`

+
如果叢集中的任何 LIF 尚未恢復到其主端口，請手動將其復原。您必須連接到擁有該 LIF 的本機節點的每個節點管理 LIF 或SP/ BMC系統控制台：

+
`network interface revert -vserver Cluster -lif *`

. 將權限等級改回管理員：
+
`set -privilege admin`

. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
