---
permalink: switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: 如果您有現有的雙節點無交換式叢集環境、可以使用NVIDIA SN2100交換器移轉至雙節點交換式叢集環境、以便擴充至叢集內的兩個節點以外。 
---
= 使用NVIDIA SN2100叢集交換器移轉至雙節點交換叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有現有的雙節點無交換式叢集環境、可以使用NVIDIA SN2100交換器移轉至雙節點交換式叢集環境、以便擴充至叢集內的兩個節點以外。

您使用的程序取決於每個控制器上是否有兩個專屬的叢集網路連接埠、或每個控制器上是否有一個叢集連接埠。記錄的程序適用於所有使用光纖或雙軸纜線連接埠的節點、但如果節點使用內建10GBASE-T RJ45連接埠來連接叢集網路連接埠、則此交換器不支援此程序。



== 檢閱要求

.雙節點無交換器組態
確保：

* 雙節點無交換器組態已正確設定並正常運作。
* 節點執行ONTAP 的是功能不全的9.10.1P3及更新版本。
* 所有叢集連接埠都處於* up*狀態。
* 所有叢集邏輯介面（LIF）都處於* up*狀態、並位於其主連接埠上。


.NVIDIA SN2100叢集交換器組態
確保：

* 兩台交換器都有管理網路連線功能。
* 有對叢集交換器的主控台存取權。
* NVIDIA SN2100節點對節點交換器和交換器對交換器連線使用雙軸纜線或光纖纜線。
+

IMPORTANT: 請參閱 link:cabling-considerations-sn2100-cluster.html["檢閱纜線佈線和組態考量"] 以瞭解相關注意事項及進一步的詳細資料。。 https://hwu.netapp.com/SWITCH/INDEX["交換器Hardware Universe"^] 也包含纜線的詳細資訊。

* 交換器間連結（ISL）纜線連接至兩個NVIDIA SN2100交換器的交換器交換器連接埠swp15和swp16。
* 完成兩個SN2100交換器的初始自訂、以便：
+
** SN2100交換器正在執行最新版的Cummuls Linux
** 參考組態檔（RCT）會套用至交換器
** 任何站台自訂功能（例如、SMTP、SNMP和SSH）都會在新交換器上設定。
+
。 https://hwu.netapp.com["Hardware Universe"^] 包含平台實際叢集連接埠的最新資訊。







== 移轉交換器

.關於範例
本程序中的範例使用下列叢集交換器和節點命名法：

* SN2100交換器的名稱為_sw1_和_SW2_。
* 叢集SVM的名稱為_node1_和_node2_。
* lifs的名稱分別是節點1上的_node1_clus1_和節點1_clus2_、節點2上的節點2_clus1_和節點2_clus2_。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 此程序中使用的叢集連接埠為_e3a_和_e3c_。
* 中斷連接埠的格式為：swp[port] s[中斷 連接埠0-3]。例如、swp1上的四個中斷連接埠分別是_swp1s0_、_swp1s1_、_swp1s2_和_swp1s3_。




=== 步驟1：準備移轉

. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 「系統節點AutoSupport 支援功能叫用節點*-type all -most MAn=xh」訊息來禁止自動建立案例
+
其中_x_是維護時段的持續時間（以小時為單位）。

. 請將權限等級變更為進階、並在系統提示您繼續時輸入「y」：「et -priv榮幸 進階」
+
出現進階提示（「*>」）。





=== 步驟2：設定連接埠和纜線

. 在新的叢集交換器sw1和SW2上停用所有面向節點的連接埠（非ISL連接埠）。
+
您不得停用ISL連接埠。

+
.顯示範例
[%collapsible]
====
下列命令會停用交換器sw1和SW2上的節點對準連接埠：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 驗證兩個SN2100交換器sw1和SW2之間的ISL和ISL實體連接埠是否在交換器swp15和swp16上開啟：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
下列範例顯示交換器sw1上的ISL連接埠為開啟：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)
----
+以下範例顯示交換器SW2上的ISL連接埠為開啟狀態：

+

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----
====
. 驗證所有叢集連接埠是否正常運作：
+
「網路連接埠展示」

+
應顯示每個連接埠 `up` 適用於 `Link` 而且健康 `Health Status`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. 驗證所有叢集生命體是否正常運作：
+
「網路介面展示」

+
每個叢集LIF都應顯示為true `Is Home` 並擁有 `Status Admin/Oper` 的 `up/up`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. 停用叢集生命體上的自動還原：
+
「網路介面修改-vserver叢集-lIF *-auta-fRevert假」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. 從節點1上的叢集連接埠e3a拔下纜線、然後使用SN2100交換器所支援的適當纜線、將e3a連接至叢集交換器sw1上的連接埠3。
+
。 https://hwu.netapp.com/SWITCH/INDEX["交換器Hardware Universe"^] 包含纜線的詳細資訊。

. 從節點2上的叢集連接埠e3a拔下纜線、然後使用SN2100交換器所支援的適當纜線、將e3a連接至叢集交換器sw1上的連接埠4。
. 在交換器sw1上、啟用所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
下列命令可啟用交換器sw1上的所有面向節點的連接埠：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 在交換器sw1上、確認所有連接埠都已啟動：
+
`net show interface all`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. 驗證所有叢集連接埠是否正常運作：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
以下範例顯示節點1和節點2上的所有叢集連接埠都已啟動：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. 顯示叢集中節點狀態的相關資訊：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
下列範例顯示叢集中節點的健全狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. 從節點1上的叢集連接埠e3b拔下纜線、然後使用SN2100交換器所支援的適當纜線、將e3b連接至叢集交換器SW2上的連接埠3。
. 從節點2上的叢集連接埠e3b拔下纜線、然後使用SN2100交換器所支援的適當纜線、將e3b連接至叢集交換器SW2上的連接埠4。
. 在交換器SW2上、啟用所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
下列命令可在交換器SW2上啟用面向節點的連接埠：

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 在交換器SW2上、確認所有連接埠都正常運作：
+
`net show interface all`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. 在交換器sw1和SW2上、確認兩個節點都有一個連接到每個交換器的連線：
+
`net show lldp`

+
.顯示範例
[%collapsible]
====
下列範例顯示交換器sw1和SW2的適當結果：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====
. 顯示叢集中探索到的網路裝置相關資訊：
+
`net device-discovery show -protocol lldp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. 驗證所有叢集連接埠是否正常運作：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
以下範例顯示節點1和節點2上的所有叢集連接埠都已啟動：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====




=== 步驟3：完成程序

. 在所有叢集生命體上啟用自動還原：
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. 驗證所有介面是否都顯示「true」表示「is Home」：
+
`net interface show -vserver Cluster`

+

NOTE: 這可能需要一分鐘的時間才能完成。

+
.顯示範例
[%collapsible]
====
以下範例顯示所有lifs都在node1和node2上、而且「is Home」結果為真：

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. 確認設定已停用：
+
「網路選項、無交換式叢集展示」

+
.顯示範例
[%collapsible]
====
下列範例中的假輸出顯示組態設定已停用：

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. 驗證叢集中節點成員的狀態：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
下列範例顯示叢集中節點的健全狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 驗證叢集網路是否具備完整連線能力：
+
「叢集ping叢集節點節點名稱」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node1*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. 使用下列命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔：
+
「系統交換器乙太網路記錄設定密碼」和「系統交換器乙太網路記錄啟用-收集」

+
.. 輸入：「System交換器乙太網路記錄設定密碼」
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*sw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
.. 接著是：「系統交換器乙太網路記錄啟用-收集」
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====


+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 啟動交換器記錄收集功能：
+
`system switch ethernet log collect -device *`

+
等待10分鐘、然後使用以下命令檢查記錄收集是否成功：

+
`system switch ethernet log show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
. 將權限層級變更回管理：
+
「et -priv. admin」

. 如果您禁止自動建立個案、請叫用AutoSupport 下列消息來重新啟用此功能：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」


