---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 在不中斷營運的程序中更換有瑕疵的NVIDIA SN2100儲存交換器（NDU）。 
---
= 更換NVIDIA SN2100儲存交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更換NVIDIA SN2100儲存交換器時、您必須注意特定的組態資訊、連接埠連線和纜線需求。

.開始之前
在NVIDIA SN2100儲存交換器上安裝Cummulos軟體和RCFs之前、您必須先確認下列情況是否存在：

* 您的系統可支援NVIDIA SN2100儲存交換器。
* 您必須下載適用的RCT。
* 。 http://hwu.netapp.com["Hardware Universe"^] 提供支援連接埠及其組態的完整詳細資料。


.關於這項工作
現有的網路組態必須具有下列特性：

* 請確定已完成所有疑難排解步驟、以確認您的交換器需要更換。
* 兩台交換器都必須具備管理連線能力。
+

NOTE: 請確定已完成所有疑難排解步驟、以確認您的交換器需要更換。



替換的NVIDIA SN2100交換器必須具備下列特性：

* 管理網路連線功能必須正常。
* 更換交換器的主控台存取必須已就緒。
* 必須將適當的RCF和Cummuls作業系統映像載入交換器。
* 交換器的初始自訂必須完成。


.程序摘要
此程序將第二個NVIDIA SN2100儲存交換器SW2取代為新的NVIDIA SN2100交換器nsw2。這兩個節點分別是node1和node2。

完成步驟：

* 確認要更換的交換器為SW2。
* 從交換器SW2拔下纜線。
* 將纜線重新連接至交換器nsw2。
* 確認交換器nsw2上的所有裝置組態。


.步驟
. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 下列訊息來抑制自動建立案例：「System Node AutoSupport 支援功能叫用節點*-type all - Message MAn=xh」
+
_x_是維護時段的持續時間（以小時為單位）。

. 將權限層級變更為進階、並在系統提示您繼續時輸入* y*：「et -priv家 特權進階」
. 檢查儲存節點連接埠的健全狀況、確定已連線至儲存交換器S1：
+
「torage port show -port-type ENET」

+
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
. 驗證儲存交換器sw1是否可用：「網路裝置探索秀」
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show protocol lldp*
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface   Platform
--------   ----  -----------------------   ---------   ---------
node1/lldp
           e3a   sw1 (b8:ce:f6:19:1b:42)   swp3        -
node2/lldp
           e3a   sw1 (b8:ce:f6:19:1b:42)   swp4        -
cluster1::*>
----
. 在工作交換器上執行「net show介面」命令、確認您可以同時看到節點和所有磁碟櫃：「net show介面」
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
. 驗證儲存系統中的機櫃連接埠：「torage機櫃連接埠show -Fields reme-Device、reme-port」
+
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
. 拔下連接至儲存交換器SW2的所有纜線。
. 將所有纜線重新連接至更換的交換器nsw2。
. 重新檢查儲存節點連接埠的健全狀況：「torage port show -port-type ENET」
+
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
. 確認兩個交換器都可用：「net device-dDiscovery show」
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show protocol lldp*
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/lldp
          e3a  sw1 (b8:ce:f6:19:1b:96)    swp1        -
          e7b  nsw2 (b8:ce:f6:19:1a:7e)   swp1        -
node2/lldp
          e3a  sw1 (b8:ce:f6:19:1b:96)    swp2        -
          e7b  nsw2 (b8:ce:f6:19:1a:7e)   swp2        -
cluster1::*>
----
. 驗證儲存系統中的機櫃連接埠：「torage機櫃連接埠show -Fields reme-Device、reme-port」
+
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
. 使用兩個命令：「ystem switchEthernet log setup-password」（系統交換器乙太網路記錄設定密碼）和「系統交換器乙太網路記錄啟用資料收集」、啟用乙太網路交換器健全狀況監視器記錄收集功能來收集交換器相關的記錄檔
+
輸入：「System交換器乙太網路記錄設定密碼」

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*nsw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *nsw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
接著是：「系統交換器乙太網路記錄啟用-收集」

+
[listing, subs="+quotes"]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 啟動交換器記錄收集功能：「System交換器乙太網路記錄collect -device *」
+
請等待10分鐘、然後使用「ystem switchEthernet log show」命令檢查記錄收集是否成功

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      nsw2 (b8:ce:f6:19:1b:96)     4/29/2022 03:07:42   complete
----
. 將權限等級變更回admin：「et -priv. admin」
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息重新啟用此功能：「System Node AutoSupport 現象叫用節點*-type all -most MAn=end」

