---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia SN2100 
summary: 在叢集網路中更換故障的NVIDIA SN2100交換器、是不中斷營運的程序（NDU）。 
---
= 更換NVIDIA SN2100叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請遵循此程序、在叢集網路中更換故障的NVIDIA SN2100交換器。這是不中斷營運的程序（NDU）。



== 檢閱要求

.現有的叢集與網路基礎架構
確保：

* 現有的叢集已通過驗證為完全正常運作、至少有一個完全連接的叢集交換器。
* 所有叢集連接埠均已啟動。
* 所有叢集邏輯介面（LIF）都在其主連接埠上。
* The The ONTAP `cluster ping-cluster -node node1` Command表示所有路徑上的基本連線能力和大於PMTU的通訊均成功。


.NVIDIA SN2100替換交換器
確保：

* 替換交換器上的管理網路連線功能正常。
* 更換交換器的主控台存取已就緒。
* 節點連線是連接埠swp1到swp14。
* 所有交換器間連結（ISL）連接埠都會停用swp15和swp16上的連接埠。
* 所需的參考組態檔（RCF）和Cummuls作業系統映像交換器會載入。
* 交換器的初始自訂已完成。


此外、請務必將任何先前的站台自訂項目（例如STP、SNMP和SSH）複製到新交換器。


NOTE: 您必須執行命令、從裝載叢集LIF的節點移轉叢集LIF。



== 啟用主控台記錄

NetApp 強烈建議您在使用的裝置上啟用主控台記錄功能、並在更換交換器時採取下列動作：

* 在維護期間保持啟用 AutoSupport 。
* 在維護前後觸發維護 AutoSupport 、以在維護期間停用案例建立。請參閱本知識庫文件 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92 ：如何在排程的維護期間內、禁止自動建立案例"^] 以取得更多詳細資料。
* 啟用任何 CLI 工作階段的工作階段記錄。如需如何啟用工作階段記錄的說明、請參閱本知識庫文件中的「記錄工作階段輸出」一節 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何設定 Putty 以最佳化連線至 ONTAP 系統"^]。




== 更換交換器

.關於範例
本程序中的範例使用下列交換器和節點命名法：

* 現有NVIDIA SN2100交換器的名稱為_sw1_和_SW2_。
* 新NVIDIA SN2100交換器的名稱為_nsw2_。
* 節點名稱是_node1_和_node2_。
* 每個節點上的叢集連接埠名稱為_e3a_和_e3c_。
* 叢集LIF名稱為節點1的_node1_clus1_和節點1的_node1_clus2_、節點2的節點2為_node2_clus1_和節點2為_node2_clus2_。
* 對所有叢集節點進行變更的提示是「cluster1：*>」
* 中斷連接埠的格式為：swp[port] s[中斷 連接埠0-3]。例如、swp1上的四個中斷連接埠分別是_swp1s0_、_swp1s1_、_swp1s2_和_swp1s3_。


.關於叢集網路拓撲
此程序以下列叢集網路拓撲為基礎：

.顯示拓撲範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true


cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
+

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw2                e3a
swp4       100G   Trunk/L2    sw2                e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16


cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw1                e3b
swp4       100G   Trunk/L2    sw1                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====


=== 步驟1：準備更換

. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -Message MAn=xh」

+
其中_x_是維護時段的持續時間（以小時為單位）。

. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
"進階權限"

+
出現進階提示（*>）。

. 在交換器nsw2上安裝適當的RCF和映像、並進行必要的站台準備。
+
如有必要、請為新交換器驗證、下載及安裝適當版本的RCF和Cummuls軟體。

+
.. 您可以從_NVIDIA Support_網站下載適用於叢集交換器的Cummulus軟體。請依照下載頁面上的步驟、下載您ONTAP 所安裝之版本的Cummuls Linux。
.. 您可從取得適當的RCF link:https://mysupport.netapp.com/site/products/all/details/nvidia-cluster-storage-switch/downloads-tab["_NVIDIA叢集與儲存交換器_"^] 頁面。請依照下載頁面上的步驟、針對ONTAP 您要安裝的版本、下載正確的RCF。






=== 步驟2：設定連接埠和纜線

. 在新的交換器nsw2上、以admin身分登入、並關閉所有連接至節點叢集介面的連接埠（連接埠swp1至swp14）。
+
叢集節點上的LIF應已容錯移轉至每個節點的其他叢集連接埠。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
====
. 停用叢集生命體上的自動還原：
+
「網路介面修改-vserver叢集-lIF *-auta-fRevert假」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
====
. 確認所有叢集生命體均已啟用自動還原：
+
`net interface show -vserver Cluster -fields auto-revert`

. 關閉SN2100交換器sw1上的ISL連接埠swp15和swp16。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 從SN2100 sw1交換器拔下所有纜線、然後將其連接至SN2100 nsw2交換器上的相同連接埠。
. 在sw1和nsw2交換器之間啟動ISL連接埠swp15和swp16。
+
.顯示範例
[%collapsible]
====
下列命令可啟用交換器sw1上的ISL連接埠swp15和swp16：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
下列範例顯示交換器sw1上的ISL連接埠為開啟：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+以下範例顯示交換器nsw2上的ISL連接埠為開啟狀態：

+

[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
====
. 驗證該連接埠 `e3b` 在所有節點上都啟動：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
輸出應類似於下列內容：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
====
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
====
. 驗證所有節點叢集連接埠是否正常運作：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 驗證兩個節點各自與每個交換器都有一個連線：
+
`net show lldp`

+
.顯示範例
[%collapsible]
====
以下範例顯示兩個交換器的適當結果：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====
. 在叢集生命體上啟用自動還原：
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 在交換器nsw2上、開啟連接至節點網路連接埠的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net del interface swp1-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
====
. 顯示叢集中節點的相關資訊：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
此範例顯示此叢集中節點1和節點2的節點健全狀況為真：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
====
. 驗證所有實體叢集連接埠是否正常運作：
+
「網路連接埠顯示IPSpace叢集」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----
====




=== 步驟3：驗證組態

. 驗證叢集網路是否正常。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----
====
. 將權限層級變更回管理：
+
「et -priv. admin」

. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」



.接下來呢？
link:../switch-cshm/config-overview.html["設定交換器健全狀況監控"]。
