---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia SN2100 
summary: 'еңЁеҸўйӣҶз¶Іи·ҜдёӯжӣҙжҸӣжңүзјәйҷ·зҡ„NVIDIA SN2100 дәӨжҸӣеҷЁжҳҜдёҖеҖӢйқһдёӯж–·зЁӢеәҸ (NDU)гҖӮ' 
---
= жӣҙжҸӣNVIDIA SN2100 еҸўйӣҶдәӨжҸӣж©ҹ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
и«Ӣдҫқз…§дёӢеҲ—жӯҘй©ҹжӣҙжҸӣеҸўйӣҶз¶Іи·Ҝдёӯзҷјз”ҹж•…йҡңзҡ„NVIDIA SN2100 дәӨжҸӣеҷЁгҖӮйҖҷжҳҜдёҖеҖӢз„Ўдёӯж–·зЁӢејҸ (NDU)гҖӮ



== еҜ©жҹҘиҰҒжұӮ

.зҸҫжңүйӣҶзҫӨе’Ңз¶Іи·ҜеҹәзӨҺиЁӯж–Ҫ
зўәдҝқпјҡ

* зҸҫжңүйӣҶзҫӨе·Ій©—иӯүеҠҹиғҪе®Ңе…ЁжӯЈеёёпјҢиҮіе°‘жңүдёҖеҖӢе®Ңе…ЁйҖЈжҺҘзҡ„йӣҶзҫӨдәӨжҸӣеҷЁгҖӮ
* еҸўйӣҶжүҖжңүйҖЈжҺҘеҹ еқҮе·Іе•ҹеӢ•гҖӮ
* жүҖжңүзҫӨйӣҶйӮҸијҜд»ӢйқўпјҲLIFпјүеқҮе·Іе•ҹеӢ•дёҰдҪҚж–је…¶жүҖеұ¬йҖЈжҺҘеҹ дёҠгҖӮ
* ONTAP `cluster ping-cluster -node node1`жӯӨе‘Ҫд»ӨйЎҜзӨәжүҖжңүи·Ҝеҫ‘дёҠзҡ„еҹәжң¬йҖЈжҺҘе’ҢеӨ§ж–ј PMTU зҡ„йҖҡиЁҠеқҮе·ІжҲҗеҠҹгҖӮ


.NVIDIA SN2100 жӣҝжҸӣй–Ӣй—ң
зўәдҝқпјҡ

* жӣҝжҸӣдәӨжҸӣеҷЁзҡ„з®ЎзҗҶз¶Іи·ҜйҖЈз·ҡеҠҹиғҪжӯЈеёёгҖӮ
* жҺ§еҲ¶еҸ°е·Іе°ұз·’пјҢеҸҜеӯҳеҸ–жӣҝжҸӣй–Ӣй—ңгҖӮ
* зҜҖй»һйҖЈжҺҘеҹ зӮә swp1 иҮі swp14гҖӮ
* swp15 е’Ң swp16 йҖЈжҺҘеҹ дёҠзҡ„жүҖжңүдәӨжҸӣеҷЁй–“йҖЈзөҗ (ISL) йҖЈжҺҘеҹ еқҮе·ІеҒңз”ЁгҖӮ
* жүҖйңҖзҡ„еҸғиҖғиЁӯе®ҡжӘ”пјҲRCFпјүе’Ң Cumulus дҪңжҘӯзі»зөұжҳ еғҸдәӨжҸӣеҷЁе·Іијүе…ҘеҲ°дәӨжҸӣеҷЁдёҠгҖӮ
* дәӨжҸӣеҷЁзҡ„еҲқе§Ӣе®ҡеҲ¶е·Іе®ҢжҲҗгҖӮ


д№ҹиҰҒзўәдҝқе°Үе…ҲеүҚз¶Із«ҷзҡ„жүҖжңүиҮӘиЁӮиЁӯе®ҡпјҲдҫӢеҰӮ STPгҖҒSNMP е’Ң SSHпјүиӨҮиЈҪеҲ°ж–°дәӨжҸӣеҷЁгҖӮ


NOTE: жӮЁеҝ…й ҲеҫһеҸўйӣҶ LIF жүҖеңЁзҡ„зҜҖй»һеҹ·иЎҢйҒ·з§»еҸўйӣҶ LIF зҡ„е‘Ҫд»ӨгҖӮ



== е•ҹз”ЁжҺ§еҲ¶еҸ°ж—ҘиӘҢиЁҳйҢ„

NetAppеј·зғҲе»әиӯ°жӮЁеңЁдҪҝз”Ёзҡ„иЈқзҪ®дёҠе•ҹз”ЁжҺ§еҲ¶еҸ°ж—ҘиӘҢиЁҳйҢ„пјҢдёҰеңЁжӣҙжҸӣдәӨжҸӣеҷЁжҷӮеҹ·иЎҢд»ҘдёӢж“ҚдҪңпјҡ

* з¶ӯиӯ·жңҹй–“и«ӢдҝқжҢҒAutoSupportеҠҹиғҪе•ҹз”ЁгҖӮ
* еңЁз¶ӯиӯ·еүҚеҫҢи§ёзҷјз¶ӯиӯ· AutoSupportпјҢд»ҘеңЁз¶ӯиӯ·жңҹй–“еҒңз”ЁжЎҲдҫӢе»әз«ӢеҠҹиғҪгҖӮеҰӮйңҖжӣҙеӨҡи©ізҙ°иіҮж–ҷпјҢи«ӢеҸғй–ұжӯӨзҹҘиӯҳеә«ж–Үз«  link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92пјҡеҰӮдҪ•еңЁиЁҲеҠғз¶ӯиӯ·иҰ–зӘ—жңҹй–“жҠ‘еҲ¶иҮӘеӢ•е»әз«ӢжЎҲдҫӢ"^]гҖӮ
* е•ҹз”ЁжүҖжңү CLI жңғи©ұвҖӢвҖӢзҡ„жңғи©ұж—ҘиӘҢиЁҳйҢ„гҖӮжңүй—ңеҰӮдҪ•е•ҹз”Ёжңғи©ұж—ҘиӘҢиЁҳйҢ„зҡ„иӘӘжҳҺпјҢи«ӢжҹҘзңӢжӯӨзҹҘиӯҳеә«ж–Үз« дёӯзҡ„гҖҢиЁҳйҢ„жңғи©ұијёеҮәгҖҚйғЁеҲҶгҖӮ https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["еҰӮдҪ•й…ҚзҪ® PuTTY д»ҘзҚІеҫ—иҲҮONTAPзі»зөұзҡ„жңҖдҪійҖЈжҺҘ"^] гҖӮ




== жӣҙжҸӣй–Ӣй—ң

.й—ңж–јзҜ„дҫӢ
жң¬жөҒзЁӢдёӯзҡ„зҜ„дҫӢдҪҝз”Ёд»ҘдёӢй–Ӣй—ңе’ҢзҜҖй»һе‘ҪеҗҚиҰҸеүҮпјҡ

* зҸҫжңүзҡ„NVIDIA SN2100 дәӨжҸӣеҷЁзҡ„еҗҚзЁұзӮә _sw1_ е’Ң _sw2_гҖӮ
* NVIDIA SN2100 ж–°дәӨжҸӣеҷЁзҡ„еҗҚзЁұжҳҜ _nsw2_гҖӮ
* зҜҖй»һеҗҚзЁұзӮә _node1_ е’Ң _node2_гҖӮ
* жҜҸеҖӢзҜҖй»һдёҠзҡ„еҸўйӣҶйҖЈжҺҘеҹ еҲҶеҲҘе‘ҪеҗҚзӮә_e3a_е’Ң_e3b_гҖӮ
* зҜҖй»һ 1 зҡ„зҫӨйӣҶ LIF дҪҚзЁұзӮә _node1_clus1_ е’Ң _node1_clus2_пјҢзҜҖй»һ 2 зҡ„зҫӨйӣҶ LIF дҪҚзЁұзӮә _node2_clus1_ е’Ң _node2_clus2_гҖӮ
* жҸҗзӨәе°ҚжүҖжңүеҸўйӣҶзҜҖй»һйҖІиЎҢжӣҙж”№ `cluster1::*>`
* еҲҶж”Ҝз«ҜеҸЈжҺЎз”Ёд»ҘдёӢж јејҸпјҡswp[з«ҜеҸЈ]s[еҲҶж”Ҝз«ҜеҸЈ 0-3]гҖӮдҫӢеҰӮпјҢswp1 дёҠзҡ„еӣӣеҖӢеҲҶж”ҜйҖЈжҺҘеҹ еҲҶеҲҘжҳҜ _swp1s0_гҖҒ_swp1s1_гҖҒ_swp1s2_ е’Ң _swp1s3_гҖӮ


.й—ңж–јеҸўйӣҶз¶Іи·ҜжӢ“ж’І
жӯӨжөҒзЁӢеҹәж–јд»ҘдёӢеҸўйӣҶз¶Іи·ҜжӢ“ж’Ізөҗж§Ӣпјҡ

.йЎҜзӨәзҜ„дҫӢжӢ“ж’І
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true


cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
+

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw2                e3a
swp4       100G   Trunk/L2    sw2                e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16


cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw1                e3b
swp4       100G   Trunk/L2    sw1                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====


=== з¬¬дёҖжӯҘпјҡжә–еӮҷжӣҙжҸӣ

. еҰӮжһңжӯӨеҸўйӣҶдёҠе•ҹз”ЁдәҶAutoSupport пјҢеүҮйҖҸйҒҺе‘јеҸ«AutoSupportиЁҠжҒҜдҫҶжҠ‘еҲ¶иҮӘеӢ•е»әз«ӢжЎҲдҫӢпјҡ
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
е…¶дёӯ _x_ зӮәз¶ӯиӯ·иҰ–зӘ—зҡ„жҢҒзәҢжҷӮй–“пјҲе°ҸжҷӮпјүгҖӮ

. е°Үж¬ҠйҷҗзҙҡеҲҘи®ҠжӣҙзӮәй«ҳзҙҡпјҢдёҰеңЁжҸҗзӨәз№јзәҢжҷӮијёе…Ҙ *y*пјҡ
+
`set -privilege advanced`

+
еҮәзҸҫй«ҳйҡҺжҸҗзӨәз¬ҰиҷҹпјҲ*>пјүгҖӮ

. еңЁдәӨжҸӣеҷЁ nsw2 дёҠе®үиЈқзӣёжҮүзҡ„ RCF е’Ңжҳ еғҸпјҢдёҰйҖІиЎҢд»»дҪ•еҝ…иҰҒзҡ„зҸҫе ҙжә–еӮҷгҖӮ
+
еҰӮжңүеҝ…иҰҒпјҢи«Ӣй©—иӯүгҖҒдёӢијүдёҰе®үиЈқйҒ©з”Ёж–јж–°дәӨжҸӣеҷЁзҡ„ RCF е’Ң Cumulus и»ҹй«”зҡ„зӣёжҮүзүҲжң¬гҖӮ

+
.. жӮЁеҸҜд»Ҙеҫһ _NVIDIA ж”ҜжҸҙ_ з¶Із«ҷдёӢијүйҒ©з”Ёж–јжӮЁзҡ„еҸўйӣҶдәӨжҸӣеҷЁзҡ„ Cumulus и»ҹй«”гҖӮи«ӢжҢүз…§дёӢијүй ҒйқўдёҠзҡ„жӯҘй©ҹпјҢдёӢијүиҲҮжӮЁиҰҒе®үиЈқзҡ„ONTAPи»ҹй«”зүҲжң¬зӣёз¬Ұзҡ„ Cumulus LinuxгҖӮ
.. еҸҜеҫһд»ҘдёӢйҖ”еҫ‘еҸ–еҫ—е°ҚжҮүзҡ„ RCFпјҡlink:https://mysupport.netapp.com/site/products/all/details/nvidia-cluster-storage-switch/downloads-tab["NVIDIA еҸўйӣҶе’Ңе„ІеӯҳдәӨжҸӣж©ҹ"^]й ҒгҖӮи«Ӣдҫқз…§дёӢијүй ҒйқўдёҠзҡ„жӯҘй©ҹпјҢдёӢијүиҲҮжӮЁиҰҒе®үиЈқзҡ„ONTAPи»ҹй«”зүҲжң¬зӣёз¬Ұзҡ„жӯЈзўә RCF жӘ”жЎҲгҖӮ






=== жӯҘй©ҹдәҢпјҡиЁӯе®ҡеҹ е’Ңз·ҡзәң

[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. еңЁж–°дәӨжҸӣеҷЁ nsw2 дёҠпјҢд»Ҙз®ЎзҗҶе“Ўиә«еҲҶзҷ»йҢ„пјҢдёҰй—ңй–үжүҖжңүе°ҮйҖЈжҺҘеҲ°зҜҖй»һеҸўйӣҶд»Ӣйқўзҡ„йҖЈжҺҘеҹ пјҲйҖЈжҺҘеҹ  swp1 еҲ° swp14пјүгҖӮ
+
еҸўйӣҶзҜҖй»һдёҠзҡ„ LIF жҮүи©Іе·Із¶“йҮқе°ҚжҜҸеҖӢзҜҖй»һж•…йҡңиҪүз§»еҲ°еҸҰдёҖеҖӢеҸўйӣҶйҖЈжҺҘеҹ гҖӮ

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
. еҒңз”ЁеҸўйӣҶ LIF зҡ„иҮӘеӢ•еӣһж»ҫеҠҹиғҪпјҡ
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
. зўәиӘҚжүҖжңүзҫӨйӣҶ LIF йғҪе·ІеҒңз”ЁиҮӘеӢ•еӣһж»ҫеҠҹиғҪпјҡ
+
`net interface show -vserver Cluster -fields auto-revert`

. й—ңй–ү SN2100 дәӨжҸӣеҷЁ sw1 дёҠзҡ„ ISL йҖЈжҺҘеҹ  swp15 е’Ң swp16гҖӮ
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
. еҫһ SN2100 sw1 дәӨжҸӣеҷЁдёҠжӢҶдёӢжүҖжңүйӣ»зәңпјҢз„¶еҫҢе°Үе®ғеҖ‘йҖЈжҺҘеҲ° SN2100 nsw2 дәӨжҸӣеҷЁдёҠзҡ„зӣёеҗҢйҖЈжҺҘеҹ гҖӮ
. е•ҹз”Ё sw1 е’Ң nsw2 дәӨжҸӣеҷЁд№Ӣй–“зҡ„ ISL йҖЈжҺҘеҹ  swp15 е’Ң swp16гҖӮ
+
д»ҘдёӢе‘Ҫд»Өе•ҹз”ЁдәӨжҸӣеҷЁ sw1 дёҠзҡ„ ISL йҖЈжҺҘеҹ  swp15 е’Ң swp16пјҡ

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
+
д»ҘдёӢзҜ„дҫӢиЎЁзӨәдәӨжҸӣеҷЁ sw1 дёҠзҡ„ ISL йҖЈжҺҘеҹ е·Іе•ҹеӢ•пјҡ

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+
д»ҘдёӢзҜ„дҫӢиЎЁзӨәдәӨжҸӣеҷЁ nsw2 дёҠзҡ„ ISL йҖЈжҺҘеҹ е·Іе•ҹеӢ•пјҡ

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
. й©—иӯүи©ІйҖЈжҺҘеҹ  `e3b`жүҖжңүзҜҖй»һе·Іе•ҹеӢ•пјҡ
+
`network port show -ipspace Cluster`

+
ијёеҮәзөҗжһңжҮүйЎһдјјд»ҘдёӢе…§е®№пјҡ

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
. еҫһзҜҖй»һзҡ„и§’еәҰдҫҶзңӢпјҢжҜҸеҖӢзҜҖй»һдёҠзҡ„еҸўйӣҶйҖЈжҺҘеҹ зҸҫеңЁжңғд»Ҙд»ҘдёӢж–№ејҸйҖЈжҺҘеҲ°еҸўйӣҶдәӨжҸӣеҷЁпјҡ
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
. и«ӢзўәиӘҚжүҖжңүзҜҖй»һеҸўйӣҶйҖЈжҺҘеҹ еқҮе·Іе•ҹеӢ•пјҡ
+
`net show interface`

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. зўәиӘҚе…©еҖӢзҜҖй»һйғҪеҲҶеҲҘиҲҮжҜҸеҖӢдәӨжҸӣеҷЁе»әз«ӢдәҶдёҖеҖӢйҖЈз·ҡпјҡ
+
`net show lldp`

+
д»ҘдёӢзҜ„дҫӢйЎҜзӨәдәҶе…©зЁ®й–Ӣй—ңзҡ„жӯЈзўәзөҗжһңпјҡ

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
. е•ҹз”ЁеҸўйӣҶ LIF зҡ„иҮӘеӢ•еӣһж»ҫеҠҹиғҪпјҡ
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. еңЁдәӨжҸӣеҷЁ nsw2 дёҠпјҢе•ҹеӢ•йҖЈжҺҘеҲ°зҜҖй»һз¶Іи·ҜйҖЈжҺҘеҹ зҡ„йҖЈжҺҘеҹ гҖӮ
+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net del interface swp1-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
. йЎҜзӨәеҸўйӣҶдёӯзҜҖй»һзҡ„зӣёй—ңиіҮиЁҠпјҡ
+
`cluster show`

+
жӯӨзҜ„дҫӢиЎЁжҳҺпјҢи©ІеҸўйӣҶдёӯзҜҖй»һ 1 е’ҢзҜҖй»һ 2 зҡ„зҜҖй»һеҒҘеә·зӢҖжіҒзӮәзңҹпјҡ

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
. зўәиӘҚжүҖжңүеҜҰй«”еҸўйӣҶйҖЈжҺҘеҹ еқҮе·Іе•ҹеӢ•пјҡ
+
`network port show ipspace Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----


--
.Cumulus Linux 5.x
--
. еңЁж–°дәӨжҸӣеҷЁ nsw2 дёҠпјҢд»Ҙз®ЎзҗҶе“Ўиә«еҲҶзҷ»йҢ„пјҢдёҰй—ңй–үжүҖжңүе°ҮйҖЈжҺҘеҲ°зҜҖй»һеҸўйӣҶд»Ӣйқўзҡ„йҖЈжҺҘеҹ пјҲйҖЈжҺҘеҹ  swp1 еҲ° swp14пјүгҖӮ
+
еҸўйӣҶзҜҖй»һдёҠзҡ„ LIF жҮүи©Іе·Із¶“йҮқе°ҚжҜҸеҖӢзҜҖй»һж•…йҡңиҪүз§»еҲ°еҸҰдёҖеҖӢеҸўйӣҶйҖЈжҺҘеҹ гҖӮ

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv set interface swp15-16 link state down*
cumulus@nsw2:~$ *nv config apply*
----
. еҒңз”ЁеҸўйӣҶ LIF зҡ„иҮӘеӢ•еӣһж»ҫеҠҹиғҪпјҡ
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
. зўәиӘҚжүҖжңүзҫӨйӣҶ LIF йғҪе·ІеҒңз”ЁиҮӘеӢ•еӣһж»ҫеҠҹиғҪпјҡ
+
`network interface show -vserver Cluster -fields auto-revert`

. й—ңй–ү SN2100 дәӨжҸӣеҷЁ sw1 дёҠзҡ„ ISL йҖЈжҺҘеҹ  swp15 е’Ң swp16гҖӮ
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp15-16 link state down*
cumulus@sw1:~$ *nv config apply*
----
. еҫһ SN2100 sw1 дәӨжҸӣеҷЁдёҠжӢҶдёӢжүҖжңүйӣ»зәңпјҢз„¶еҫҢе°Үе®ғеҖ‘йҖЈжҺҘеҲ° SN2100 nsw2 дәӨжҸӣеҷЁдёҠзҡ„зӣёеҗҢйҖЈжҺҘеҹ гҖӮ
. е•ҹз”Ё sw1 е’Ң nsw2 дәӨжҸӣеҷЁд№Ӣй–“зҡ„ ISL йҖЈжҺҘеҹ  swp15 е’Ң swp16гҖӮ
+
д»ҘдёӢе‘Ҫд»Өе•ҹз”ЁдәӨжҸӣеҷЁ sw1 дёҠзҡ„ ISL йҖЈжҺҘеҹ  swp15 е’Ң swp16пјҡ

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp15-16 link state down*
cumulus@sw1:~$ *nv config apply*
----
+
д»ҘдёӢзҜ„дҫӢиЎЁзӨәдәӨжҸӣеҷЁ sw1 дёҠзҡ„ ISL йҖЈжҺҘеҹ е·Іе•ҹеӢ•пјҡ

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+
д»ҘдёӢзҜ„дҫӢиЎЁзӨәдәӨжҸӣеҷЁ nsw2 дёҠзҡ„ ISL йҖЈжҺҘеҹ е·Іе•ҹеӢ•пјҡ

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
. й©—иӯүи©ІйҖЈжҺҘеҹ  `e3b`жүҖжңүзҜҖй»һе·Іе•ҹеӢ•пјҡ
+
`network port show -ipspace Cluster`

+
ијёеҮәзөҗжһңжҮүйЎһдјјд»ҘдёӢе…§е®№пјҡ

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
. еҫһзҜҖй»һзҡ„и§’еәҰдҫҶзңӢпјҢжҜҸеҖӢзҜҖй»һдёҠзҡ„еҸўйӣҶйҖЈжҺҘеҹ зҸҫеңЁжңғд»Ҙд»ҘдёӢж–№ејҸйҖЈжҺҘеҲ°еҸўйӣҶдәӨжҸӣеҷЁпјҡ
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
. и«ӢзўәиӘҚжүҖжңүзҜҖй»һеҸўйӣҶйҖЈжҺҘеҹ еқҮе·Іе•ҹеӢ•пјҡ
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. зўәиӘҚе…©еҖӢзҜҖй»һйғҪеҲҶеҲҘиҲҮжҜҸеҖӢдәӨжҸӣеҷЁе»әз«ӢдәҶдёҖеҖӢйҖЈз·ҡпјҡ
+
`nv show interface lldp`

+
д»ҘдёӢзҜ„дҫӢйЎҜзӨәдәҶе…©зЁ®й–Ӣй—ңзҡ„жӯЈзўәзөҗжһңпјҡ

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
. е•ҹз”ЁеҸўйӣҶ LIF зҡ„иҮӘеӢ•еӣһж»ҫеҠҹиғҪпјҡ
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. еңЁдәӨжҸӣеҷЁ nsw2 дёҠпјҢе•ҹеӢ•йҖЈжҺҘеҲ°зҜҖй»һз¶Іи·ҜйҖЈжҺҘеҹ зҡ„йҖЈжҺҘеҹ гҖӮ
+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv set interface swp1-14 link state up*
cumulus@nsw2:~$ *nv config apply*
----
. йЎҜзӨәеҸўйӣҶдёӯзҜҖй»һзҡ„зӣёй—ңиіҮиЁҠпјҡ
+
`cluster show`

+
жӯӨзҜ„дҫӢиЎЁжҳҺпјҢи©ІеҸўйӣҶдёӯзҜҖй»һ 1 е’ҢзҜҖй»һ 2 зҡ„зҜҖй»һеҒҘеә·зӢҖжіҒзӮәзңҹпјҡ

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
. зўәиӘҚжүҖжңүеҜҰй«”еҸўйӣҶйҖЈжҺҘеҹ еқҮе·Іе•ҹеӢ•пјҡ
+
`network port show ipspace Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----


--
====


=== жӯҘй©ҹ 3пјҡй©—иӯүй…ҚзҪ®

[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. й©—иӯүеҸўйӣҶз¶Іи·ҜжҳҜеҗҰйҒӢдҪңжӯЈеёёгҖӮ
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----


--
.Cumulus Linux 5.x
--
. й©—иӯүеҸўйӣҶз¶Іи·ҜжҳҜеҗҰйҒӢдҪңжӯЈеёёгҖӮ
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----


--
====
. жӯҘй©ҹ2пјҡе°Үж¬Ҡйҷҗзӯүзҙҡж”№еӣһз®ЎзҗҶе“ЎгҖӮ
+
`set -privilege admin`

. еҰӮжһңжӮЁе·ІеҒңз”ЁиҮӘеӢ•е»әз«ӢжЎҲдҫӢеҠҹиғҪпјҢи«ӢйҖҸйҒҺе‘јеҸ«AutoSupportиЁҠжҒҜйҮҚж–°е•ҹз”Ёи©ІеҠҹиғҪпјҡ
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.дёӢдёҖжӯҘжҳҜд»Җйәјпјҹ
жӣҙжҸӣй–Ӣй—ңеҫҢпјҢжӮЁеҸҜд»Ҙ link:../switch-cshm/config-overview.html["й…ҚзҪ®дәӨжҸӣеҷЁеҒҘеә·зӣЈжҺ§"]гҖӮ
