---
permalink: switch-nvidia-sn2100/replace_sn2100_switch_cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia SN2100 
summary: 在叢集網路中更換故障的NVIDIA SN2100交換器、是不中斷營運的程序（NDU）。 
---
= 更換NVIDIA SN2100叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在叢集網路中更換故障的NVIDIA SN2100交換器、是不中斷營運的程序（NDU）。

在目前環境和更換交換器上執行交換器更換之前、必須符合下列條件。

* 現有的叢集與網路基礎架構：
+
** 必須使用至少一個完全連接的叢集交換器、驗證現有叢集是否完全正常運作。
** 所有叢集連接埠都必須正常運作。
** 所有叢集邏輯介面（LIF）都必須在其主連接埠上正常運作。
** 使用指令《叢集ping叢集節點節點1》必須指出、所有路徑上的基本連線能力和大於PMTU的通訊都會成功。ONTAP


* NVIDIA SN2100替換交換器：
+
** 替換交換器上的管理網路連線功能必須正常運作。
** 更換交換器的主控台存取必須已就緒。
** 節點連線是連接埠swp1到swp14。
** 所有交換器間連結（ISL）連接埠必須停用swp15和swp16上的連接埠。
** 必須將所需的參考組態檔（RCF）和CummUS作業系統映像交換器載入。
** 交換器的初始自訂作業必須完成、如以下所述：
+
任何先前的站台自訂（例如STP、SNMP和SSH）都應該複製到新交換器。





您必須執行命令、從裝載叢集LIF的節點移轉叢集LIF。

本程序中的範例使用下列交換器和節點命名法：

* 現有NVIDIA SN2100交換器的名稱為_sw1_和_SW2_。
* 新NVIDIA SN2100交換器的名稱為_nsw2_。
* 節點名稱是_node1_和_node2_。
* 每個節點上的叢集連接埠名稱為_e3a_和_e3c_。
* 叢集LIF名稱為節點1的_node1_clus1_和節點1的_node1_clus2_、節點2的節點2為_node2_clus1_和節點2為_node2_clus2_。
* 對所有叢集節點進行變更的提示是「cluster1：*>」
* 中斷連接埠的格式為：swp[port] s[中斷 連接埠0-3]。例如、swp1上的四個中斷連接埠分別是_swp1s0_、_swp1s1_、_swp1s2_和_swp1s3_。
+

NOTE: 下列程序以下列叢集網路拓撲為基礎：

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true


cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw2                e3a
swp4       100G   Trunk/L2    sw2                e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16


cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw1                e3b
swp4       100G   Trunk/L2    sw1                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----


.步驟
. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 「系統節點AutoSupport 支援功能叫用節點*-type all -most MAn=xh」訊息來禁止自動建立案例
+
其中_x_是維護時段的持續時間（以小時為單位）。

. 將權限層級變更為進階、並在系統提示您繼續時輸入* y*：「et -priv家 特權進階」
+
出現進階提示（*>）。

. 在交換器nsw2上安裝適當的RCF和映像、並進行必要的站台準備。
+
如有必要、請為新交換器驗證、下載及安裝適當版本的RCF和Cummuls軟體。如果您已確認新交換器已正確設定、而且不需要更新RCF和Cummuls軟體、請繼續執行步驟3。請參閱 link:install_setup_sn2100_switches_overview.html["設定及設定NVIDIA SN2100交換器"] 以取得更多詳細資料。

+
.. 您可以從_NVIDIA Support_網站下載適用於叢集交換器的Cummulus軟體。請依照下載頁面上的步驟、下載您ONTAP 所安裝之版本的Cummuls Linux。
.. 您可從取得適當的RCF link:https://mysupport.netapp.com/site/products/all/details/nvidia-cluster-storage-switch/downloads-tab["_NVIDIA叢集與儲存交換器_"^] 頁面。請依照下載頁面上的步驟、針對ONTAP 您要安裝的版本、下載正確的RCF。


. 在新的交換器nsw2上、以admin身分登入、並關閉所有連接至節點叢集介面的連接埠（連接埠swp1至swp14）。
+
如果您要更換的交換器無法正常運作且已關機、請前往步驟4。叢集節點上的LIF應已容錯移轉至每個節點的其他叢集連接埠。

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
. 停用叢集lifs上的自動還原：「網路介面修改-vserver叢集-lif*-auta-fRevert假」
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
. 關閉SN2100交換器sw1上的ISL連接埠swp15和swp16：
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
. 從SN2100 sw1交換器拔下所有纜線、然後將其連接至SN2100 nsw2交換器上的相同連接埠。
. 在sw1和nsw2交換器之間啟動ISL連接埠swp15和swp16。
+
下列命令可啟用交換器sw1上的ISL連接埠swp15和swp16：

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
+
下列範例顯示交換器sw1上的ISL連接埠為開啟：

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+
以下範例顯示交換器nsw2上的ISL連接埠為開啟：

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
. 驗證所有節點上的連接埠「e3b」是否都已開啟：「network port show -IPSpace Cluster」（網路連接埠顯示-IPSpace叢集）
+
輸出應類似於下列內容：

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
. 確認所有節點叢集連接埠都已啟動：「net show interface」
+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. 確認兩個節點都有一個連線可連線至每個交換器：「net show LLDP」
+
以下範例顯示兩個交換器的適當結果：

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
. 在叢集lifs上啟用自動還原：「cluster1：：*>網路介面修改-vserver叢集-lif*-aut-revert true」
. 在交換器nsw2上、開啟連接至節點網路連接埠的連接埠。
+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net del interface swp1-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
. 顯示叢集中節點的相關資訊：「叢集顯示」
+
此範例顯示此叢集中節點1和節點2的節點健全狀況為真：

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
. 驗證所有實體叢集連接埠是否正常運作：「network port show IPSpace Cluster（網路連接埠顯示IPSpace叢集）」
+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false

----
. 驗證叢集網路是否正常：
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----
. 使用以下命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔：「System Switch Ethernet log setup-password」（系統交換器乙太網路記錄啟用-收集）和「System Switch Ethernet log enable - collection」（系統交換器乙太網路記錄啟用-收集）
+
輸入：「System交換器乙太網路記錄設定密碼」

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*nsw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *nsw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
接著是：「系統交換器乙太網路記錄啟用-收集」

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 啟動交換器記錄收集功能：「System交換器乙太網路記錄collect -device *」
+
請等待10分鐘、然後使用「ystem switchEthernet log show」命令檢查記錄收集是否成功

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      nsw2 (b8:ce:f6:19:1b:96)     4/29/2022 03:07:42   complete
----
. 將權限等級變更回admin：「et -priv. admin」
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息重新啟用此功能：「System Node AutoSupport 現象叫用節點*-type all -most MAn=end」

