---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches' 
summary: 您可以使用此程序來安裝適用的組態檔、以監控 NVIDIA SN2100 叢集交換器的叢集交換器健全狀況。 
---
= 安裝乙太網路交換器健全狀況監視器組態檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在 NVIDIA 乙太網路交換器上設定乙太網路交換器健康監控，請依照下列步驟操作。

如果 NVIDIA X190006-PE 和 X190006-PI 交換器無法正確偵測，則適用這些說明，可以透過執行 `system switch ethernet show`並檢查您的型號是否顯示*OTHER*。若要辨識您的 NVIDIA 交換器型號，請使用以下指令尋找零件編號 `nv show platform hardware`對於 NVIDIA CL 5.8 及更早版本或 `nv show platform`適用於後續版本。

[NOTE]
====
如果您希望在使用 NVIDIA CL 5.11.x 和以下 ONTAP 版本時，健康監控和日誌收集能夠如預期運作，也建議您執行這些步驟。雖然沒有這些步驟，健康監測和日誌收集可能仍會起作用，但遵循這些步驟可以確保一切正常運作。

* 9.10.1P20、9.11.1P18、9.12.1P16、9.13.1P8、9.14.1、9.15.1 及更高補丁版本


====
.開始之前
* 請確定ONTAP 支援並執行不中斷的叢集。
* 在交換器上啟用 SSH 以使用 CSHM 中可用的所有功能。
* 清除 `/mroot/etc/cshm_nod/nod_sign/`所有節點上的目錄：
+
.. 輸入節點：
+
`system node run -node <name>`

.. 變更為進階權限：
+
`priv set advanced`

.. 列出目錄中的組態檔案 `/etc/cshm_nod/nod_sign`。如果目錄存在且包含組態檔案，則會列出檔案名稱。
+
`ls /etc/cshm_nod/nod_sign`

.. 刪除所有與您所連接交換器機型對應的組態檔案。
+
如果您不確定，請移除上述所列支援機型的所有組態檔案，然後下載並安裝相同機型的最新組態檔案。

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. 確認刪除的組態檔不再位於目錄中：
+
`ls /etc/cshm_nod/nod_sign`





.步驟
. 根據對應的 ONTAP 版本、下載乙太網路交換器健全狀況監視器組態 zip 檔案。此檔案可從 https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA 乙太網路交換器"^] 頁面取得。
+
.. 在 NVIDIA SN2100 軟體下載頁面上、選取 * Nvidia CSHM 檔案 * 。
.. 在「注意 / 必須閱讀」頁面上、勾選核取方塊以同意。
.. 在「終端使用者授權合約」頁面上、勾選核取方塊以同意、然後按一下 * 接受並繼續 * 。
.. 在 Nvidia CSHM File - Download 頁面上、選取適用的組態檔案。以下檔案可供使用：




[role="tabbed-block"]
====
.ONTAP 9.15.1 及更新版本
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 至 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]] 將適用的 zip 檔案上傳至內部 Web 伺服器。
. 從叢集中的其中一個 ONTAP 系統存取進階模式設定。
+
"進階權限"

. 執行交換器健全狀況監視器組態命令。
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. 確認 ONTAP 版本的命令輸出結尾為下列文字：


[role="tabbed-block"]
====
.ONTAP 9.15.1 及更新版本
--
乙太網路交換器健全狀況監控已安裝組態檔。

--
.ONTAP 9.11.1 至 9.14.1
--
shm 已安裝組態檔案。

--
.ONTAP 9.10.1.
--
CSHM 下載套件已成功處理。

--
====
如果發生錯誤、請聯絡NetApp支援部門。

. [[step6]] 在完成下一個步驟之前、請等待最多兩倍的乙太網路交換器健全狀況監視器輪詢時間間隔（透過執行找到 `system switch ethernet polling-interval show`）。
. 運行該命令 `system switch ethernet configure-health-monitor show`在ONTAP系統中，確保已發現叢集交換機，並且監控欄位設定為 *True*，序號欄位不顯示 *Unknown*。
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----



NOTE: 如果套用組態檔案後、您的機型仍顯示 * 其他 * 、請聯絡 NetApp 支援部門。

查看 https://docs.netapp.com/us-en/ontap-cli/system-switch-ethernet-configure-health-monitor.html["系統交換器乙太網路設定-健康-監控"^]命令以了解更多詳細資訊。

.接下來呢？
安裝 CSHM 檔案後，您可以link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
