---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/configure-reqs-9336c-storage.html 
keywords: shared storage cluster switch 
summary: 從ONTAP 9.9.1 開始，您可以使用Cisco Nexus 9336C-FX2 交換器將儲存和叢集功能組合到共用交換器場景。 
---
= Cisco Nexus 9336C-FX2 和 9336C-FX2-T 儲存交換器的設定需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
對於Cisco Nexus 9336C-FX2 和 9336C-FX2-T 交換器的安裝和維護，請務必檢查設定和網路需求。



== ONTAP 支援

[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
從ONTAP 9.9.1 開始，您可以使用Cisco Nexus 9336C-FX2 交換器將儲存和叢集功能組合到共用交換器配置中。

如果要建置包含兩個以上節點的ONTAP集群，則需要兩個受支援的網路交換器。


NOTE: 乙太網路交換器健康監視器不支援ONTAP 9.13.1P8 及更早版本、9.14.1P3 及更早版本或 NX-OS 版本 10.3(4a)(M)。

--
.ONTAP 9.10.1 及更高版本
--
此外，從ONTAP 9.10.1 開始，您可以使用Cisco Nexus 9336C-FX2-T 交換器將儲存和叢集功能組合到共用交換器設定中。

如果要建置包含兩個以上節點的ONTAP集群，則需要兩個受支援的網路交換器。

--
====


== 配置要求

配置時，您需要為交換器準備相應數量和類型的電纜和電纜連接器。

根據您最初設定的交換器類型，您需要使用隨附的控制台連接線連接到交換器控制台連接埠；您還需要提供特定的網路資訊。



== 網路需求

所有交換器配置都需要以下網路資訊。

* 管理網路流量的 IP 子網
* 每個儲存系統控制器和所有適用交換器的主機名稱和 IP 位址
* 大多數儲存系統控制器透過連接到乙太網路服務連接埠（扳手圖示）透過 e0M 介面進行管理。在AFF A800和AFF A700s系統中，e0M 介面使用專用乙太網路連接埠。
* 請參閱 https://hwu.netapp.com["Hardware Universe"]獲取最新資訊。


有關交換器初始配置的更多信息，請參閱以下指南： https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2 安裝與升級指南"] 。

.下一步
在您查看完配置要求後，您可以確認您的配置。 link:components-9336c-storage.html["組件和零件編號"]。
