---
permalink: switch-cisco-9336c-fx2/index.html 
sidebar: sidebar 
keywords: cisco, switch, cisco 9336 switch 
summary: Cisco 9336-FX2交換器 
---
= 概述與要求：Cisco Nexus 9336C-FX2交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於Cisco Nexus 9336C-FX2交換器的安裝與維護、請務必檢閱組態要求與文件要求。

如果您想要建置ONTAP 具有兩個以上節點的叢集、您需要兩個支援的叢集網路交換器。您可以使用額外的管理交換器、這是選用的。

您可以將Cisco Nexus 9336C-FX2交換器（X190200/X190210）安裝在NetApp系統機櫃或第三方機櫃中、並附有交換器隨附的標準支架。



== 交換器元件

下表列出9336C-FX2交換器、風扇和電源供應器的零件編號和說明：

[cols="1,2"]
|===
| 產品編號 | 說明 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2、CS、PTSX、36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2、CS、PSIN、36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C、FTE、PTSX、36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C、FTE、PSIN、36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
配件套件X190001/X190003



 a| 
X-NXA-PAC-1100 W-PE2
 a| 
N9K-9336C AC 1100 W PSU -連接埠側邊排氣氣流



 a| 
X-NXA-PAC-1100 W-Pi2
 a| 
N9K-9336C AC 1100 W PSU -連接埠側進氣



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM、連接埠側邊排氣氣流



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM、連接埠側進氣氣流

|===


== 組態需求

若要設定叢集、您需要適當數量和類型的纜線、以及交換器的纜線連接器。視您初始設定的交換器類型而定、您需要使用隨附的主控台纜線連接至交換器主控台連接埠；您也需要提供特定的網路資訊。



== 網路需求

所有交換器組態都需要下列網路資訊：

* 用於管理網路流量的IP子網路
* 每個儲存系統控制器和所有適用交換器的主機名稱和IP位址
* 大部分的儲存系統控制器都是透過e0M介面來管理、方法是連接至乙太網路服務連接埠（扳手圖示）。在ESIA800和ESIEA700系統上AFF 、e0M介面使用專用的乙太網路連接埠。AFF


請參閱 https://hwu.netapp.com["Hardware Universe"^] 以取得最新資訊。



== 智慧電話住家需求

Smart Call Home可監控網路上的硬體和軟體元件、針對關鍵系統狀況產生電子郵件通知。當裝置發生事件時、Smart Call Home會向目的地設定檔中設定的所有收件者發出警示。

您必須將叢集網路交換器設定為使用電子郵件與Smart Call Home系統進行通訊。您可以選擇設定叢集網路交換器、以充分利用Cisco的內嵌Smart Call Home支援功能。

在您使用智慧電話主選項之前、您必須先注意下列考量事項：

* 電子郵件伺服器必須就位。
* 交換器必須具備IP連線至電子郵件伺服器的功能。
* 必須設定聯絡人名稱（SNMP伺服器聯絡人）、電話號碼和街道地址資訊。這是判斷接收訊息來源所需的條件。
* 您的公司必須將一個CCO ID與適當的Cisco SMARTnet服務合約建立關聯。
* Cisco SMARTnet服務必須就位、才能登錄裝置。


。 http://www.cisco.com/c/en/us/products/switches/index.html["Cisco支援網站"^] 包含有關設定Smart Call Home的命令資訊。



== 文件需求

您需要特定的交換器和控制器文件、才能設定Cisco 9336-FX2交換器和ONTAP 叢集。



=== 交換器文件

若要設定Cisco Nexus 9336C-FX2交換器、您需要提供下列文件 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000系列交換器支援"^] 頁面：

[cols="1,2"]
|===
| 文件標題 | 說明 


 a| 
_Nexus 9000系列硬體安裝指南_
 a| 
提供有關站台需求、交換器硬體詳細資料及安裝選項的詳細資訊。



 a| 
_Cisco Nexus 9000系列交換器軟體組態指南_（請選擇您交換器上安裝的NX-OS版本指南）
 a| 
提供您需要的初始交換器組態資訊、然後才能設定交換器ONTAP 以供執行故障操作。



 a| 
_Cisco Nexus 9000系列NX-OS軟體升級與降級指南_（請針對安裝在交換器上的NX-OS版本選擇指南）
 a| 
如ONTAP 有必要、提供如何將交換器降級至支援的交換器軟體的相關資訊。



 a| 
_Cisco Nexus 9000系列NX-OS命令參考主索引_
 a| 
提供Cisco所提供之各種命令參考資料的連結。



 a| 
_Cisco Nexus 9000 MIBs參考資料_
 a| 
說明Nexus 9000交換器的管理資訊庫（MIB）檔案。



 a| 
_Nexus 9000系列NX-OS系統訊息參考_
 a| 
說明Cisco Nexus 9000系列交換器的系統訊息、資訊訊息、以及其他可能有助於診斷連結、內部硬體或系統軟體問題的訊息。



 a| 
_Cisco Nexus 9000系列NX-OS版本資訊（請選擇安裝在交換器上的NX-OS版本附註）_
 a| 
說明Cisco Nexus 9000系列的功能、錯誤和限制。



 a| 
Cisco Nexus 9000系列的法規遵循與安全資訊
 a| 
提供Nexus 9000系列交換器的國際機構法規遵循、安全及法規資訊。

|===


=== 系統文件ONTAP

若要設定ONTAP 一套作業系統、您需要從取得下列作業系統版本的文件 https://docs.netapp.com/ontap-9/index.jsp["供應說明文件中心 ONTAP"^]。

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
控制器專屬的安裝與設定指示_
 a| 
說明如何安裝NetApp硬體。



 a| 
本文檔 ONTAP
 a| 
提供ONTAP 有關這些版本的所有方面的詳細資訊。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
提供NetApp硬體組態與相容性資訊。

|===


=== 軌道套件與機櫃文件

若要在NetApp機櫃中安裝Cisco 9336-FX2交換器、請參閱下列硬體文件。

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U系統機櫃、深度指南"^]
 a| 
說明與42U系統機櫃相關的FRU、並提供維護與FRU更換指示。



 a| 
link:install-switch-and-passthrough-panel.html["在NetApp機櫃中安裝Cisco 9336-FX2交換器"^]
 a| 
說明如何在四柱NetApp機櫃中安裝Cisco Nexus 9336C-FX2交換器。

|===