---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: '必須在Cisco Nexus 9336C-FX2 叢集交換器上安裝Cisco NX-OS 軟體和參考設定檔 \(RCFs\)。' 
---
= 準備安裝或升級 NX-OS 軟體和 RCF
:allow-uri-read: 


[role="lead"]
在安裝 NX-OS 軟體和參考設定檔 (RCF) 之前，請依照下列步驟操作。

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩個 Cisco 交換器的名稱分別是 s1 和 s2。
* 節點名稱為 cluster1-01 和 cluster1-02。


.關於此任務
流程需要同時使用ONTAP指令和Cisco Nexus 9000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

.步驟
. 如果啟用 AutoSupport，請透過叫用 AutoSupport 訊息來隱藏自動建立案例： `system node autosupport invoke -node * -type all -message MAINT=xh`
+
其中 x 為維護窗口的持續時間（小時）。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
[source, cli]
----
set -privilege advanced
----
+
進階提示(`*>`出現。

. 顯示每個節點中為每個交換器設定的介面數量：
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e5a    s1                        Eth1/2            N9K-C9336C
            e3b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e5a    s1                        Eth1/1            N9K-C9336C
            e3b    s2                        Eth1/1            N9K-C9336C
.
.
----
====
. 檢查每個節點儲存連接埠和儲存架連接埠的管理或運作狀態。
+
.. 顯示節點儲存連接埠屬性：
+
[source, cli]
----
storage port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -

.
.
----
====
.. 顯示儲存櫃連接埠屬性：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 確認交換器已啟用交換器健全狀況監控（CSHM），以便對交換器進行監控：
+
[source, cli]
----
system switch ethernet show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.下一步是什麼？
準備好安裝 NX-OS 軟體和 RCF 後，您可以… link:install-nxos-software-9336c-storage.html["安裝或升級 NX-OS 軟體"]。
