---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 如果您還沒有所需的設定資訊和文檔，則需要在設定叢集和管理網路交換器之前收集這些資訊。 
---
= 安裝 9336C-FX2 和 9336C-FX2-T 儲存交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟安裝Cisco Nexus 9336C-FX2 和 9336C-FX2-T 儲存交換器。

.開始之前
請確保您擁有以下物品：

* 在安裝現場存取 HTTP、FTP 或 TFTP 伺服器，以下載適用的 NX-OS 和參考設定檔 (RCF) 版本。
* 適用的NX-OS版本，可從以下網址下載： https://software.cisco.com/download/home["Cisco軟體下載"^]頁。
* 適用的許可證、網路和設定資訊以及線纜。
* 完全的link:setup-worksheet-9336c-storage.html["佈線工作表"]。
* 可從NetApp支援網站下載適用的NetApp叢集網路和管理網路 RCF。 http://mysupport.netapp.com/["mysupport.netapp.com"^] 。所有Cisco集群網路和管理網路交換器均採用Cisco標準出廠預設設定。這些交換器也具有目前版本的 NX-OS 軟體，但未載入 RCF。
* 需要提供交換器文件。看link:required-documentation-9336c-storage.html["所需文件"]了解更多。


.步驟
. 將叢集網路和管理網路交換器及控制器安裝到機架上。
+
[cols="1,2"]
|===
| 如果您正在安裝… | 然後... 


 a| 
NetApp系統機櫃中的Cisco Nexus 9336C-FX2
 a| 
看link:install-switch-and-passthrough-panel-9336c-storage.html["在NetApp機櫃中安裝交換機"]有關在NetApp機櫃中安裝交換器的說明。



 a| 
電信機架中的設備
 a| 
請參閱交換器硬體安裝指南和NetApp安裝設定說明中提供的步驟。

|===
. 使用已完成的佈線工作表，將叢集網路和管理網路交換器連接到控制器。
. 啟動叢集網路和管理網路交換器及控制器。


.下一步是什麼？
（可選） link:install-switch-and-passthrough-panel-9336c-storage.html["在NetApp機櫃中安裝Cisco Nexus 9336C-FX2 交換機"]。否則，請前往 link:setup-switch-9336c-storage.html["配置交換機"]。
