---
permalink: switch-cisco-9336c-fx2-storage/migrate-to-2n-switched-9336-storage.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched 9336C-FX2 cluster environment,switchless cluster environments,9336C-FX2 switches 
summary: 如果您現有的雙節點無交換式叢集環境、可以使用Cisco Nexus 9336C-FX2交換器移轉至雙節點交換式叢集環境、以便擴充至叢集中的兩個節點以外。 
---
= 移轉至雙節點交換叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您現有的雙節點_無交換器_叢集環境、則可使用Cisco Nexus 9336C-FX2交換器移轉至雙節點_交換_叢集環境、以便擴充至叢集中的兩個節點以外。

移轉程序適用於使用光纖或雙軸纜線連接埠的所有節點、但如果節點使用內建10Gb Base-T RJ45連接埠作為叢集網路連接埠、則此交換器不支援此程序。



== 檢閱要求

.開始之前
請確定您擁有下列項目：

* 對於雙節點無交換器組態：
+
** 雙節點無交換器組態已正確設定並正常運作。
** 節點執行ONTAP 的是功能不正常的9.8或更新版本。
** 所有叢集連接埠都處於* up*狀態。
** 所有叢集邏輯介面（LIF）都處於* up*狀態、並位於其主連接埠上。


* Cisco Nexus 9336C-FX2交換器組態：
+
** 兩台交換器都有管理網路連線功能。
** 有對叢集交換器的主控台存取權。
** Nexus 9336C-FX2節點對節點交換器和交換器對交換器連線使用雙軸纜線或光纖纜線。
+
請參閱 https://hwu.netapp.com/SWITCH/INDEX["交換器Hardware Universe"^] 如需纜線的詳細資訊、



* 交換器間連結（ISL）纜線連接至9336C-FX2交換器的連接埠1/35和1/36。
* 9336C-FX2交換器的初始自訂已完成、因此：
+
** 9336C-FX2交換器正在執行最新版本的軟體。
** 參考組態檔（RCT）會套用至交換器。任何站台自訂功能（例如、SMTP、SNMP和SSH）都會在新交換器上設定。




.關於範例
本程序中的範例使用下列叢集交換器和節點命名法：

* 9336C-FX2交換器的名稱為CS1和CS2。
* 叢集SVM的名稱為node1和node2。
* lifs的名稱分別是節點1上的node1_clus1和node1_clus2、以及節點2上的node2_clus1和node2_clus2。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 此程序中使用的叢集連接埠為e0a和e0b。


請參閱 https://hwu.netapp.com["Hardware Universe"^] 以取得平台叢集連接埠的相關資訊。



== 移轉交換器



=== 步驟1：準備移轉

. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -Message MAn=xh」

+
其中x是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

. 將權限等級變更為進階、並在系統提示您繼續時輸入「y」：
+
"進階權限"

+
出現進階提示（「*>」）。





=== 步驟2：設定連接埠和纜線

. 在新的叢集交換器CS1和CS2上停用所有面向節點的連接埠（非ISL連接埠）。
+
請勿停用ISL連接埠。

+
.顯示範例
[%collapsible]
====
以下範例顯示、交換器CS1上的節點對介連接埠1至34已停用：

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# shutdown
----
====
. 驗證ISL和ISL上兩個9336C-FX2交換器CS1和CS2之間的實體連接埠是否在連接埠1/35和1/36上正常運作：
+
「How port-channel Summary」

+
.顯示範例
[%collapsible]
====
下列範例顯示交換器CS1上的ISL連接埠已開啟：

[listing]
----
cs1# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
以下範例顯示交換器CS2上的ISL連接埠已開啟：

[listing]
----
(cs2)# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====
. 顯示鄰近裝置的清單：
+
「How cup neighbor」

+
此命令提供有關連線至系統之裝置的資訊。

+
.顯示範例
[%collapsible]
====
下列範例列出交換器CS1上的鄰近裝置：

[listing]
----
cs1# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
下列範例列出交換器CS2上的鄰近裝置：

[listing]
----
cs2# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====
. 驗證所有叢集連接埠是否正常運作：
+
「網路連接埠show -IPSpace Cluster」

+
每個連接埠應顯示「Link」（連結）、「Health Status」（健全狀況狀態）則顯示為「Healthy」（健全狀況）。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. 驗證所有叢集生命體是否正常運作：
+
「網路介面show -vserver叢集」

+
應顯示每個叢集LIF `true` 適用於 `Is Home` 並擁有 `Status Admin/Oper` 增加/增加

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 驗證是否已在所有叢集生命體上啟用自動還原：
+
「網路介面show -vserver叢集-功能 變數自動回復」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 從節點1上的叢集連接埠e0a拔下纜線、然後使用9336C-FX2交換器支援的適當纜線、將e0a連接至叢集交換器CS1上的連接埠1。
+
。 https://hwu.netapp.com/SWITCH/INDEX["交換器Hardware Universe"^] 包含纜線的詳細資訊。

. 從節點2上的叢集連接埠e0a拔下纜線、然後使用9336C-FX2交換器支援的適當纜線、將e0a連接至叢集交換器CS1上的連接埠2。
. 在叢集交換器CS1上啟用所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
下列範例顯示交換器CS1上已啟用連接埠1/1至1/34：

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# no shutdown
----
====
. 驗證所有叢集生命體是否都正常運作、並顯示為「真實」、表示「是家」：
+
「網路介面show -vserver叢集」

+
.顯示範例
[%collapsible]
====
以下範例顯示、節點1和節點2上的所有lifs都已啟動、而且「是主目錄」結果為真：

[listing]
----
cluster1::*> network interface show -vserver Cluster

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. 顯示叢集中節點狀態的相關資訊：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
下列範例顯示叢集中節點的健全狀況和資格資訊：

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 從節點1上的叢集連接埠e0b拔下纜線、然後使用9336C-FX2交換器支援的適當纜線、將e0b連接至叢集交換器CS2上的連接埠1。
. 從節點2上的叢集連接埠e0b拔下纜線、然後使用9336C-FX2交換器支援的適當纜線、將e0b連接至叢集交換器CS2上的連接埠2。
. 在叢集交換器CS2上啟用所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
下列範例顯示交換器CS2上已啟用連接埠1/1至1/34：

[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs2(config-if-range)# no shutdown
----
====
. 驗證所有叢集連接埠是否正常運作：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
以下範例顯示節點1和節點2上的所有叢集連接埠都已啟動：

[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====




=== 步驟3：驗證組態

. 驗證所有介面是否顯示「is Home」（原為主介面）為真：
+
「網路介面show -vserver叢集」

+

NOTE: 這可能需要幾分鐘的時間才能完成。

+
.顯示範例
[%collapsible]
====
以下範例顯示所有lifs都在node1和node2上、而且「is Home」結果為真：

[listing]
----
cluster1::*> network interface show -vserver Cluster

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. 驗證兩個節點各自與每個交換器都有一個連線：
+
「How cup neighbor」

+
.顯示範例
[%collapsible]
====
以下範例顯示兩個交換器的適當結果：

[listing]
----
(cs1)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0a
node2              Eth1/2         133    H           FAS2980       e0a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4

(cs2)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0b
node2              Eth1/2         133    H           FAS2980       e0b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4
----
====
. 顯示叢集中探索到的網路裝置相關資訊：
+
「network device-dDiscovery show -protocol cup」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

4 entries were displayed.
----
====
. 確認設定已停用：
+
「網路選項、無交換式叢集展示」

+

NOTE: 命令可能需要幾分鐘的時間才能完成。等待「3分鐘壽命即將到期」公告。

+
.顯示範例
[%collapsible]
====
下列範例中的假輸出顯示組態設定已停用：

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
====
. 驗證叢集中節點成員的狀態：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
下列範例顯示叢集中節點的健全狀況和資格資訊：

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 驗證遠端叢集介面的連線能力：


[role="tabbed-block"]
====
.更新版本ONTAP
--
您可以使用 `network interface check cluster-connectivity` 命令以啟動叢集連線的存取檢查、然後顯示詳細資料：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 注意： * 請等待數秒後再執行 `show`命令以顯示詳細資料。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有 ONTAP 版本
--
對於所有 ONTAP 版本、您也可以使用 `cluster ping-cluster -node <name>` 檢查連線能力的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step7]] 將權限等級變更回 admin ：
+
「et -priv. admin」

. 對於更新版本的支援、請使用下列命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔ONTAP ：
+
「系統交換器乙太網路記錄設定密碼」和「系統交換器乙太網路記錄啟用-收集」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 針對發行9.5P16、9.6P12及9.7P10及更新版本的修補程式、請使用下列命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔ONTAP ：
+
「系統叢集交換器記錄設定密碼」和「系統叢集交換器記錄啟用收集」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 如果您禁止自動建立個案、請叫用AutoSupport 下列消息來重新啟用此功能：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」


