---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 在叢集網路中更換故障的Nexus 9336C-FX2交換器、是不中斷營運的程序（NDU）。 
---
= 更換Cisco Nexus 9336C-FX2儲存交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在叢集網路中更換故障的Nexus 9336C-FX2交換器。這是不中斷營運的程序。

.開始之前
在Cisco Nexus 9336C-FX2儲存交換器上安裝NX-OS軟體和RCF之前、請確認：

* 您的系統可支援Cisco Nexus 9336C-FX2儲存交換器。
* 您已參閱Cisco乙太網路交換器頁面上的交換器相容性表、瞭解支援ONTAP 的版本、包括支援的版本、NX-OS和RCF。
* 您已參閱Cisco網站上提供的適當軟體與升級指南。


Cisco Nexus 3000系列交換器：

* 您已下載適用的RCT。
* 現有的網路組態具有下列特性：
+
** 「Cisco乙太網路交換器」頁面提供您交換器上最新的RCF和NX-OS版本。
** 兩台交換器都必須具備管理連線能力。


* 替換的Cisco Nexus 9336C-FX2交換器具有下列特性：
+
** 管理網路連線功能正常。
** 更換交換器的主控台存取已就緒。
** 適當的RCF和NX-OS作業系統映像會載入交換器。
** 交換器的初始配置已完成。




.關於這項工作
此程序將第二個Nexus 9336C-FX2儲存交換器S2取代為新的9336C-FX交換器NS2。這兩個節點分別是node1和node2。

完成步驟：

* 確認要更換的交換器為S2。
* 從交換器S2拔下纜線。
* 將纜線重新連接至交換器NS2。
* 確認交換器NS2上的所有裝置組態。
+

NOTE: RCF和NX-OS版本中的命令語法可能會有相依性。



.步驟
. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -訊息MAn=xh」

+
_x_是維護時段的持續時間（以小時為單位）。

. 檢查儲存節點連接埠的健全狀況、確定已連線至儲存交換器S1：
+
「torage port show -port-type ENET」

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 確認儲存交換器S1可用：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. 執行展示 `lldp neighbors` 在工作交換器上執行命令、確認您可以同時看到節點和所有磁碟櫃：
+
`show lldp neighbors`

+
.顯示範例
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 驗證儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. 拔下連接至儲存交換器S2的所有纜線。
. 將所有纜線重新連接至更換的交換器NS2。
. 重新檢查儲存節點連接埠的健全狀況：
+
「torage port show -port-type ENET」

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 確認兩個交換器都可用：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. 驗證儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」



.接下來呢？
link:../switch-cshm/config-overview.html["設定交換器健全狀況監控"]。
