---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: '更換叢集網路中有缺陷的 Nexus 9336C-FX2 交換器是一個無中斷過程 \(NDU\)。' 
---
= 更換Cisco Nexus 9336C-FX2 和 9336C-FX2-T 儲存交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更換集群網路中有缺陷的 Nexus 9336C-FX2 和 9336C-FX2-T 交換器。這是一個非破壞性的過程。

.開始之前
在Cisco Nexus 9336C-FX2 和 9336C-FX2-T 儲存交換器上安裝 NX-OS 軟體和 RCF 之前，請確保：

* 您的系統可以支援Cisco Nexus 9336C-FX2 和 9336C-FX2-T 儲存交換器。
* 您已在Cisco乙太網路交換器頁面上查閱了交換器相容性表，以了解支援的ONTAP、NX-OS 和 RCF 版本。
* 您已參考Cisco網站上提供的相應軟體和升級指南。
* 您已下載適用的 RCF 檔案。
* 現有網路配置有以下特點：
+
** Cisco乙太網路交換器頁麵包含交換器上最新的 RCF 和 NX-OS 版本。
** 兩台交換器都必須具備管理連線功能。


* 替代CiscoNexus 9336C-FX2 交換器具有以下特點：
+
** 管理網路連線正常。
** 已具備對替換開關的控制台存取權限。
** 將對應的 RCF 和 NX-OS 作業系統映像載入到交換器上。
** 交換器的初始配置已完成。




.關於此任務
此程序將第二台 Nexus 9336C-FX2 儲存交換器 s2 替換為新的 9336C-FX 交換器 ns2。這兩個節點分別是 cluster1-01 和 cluster1-02。

完成步驟：

* 確認要更換的交換器是 s2。
* 中斷交換器 s2 的纜線連線。
* 重新連接纜線至交換器 ns2。
* 驗證交換器 ns2 上的所有裝置組態。
+

NOTE: RCF 和 NX-OS 版本中的指令語法可能存在相依性。



.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

. 檢查儲存節點連接埠的健全狀況狀態，確保與儲存交換器 s1 有連線：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 確認儲存交換器 s1 是否可用：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. 掌控全場 `lldp neighbors`在工作交換器上執行指令，確認可以看到兩個節點和所有機架：
+
`show lldp neighbors`

+
.顯示範例
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 驗證儲存系統中的儲存櫃連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. 拆除連接到儲存交換器 s2 的所有纜線。
. 將所有纜線重新連接至替換交換器 ns2 。
. 請重新檢查儲存節點連接埠的運作狀況：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 確認兩台交換器均可用：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. 檢查儲存系統中的貨架連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
更換開關後，您可以 link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
