---
permalink: switch-cisco-9336c-fx2-storage/upgrade-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 您可以使用此程序升級您的 RCF 版本。 
---
= 升級您的參考設定檔 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您的運行交換器上已安裝了現有版本的 RCF 檔案時，您需要升級 RCF 版本。

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* 當前的RCF。
* 如果您要更新 RCF 版本，則需要在 RCF 中進行啟動配置，以反映所需的啟動映像。
+
如果需要更改啟動配置以反映目前的啟動映像，則必須在重新套用 RCF 之前進行更改，以便在以後的重新啟動中實例化正確的版本。




NOTE: 在此過程中不需要任何可操作的交換器間連結 (ISL)。這是設計使然，因為 RCF 版本的變更可能會暫時影響 ISL 連線。為確保叢集運作不會中斷，以下步驟將所有叢集 LIF 遷移到運作夥伴交換機，同時在目標交換器上執行對應步驟。


CAUTION: 在安裝新的交換器軟體版本和 RCF 之前，必須清除交換器設定並執行基本設定。在清除交換器設定之前，您必須使用序列控制台連接到交換機，或保留基本設定資訊。



== 第一步：準備升級

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 為維護視窗的持續時間（小時）。

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 顯示每個節點上連接到交換器的連接埠：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
node1-01/cdp
            e3a    cs1                       Ethernet1/7     N9K-C9336C
            e3b    cs2                       Ethernet1/7     N9K-C9336C
node1-02/cdp
            e3a    cs1                       Ethernet1/8     N9K-C9336C
            e3b    cs2                       Ethernet1/8     N9K-C9336C
.
.
.
----
====
. 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
node1-02
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
.
.
.
----
====
. 停用群集 LIF 的自動回滾功能。
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





== 步驟 2：設定埠

. 在交換器cs1上，關閉與節點所有連接埠連接的連接埠。
+
[listing, subs="+quotes"]
----
cs1> *enable*
cs1# *configure*
cs1(config)# *interface eth1/1/1-2,eth1/7-8*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: 確保關閉所有連接的連接埠以避免任何網路連線問題。請參閱知識庫文章 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["在切換作業系統升級期間遷移叢集 LIF 時，節點脫離仲裁。"^]更多詳情請見下文。

. 驗證叢集 LIF 是否已故障轉移到交換器 cs1 上託管的連接埠。這可能需要幾秒鐘。
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e7b     true

8 entries were displayed.
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false

4 entries were displayed.
----
====
. 如果您尚未儲存目前交換器配置，請將以下命令的輸出複製到文字檔案中：
+
`show running-config`

+
.. 記錄目前版本與目前版本之間的任何自訂新增內容。 `running-config`以及正在使用的 RCF 檔案（例如貴組織的 SNMP 配置）。
.. 對於 NX-OS 10.2 及更高版本，請使用 `show diff running-config`用於與 bootflash 中儲存的 RCF 檔案進行比較的命令。否則，請使用第三方差異比較工具。


. 儲存基本配置詳細信息 `write_erase.cfg`啟動閃存上的檔案。
+
[NOTE]
====
確保配置以下內容：

** 使用者名稱和密碼
** 管理 IP 位址
** 預設網關
** 交換器名稱


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

. 升級到 RCF 版本 1.12 及更高版本時，請執行以下命令：
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1280 >> bootflash:write_erase.cfg`

+
請參閱知識庫文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除Cisco互連交換器上的配置"^]更多詳情請見下文。

. 確認 `write_erase.cfg`文件已如預期填入：
+
`*show file bootflash:write_erase.cfg*`

. 問題 `write erase`清除目前已儲存配置的命令：
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 將先前儲存的基本配置複製到啟動配置中。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. 重啟交換器：
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP 位址恢復正常後，透過 SSH 登入交換器。
+
您可能需要更新與 SSH 金鑰相關的 hosts 檔案項目。

. 使用下列傳輸協定之一將 RCF 複製到交換器 cs1 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 指令參考"^]指南。

+
.顯示範例
[%collapsible]
====
此範例展示如何使用 TFTP 將 RCF 檔案複製到交換器 cs1 的啟動快閃記憶體中：

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_9336C_RCF_v1.6-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 將先前下載的 RCF 檔案套用到啟動快閃記憶體。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 指令參考"^]指南。

+
此範例展示了 RCF 文件 `NX9336C-FX2-RCF-v1.13-1-Storage.txt`正在交換器 cs1 上安裝：

+
[listing, subs="+quotes"]
----
cs1# *copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
確保仔細閱讀 RCF 的 *安裝說明*、*重要說明* 和 *橫幅* 部分。您必須閱讀並遵循這些說明以確保交換器的正確配置和操作。

====
. 請確認 RCF 檔案是否為最新版本：
+
`show running-config`

+
檢查輸出結果以驗證是否擁有正確的 RCF 時，請確保以下資訊正確：

+
** RCF橫幅
** 節點和連接埠設置
** 客製化
+
輸出結果會根據您的網站配置而有所不同。檢查連接埠設置，並參考發行說明，以了解您安裝的 RCF 版本是否有任何特定變更。



. 將先前對交換器配置所做的任何自訂設定重新套用。
. 確認 RCF 版本、自訂新增項目和交換器設定正確後，複製以下內容： `running-config`文件到 `startup-config`文件。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 指令參考"^]指南。

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. 重啟交換器cs1。在交換器重新啟動期間，您可以忽略節點上報告的「叢集交換器健康監視器」警報和「叢集連接埠關閉」事件。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
node1-02
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
.
.
.
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. 在交換器 cs2 上重複步驟 4 至 19。
. 啟用叢集 LIF 的自動回滾功能。
+
`network interface modify -vserver Cluster -lif * -auto-revert true`





== 步驟 3：驗證叢集網路配置和叢集健康狀況

. 確認連接到叢集連接埠的交換器連接埠已啟用。
+
[source, cli]
----
show interface brief
----
. 確認預期節點仍然連接：
+
[source, cli]
----
show cdp neighbors
----
. 使用下列命令驗證叢集節點是否位於正確的叢集 VLAN 中：
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
. 確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -role cluster
----
+
如果任何叢集 LIF 尚未返回其來源端口，請從本機節點手動將其還原：

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. 驗證叢集是否運作正常：
+
[source, cli]
----
cluster show
----
. 驗證遠端集群介面的連接性：
+
.. 你可以使用 `network interface check cluster-connectivity show`用於顯示叢集連接性可訪問性檢查詳細資訊的命令：
+
[source, cli]
----
network interface check cluster-connectivity show
----
.. 或者，您可以使用 `cluster ping-cluster -node <node-name>`檢查連接性的命令：
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----




.下一步是什麼？
升級 RCF 後，您可以link:configure-ssh-keys.html["驗證 SSH 配置"]。
