---
permalink: switch-cisco-9808/configure-upgrade-nxos-9808.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9808 
summary: 您可以升級 Cisco Nexus 9808 交換器上的 NX-OS，以支援新硬體或 AFX 2K 系統上的新 ONTAP 版本。 
---
= 升級 NX-OS - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級 Cisco Nexus 9808 交換器上的 NX-OS，以支援新硬體或 AFX 2K 系統上的新 ONTAP 版本。

.開始之前
* 請確保您已備份最新的交換器組態。
* 確認您的叢集功能完全正常，即日誌中沒有錯誤或類似問題。


.關於此任務
* 如有需要，您可以參考 link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Cisco Nexus 9000 系列 NX-OS 軟體升級與降級指南"^] 以取得更多資訊。
* AFX 系統上執行的 ONTAP 版本決定了交換器支援的 NX-OS 版本。
+
** 支援在 AFX 2K 系統中執行 ONTAP 9.19.1GA 或更高版本以及 NX-OS 10.6 及更高版本的交換器。
+
有關目前支援的 NX-OS 版本列表，請參閱link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 乙太網路交換器"^]頁面。

+

NOTE: 請勿將 NX-OS 版本升級或降級至不支援的版本。



* 此程序需要使用 ONTAP 指令和 Cisco Nexus 9000 系列交換器指令，步驟中會說明您使用哪個 CLI 來輸入指令。
* 本流程中的範例使用以下開關和節點命名規則：
+
** 這兩個Cisco交換器的名稱分別是 cs1 和 cs2。
** 節點名稱為node1-01、node1-02、node1-03和node1-04。
** 集群 LIF 名稱為：
+
*** node1-01 的 node1-01_clus1 和 node1-01_clus2
*** node1-02 的 node1-02_clus1 和 node1-02_clus2
*** node1-03 的 node1-03_clus1 和 node1-03_clus2
*** node1-04 的 node1-04_clus1 和 node1-04_clus2


** 這 `cluster1::*>`prompt 指示叢集名稱。






[[step-1-prepare-to-upgrade-the-nx-os]]
== 步驟 1：準備升級 NX-OS

準備升級 NX-OS，請確保每個交換器都已連接管理網路，下載 NX-OS 版本，檢查叢集上的連接埠狀態，並停用叢集 LIF 上的自動還原功能。

.步驟
. 將每台交換器連接到管理網路。
. 使用交換器 CLI，驗證與託管 NX-OS 的伺服器的連線。
+
`ping <IP address>`

+
.顯示範例
[%collapsible]
====
此範例驗證交換器可以存取 IP 位址為 172.19.2.1 的伺服器：

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 從 https://software.cisco.com/download/home["Cisco軟體下載"^]頁面將正確版本的 NX-OS 下載至交換器。
. 使用 ONTAP CLI，顯示連接到叢集交換器的每個節點上的叢集連接埠：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-01/lldp
            e10a   cs1 (ec:bb:78:9e:c7:e8)   Ethernet1/5       -
            e10b   cs2 (ec:bb:78:9e:c8:0c)   Ethernet1/14      -
            e8a    cs1 (ec:bb:78:9e:c7:f0)   Ethernet1/7       -
            e8b    cs2 (ec:bb:78:9e:c8:14)   Ethernet1/16      -
            e2a    cs1 (ec:bb:78:9e:c7:d8)   Ethernet1/1       -
            e2b    cs2 (ec:bb:78:9e:c7:fc)   Ethernet1/10      -
            e1a    cs1 (ec:bb:78:9e:c7:e0)   Ethernet1/3       -
            e1b    cs2 (ec:bb:78:9e:c8:04)   Ethernet1/12      -
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/2       N9K-C9808
            e2b    cs2(FDOXXXXXXXX)          Ethernet1/13      N9K-C9808
node1-02/lldp
            e10a   cs1 (ec:bb:78:9e:c7:ec)   Ethernet1/6       -
            e10b   cs2 (ec:bb:78:9e:c8:10)   Ethernet1/15      -
            e8a    cs1 (ec:bb:78:9e:c7:f4)   Ethernet1/8       -
            e8b    cs2 (ec:bb:78:9e:c8:18)   Ethernet1/17      -
            e1a    cs1 (ec:bb:78:9e:c7:dc)   Ethernet1/2       -
            e1b    cs2 (ec:bb:78:9e:c8:00)   Ethernet1/11      -
            e2a    cs1 (ec:bb:78:9e:c7:e4)   Ethernet1/4       -
            e2b    cs2 (ec:bb:78:9e:c8:08)   Ethernet1/13      -
----
====
. 使用 ONTAP CLI 檢查每個連接埠的管理和運作狀態：
+
.. *集群連接埠*
+
... 確認叢集所有連接埠均已啟動且狀態正常：
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy false

Node: node1-03

                                                                       Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... 確認所有叢集介面（LIF）都位於主連接埠上：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current   Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node      Port    Home
----------- --------------- ---------- ------------------ --------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01  e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01  e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02  e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02  e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03  e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03  e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04  e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04  e2b     true
----
====
... 確認集群顯示兩個集群交換器的資訊：
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP


cs1(FOXXXXXXXXX)             cluster-network   10.228.137.253   N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP
----
====


.. *HA 連接埠*
+
... 驗證所有 HA 連接埠是否處於正常運作狀態：
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... 確認所有 HA 連接埠均已正確配置，且互連類型為 RoCE：
+
[source, cli]
----
ha interconnect config show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *儲存連接埠*
+
... 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *儲存架連接埠*
+
... 驗證所有儲存架連接埠是否處於正常狀態：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... 驗證所有儲存架連接埠的連線狀態：
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. 使用 ONTAP CLI，停用叢集 LIF 的自動還原功能。叢集 LIF 將容錯移轉至合作夥伴叢集交換器，並在您對目標交換器執行此程序時保持在該交換器上：
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




[[step-2-install-the-nx-os]]
== 步驟 2：安裝 NX-OS

在第一個交換器 (cs1) 上安裝 NX-OS，方法是安裝並驗證新版本的 NX-OS 和 EPLD，驗證叢集上所有連接埠的運作狀況，然後在第二個交換器 (cs2) 上重複這些步驟。

. 使用交換器 CLI，將 NX-OS 和 EPLD 映像複製到交換器。
+
`copy <protocol>: bootflash: vrf management`

+
.顯示範例
[%collapsible]
====
此範例使用 sftp。

[listing, subs="+quotes"]
----
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos64-s1.10.6.3.F.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
  Progress meter enabled
sftp> *get code/nxos64-s1.10.6.3.F.bin /bootflash/nxos64-s1.10.6.3.F.bin*
/code/nxos64-s1.10.6.3.F.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 使用交換器 CLI，驗證 NX-OS 的運作版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.5(3)(F) [Feature Release]
  Host NXOS: version 10.5(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.5.3.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(1)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 使用交換器 CLI 安裝 NX-OS 和 EPLD 映像。
+
安裝鏡像檔案後，每次交換器重新啟動時都會載入該檔案。

+
`install all nxos bootflash:nxos.<version number>.bin`

+
.顯示範例
[%collapsible]
====
此範例使用 NX-OS 版本 10.6(3)(F)。

[listing, subs="+quotes"]
----
cs1# *install all nxos bootflash:/nxos64-s1.10.6.3.F.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos64-s1.10.6.3.F.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash://nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.5(3)(F)                               10.6(3)(F)          Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 交換器重新啟動後，使用交換器 CLI 驗證 NX-OS 的新版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.6(3)(F) [Feature Release]
  Host NXOS: version 10.6(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.6.3.F.bin
  NXOS compile time:  05/30/2026 12:00:00 [06/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(2)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 使用交換器 CLI，驗證新版本的 EPLD 是否已成功載入：
+
`show install epld status`

+
.顯示範例
[%collapsible]
====
此範例使用 EPLD 版本 10.6(3)(F)。

[listing, subs="+quotes"]
----
cs1# *show install epld status*

1) Module 2 upgraded on Mon May  4 09:17:08 2026 (631239  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Fri Apr 24 19:49:50 2026

Status: EPLD Upgrade was Successful

EPLD                             Curr Ver       Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006

2) Module 27 upgraded on Wed Apr  1 15:03:13 2026 (193093  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

3) Module 28 upgraded on Wed Apr  1 14:59:53 2026 (843907  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

4) Module 27 upgraded on Fri Mar 27 21:55:55 2026 (132290  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

5) Module 27 upgraded on Fri Mar 27 21:50:16 2026 (  4899  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

6) Module 27 upgraded on Fri Mar 27 21:44:36 2026 (775397  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

7) Module 27 upgraded on Fri Mar 27 21:38:58 2026 (330582  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

8) Module 27 upgraded on Fri Mar 27 21:33:19 2026 (112679  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

9) Module 27 upgraded on Fri Mar 27 21:27:41 2026 (957182  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

10) Module 27 upgraded on Fri Mar 27 21:22:03 2026 ( 90303  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

11) Module 1 upgraded on Fri Mar 27 21:16:24 2026 (240369  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006
----
====
. 使用 ONTAP CLI 驗證叢集上所有連接埠的運作狀況。
+
.. *集群連接埠*
+
... 確認叢集中所有節點的叢集連接埠均已啟動且運作狀況良好：
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03
                                                                         Ignore
                                                  Speed(Mbps)   Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper    Status   Status
--------- ------------ ---------------- ---- ---- ------------- -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... 從叢集驗證交換器運作狀況：
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
.
.
.
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/2       N9K-C9808
            e2b    cs2(FDOXXXXXXXX)          Ethernet1/13      N9K-C9808
.
.
.
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1(FOXXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP


cs2(FDOXXXXXXXX)             cluster-network   10.228.137.253   N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP
----
====


.. *HA 連接埠*
+
... 驗證所有 HA 連接埠是否處於正常運作狀態：
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... 確認所有 HA 連接埠均已正確配置，且互連類型為 RoCE：
+
[source, cli]
----
ha interconnect config show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *儲存連接埠*
+
... 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *儲存架連接埠*
+
... 驗證所有儲存架連接埠是否處於正常狀態：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... 驗證所有儲存架連接埠的連線狀態：
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)

16 entries were displayed.
----
====




. 使用 ONTAP CLI 驗證叢集是否運作正常：
+
[source, cli]
----
cluster show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*


Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1-01             true    true          false
node1-02             true    true          false
node1-03             true    true          false
node1-04             true    true          true
----
====
. 重複這些步驟，在交換器 cs2 上安裝 NX-OS 和 EPLD 映像。




[[step-3-complete-the-nx-os-upgrade]]
== 步驟 3：完成 NX-OS 升級

使用 ONTAP CLI，重新啟用叢集 LIF 上的自動還原功能，並驗證叢集 LIF 是否已還原至其主連接埠，從而完成 NX-OS 升級。

. 重新啟用叢集 LIF 的自動回復功能。
+
`network interface modify -vserver Cluster -lif * -auto-revert true`

. 確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true
----
====
+
如果任何叢集 LIF 尚未返回其來源端口，請從本機節點手動將其還原：

+
[source, cli]
----
network interface revert -vserver Cluster -lif <lif-name>
----


.下一步是什麼？
在交換器上升級 NX-OS 之後，您需要從 link:configure-install-upgrade-rcf-overview-9808.html["安裝或升級 RCF 概述"] 開始升級 RCF。
