---
permalink: switch-cisco-9808/configure-install-nxos-9808.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9808 
summary: 您可以在 Cisco Nexus 9808 交換器上安裝 NX-OS，作為新 AFX 2K 系統安裝、主管模組更換或交換器重設為原廠預設值的一部分。 
---
= 安裝 NX-OS - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 Cisco Nexus 9808 交換器上安裝 NX-OS，作為新 AFX 2K 系統安裝、主管模組更換或交換器重設為原廠預設值的一部分。

.開始之前
* 交換器必須通電，且您必須已完成 link:configure-complete-initial-setup-9808.html["完成初始交換器設置"] 程序。
* 如果您在交換器上安裝 NX-OS 是為了進行新的 AFX 系統安裝或更換管理模組，請確認交換器上的 NX-OS 版本是目前 NetApp 支援的版本。
+
** 如果您的交換器已安裝目前 NetApp 支援的版本，則無需安裝 NX-OS。您需要安裝參考組態檔案 （RCF）。首先，請執行link:configure-install-upgrade-rcf-overview-9808.html["安裝或升級 RCF 概述"]。
** 如果您的交換器沒有目前 NetApp 支援的版本，請繼續執行此步驟來安裝 NX-OS。


* 如果您在交換器上安裝 NX-OS，作為交換器更換或交換器重設為原廠預設值的一部分，請驗證您的叢集是否完全正常運作，即日誌中沒有錯誤或類似問題。
* 如果您正在安裝 NX-OS 作為新 AFX 系統安裝的一部分，則可以跳過此要求，因為在 AFX 系統安裝和設定的這一階段，AFX 系統中的控制器尚未通電。


.關於此任務
* AFX 系統上執行的 ONTAP 版本決定了交換器支援的 NX-OS 版本。
+
** 支援在 AFX 2K 系統中執行 ONTAP 9.19.1GA 或更高版本以及 NX-OS 10.6(3) 及更高版本的交換器。
+
有關目前支援的 NX-OS 版本列表，請參閱link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 乙太網路交換器"^]。



* 此程序僅需使用 Cisco Nexus 9000 系列交換器指令。
* 本程序中的範例將第一個交換器稱為 cs1，第二個交換器稱為 cs2。
* 如果您已將交換器作為新的 AFX 2K 系統安裝的一部分進行安裝，請先在第一個交換器 (cs1) 上安裝 NX-OS，然後使用此程序對第二個交換器 (cs2) 重複這些步驟。




[[step-1-prepare-to-install-the-nx-os]]
== 步驟 1：準備安裝 NX-OS

要準備在交換器上安裝 NX-OS，請確保您能夠存取具有支援的 NX-OS 版本的伺服器，下載 NX-OS，連接到管理網路進行檔案傳輸，然後驗證與伺服器的連線。

.步驟
. 您必須擁有對 HTTP、SFTP、FTP 或 TFTP 伺服器的存取權限。存取其中任何一個伺服器，即可下載支援的 NX-OS 版本。
. 從 https://software.cisco.com/download/home["Cisco軟體下載"^]頁面下載正確版本的 NX-OS 和 EPLD 映像檔到交換器。
. 將交換器連接到管理網路（用於檔案傳輸）。
. 使用  `ping` 命令驗證與託管 NX-OS 之伺服器的連線。
+
`ping <IP address>`

+
.顯示範例
[%collapsible]
====
此範例驗證交換器可以存取 IP 位址為 172.19.2.1 的伺服器：

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====




[[step-2-install-the-nx-os-and-epld-image]]
== 步驟 2：安裝 NX-OS 和 EPLD 映像

在第一個交換器 (cs1) 上安裝 NX-OS 和 EPLD 映像，方法是安裝並驗證 NX-OS 和 EPLD 映像版本；如果要將 NX-OS 作為新的 AFX 系統安裝的一部分進行安裝，請在第二個交換器 (cs2) 上重複這些步驟。

. 將 NX-OS 和 EPLD 映像複製到第一台交換器。
+
`copy <protocol>: bootflash: vrf management`

+
.顯示範例
[%collapsible]
====
此範例使用 sftp。

[listing, subs="+quotes"]
----
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos64-s1.10.6.3.F.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
  Progress meter enabled
sftp> *get code/nxos64-s1.10.6.3.F.bin /bootflash/nxos64-s1.10.6.3.F.bin*
/code/nxos64-s1.10.6.3.F.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 請確認 NX-OS 的運作版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.5(3)(F) [Feature Release]
  Host NXOS: version 10.5(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.5.3.F.bin
  NXOS compile time:  02/27/2026 12:00:00 [03/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Mar 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.5(3)(F)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 安裝 NX-OS 和 EPLD 映像。
+
安裝鏡像檔案後，每次交換器重新啟動時都會載入該檔案。

+
`install all nxos bootflash:nxos.<image_file>.bin`

+
.顯示範例
[%collapsible]
====
此範例使用 NX-OS 版本 10.6(3)(F)。

[listing, subs="+quotes"]
----
cs1# *install all nxos bootflash:nxos64-s1.10.6.3.F.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos64-s1.10.6.3.F.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.5(3)(F)                               10.6(3)(F)          Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 交換器重新啟動後，請驗證 NX-OS 的新版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.6(3)(F) [Feature Release]
  Host NXOS: version 10.6(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.6.3.F.bin
  NXOS compile time:  05/30/2026 12:00:00 [06/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.6(3)(F)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 確認新版 EPLD 已成功載入：
+
`show install epld status`

+
.顯示範例
[%collapsible]
====
此範例使用 EPLD 版本 10.6(3)(F)。

[listing, subs="+quotes"]
----
cs1# *show install epld status*

1) Module 2 upgraded on Mon May  4 09:17:08 2026 (631239  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Fri Apr 24 19:49:50 2026

Status: EPLD Upgrade was Successful

EPLD                             Curr Ver       Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006

2) Module 27 upgraded on Wed Apr  1 15:03:13 2026 (193093  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

3) Module 28 upgraded on Wed Apr  1 14:59:53 2026 (843907  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

4) Module 27 upgraded on Fri Mar 27 21:55:55 2026 (132290  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

5) Module 27 upgraded on Fri Mar 27 21:50:16 2026 (  4899  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

6) Module 27 upgraded on Fri Mar 27 21:44:36 2026 (775397  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

7) Module 27 upgraded on Fri Mar 27 21:38:58 2026 (330582  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

8) Module 27 upgraded on Fri Mar 27 21:33:19 2026 (112679  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

9) Module 27 upgraded on Fri Mar 27 21:27:41 2026 (957182  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

10) Module 27 upgraded on Fri Mar 27 21:22:03 2026 ( 90303  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

11) Module 1 upgraded on Fri Mar 27 21:16:24 2026 (240369  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006
cs1#
----
====
. 如果您要將 NX-OS 作為新 AFX 系統安裝的一部分來安裝，請重複這些步驟，在交換器 cs2 上安裝 NX-OS 和 EPLD 映像。


.下一步是什麼？
在交換器上安裝 NX-OS 後，您需要從 link:configure-install-upgrade-rcf-overview-9808.html["安裝或升級 RCF 概述"] 開始安裝 RCF。
