---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/9336c_migrate_from_a_switchless_cluster_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= 透過新增兩個共用交換器、從具有直接附加儲存設備的無交換器叢集移轉
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




== 使用直接附加儲存設備從無交換器叢集移轉

將雙節點無交換式叢集（不中斷營運）移轉至採用Cisco Nexus 9336C-FX2叢集交換器的叢集時、您必須瞭解某些組態資訊、連接埠連線和纜線需求。您使用的程序取決於每個控制器上是否有兩個專屬的叢集網路連接埠、或每個控制器上是否有一個叢集連接埠。記錄的程序適用於所有使用光纖或雙軸纜線連接埠的節點、但如果節點使用內建10Gb Base-T RJ45連接埠作為叢集網路連接埠、則此交換器不支援此程序。

大多數系統在每個控制器上都需要兩個專用的叢集網路連接埠。請參閱  https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換器"] 以取得更多資訊。

如果您現有的雙節點無交換式叢集環境、可以使用Cisco Nexus 9336C-FX2交換器移轉至雙節點交換式叢集環境、以便擴充至叢集中的兩個節點以外。

.開始之前
* 雙節點無交換器組態：
+
** 雙節點無交換器組態必須正確設定並正常運作。
** 節點必須執行ONTAP 的是更新版本的版本。
** 所有叢集連接埠都必須處於* up *狀態。
** 所有叢集邏輯介面（lifs）都必須處於* up *狀態、而且必須位於* home*連接埠上。


* Cisco Nexus 9336C-FX2交換器組態：
+
** 兩台交換器都必須具備管理網路連線能力。
** 叢集交換器必須有主控台存取權。
** Nexus 9336C-FX2節點對節點交換器和交換器對交換器連線必須使用雙軸纜線或光纖纜線。
** NetApp https://hwu.netapp.com["Hardware Universe"] 包含纜線的詳細資訊。
** 交換器間連結（ISL）纜線必須連接至9336C-FX2交換器的連接埠1/35和1/36。


* 9336C-FX2交換器的初始自訂必須完成。因此：
+
** 9336C-FX2交換器正在執行最新版本的軟體
** 參考組態檔（RCT）已套用至交換器
** 必須在新交換器上設定任何站台自訂、例如：SMTP、SNMP和SSH。




本程序中的範例使用下列叢集交換器和節點命名法：

* 9336C-FX2交換器的名稱為_CS1_和_CS2_。
* 叢集SVM的名稱為_node1_和_node2_。
* lifs的名稱分別是節點1上的_node1_clus1_和節點1_clus2_、節點2上的節點2_clus1_和節點2_clus2_。
* cluster1：：*>提示會指出叢集的名稱。
* 此程序中使用的叢集連接埠是_e3a_和_e3c_、如同AFF 根據ESIA400控制器。。 https://hwu.netapp.com["Hardware Universe"] 包含平台實際叢集連接埠的最新資訊。


.步驟
. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 「系統節點AutoSupport 支援功能叫用節點*-type all -most MAn=xh」訊息來禁止自動建立案例。
+
其中x是維護時段的持續時間（以小時為單位）。




NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

. [[step2]]將權限層級變更為進階、並在系統提示您繼續時輸入y：「et -priv榮幸advanced'（設定-權限進階）」
+
出現進階提示（*>）。

. 在新的叢集交換器CS1和CS2上停用所有面向節點的連接埠（非ISL連接埠）。您不得停用ISL連接埠。
+
以下範例顯示、交換器CS1上的節點對介連接埠1至34已停用：



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e/1-34
cs1(config-if-range)# shutdown
----
. [[step4]驗證兩個9336C-FX2交換器CS1和CS2之間的ISL和實體連接埠是否在連接埠1/35和1/36上為開啟狀態：「顯示連接埠通道摘要」
+
下列範例顯示交換器CS1上的ISL連接埠已開啟：



[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
下列範例顯示交換器CS2上的ISL連接埠已開啟：

[listing]
----
       cs2# show port-channel summary
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
. [[step5]顯示鄰近裝置的清單：「How cup neighbor」。
+
此命令提供有關連線至系統之裝置的資訊。下列範例列出交換器CS1上的鄰近裝置：



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
下列範例列出交換器CS2上的鄰近裝置：

[listing]
----
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
. [[step6]確認所有叢集連接埠都已啟動：「network port show - IPSpace Cluster（網路連接埠顯示- IPSpace叢集）」
+
每個連接埠應顯示「Link」（連結）和「Healthy for Health」（健全狀況）狀態：



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
. [[step7]確認所有叢集生命週年都在運作中：「network interface show - vserver cluster」（網路介面顯示- vserver叢集）
+
每個叢集LIF都應該顯示為「原位」、並具有「狀態管理/作業者」的開機/開機狀態。



[listing]
----
cluster1::*> network interface show -vserver Cluster
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
. [[step8]確認所有叢集生命體上都已啟用自動還原功能：「network interface show - vserver cluster -Fields autosupgres'（網路介面顯示- Vserver叢集-欄位自動還原）」


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
. [[step9]使用936C-FX2交換器所支援的適當纜線、從節點1上的叢集連接埠e3a拔下纜線、然後將e3a連接至叢集交換器CS1上的連接埠1。
+
NetApp https://hwu.netapp.com["Hardware Universe"] 包含纜線的詳細資訊。

. 從節點2上的叢集連接埠e3a拔下纜線、然後使用9336C-FX2交換器支援的適當纜線、將e3a連接至叢集交換器CS1上的連接埠2。
. 在叢集交換器CS1上啟用所有面向節點的連接埠。
+
下列範例顯示交換器CS1上已啟用連接埠1/1至1/34：



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1-34
cs1(config-if-range)# no shutdown
----
. [[step12]驗證所有叢集生命體是否均為*正常運作*、並顯示為真實的「is Home」：「network interface show - vserver Cluster（網路介面顯示- Vserver叢集）」
+
以下範例顯示節點1和節點2上的所有lifs均為* up *、且「is Home」結果為* true*：



[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
. [[step13]顯示叢集中節點狀態的相關資訊：「叢集顯示」
+
下列範例顯示叢集中節點的健全狀況和資格資訊：



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. [[step14]使用9336C-FX2交換器支援的適當纜線、從節點1上的叢集連接埠e3b拔下纜線、然後將e3b連接至叢集交換器CS2上的連接埠1。
. 從節點2上的叢集連接埠e3b拔下纜線、然後使用9336C-FX2交換器支援的適當纜線、將e3b連接至叢集交換器CS2上的連接埠2。
. 在叢集交換器CS2上啟用所有面向節點的連接埠。
+
下列範例顯示交換器CS2上已啟用連接埠1/1至1/34：



[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1-34
cs2(config-if-range)# no shutdown
----
. [[step17]確認所有叢集連接埠都已啟動：「network port show - IPSpace Cluster（網路連接埠顯示- IPSpace叢集）」
+
以下範例顯示節點1和節點2上的所有叢集連接埠都已啟動：



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
. [[step18]驗證所有介面是否都顯示為「is Home」（原為首頁）：「network interface show - vserver Cluster（網路介面顯示- Vserver叢集）」



NOTE: 這可能需要幾分鐘的時間才能完成。

以下範例顯示節點1和節點2上的所有lifs均為* up *、且「is Home」結果為真：

[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
. [[step19]確認兩個節點都有一個連線可連線至每個交換器：「How cup neighbor」
+
以下範例顯示兩個交換器的適當結果：



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
. [[step20]顯示叢集中探索到的網路裝置相關資訊：「network device-dDiscovery show -protocol cup」


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
. [[step2a]確認HA配對1（和HA配對2）的儲存組態正確無誤、而且沒有錯誤：「System Switch Ethernet show」（系統交換器乙太網路顯示）


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step22]確認設定已停用：「network options switchless cluster show」



NOTE: 命令可能需要幾分鐘的時間才能完成。等待「3分鐘壽命到期」公告。

以下範例中的「假」輸出顯示組態設定已停用：

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
. [[step23]驗證叢集中節點成員的狀態：「cluster show」（叢集顯示）
+
下列範例顯示叢集中節點的健全狀況和資格資訊：



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. [[step24]確保叢集網路具備完整連線能力：「叢集ping叢集節點節點名稱」


[listing]
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step25]將權限層級改回admin：「et -priv. admin」
. 使用下列命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔：
+
** 「系統交換器乙太網路記錄設定密碼」
** 「系統交換器乙太網路記錄啟用收集」




[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.

Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----


==== 設定共享交換器

本程序中的範例使用下列交換器和節點命名法：

* 這兩個共享交換器的名稱為_SH1_和_sh2_。
* 節點是_node1_和_node2_。



NOTE: 此程序需要同時使用ONTAP 支援指令和Cisco Nexus 9000系列交換器的指令ONTAP 、除非另有說明、否則會使用指令。

.步驟
. 確認HA配對1（和HA配對2）的儲存組態正確無誤、而且沒有錯誤：「System Switch Ethernet show」（系統交換器乙太網路顯示）


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step2]確認儲存節點連接埠正常運作：「torage port show -port-type ENET」


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step3]]將HA配對1、NSM224路徑A連接埠移至SH1連接埠範圍11-22。
. 安裝HA配對1、節點1、SH1連接埠範圍11-22路徑A的纜線。例如AFF 、在不經意的情況下、儲存連接埠的路徑是e0c。
. 安裝從HA配對1、節點2、路徑A到SH1連接埠範圍11-22的纜線。
. 驗證節點連接埠是否正常運作：「torage port show -port-type ENET」


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step7]檢查叢集是否有儲存交換器或纜線問題：「系統健全狀況警示顯示-instance」


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step8]將HA配對1、NSM224路徑B連接埠移至sh2連接埠範圍11-22。
. 安裝從HA配對1、節點1、路徑B到sh2連接埠範圍11-22的纜線。例如AFF 、位於ESIVA400上的路徑B儲存連接埠是e5b。
. 安裝從HA配對1、節點2、路徑B到sh2連接埠範圍11-22的纜線。
. 驗證節點連接埠是否正常運作：「torage port show -port-type ENET」


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step12]確認HA配對1的儲存組態正確無誤、而且沒有錯誤：「System Switch Ethernet show」（系統交換器乙太網路顯示）


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step13]重新設定HA配對1上未使用的（控制器）二線儲存連接埠、從儲存設備到網路。如果直接連接多個NS224、則應該重新設定連接埠。


[listing]
----
storage port modify –node [node name] –port [port name] –mode network
----
若要將儲存連接埠放入廣播網域：

* 「網路連接埠廣播網域建立」（如有需要、可建立新網域）
* 「網路連接埠廣播網域附加連接埠」（將連接埠新增至現有網域）


. [[step14]如果您禁止自動建立案例、請叫用AutoSupport 下列訊息來重新啟用：「System nodeeseInvoke AutoSupport -Node *-type all -Message MAn=end」

