---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/9336c_migrate_from_a_switched_configuration_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= 透過新增兩個共用交換器、從具有直接附加儲存設備的交換式組態進行移轉
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




== 使用直接附加儲存設備從交換式組態移轉

當您使用Cisco Nexus 9336C-FX2共用交換器來取代某些舊版Cisco Nexus叢集交換器時、必須注意特定的組態資訊、連接埠連線和纜線需求。

* 支援下列交換器：
+
** Nexus 9336C-FX2
** Nexus 3232C


* 交換器使用下列連接埠來連線至節點：
* Nexus 9336C-FX2：
+
** 連接埠1-3：離線模式（4個10G）叢集內連接埠、int E1/1/1-4、E1/2/1-4
** 連接埠4-6：中斷模式（4個25G）叢集內/ HA連接埠、int E1/4/1-4、E1/5/1-4
** 連接埠7-34：40/100GbE叢集內/ HA連接埠、int E1/7-34


* Nexus 3232C：
+
** 連接埠1-30：10/40/100 GbE


* 交換器使用下列交換器間連結（ISL）連接埠：
+
** 連接埠int E1/35-36：Nexus 9336C-FX2
** 連接埠E1/31至32：Nexus 3232C


* 包含所有叢集交換器所支援的纜線佈線相關資訊。Hardware Universe
+
請參閱 https://hwu.netapp.com["Hardware Universe"] 以取得更多資訊。

* 您已將Nexus 9336C-FX2交換器上的部分連接埠設定為以100 GbE執行。
* 您已規劃、移轉並記錄從節點到Nexus 9336C-FX2交換器的100 GbE連線。
* 本程序所支援的支援的支援版本包括Cisco乙太網路交換器頁面。ONTAP請參閱 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換器"]。
* 您可以在不中斷營運的情況下、將其他Cisco叢集交換器從ONTAP 一個故障叢集移轉至Cisco Nexus 9336C-FX2網路交換器。


.開始之前
* 現有的交換器網路必須正確設定並正常運作。
* 所有連接埠都必須處於「* up」狀態、才能確保不中斷營運。
* Nexus 9336C-FX2交換器必須設定並在適當版本的NX-OS安裝和套用參考組態檔（RCF）下運作。
* 現有的網路組態必須具備下列項目：
+
** 使用兩個舊Cisco交換器的備援且功能完整的NetApp叢集。
** 管理連線能力、以及對舊Cisco交換器和新交換器的主控台存取。
** 使用叢集生命區的所有叢集生命區都位於其主連接埠上。
** 在其他Cisco交換器之間以及新交換器之間啟用或連接ISL連接埠。




本程序中的範例使用下列交換器和節點命名法：

* 現有的Cisco Nexus 3232C叢集交換器為_C1_和_C2_。
* 新的Nexus 9336C-FX2交換器為_SH1_和_sh2_。
* 節點是_node1_和_node2_。
* 叢集生命區分別是節點1上的_node1_clus1_和節點1上的_node1_clus2_、以及節點2上的節點2_node2_clus1_和節點2_clus2_。
* 交換器C2會先由交換器sh2取代、然後由交換器SH1取代交換器C1。


.步驟
. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 下列訊息來抑制自動建立案例：「System Node AutoSupport Rsepooke -Node *-type all -most MAn=x h」
+
其中x是維護時段的持續時間（以小時為單位）。

. 檢查每個叢集連接埠的管理和作業狀態。
. 驗證所有叢集連接埠是否都正常運作：「network port show–role cluster」（網路連接埠顯示–角色叢集）
+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
. [[step4]]確認所有叢集介面（lifs）都位於主連接埠：「網路介面show -role cluster」（網路介面show -role cluster）
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
. [[step5]驗證叢集是否顯示兩個叢集交換器的資訊：「系統叢集交換器show -is監控啟用運作的true」
+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
. [[step6]]停用叢集生命體上的自動還原功能。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. [[step7]關閉C2交換器：
+
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
. [[step8]請確認叢集lifs已移轉至叢集交換器SH1上裝載的連接埠：「網路介面show -role cluster」（網路介面顯示角色叢集）、這可能需要幾秒鐘的時間。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
. [[step9]]將交換器C2更換為新交換器sh2、然後重新連接新交換器。
. 確認sh2上的連接埠已備份。*注意*生命仍在交換器C1上。
. 關閉C1交換器：
+
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
. [[step12]驗證叢集LIF是否已移轉至叢集交換器sh2上裝載的連接埠。這可能需要幾秒鐘的時間。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
. [[step13]將交換器C1更換為新的交換器SH1、然後重新連接新的交換器。
. 確認SH1上的連接埠已備份。*注意*生命仍在交換器C2上。
. 在叢集生命體上啟用自動還原：
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
. [[step16]驗證叢集是否正常：「叢集顯示」
+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----

