---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= 從無交換器叢集遷移到直連存儲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以透過新增兩個新的共用交換機，從無交換機叢集（採用直連儲存）遷移到共用叢集。

具體操作步驟取決於每個控制器上是有兩個專用叢集網路連接埠還是只有一個叢集連接埠。記錄的過程適用於所有使用光纖或 Twinax 連接埠的節點，但如果節點使用板載 10Gb BASE-T RJ45 連接埠作為叢集網路端口，則此交換器不支援此流程。

大多數系統需要在每個控制器上設定兩個專用的叢集網路連接埠。看 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"]了解更多。

如果您已有雙節點無交換器叢集環境，則可以使用Cisco Nexus 9336C-FX2 交換器遷移到雙節點有交換器叢集環境，以便能夠將叢集擴展到兩個以上節點。



== 審查要求

確保：

* 對於雙節點無交換器配置：
+
** 雙節點無交換器配置已正確設定並運作正常。
** 這些節點運行的是ONTAP 9.8 及更高版本。
** 叢集所有連接埠均處於*開啟*狀態。
** 所有群集邏輯介面（LIF）均處於 *up* 狀態，並位於其 *home* 連接埠上。


* 對於Cisco Nexus 9336C-FX2 交換器配置：
+
** 兩台交換器都具備管理網路連線功能。
** 可以透過控制台存取叢集交換器。
** Nexus 9336C-FX2 節點到節點交換器和交換器到交換器連接使用 Twinax 或光纖電纜。
** NetApp https://hwu.netapp.com["Hardware Universe"]包含更多關於佈線的資訊。
** 交換器間連結 (ISL) 電纜連接到兩個 9336C-FX2 交換器上的連接埠 1/35 和 1/36。


* 9336C-FX2交換器的初步客製化工作已完成。因此：
+
** 9336C-FX2交換器運作的是最新版本的軟體
** 參考設定檔 (RCF) 已套用於交換機
** 任何站點定制，如 SMTP、SNMP 和 SSH，都在新交換器上進行設定。






== 遷移交換機

.關於範例
本流程中的範例使用下列叢集交換器和節點命名規則：

* 9336C-FX2 交換器的名稱是 _cs1_ 和 _cs2_。
* 聚類SVM的名稱為_node1_和_node2_。
* 節點 1 上的 LIF 名稱分別為 _node1_clus1_ 和 _node1_clus2_，節點 2 上的 LIF 名稱分別為 _node2_clus1_ 和 _node2_clus2_。
* cluster1::*> 提示符號指示叢集的名稱。
* 根據AFF A400控制器，此過程中使用的叢集連接埠為 _e3a_ 和 _e3b_。這 https://hwu.netapp.com["Hardware Universe"]包含您平台實際集群連接埠的最新資訊。




=== 步驟 1：從無交換器的集群遷移到直連式集群

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例： `system node autosupport invoke -node * -type all -message MAINT=xh` 。
+
其中 x 為維護窗口的持續時間（小時）。




NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

. 步驟2：將權限級別變更為高級，並在提示繼續時輸入y：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 停用新叢集交換器 cs1 和 cs2 上所有面向節點的連接埠（非 ISL 連接埠）。您不得禁用 ISL 連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示交換器 cs1 上面向節點的連接埠 1 到 34 已停用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]]驗證兩個 9336C-FX2 交換器 cs1 和 cs2 之間的 ISL 以及 ISL 上的實體連接埠 1/35 和 1/36 是否已啟動：
+
`show port-channel summary`

+
.顯示範例
[%collapsible]
====
以下範例表示交換器 cs1 上的 ISL 連接埠已啟動：

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
以下範例表示交換器 cs2 上的 ISL 連接埠已啟動：

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. 【步驟5】顯示相鄰設備清單：
+
`show cdp neighbors`

+
此命令提供有關連接到系統的設備的資訊。

+
.顯示範例
[%collapsible]
====
以下範例列出了交換器 cs1 上的相鄰設備：

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
以下範例列出了交換器 cs2 上的相鄰設備：

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. 步驟6：驗證叢集所有連接埠是否都已啟動：
+
`network port show - ipspace Cluster`

+
每個連接埠的“連接”狀態應顯示為“已連接”，並且“健康狀況”狀態應顯示為“正常”。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. 步驟7：驗證所有叢集LIF是否已啟動並正常運作：
+
`network interface show - vserver Cluster`

+
每個聚類 LIF 都應該顯示為 true `Is Home`且管理員/操作員狀態為 up/up。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[步驟8]]驗證所有叢集 LIF 是否已啟用自動回滾功能：
+
`network interface show - vserver Cluster -fields auto-revert`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]斷開節點 1 上的叢集連接埠 e3a 的電纜，然後使用 9336C-FX2 交換器支援的適當電纜將 e3a 連接到叢集交換器 cs1 上的連接埠 1。
+
NetApp https://hwu.netapp.com["Hardware Universe"]包含更多關於佈線的資訊。

. 斷開節點 2 上的叢集連接埠 e3a 的電纜，然後使用 9336C-FX2 交換器支援的適當電纜將 e3a 連接到叢集交換器 cs1 上的連接埠 2。
. 啟用叢集交換器 cs1 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示交換器 cs1 上的連接埠 1/1 到 1/34 已啟用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[步驟12]]驗證所有叢集 LIF 是否已啟動、運作正常，並且顯示為 true。 `Is Home` ：
+
`network interface show - vserver Cluster`

+
.顯示範例
[%collapsible]
====
以下範例表明，節點 1 和節點 2 上的所有 LIF 都已啟動。 `Is Home`結果屬實：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]顯示叢集中節點的狀態資訊：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集中節點的健康狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]斷開節點 1 上的叢集連接埠 e3b 的電纜，然後使用 9336C-FX2 交換器支援的適當電纜將 e3b 連接到叢集交換器 cs2 上的連接埠 1。
. 斷開節點 2 上的叢集連接埠 e3b 的電纜，然後使用 9336C-FX2 交換器支援的適當電纜將 e3b 連接到叢集交換器 cs2 上的連接埠 2。
. 啟用叢集交換器 cs2 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示交換器 cs2 上的連接埠 1/1 到 1/34 已啟用：

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. 步驟17：驗證叢集所有連接埠是否都已啟動。
+
`network port show - ipspace Cluster`

+
.顯示範例
[%collapsible]
====
以下範例顯示節點 1 和節點 2 上的所有叢集連接埠均已啟動：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. 步驟18：驗證所有介面是否都顯示為 true。 `Is Home` ：
+
`network interface show - vserver Cluster`

+

NOTE: 這可能需要幾分鐘才能完成。

+
.顯示範例
[%collapsible]
====
以下範例表明，節點 1 和節點 2 上的所有 LIF 都已啟動。 `Is Home`結果屬實：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. 步驟19：驗證兩個節點是否都與每個交換器有一條連接：
+
`show cdp neighbors`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩種開關的正確結果：

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]顯示集群中已發現的網路設備資訊：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]驗證 HA 對 1（和 HA 對 2）的儲存配置是否正確且無錯誤：
+
`system switch ethernet show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. 步驟22：確認這些設定已停用：
+
`network options switchless-cluster show`

+

NOTE: 命令可能需要幾分鐘才能完成。等待「剩餘3分鐘生命即將耗盡」的公告。

+
這 `false`以下範例的輸出表示組態設定已停用：

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[步驟23]]驗證叢集中節點成員的狀態：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集中節點的健康狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. 步驟25：將權限等級改回管理員：
+
`set -privilege admin`





=== 步驟 2：設定共享交換機

本流程中的範例使用以下開關和節點命名規則：

* 兩個共用交換器的名稱分別為 _sh1_ 和 _sh2_。
* 節點分別為 _node1_ 和 _node2_。



NOTE: 流程需要同時使用ONTAP指令和Cisco Nexus 9000 系列交換器指令，除非另有說明，否則使用ONTAP指令。

. 驗證 HA 對 1（和 HA 對 2）的儲存配置是否正確且無錯誤：
+
`system switch ethernet show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. 確認儲存節點連接埠運作正常：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]將 HA 對 1、NSM224 路徑 A 連接埠移至 sh1 連接埠範圍 11-22。
. 安裝一條從 HA 對 1、節點 1、路徑 A 到 sh1 連接埠範圍 11-22 的電纜。例如， AFF A400上的 A 路徑儲存連接埠為 e0c。
. 安裝一條從 HA 對 1、節點 2、路徑 A 到 sh1 連接埠範圍 11-22 的電纜。
. 確認節點連接埠運作正常：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. 檢查叢集是否有儲存交換器或線纜問題：
+
`system health alert show -instance`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. 將 HA 對 1、NSM224 路徑 B 連接埠移至 sh2 連接埠範圍 11-22。
. 安裝一條從 HA 對 1、節點 1、路徑 B 到 sh2 連接埠範圍 11-22 的電纜。例如， AFF A400上的 B 路徑儲存連接埠為 e5b。
. 安裝一條從 HA 對 1、節點 2、路徑 B 到 sh2 連接埠範圍 11-22 的電纜。
. 確認節點連接埠運作正常：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. 驗證HA對1的儲存配置是否正確且無錯誤：
+
`system switch ethernet show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. 將 HA 對 1 上未使用的（控制器）輔助儲存連接埠從儲存重新配置為網路。如果直接連接了多個 NS224，則需要重新設定某些連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
將儲存連接埠放入廣播域：

+
** `network port broadcast-domain create`（如有需要，建立新網域）
** `network port broadcast-domain add-ports`（向現有網域新增連接埠）


. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
