---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= 從交換式配置遷移到直連存儲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以透過新增兩個新的共用交換機，從具有直連儲存的交換式設定遷移到共用式設定。

.支援的交換機
支援以下交換器：

* Nexus 9336C-FX2
* Nexus 3232C


此過程中支援的ONTAP和 NX-OS 版本請參閱Cisco乙太網路交換器頁面。看 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"]。

.連接埠
交換器使用以下連接埠連接到節點：

* Nexus 9336C-FX2：
+
** 連接埠 1-3：分支模式 (4x10G) 叢集內端口，內部 e1/1/1-4、e1/2/1-4、e1/3/1-4
** 連接埠 4-6：分支模式 (4x25G) 叢集內/高可用性端口，內部 e1/4/1-4、e1/5/1-4、e1/6/1-4
** 連接埠 7-34：40/100GbE 叢集內/高可用性端口，內部 e1/7-34


* Nexus 3232C：
+
** 連接埠 1-30：10/40/100 GbE


* 這些交換器使用以下交換器間連結（ISL）連接埠：
+
** 埠 int e1/35-36：Nexus 9336C-FX2
** 連接埠 e1/31-32：Nexus 3232C




這 https://hwu.netapp.com["Hardware Universe"]包含所有群集交換器支援的佈線資訊。

.你需要什麼
* 請確保您已完成以下任務：
+
** 將 Nexus 9336C-FX2 交換器上的一些連接埠配置為以 100 GbE 運作。
** 規劃、遷移並記錄了從節點到 Nexus 9336C-FX2 交換器的 100 GbE 連線。
** 將其他Cisco集群交換器從ONTAP集群無中斷地遷移到Cisco Nexus 9336C-FX2 網路交換器。


* 現有交換網路已正確設定並正常運作。
* 所有連接埠均處於*開啟*狀態，以確保運作不會中斷。
* Nexus 9336C-FX2 交換器已設定並運作在已安裝的正確版本的 NX-OS 和已套用的參考設定檔 (RCF) 下。
* 現有網路配置如下：
+
** 使用較舊的Cisco交換機構建立冗餘且功能齊全的NetApp叢集。
** 舊款Cisco交換器和新交換器的管理連線和控制台存取。
** 叢集中所有處於 *up* 狀態的 LIF 都位於其主連接埠上。
** ISL 連接埠已啟用，並且已在其他Cisco交換器之間以及新交換器之間連接了電纜。




.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 現有的Cisco Nexus 3232C 叢集交換器是 _c1_ 和 _c2_。
* 新的 Nexus 9336C-FX2 交換器型號為 _sh1_ 和 _sh2_。
* 節點分別為 _node1_ 和 _node2_。
* 節點 1 上的叢集 LIF 分別為 _node1_clus1_ 和 _node1_clus2_，節點 2 上的叢集 LIF 分別為 _node2_clus1_ 和 _node2_clus2_。
* 首先將交換器 c2 替換為交換器 sh2，然後將交換器 c1 替換為交換器 sh1。


.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
其中 x 為維護窗口的持續時間（小時）。

. 檢查每個叢集連接埠的管理和運作狀態。
. 確認叢集所有連接埠均已啟動且狀態正常：
+
`network port show –role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[步驟4]]驗證所有叢集介面（LIF）是否都在主連接埠上：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[步驟5]]驗證叢集是否顯示兩個叢集交換器的資訊：
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]停用叢集 LIF 的自動還原功能。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]關閉 c2 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[步驟8]]驗證叢集 LIF 是否已移轉到叢集交換器 sh1 上託管的連接埠：
+
`network interface show -role cluster`

+
這可能需要幾秒鐘。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]將交換器 c2 替換為新的交換器 sh2，並重新連接新交換器的電纜。
. 請確認 sh2 上的連接埠是否已恢復正常。  *注意* LIF 仍在交換器 c1 上。
. 關閉 c1 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]驗證叢集 LIF 是否已移轉到叢集交換器 sh2 上託管的連接埠。這可能需要幾秒鐘。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]將交換器 c1 更換為新的交換器 sh1，並重新連接新交換器的電纜。
. 請確認 sh1 上的連接埠是否已恢復正常。  *注意* LIF 仍在交換器 c2 上。
. 啟用叢集 LIF 的自動回滾功能：
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[步驟16]]驗證叢集是否健康：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.下一步是什麼？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
