---
permalink: switch-cisco-9364d-gx2a/configure-complete-initial-setup-9364d.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9364d-gx2a 
summary: 安裝新的 AFX 1K 或 AFX 2K 系統或更換交換器時，或將交換器重設為原廠預設設定後，當您啟動 Cisco Nexus 9364D-GX2A 交換器時，系統會提示您使用設定精靈完成交換器的初始設定。您可以參考以下設定精靈問題和建議答案，以協助您完成交換器的初始設定。 
---
= 完成初始交換器設定 - Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝新的 AFX 1K 或 AFX 2K 系統或更換交換器時，或將交換器重設為原廠預設設定後，當您啟動 Cisco Nexus 9364D-GX2A 交換器時，系統會提示您使用設定精靈完成交換器的初始設定。您可以參考以下設定精靈問題和建議答案，以協助您完成交換器的初始設定。

.開始之前
請確保您擁有每台交換器的網路和組態資訊以及相應的授權。

.關於此任務
* 您必須完成每個交換器的初始設定。
* 如有需要，您可以參考 NX-OS 版本的link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/104x/configuration/fundamentals/cisco-nexus-9000-series-nx-os-fundamentals-configuration-guide-release-104x.html["Cisco Nexus 9000 系列 NX-OS 基礎設定指南"^]，以了解有關交換器設定的資訊，相關內容位於「Using the Cisco NX-OS Setup Utility」章節。您也可以在「Configuring Terminal Settings and Sessions」章節中找到有關終端設定的資訊。


.步驟
. 將筆記型電腦連接到交換器的序列控制台連接埠。
+
.. 將筆記型電腦上的序列主控台連接埠設定為 9,600 baud，使用 N-8-1。


. 依照提示設定管理員使用者的密碼。
. 請回答以下問題，完成交換器的初始設定。
+

NOTE: 您網站的安全性原則定義了要啟用的回應和服務。

+
[cols="1,2"]
|===
| 迅速的 | 回覆 


 a| 
中止自動配置並繼續進行正常設定？  （是/否）
 a| 
請回答「是」。預設值為否。



 a| 
您是否希望強制執行安全密碼標準？  （是/否）
 a| 
請回答「是」。預設值為“是”。



 a| 
請輸入管理者密碼。
 a| 
預設密碼為「`admin`」；您必須建立一個新的、強密碼。弱密碼可能會被拒絕。



 a| 
您想進入基本設定對話框嗎？  （是/否）
 a| 
在交換器的初始設定階段，請回答「是」。



 a| 
建立另一個登入帳戶？  （是/否）
 a| 
答案取決於您網站關於備用管理員的政策。預設值為*否*。



 a| 
配置唯讀 SNMP 團體字串？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
配置讀寫 SNMP 團體字串？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
請輸入交換器名稱。
 a| 
請輸入交換器名稱，字數限制為 63 個字母數字字元。



 a| 
繼續進行帶外（mgmt0）管理配置？  （是/否）
 a| 
在該提示出現時，請回答「是」（預設值）。在 mgmt0 IPv4 位址提示字元處，輸入您的 IP 位址：ip_address。



 a| 
配置預設網關？  （是/否）
 a| 
請回答「是」。在預設閘道的 IPv4 位址提示字元處，輸入您的預設閘道。



 a| 
配置進階 IP 選項？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
啟用 Telnet 服務？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
已啟用 SSH 服務？  （是/否）
 a| 
請回答「是」。預設值為“是”。


NOTE: 使用乙太網路交換器健康監視器 (CSHM) 時，建議使用 SSH 進行日誌收集。為了提高安全性，建議使用 SSHv2。



 a| 
請輸入要產生的 SSH 金鑰類型（dsa/rsa/rsa1）。
 a| 
預設值為 *rsa*。



 a| 
請輸入密鑰位數（1024-2048）。
 a| 
請輸入1024到2048之間的密鑰位數。



 a| 
配置NTP伺服器？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
配置預設介面層（L3/L2）
 a| 
請用*L2*回覆。預設值為 L2。



 a| 
配置交換器連接埠介面的預設狀態（關閉/不關閉）
 a| 
回覆 *noshut*。預設為 noshut。



 a| 
設定 CoPP 系統設定檔（嚴格/中/寬鬆/嚴格）
 a| 
回覆時請使用 *strict*。預設為嚴格。



 a| 
您想修改配置嗎？  （是/否）
 a| 
此時您應該可以看到新的配置。請檢查並對您剛剛輸入的配置進行必要的更改。如果對配置滿意，請在提示時回答「否」。如果要編輯配置設置，請回覆「是」。



 a| 
使用此配置並儲存？  （是/否）
 a| 
回覆“是”以儲存配置。這會自動更新啟動鏡像和系統鏡像。


NOTE: 如果此時不儲存配置，下次重新啟動交換器時，所有變更都會失效。

|===
. 在設定結束時顯示的介面中，確認您所做的配置選擇，並確保儲存配置。


.下一步是什麼？
完成初始交換器設定後，您link:configure-review-cabling-config-requirements-9364d.html["審查佈線和配置要求"]。
