---
permalink: switch-cisco-9364d-gx2a/upgrade-rcf-software-9364d-cluster.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 您可以使用此程序升級您的 RCF 版本。 
---
= 升級您的參考設定檔 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您的運行交換器上已安裝了現有版本的 RCF 檔案時，您需要升級 RCF 版本。

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* 當前的RCF。
* 如果您要更新 RCF 版本，則需要在 RCF 中進行啟動配置，以反映所需的啟動映像。
+
如果需要更改啟動配置以反映目前的啟動映像，則必須在重新套用 RCF 之前進行更改，以便在以後的重新啟動中實例化正確的版本。




NOTE: 在此過程中不需要任何可操作的交換器間連結 (ISL)。這是設計使然，因為 RCF 版本的變更可能會暫時影響 ISL 連線。為確保叢集運作不會中斷，以下步驟將所有叢集 LIF 遷移到運作夥伴交換機，同時在目標交換器上執行對應步驟。


CAUTION: 在安裝新的交換器軟體版本和 RCF 之前，必須清除交換器設定並執行基本設定。您必須使用序列控制台連接到交換機，或在擦除交換器設定之前保留基本設定資訊。



== 第一步：準備升級

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 為維護視窗的持續時間（小時）。

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 顯示每個節點上連接到交換器的叢集連接埠：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)         Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs1(FDOXXXXXXXX)         Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)         Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs1(FDOXXXXXXXX)         Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)         Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs1(FDOXXXXXXXX)         Ethernet1/13/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)         Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs1(FDOXXXXXXXX)         Ethernet1/13/2    N9K-C9364D-GX2A
node1-01/lldp
            e10a   cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/3    -
            e10b   cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/3    -
            e11a   cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/4    -
            e11b   cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/4    -
            e1a    cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/1    -
            e1b    cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/1    -
            .
            .
            .
            e7a    cs1 (c8:60:8f:xx:xx:xx)   Ethernet1/16/2    -
            e7b    cs2 (04:e3:87:xx:xx:xx)   Ethernet1/16/2    -
.
.
.
----
====
. 檢查各港口的行政及營運狀況。
+
.. *集群連接埠*
+
... 確認叢集所有連接埠均已啟動且狀態正常：
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node:node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-03

                                                                    Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
... 確認所有叢集介面（LIF）都位於主連接埠上：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical          Status      Network           Current      Current Is
Vserver     Interface        Admin/Oper  Address/Mask      Node         Port    Home
----------- ---------------- ----------- ----------------- ------------ ------- ----
Cluster
            node1-01_clus1   up/up       169.254.3.4/23    node1-01     e7a     true
            node1-01_clus2   up/up       169.254.3.5/23    node1-01     e7b     true
            node1-02_clus1   up/up       169.254.3.8/23    node1-02     e7a     true
            node1-02_clus2   up/up       169.254.3.9/23    node1-02     e7b     true
            node1-03_clus1   up/up       169.254.1.3/23    node1-03     e7a     true
            node1-03_clus2   up/up       169.254.1.1/23    node1-03     e7b     true
            node1-04_clus1   up/up       169.254.1.6/23    node1-04     e7a     true
            node1-04_clus2   up/up       169.254.1.7/23    node1-04     e7b     true
8 entries were displayed.
----
====
... 驗證叢集是否顯示兩台交換器的資訊：
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

cs2(FLMXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9364D-GX2A
     Serial Number: FLMXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP
----
====


.. *HA 連接埠*
+
... 驗證所有 HA 連接埠是否處於正常運作狀態：
+
`ha interconnect status show -node <node-name>`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *儲存連接埠*
+
... 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *儲存架連接埠*
+
... 驗證所有儲存架連接埠是否處於正常狀態：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... 驗證所有儲存架連接埠的連線狀態：
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. 停用叢集 LIF 的自動回滾功能：
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





== 步驟 2：設定埠

. 在交換器cs1上，關閉與節點所有連接埠連接的連接埠。
+
[listing, subs="+quotes"]
----
cs1# *config*
cs1(config)# *interface e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7/1-4,e1/8/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/9/1-4,e1/10/1-4,e1/11/1-4,e1/12/1-4,e1/13/1-4,e1/14/1-4,e1/15/1-4,e1/16/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/17/1-4,e1/18/1-4,e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/33/1-4,e1/34/1-4,e1/35/1-4,e1/36/1-4,e1/37/1-4,e1/38/1-4,e1/39/1-4,e1/40/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/41/1-4,e1/42/1-4,e1/43/1-4,e1/44/1-4,e1/35/1-4,e1/46/1-4,e1/47/1-4,e1/48/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/49/1-4,e1/50/1-4,e1/51/1-4,e1/52/1-4,e1/53/1-4,e1/54/1-4,e1/55/1-4,e1/56/1-4*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/57/1-4,e1/58/1-4,e1/59/1-4,e1/60/1-4,e1/61/1-4,e1/62/1-4*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: 確保關閉所有連接的連接埠以避免任何網路連線問題。請參閱知識庫文章 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["在切換作業系統升級期間遷移叢集 LIF 時，節點脫離仲裁。"^]更多詳情請見下文。

. 驗證叢集 LIF 是否已故障轉移到叢集交換器 cs1 上託管的連接埠。這可能需要幾秒鐘。
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            node1-01_clus1    up/up      169.254.36.44/16   node1-01      e7a     true
            node1-01_clus2    up/up      169.254.7.5/16     node1-01      e7b     true
            node1-02_clus1    up/up      169.254.197.206/16 node1-02      e7a     true
            node1-02_clus2    up/up      169.254.195.186/16 node1-02      e7b     true
            node1-03_clus1    up/up      169.254.192.49/16  node1-03      e7a     true
            node1-03_clus2    up/up      169.254.182.76/16  node1-03      e7b     true
            node1-04_clus1    up/up      169.254.59.49/16   node1-04      e7a     true
            node1-04_clus2    up/up      169.254.62.244/16  node1-04      e7b     true
8 entries were displayed.
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
4 entries were displayed.
----
====
. 如果您尚未儲存目前交換器配置，請將以下命令的輸出複製到文字檔案中：
+
`show running-config`

+
.. 記錄目前版本與目前版本之間的任何自訂新增內容。 `running-config`以及正在使用的 RCF 檔案（例如貴組織的 SNMP 配置）。
.. 對於 NX-OS 10.2 及更高版本，請使用 `show diff running-config`用於與 bootflash 中儲存的 RCF 檔案進行比較的命令。否則，請使用第三方差異/比較工具。


. 儲存基本配置詳細信息 `write_erase.cfg`啟動閃存上的檔案。
+
[NOTE]
====
確保配置以下內容：

** 使用者名稱和密碼
** 管理 IP 位址
** 預設網關
** 交換器名稱


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`

+
請參閱知識庫文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除Cisco互連交換器上的配置"^]更多詳情請見下文。

. 確認 `write_erase.cfg`文件已如預期填入：
+
`*show file bootflash:write_erase.cfg*`

. 問題 `write erase`清除目前已儲存配置的命令：
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 將先前儲存的基本配置複製到啟動配置中。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. 重啟交換器：
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP 位址恢復正常後，透過 SSH 登入交換器。
+
您可能需要更新與 SSH 金鑰相關的 hosts 檔案項目。

. 使用下列傳輸協定之一將 RCF 複製到交換器 cs1 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 指令參考"^]指南。

+
.顯示範例
[%collapsible]
====
此範例展示如何使用 TFTP 將 RCF 檔案複製到交換器 cs1 的啟動快閃記憶體中：

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9364D-GX2A-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 將先前下載的 RCF 檔案套用到啟動快閃記憶體。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 指令參考"^]指南。

+
此範例展示了 RCF 文件 `NX9364D-GX2A-RCF-v10.0-Shared.txt`正在交換器 cs1 上安裝：

+
[listing, subs="+quotes"]
----
cs1# *copy NX9364D-GX2A-RCF-v10.0-Shared.txt running-config echo-commands*
----
+

CAUTION: 請務必仔細閱讀 RCF 的 *安裝說明*、*重要說明* 和 *橫幅* 部分。您必須閱讀並遵循這些說明以確保交換器的正確配置和操作。

. 請確認 RCF 檔案是否為最新版本：
+
`show running-config`

+
檢查輸出結果以驗證是否擁有正確的 RCF 時，請確保以下資訊正確：

+
** RCF橫幅
** 節點和連接埠設置
** 客製化
+
輸出結果會根據您的網站配置而有所不同。檢查連接埠設置，並參考發行說明，以了解您安裝的 RCF 版本是否有任何特定變更。



. 將先前對交換器配置所做的任何自訂設定重新套用。
. 確認 RCF 版本、自訂新增項目和交換器設定正確後，將運行設定檔複製到啟動設定檔。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 指令參考"^]指南。

+
`cs1# copy running-config startup-config`

+
`[########################################] 100% Copy complete`

. 重啟交換器cs1。在交換器重新啟動期間，您可以忽略節點上報告的「叢集交換器健康監視器」警報和「叢集連接埠關閉」事件。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 驗證叢集上連接埠的健康狀況。
+
.. *集群連接埠*
+
... 確認叢集中所有節點的叢集連接埠均已啟動且運作狀況良好：
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.
----
====
... 從叢集中驗證交換器的運作狀況。
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/13/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/13/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FLMXXXXXXXX)          Ethernet1/13/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/13/2    N9K-C9364D-GX2A
node1-02/cdp
.
.
.

cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9364D-GX2A
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

cs1(FLMXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9364D-GX2A
     Serial Number: FLMXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.4(2)
    Version Source: CDP/ISDP

2 entries were displayed.
----
====


.. *HA 連接埠*
+
... 驗證所有 HA 連接埠是否處於正常運作狀態：
+
`ha interconnect status show -node <node-name>`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *儲存連接埠*
+
... 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *儲存架連接埠*
+
... 驗證所有儲存架連接埠是否處於正常狀態：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... 驗證所有儲存架連接埠的連線狀態：
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false
4 entries were displayed.
----
====
. 在交換器 cs2 上重複步驟 4 至 18。
. 啟用叢集 LIF 的自動回滾功能：
+
`network interface modify -vserver Cluster -lif  * -auto-revert True`





== 步驟 3：驗證叢集網路配置和叢集健康狀況

. 確認連接到叢集連接埠的交換器連接埠已開啟。
+
`show interface brief`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
.
----
====
. 確認預期節點仍然連接：
+
`show cdp neighbors`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2(FDOXXXXXXXX)    Eth1/63        179    R S I s   N9K-C9332D-GX2B   Eth1/31
cs2(FDOXXXXXXXX)    Eth1/64        179    R S I s   N9K-C9332D-GX2B   Eth1/32
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18
----
====
. 使用下列命令驗證叢集節點是否位於正確的叢集 VLAN 中：
+
`show vlan brief`

+
`show interface trunk`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/63, Eth1/64
                                                Eth1/65, Eth1/66, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
                                                Eth1/2/1, Eth1/2/2, Eth1/2/3
                                                Eth1/2/4, Eth1/3/1, Eth1/3/2
                                                Eth1/3/3, Eth1/3/4, Eth1/4/1
                                                Eth1/4/2, Eth1/4/3, Eth1/4/4
                                                Eth1/5/1, Eth1/5/2, Eth1/5/3
                                                Eth1/5/4, Eth1/6/1, Eth1/6/2
                                                Eth1/6/3, Eth1/6/4, Eth1/7/1
                                                Eth1/7/2, Eth1/7/3, Eth1/7/4
                                                Eth1/8/1, Eth1/8/2, Eth1/8/3
                                                Eth1/8/4, Eth1/9/1, Eth1/9/2
                                                Eth1/9/3, Eth1/9/4, Eth1/10/1
                                                Eth1/10/2, Eth1/10/3, Eth1/10/4
                                                Eth1/11/1, Eth1/11/2, Eth1/11/3
                                                Eth1/11/4, Eth1/12/1, Eth1/12/2
                                                Eth1/12/3, Eth1/12/4, Eth1/13/1
                                                Eth1/13/2, Eth1/13/3, Eth1/13/4
                                                Eth1/14/1, Eth1/14/2, Eth1/14/3
                                                Eth1/14/4, Eth1/15/1, Eth1/15/2
                                                Eth1/15/3, Eth1/15/4, Eth1/16/1
                                                Eth1/16/2, Eth1/16/3, Eth1/16/4
                                                Eth1/17/1, Eth1/17/2, Eth1/17/3
                                                Eth1/17/4, Eth1/18/1, Eth1/18/2
                                                Eth1/18/3, Eth1/18/4, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
                                                Eth1/28/2, Eth1/28/3, Eth1/28/4
                                                Eth1/29/1, Eth1/29/2, Eth1/29/3
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4, Eth1/31/1
                                                Eth1/31/2, Eth1/31/3, Eth1/31/4
                                                Eth1/32/1, Eth1/32/2, Eth1/32/3
                                                Eth1/32/4, Eth1/33/1, Eth1/33/2
                                                Eth1/33/3, Eth1/33/4, Eth1/34/1
                                                Eth1/34/2, Eth1/34/3, Eth1/34/4
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4, Eth1/36/1, Eth1/36/2
                                                Eth1/36/3, Eth1/36/4, Eth1/37/1
                                                Eth1/37/2, Eth1/37/3, Eth1/37/4
                                                Eth1/38/1, Eth1/38/2, Eth1/38/3
                                                Eth1/38/4, Eth1/39/1, Eth1/39/2
                                                Eth1/39/3, Eth1/39/4, Eth1/40/1
                                                Eth1/40/2, Eth1/40/3, Eth1/40/4
                                                Eth1/41/1, Eth1/41/2, Eth1/41/3
                                                Eth1/41/4, Eth1/42/1, Eth1/42/2
                                                Eth1/42/3, Eth1/42/4, Eth1/43/1
                                                Eth1/43/2, Eth1/43/3, Eth1/43/4
                                                Eth1/44/1, Eth1/44/2, Eth1/44/3
                                                Eth1/44/4, Eth1/45/1, Eth1/45/2
                                                Eth1/45/3, Eth1/45/4, Eth1/46/1
                                                Eth1/46/2, Eth1/46/3, Eth1/46/4
                                                Eth1/47/1, Eth1/47/2, Eth1/47/3
                                                Eth1/47/4, Eth1/48/1, Eth1/48/2
                                                Eth1/48/3, Eth1/48/4, Eth1/49/1
                                                Eth1/49/2, Eth1/49/3, Eth1/49/4
                                                Eth1/50/1, Eth1/50/2, Eth1/50/3
                                                Eth1/50/4, Eth1/51/1, Eth1/51/2
                                                Eth1/51/3, Eth1/51/4, Eth1/52/1
                                                Eth1/52/2, Eth1/52/3, Eth1/52/4
                                                Eth1/53/1, Eth1/53/2, Eth1/53/3
                                                Eth1/53/4, Eth1/54/1, Eth1/54/2
                                                Eth1/54/3, Eth1/54/4, Eth1/55/1
                                                Eth1/55/2, Eth1/55/3, Eth1/55/4
                                                Eth1/56/1, Eth1/56/2, Eth1/56/3
                                                Eth1/56/4, Eth1/57/1, Eth1/57/2
                                                Eth1/57/3, Eth1/57/4, Eth1/58/1
                                                Eth1/58/2, Eth1/58/3, Eth1/58/4
                                                Eth1/59/1, Eth1/59/2, Eth1/59/3
                                                Eth1/59/4, Eth1/60/1, Eth1/60/2
                                                Eth1/60/3, Eth1/60/4, Eth1/61/1
                                                Eth1/61/2, Eth1/61/3, Eth1/61/4
                                                Eth1/62/1, Eth1/62/2, Eth1/62/3
                                                Eth1/62/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
                                                Eth1/31/1, Eth1/31/2, Eth1/31/3
                                                Eth1/31/4, Eth1/32/1, Eth1/32/2
                                                Eth1/32/3, Eth1/32/4, Eth1/33/1
                                                Eth1/33/2, Eth1/33/3, Eth1/33/4
                                                Eth1/34/1, Eth1/34/2, Eth1/34/3
                                                Eth1/34/4, Eth1/35/1, Eth1/35/2
                                                Eth1/35/3, Eth1/35/4, Eth1/36/1
                                                Eth1/36/2, Eth1/36/3, Eth1/36/4
                                                Eth1/37/1, Eth1/37/2, Eth1/37/3
                                                Eth1/37/4, Eth1/38/1, Eth1/38/2
                                                Eth1/38/3, Eth1/38/4, Eth1/39/1
                                                Eth1/39/2, Eth1/39/3, Eth1/39/4
                                                Eth1/40/1, Eth1/40/2, Eth1/40/3
                                                Eth1/40/4, Eth1/41/1, Eth1/41/2
                                                Eth1/41/3, Eth1/41/4, Eth1/42/1
                                                Eth1/42/2, Eth1/42/3, Eth1/42/4
                                                Eth1/43/1, Eth1/43/2, Eth1/43/3
                                                Eth1/43/4, Eth1/44/1, Eth1/44/2
                                                Eth1/44/3, Eth1/44/4, Eth1/45/1
                                                Eth1/45/2, Eth1/45/3, Eth1/45/4
                                                Eth1/46/1, Eth1/46/2, Eth1/46/3
                                                Eth1/46/4, Eth1/47/1, Eth1/47/2
                                                Eth1/47/3, Eth1/47/4, Eth1/48/1
                                                Eth1/48/2, Eth1/48/3, Eth1/48/4
                                                Eth1/49/1, Eth1/49/2, Eth1/49/3
                                                Eth1/49/4, Eth1/50/1, Eth1/50/2
                                                Eth1/50/3, Eth1/50/4, Eth1/51/1
                                                Eth1/51/2, Eth1/51/3, Eth1/51/4
                                                Eth1/52/1, Eth1/52/2, Eth1/52/3
                                                Eth1/52/4, Eth1/53/1, Eth1/53/2
                                                Eth1/53/3, Eth1/53/4, Eth1/54/1
                                                Eth1/54/2, Eth1/54/3, Eth1/54/4
                                                Eth1/55/1, Eth1/55/2, Eth1/55/3
                                                Eth1/55/4, Eth1/56/1, Eth1/56/2
                                                Eth1/56/3, Eth1/56/4, Eth1/57/1
                                                Eth1/57/2, Eth1/57/3, Eth1/57/4
                                                Eth1/58/1, Eth1/58/2, Eth1/58/3
                                                Eth1/58/4, Eth1/59/1, Eth1/59/2
                                                Eth1/59/3, Eth1/59/4, Eth1/60/1
                                                Eth1/60/2, Eth1/60/3, Eth1/60/4
                                                Eth1/61/1, Eth1/61/2, Eth1/61/3
                                                Eth1/61/4, Eth1/62/1, Eth1/62/2
                                                Eth1/62/3, Eth1/62/4

cs1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/62/2     none
Eth1/62/3     none
Eth1/62/4     none
Eth1/63       none
Eth1/64       none
Po1           1
----
====
+

NOTE: 有關具體連接埠和 VLAN 使用詳情，請參閱 RCF 中的橫幅和重要說明部分。

. 驗證 cs1 和 cs2 之間的 ISL 連線是否正常：
+
[source, cli]
----
show port-channel summary
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/63(P)   Eth1/64(P)
999   Po999(SD)   Eth      NONE      --
cs1#
----
====
. 確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node         Port    Home
----------- ------------------ ---------- ------------------ ------------ ------- ----
Cluster
            node1-01_clus1     up/up      169.254.36.44/16   node1-01     e7a     true
            node1-01_clus2     up/up      169.254.7.5/16     node1-01     e7b     true
            node1-02_clus1     up/up      169.254.197.206/16 node1-02     e7a     true
            node1-02_clus2     up/up      169.254.195.186/16 node1-02     e7b     true
            node1-03_clus1     up/up      169.254.192.49/16  node1-03     e7a     true
            node1-03_clus2     up/up      169.254.182.76/16  node1-03     e7b     true
            node1-04_clus1     up/up      169.254.59.49/16   node1-04     e7a     true
            node1-04_clus2     up/up      169.254.62.244/16  node1-04     e7b     true

8 entries were displayed.
----
====
+
如果任何叢集 LIF 尚未返回其來源端口，請從本機節點手動將其還原：

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------- -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. 驗證遠端集群介面的連接性：
+
.. 你可以使用 `network interface check cluster-connectivity show`用於顯示叢集連接性可訪問性檢查詳細資訊的命令：
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*

                                  Source           Destination     Packet
Node   Date                       LIF              LIF             Loss
------ -------------------------- ---------------- --------------- -----------
node1-01
       6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1   none
       6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus1   none


node1-02
       6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1   none
       6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2   none
.
.
.
----
====
.. 或者，您可以使用 `cluster ping-cluster -node <node-name>`檢查連接性的命令：
+
`cluster ping-cluster -node <node-name>`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1-04
Getting addresses from network interface table...
Cluster node1-01_clus1 169.254.36.44 node1-01 e7a
Cluster node1-01_clus2 169.254.7.5   node1-01 e7b
Cluster node1-02_clus1 169.254.197.206 node1-02 e7a
Cluster node1-02_clus2 169.254.195.186 node1-02 e7b
Cluster node1-03_clus1 169.254.192.49 node1-03 e7a
Cluster node1-03_clus2 169.254.182.76 node1-03 e7b
Cluster node1-04_clus1 169.254.59.49 node1-04 e7a
Cluster node1-04_clus2 169.254.62.244 node1-04 e7b
Local = 169.254.59.49 169.254.62.244
Remote = 169.254.36.44 169.254.7.5 169.254.197.206 169.254.195.186 169.254.192.49 169.254.182.76
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.59.49 to Remote 169.254.182.76
    Local 169.254.59.49 to Remote 169.254.192.49
    Local 169.254.59.49 to Remote 169.254.195.186
    Local 169.254.59.49 to Remote 169.254.197.206
    Local 169.254.59.49 to Remote 169.254.36.44
    Local 169.254.59.49 to Remote 169.254.7.5
    Local 169.254.62.244 to Remote 169.254.182.76
    Local 169.254.62.244 to Remote 169.254.192.49
    Local 169.254.62.244 to Remote 169.254.195.186
    Local 169.254.62.244 to Remote 169.254.197.206
    Local 169.254.62.244 to Remote 169.254.36.44
    Local 169.254.62.244 to Remote 169.254.7.5
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
====




.下一步是什麼？
升級 RCF 後，您link:configure-ssh-keys.html["驗證 SSH 配置"]。
