= 
:allow-uri-read: 


您的 AFX 系統上執行的 ONTAP 版本和交換器上執行的 NX-OS 版本決定了交換器支援的 RCF 版本。RCF 版本具有預設的連接埠速度配置，這些配置決定了交換器連接埠中有多少處於分支模式（4x100GbE）和非分支模式。

[NOTE]
====
有關目前支援的 RCF 版本列表，請參閱 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 乙太網路交換器"^] 頁面。

交換器連接埠資訊也可以在 https://hwu.netapp.com["NetAppHardware Universe"^]中找到。

====
* 如果您擁有 AFX 1K 系統，則支援 RCF 10.0 及更高版本。
* 如果您擁有 AFX 2K 系統，則支援 RCF 10.1 及更高版本。
* RCF 10.0 只有一個檔案，並且支援共用交換器 `Cluster-HA-Storage AFX RCF_10.0`。
+
例如，下表顯示此 RCF 檔案中交換器連接埠的預設分組、連接埠速度和使用情況。

+
[cols="1,2"]
|===
| 交換器連接埠組 | 連接埠速度和使用情況 


 a| 
乙太網路 1/1/1-4 至乙太網路 1/30/1-4
 a| 
4x100GbE 模式用於叢集、HA 和儲存連接



 a| 
乙太網路1/31、乙太網路1/32
 a| 
400GbE ISL

|===
* RCF 10.1 針對 AFX 1K 和 AFX 2K 系統的不同使用情境提供了不同的檔案。根據您計劃如何在 AFX 1K 或 AFX 2K 系統設定中使用交換器（共用、僅儲存或僅叢集和高可用性），您可以選擇相應的 RCF 檔案。
+
例如，如果您在 AFX 2K 系統中將交換器用作共享交換器，則需要使用適用於該使用案例的 RCF 檔案。對應的 RCF 檔案名稱可能與此類似 `RCF-v10.1-NX9332D-GX2B-CL1-ST1-100GBR15-400G15.txt`。下表顯示此 RCF 檔案中交換器連接埠的預設群組、連接埠速度及用途。

+
[cols="1,2"]
|===
| 交換器連接埠組 | 連接埠速度和使用情況 


 a| 
Ethernet1/1/1-4 至 Ethernet1/15/1-4
 a| 
4x100GbE 模式，用於叢集內連接、高可用性連接和儲存架連接



 a| 
Ethernet1/16 至 Ethernet1/30
 a| 
400GbE 模式適用於叢集內連接、HA 和儲存連接



 a| 
乙太網路1/31、乙太網路1/32
 a| 
400GbE 叢集內 ISL 連線

|===

