---
permalink: switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Cisco Nexus 9336C-FX2叢集交換器的安裝與組態總覽 
---
= Cisco Nexus 9336C-FX2叢集交換器的安裝與組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2叢集交換器是Cisco Nexus 9000平台的一部分、可安裝在NetApp系統機櫃中。叢集交換器可讓您建立ONTAP 具有兩個以上節點的叢集。



== 初始組態總覽

若要在執行ONTAP 故障切換的系統上初始設定Cisco Nexus 9336C-FX2交換器、請依照下列步驟操作：

. link:setup-worksheet-9336c-cluster.html["填寫Cisco Nexus 9336C-FX2纜線工作表"]。
+
佈線工作表範例提供從交換器到控制器的建議連接埠指派範例。空白工作表提供範本、可用於設定叢集。

. link:install-switch-9336c-cluster.html["安裝交換器"]。
+
設定交換器硬體。

. link:setup-switch-9336c-cluster.html["設定9336C-FX2叢集交換器"]。
+
設定Cisco Nexus 9336C-FX2交換器。

. link:install-switch-and-passthrough-panel-9336c-cluster.html["在NetApp機櫃中安裝Cisco Nexus 9336C-FX2交換器"]。
+
視組態而定、您可以將Cisco Nexus 9336C-FX2交換器和直通面板安裝在NetApp機櫃中、並附有交換器隨附的標準支架。

. link:install-nxos-overview-9336c-cluster.html["準備安裝 NX-OS 軟體和 RCF"]。
+
請依照初始程序、準備安裝Cisco NX-OS軟體和參考組態檔（RCT）。

. link:install-nxos-software-9336c-cluster.html["安裝或升級 NX-OS 軟體"]。
+
在 Nexus 9336C-FX2 叢集交換器上安裝或升級 NX-OS 軟體。

. link:install-nxos-rcf-9336c-cluster.html["安裝或升級 RCF"]。
+
首次設定 Nexus 9336C-FX2 交換器之後、請安裝或升級 RCF 。您也可以使用此程序來升級RCF版本。

. link:configure-ssh-keys.html["驗證 Nexus 9336C-FX2 叢集交換器上的 SSH 組態"]。
+
如果您使用乙太網路交換器健全狀況監視器（ CSHM ）和記錄收集功能、請確認交換器上已啟用 SSH 。





== 其他資訊

開始安裝或維護之前、請務必先檢閱下列內容：

* link:configure-reqs-9336c-cluster.html["組態需求"]
* link:components-9336c-cluster.html["元件與零件編號"]
* link:required-documentation-9336c-cluster.html["必要文件"]
* link:smart-call-9336c-cluster.html["智慧電話住家需求"]

