---
sidebar: sidebar 
permalink: /switch-cisco-9336c-fx2/configure-reqs-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: 從S299.1開始ONTAP 、您可以使用Cisco Nexus 9336C-FX2交換器、將儲存設備和叢集功能結合到共享交換器情境中。 
---
= Cisco Nexus 9336C-FX2 和 9336C-FX2-T 叢集交換器的設定需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
對於Cisco Nexus 9336C-FX2 和 9336C-FX2-T 交換器的安裝和維護，請務必查看設定和網路需求。



== 支援ONTAP

[role="tabbed-block"]
====
.更新版本ONTAP
--
從S299.1開始ONTAP 、您可以使用Cisco Nexus 9336C-FX2交換器、將儲存設備和叢集功能結合到共享交換器組態中。

如果您想要建置ONTAP 具有兩個以上節點的叢集、您需要兩個支援的網路交換器。


NOTE: 乙太網路交換器健全狀況監視器不支援 ONTAP 9.13.1P8 及更早版本、以及 9.14.1P3 及更早版本或 NX-OS 版本 10.3(4a)(M) 。

--
.ONTAP 9.10.1 及更高版本
--
此外，從ONTAP 9.10.1 開始，您可以使用Cisco Nexus 9336C-FX2-T 交換器將儲存和叢集功能組合到共用交換器設定中。

如果您想要建置ONTAP 具有兩個以上節點的叢集、您需要兩個支援的網路交換器。

--
====


== 組態需求

請確定：

* 交換器的纜線和纜線連接器數量和類型都適當。請參閱 https://hwu.netapp.com["Hardware Universe"^]。
* 視您初始設定的交換器類型而定、您需要使用隨附的主控台纜線連接至交換器主控台連接埠。




== 網路需求

所有交換器組態都需要下列網路資訊。

* 用於管理網路流量的IP子網路
* 每個儲存系統控制器和所有適用交換器的主機名稱和IP位址
* 大部分的儲存系統控制器都是透過e0M介面來管理、方法是連接至乙太網路服務連接埠（扳手圖示）。在E0M介面上AFF 、E0M AFF 介面使用專用的乙太網路連接埠、可在ESIA800和ESIEA700s系統上使用。
* 請參閱 https://hwu.netapp.com["Hardware Universe"^] 以取得最新資訊。


如需交換器初始組態的詳細資訊、請參閱下列指南： https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2安裝與升級指南"^]。

.下一步
查看配置要求後，您可以確認您的link:components-9336c-cluster.html["組件和零件編號"]。
