---
permalink: switch-cisco-9336c-fx2/migrate-to-9336.html 
sidebar: sidebar 
keywords: migrating to a cluster with Cisco Nexus 9336C-FX2 cluster switches, how to migrate 
summary: 您可以將不中斷營運的舊Cisco叢集交換器移轉至ONTAP Cisco Nexus 9336C-FX2叢集網路交換器、以利進行非中斷的叢集式叢集。 
---
= 如何從Cisco交換器移轉至Cisco Nexus 9336C-FX2叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將不中斷營運的舊Cisco叢集交換器移轉至ONTAP Cisco Nexus 9336C-FX2叢集網路交換器、以利進行非中斷的叢集式叢集。

* 現有叢集必須正確設定並正常運作。
* 所有叢集連接埠都必須處於「up」狀態、以確保不中斷營運。
* Nexus 9336C-FX2叢集交換器必須在適當版本的NX-OS安裝和套用參考組態檔（RCF）下進行設定和操作。
* 現有的叢集網路組態必須具備下列項目：
+
** 使用兩個舊Cisco交換器的備援且功能完整的NetApp叢集。
** 管理連線能力、以及對舊Cisco交換器和新交換器的主控台存取。
** 使用叢集生命區的所有叢集生命區都位於主連接埠上。
** 在舊的Cisco交換器之間以及新交換器之間啟用或連接ISL連接埠。




本程序中的範例使用下列交換器和節點命名法：

* 現有的Cisco Nexus 5596UP叢集交換器為C1和C2。
* 新的Nexus 9336C-FX2叢集交換器為CS1和CS2。
* 節點是node1和node2。
* 叢集lIF分別是節點1上的node1_clus1和node1_clus2、以及節點2上的node2_clus1和node2_clus2。
* 交換器C2先由交換器CS2取代、然後由交換器CS1取代交換器C1。
+
** 將C2連接至CS2的CS2上建置了暫時ISL。
** 然後從C2中斷連接節點與C2之間的纜線、並重新連接至CS2。
** 然後、節點與C1之間的纜線會從C1中斷連線、然後重新連線至CS1。
** 接著移除C2與CS2之間的暫用ISL。




.步驟
. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 「系統節點AutoSupport 支援功能叫用節點*-type all -most MAn=xh」訊息來禁止自動建立案例
+
其中x是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

. 將權限層級變更為進階、並在系統提示您繼續時輸入* y*：「et -priv家 特權進階」
+
出現進階提示（*>）。

. 驗證是否已在所有叢集lifs上啟用自動還原：「network interface show -vserver cluster -Fields auto-Revert」
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
. 判斷每個叢集介面的管理或作業狀態：
+
每個連接埠應顯示「Link」（連結）、「Health Status」（健全狀況狀態）則顯示為「Healthy」（健全狀況）。

+
.. 顯示網路連接埠屬性：「network port show -IPSpace Cluster（網路連接埠顯示-IPSpace叢集）」
+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
.. 顯示有關邏輯介面及其指定主節點的資訊：「network interface show -vserver Cluster」（網路介面show -vserver叢集）
+
每個LIF都應顯示為「狀態管理/作業者」、而「IS主頁」則顯示為「真」。

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- -----------  ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true

4 entries were displayed.
----


. 每個節點上的叢集連接埠都會以下列方式（從節點的角度）連接至現有的叢集交換器：「network device-dDiscovery show -protocol cup」（網路裝置探索show -protocol cup）
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    c2                        0/1               N5K-C5596UP
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    c2                        0/2               N5K-C5596UP
----
. 叢集連接埠和交換器的連線方式如下（從交換器的觀點來看）：「How cup neighbor」（顯示cup鄰近裝置）
+
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1         124   H           FAS2750          e0a
node2                 Eth1/2         124   H           FAS2750          e0a
c2                    Eth1/41        179   S I s       N5K-C5596UP      Eth1/41
c2                    Eth1/42        175   S I s       N5K-C5596UP      Eth1/42
c2                    Eth1/43        179   S I s       N5K-C5596UP      Eth1/43
c2                    Eth1/44        175   S I s       N5K-C5596UP      Eth1/44
c2                    Eth1/45        179   S I s       N5K-C5596UP      Eth1/45
c2                    Eth1/46        179   S I s       N5K-C5596UP      Eth1/46
c2                    Eth1/47        175   S I s       N5K-C5596UP      Eth1/47
c2                    Eth1/48        179   S I s       N5K-C5596UP      Eth1/48
Total entries displayed: 10

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           FAS2750          e0b
node2                 Eth1/2        124    H           FAS2750          e0b
c1                    Eth1/41       175    S I s       N5K-C5596UP      Eth1/41
c1                    Eth1/42       175    S I s       N5K-C5596UP      Eth1/42
c1                    Eth1/43       175    S I s       N5K-C5596UP      Eth1/43
c1                    Eth1/44       175    S I s       N5K-C5596UP      Eth1/44
c1                    Eth1/45       175    S I s       N5K-C5596UP      Eth1/45
c1                    Eth1/46       175    S I s       N5K-C5596UP      Eth1/46
c1                    Eth1/47       176    S I s       N5K-C5596UP      Eth1/47
c1                    Eth1/48       176    S I s       N5K-C5596UP      Eth1/48
----
. 使用命令「cluster ping cluster -cluster -node-name」確保叢集網路具有完整連線能力
+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. 在連接埠E1/33-334（C1與CS1之間）的CS1上設定暫用ISL。
+
下列範例顯示如何在C1和CS1上設定新的ISL：

+
[listing, subs="+quotes"]
----
cs2# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/33-34*
cs2(config-if-range)# *description temporary ISL between Nexus 5596UP and Nexus 9336C*
cs2(config-if-range)# *no lldp transmit*
cs2(config-if-range)# *no lldp receive*
cs2(config-if-range)# *switchport mode trunk*
cs2(config-if-range)# *no spanning-tree bpduguard enable*
cs2(config-if-range)# *channel-group 101 mode active*
cs2(config-if-range)# *exit*
cs2(config)# *interface port-channel 101*
cs2(config-if)# *switchport mode trunk*
cs2(config-if)# *spanning-tree port type network*
cs2(config-if)# *exit*
cs2(config)# *exit*
----
. 從C2的連接埠E1/33-334拔下ISL纜線、並將纜線連接至CS2的連接埠E1/33-334。
. 驗證ISL連接埠和連接埠通道是否可正常運作、以連接C2和CS2：「How port-channel Summary」（顯示連接埠通道摘要）
+
以下範例顯示Cisco show port-channel摘要命令、用於驗證C2和CS2上的ISL連接埠是否正常運作：

+
[listing, subs="+quotes"]
----
c2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)


cs2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
101   Po101(SU)   Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)
----
. 對於節點1、請從C2上的E1/1拔下纜線、然後使用Nexus 9336C-FX2支援的適當纜線、將纜線連接至CS2上的E1/1。
. 對於節點2、請從C2上的E1/2拔下纜線、然後使用Nexus 9336C-FX2支援的適當纜線、將纜線連接至CS2上的E1/2。
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：「network device-dDiscovery show -protocol cup」
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    cs2                       0/1               N9K-C9336C

node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    cs2                       0/2               N9K-C9336C
----
. 對於節點1、請從C1上的E1/1拔下纜線、然後使用Nexus 9336C-FX2支援的適當纜線、將纜線連接至CS1上的E1/1。
. 對於節點2、請從C1上的E1/2拔下纜線、然後使用Nexus 9336C-FX2支援的適當纜線、將纜線連接至CS1上的E1/2。
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：「network device-dDiscovery show -protocol cup」
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
----
. 刪除CS1和C1之間的暫用ISL。
+
[listing, subs="+quotes"]
----
cs1(config)# *no interface port-channel 101*
cs1(config)# *interface e1/33-34*
cs1(config-if-range)# *lldp transmit*
cs1(config-if-range)# *lldp receive*
cs1(config-if-range)# *no switchport mode trunk*
cs1(config-if-range)# *no channel-group*
cs1(config-if-range)# *description 10GbE Node Port*
cs1(config-if-range)# *spanning-tree bpduguard enable*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
. 驗證叢集的最終組態：「network port show -IPSpace Cluster（網路連接埠show -IPSpace叢集）」
+
每個連接埠應顯示「Link」（連結）、「Health Status」（健全狀況狀態）則顯示為「Healthy」（健全狀況）。

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.


cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

4 entries were displayed.
----
. 驗證兩個節點是否都與每個交換器有一個連線：「How cup neighbor」
+
以下範例顯示兩個交換器的適當結果：

+
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         124    H           FAS2750       e0a
node2              Eth1/2         124    H           FAS2750       e0a
cs2                Eth1/35        179    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        179    R S I s     N9K-C9336C    Eth1/36


cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         124    H           FAS2750       e0b
node2              Eth1/2         124    H           FAS2750       e0b
cs1                Eth1/35        179    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        179    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4
----
. 確保叢集網路具備完整連線能力：「cluster ping-cluster -node-name」（叢集ping叢集節點節點名稱）
+
[listing, subs="+quotes"]
----
cluster1::*> *set -priv advanced*

Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by NetApp personnel.
Do you want to continue? {y|n}: *y*

cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)


cluster1::*> set -privilege admin
cluster1::*>
----
. 針對《支援乙太網路》9.8及更新版本、請使用下列兩個命令來啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔：「系統交換器乙太網路記錄設定密碼」和「系統交換器乙太網路記錄啟用收集」ONTAP
+
輸入：「System交換器乙太網路記錄設定密碼」

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
接著是：「系統交換器乙太網路記錄啟用-收集」

+
[listing, subs="+quotes"]
----
cluster1::*> *system  switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 對於9.5P16、9.6P12和9.7P10及更新版本的修補程式、請使用「系統叢集交換器記錄設定密碼」和「系統叢集交換器記錄啟用收集」命令、啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔ONTAP
+
輸入：「ystem叢集交換器記錄設定密碼」

+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
接著是：「系統叢集交換器記錄啟用-收集」

+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息重新啟用此功能：「System Node AutoSupport 現象叫用節點*-type all -most MAn=end」

