---
permalink: switch-cisco-9336c-fx2/migrate-cn1610-9336c-cluster.html 
sidebar: sidebar 
keywords: migrate cluster Cisco Nexus 9336C-FX2 cluster switches cn1610 
summary: 您可以不中斷地將 ONTAP 叢集的 NetApp CN1610 叢集交換器移轉至 Cisco Nexus 9336C-FX2 叢集網路交換器。 
---
= 從NetApp CN1610 叢集交換器遷移到Cisco 9336C-FX2 和 9336C-FX2-T 叢集交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將ONTAP叢集的NetApp CN1610 叢集交換器移轉到Cisco 9336C-FX2 和 9336C-FX2-T 叢集交換器。這是一個非破壞性的過程。



== 檢閱要求

使用Cisco 9336C-FX2 和 9336C-FX2-T 叢集交換器取代NetApp CN1610 叢集交換器時，必須了解某些設定資訊、連接埠連線和佈線要求。您還必須驗證交換器序號以確保遷移了正確的交換器。

.支援的交換器
支援下列叢集交換器：

* NetApp CN1610
* Cisco 9336C-FX2
* Cisco9336C-FX2-T


如需受支援連接埠及其組態的詳細資訊、請參閱 https://hwu.netapp.com/["Hardware Universe"^]。

.您需要的產品
確認您的組態符合下列需求：

* 現有叢集已正確設定並正常運作。
* 所有叢集連接埠都處於「* up*」狀態、以確保不中斷營運。
* Cisco 9336C-FX2 和 9336C-FX2-T 叢集交換器在安裝並套用參考設定檔 (RCF) 的正確版本的 NX-OS 下設定和運作。
* 現有的叢集網路組態具有下列特性：
+
** 使用 NetApp CN1610 交換器的備援全功能 NetApp 叢集。
** 管理 NetApp CN1610 交換器和新交換器的連線能力和主控台存取。
** 使用叢集生命區的所有叢集生命區都位於主連接埠上。


* 一些連接埠在Cisco 9336C-FX2 和 9336C-FX2-T 交換器上配置為以 40GbE 或 100GbE 運作。
* 您已經規劃、遷移並記錄了從節點到Cisco 9336C-FX2 和 9336C-FX2-T 叢集交換器的 40GbE 和 100GbE 連線。




== 移轉交換器

.關於範例
本程序中的範例使用下列交換器和節點命名法：

* 現有的 CN1610 叢集交換器為 _C1_ 和 _C2_ 。
* 全新 9336C-FX2 叢集交換器為 _CS1_ 和 _CS2_ 。
* 節點是_node1_和_node2_。
* 叢集生命區分別是節點1上的_node1_clus1_和節點1上的_node1_clus2_、以及節點2上的節點2_node2_clus1_和節點2_clus2_。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 此程序中使用的叢集連接埠為_e3a_和_e3c_。


.關於這項工作
本程序涵蓋下列案例：

* 交換機 C2 首先由交換機 CS2 取代。
+
** 關閉連接至叢集節點的連接埠。必須同時關閉所有連接埠、以避免叢集不穩定。
+
*** 所有叢集生命都會容錯移轉至新的交換器 CS2 。


** 然後、節點與 C2 之間的纜線會從 C2 中斷連線、並重新連接至 CS2 。


* 交換器 C1 由交換器 CS1 取代。
+
** 關閉連接至叢集節點的連接埠。必須同時關閉所有連接埠、以避免叢集不穩定。
+
*** 所有叢集生命都會容錯移轉至新的交換器 CS1 。


** 然後、節點與 C1 之間的纜線會從 C1 中斷連線、並重新連接至 CS1 。





NOTE: 在此程序期間、不需要運作中的交換器間連結（ISL）。這是因為RCF版本變更可能會暫時影響ISL連線。為了確保叢集作業不中斷、下列程序會在執行目標交換器上的步驟時、容錯移轉所有叢集生命體到作業夥伴交換器。



=== 步驟1：準備移轉

. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -Message MAn=xh」

+
其中_x_是維護時段的持續時間（以小時為單位）。

. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
"進階權限"

+
出現進階提示（*>）。

. 停用叢集生命體上的自動還原。
+
停用此程序的自動還原功能、叢集生命將不會自動移回其主連接埠。它們會保留在目前的連接埠上、同時仍保持正常運作。

+
「網路介面修改-vserver叢集-lIF *-auta-fRevert假」





=== 步驟2：設定連接埠和纜線

. 確定每個叢集介面的管理或作業狀態。
+
每個連接埠都應顯示為 `Link` 和 `healthy` 適用於 `Health Status`。

+
.. 顯示網路連接埠屬性：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. 顯示有關生命及其指定主節點的資訊：
+
「網路介面show -vserver叢集」

+
應顯示每個LIF `up/up` 適用於 `Status Admin/Oper` 和 `true` 適用於 `Is Home`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. 每個節點上的叢集連接埠都會以下列方式（從節點的角度）、使用命令連線至現有的叢集交換器：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    C1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    C2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    C1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    C2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. 叢集連接埠和交換器的連接方式如下（從交換器的觀點來看）：
+
「How cup neighbor」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
C1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3a
node2                 Eth1/2        124    H           AFF-A400         e3a
C2                    0/13          179    S I s       CN1610           0/13
C2                    0/14          175    S I s       CN1610           0/14
C2                    0/15          179    S I s       CN1610           0/15
C2                    0/16          175    S I s       CN1610           0/16

C2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3b
node2                 Eth1/2        124    H           AFF-A400         e3b
C1                    0/13          175    S I s       CN1610           0/13
C1                    0/14          175    S I s       CN1610           0/14
C1                    0/15          175    S I s       CN1610           0/15
C1                    0/16          175    S I s       CN1610           0/16
----
====
. 驗證遠端叢集介面的連線能力：


[role="tabbed-block"]
====
.更新版本ONTAP
--
您可以使用 `network interface check cluster-connectivity` 命令以啟動叢集連線的存取檢查、然後顯示詳細資料：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 注意： * 請等待數秒後再執行 `show`命令以顯示詳細資料。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有 ONTAP 版本
--
對於所有 ONTAP 版本、您也可以使用 `cluster ping-cluster -node <name>` 檢查連線能力的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step5]] 在交換器 C2 上、關閉連接至節點叢集連接埠的連接埠、以便容錯移轉叢集生命週期。
+

CAUTION: 請勿嘗試手動移轉叢集生命期。

+
[listing, subs="+quotes"]
----
(C2)# *configure*
(C2)(Config)# *interface 0/1-0/12*
(C2)(Interface 0/1-0/12)# *shutdown*
(C2)(Interface 0/1-0/12)# *exit*
(C2)(Config)# *exit*
----
. 使用Cisco 9336C-FX2 和 9336C-FX2-T 支援的適當電纜將節點叢集連接埠從舊交換器 C2 移至新交換器 cs2。
. 顯示網路連接埠屬性：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    C1  (6a:ad:4f:98:3b:3f)   0/1               CN1610
            e3b    cs2 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1     N9K-C9336C-FX2
node2      /cdp
            e3a    C1  (6a:ad:4f:98:3b:3f)   0/2               CN1610
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2     N9K-C9336C-FX2
----
====
. 在交換器 CS2 上、確認所有節點叢集連接埠均已啟動：
+
「網路介面show -vserver叢集」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current     Current Is
Vserver     Interfac     Admin/Oper Address/Mask       Node        Port    Home
----------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.3.4/16     node1       e0b     false
            node1_clus2  up/up      169.254.3.5/16     node1       e0b     true
            node2_clus1  up/up      169.254.3.8/16     node2       e0b     false
            node2_clus2  up/up      169.254.3.9/16     node2       e0b     true
----
====
. 在交換器 C1 上、關閉連接到節點叢集連接埠的連接埠、以便容錯移轉叢集生命期。
+
[listing, subs="+quotes"]
----
(C1)# *configure*
(C1)(Config)# *interface 0/1-0/12*
(C1)(Interface 0/1-0/12)# *shutdown*
(C1)(Interface 0/1-0/12)# *exit*
(C1)(Config)# *exit*
----
. 使用Cisco 9336C-FX2 和 9336C-FX2-T 支援的適當電纜將節點叢集連接埠從舊交換器 C1 移至新交換器 cs1。
. 驗證叢集的最終組態：
+
「網路連接埠show -IPSpace Cluster」

+
應顯示每個連接埠 `up` 適用於 `Link` 和 `healthy` 適用於 `Health Status`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /cdp
            e3a    cs1 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1   N9K-C9336C-FX2
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
node2      /cdp
            e3a    cs1 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1   N9K-C9336C-FX2
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
----
====
. 在交換器 CS1 和 CS2 上、確認所有節點叢集連接埠均已啟動：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 驗證兩個節點各自與每個交換器都有一個連線：
+
`network device-discovery show -protocol`

+
.顯示範例
[%collapsible]
====
以下範例顯示兩個交換器的適當結果：

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  --------------
node1      /cdp
            e0a    cs1 (b8:ce:f6:19:1b:42)   Ethernet1/1/1   N9K-C9336C-FX2
            e0b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2

node2      /cdp
            e0a    cs1 (b8:ce:f6:19:1b:42)   Ethernet1/1/1   N9K-C9336C-FX2
            e0b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
----
====




=== 步驟3：驗證組態

. 在叢集生命體上啟用自動還原：
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 驗證所有叢集網路lifs是否都回到其主連接埠：
+
「網路介面展示」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. 將權限層級變更回管理：
+
「et -priv. admin」

. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」



.接下來呢？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
