---
permalink: switch-cisco-9336c-fx2/replace-storage-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: '更換叢集網路中有缺陷的 Nexus 9336C-FX2 交換器是一個無中斷過程 \(NDU\)。' 
---
= 更換Cisco Nexus 9336C-FX2 儲存交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更換Cisco Nexus 9336C-FX2 儲存交換器時，您必須了解某些設定資訊、連接埠連線和佈線需求。

.你需要什麼
在Cisco Nexus 9336C-FX2 儲存交換器上安裝 NX-OS 軟體和 RCF 之前，必須先驗證以下條件是否存在：

* 您的系統可以支援Cisco Nexus 9336C-FX2 儲存交換器。
* 您必須查閱Cisco乙太網路交換器頁面上的交換器相容性表格，以了解支援的ONTAP、NX-OS 和 RCF 版本。
* 您一定參考過Cisco網站上提供的對應軟體和升級指南。CiscoNexus 3000 系列交換機
* 您必須已下載適用的 RCF 檔案。
* 現有網路配置必須具備以下特徵：
+
** Cisco乙太網路交換器頁麵包含交換器上最新的 RCF 和 NX-OS 版本。
** 兩台交換器都必須具備管理連線功能。


* 更換用的CiscoNexus 9336C-FX2 交換器必須具備以下特性：
+
** 管理網路連線必須正常。
** 必須具備對更換開關的控制台存取權限。
** 必須將對應的 RCF 和 NX-OS 作業系統映像載入到交換器上。
** 交換器的初始配置必須完成。




.關於此任務
此程序將第二台 Nexus 9336C-FX2 儲存交換器 S2 替換為新的 9336C-FX 交換器 NS2。這兩個節點分別是節點1和節點2。

完成步驟：

* 確認要更換的開關是 S2。
* 斷開交換器 S2 的電纜。
* 重新連接電纜至 NS2 交換器。
* 請核實交換器 NS2 上的所有設備配置。
+

NOTE: RCF 和 NX-OS 版本中的指令語法可能存在相依性。



.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

. 檢查儲存節點連接埠的運作狀況，確保與儲存交換器S1有連接：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 確認儲存交換器 S1 可用：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. 掌控全場 `lldp neighbors`在工作交換器上執行指令，確認可以看到兩個節點和所有機架：
+
`show lldp neighbors`

+
.顯示範例
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 檢查儲存系統中的貨架連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. 拆下連接到儲存交換器 S2 的所有電纜。
. 將所有電纜重新連接到替換交換器 NS2。
. 請重新檢查儲存節點連接埠的運作狀況：
+
`storage port show -port-type ENET`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 確認兩台交換器均可用：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. 檢查儲存系統中的貨架連接埠：
+
`storage shelf port show -fields remote-device,remote-port`

+
.顯示範例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


