---
permalink: switch-cisco-9336c-fx2/replace-install-initial.html 
sidebar: sidebar 
keywords: initial setup steps, cisco cluster switch install 
summary: 您可以使用此程序來執行Cisco Nexus 9336C-FX2交換器的初始安裝。 
---
= Nexus 9336C-FX2叢集交換器的初始安裝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此程序來執行Cisco Nexus 9336C-FX2交換器的初始安裝。

您可以從NetApp支援網站下載適用於交換器的NetApp Cisco NX-OS軟體、網址為： http://mysupport.netapp.com/["mysupport.netapp.com"^]。

NX-OS是Cisco Systems提供的Nexus系列乙太網路交換器和MDS系列光纖通道（FC）儲存區域網路交換器的網路作業系統。

本程序提供安裝交換器並讓其執行的程序摘要。

.步驟
. 將序列連接埠連接至您選擇的主機或序列連接埠。
. 將管理連接埠（位於交換器的非連接埠端）連接至SFTP伺服器所在的相同網路。
. 在主控台設定主機端序列設定：
+
** 9600傳輸速率
** 8個資料位元
** 1停止位元
** 同位元檢查：無
** 流程控制：無


. Nexus 9336C-FX2交換器會在開機週期中循環啟動、或是在清除執行組態之後重新開機。輸入* yes *中止開機自動資源配置、以中斷此週期。接著您會看到系統管理員帳戶設定：
+
[listing]
----
$ VDC-1 %$ %POAP-2-POAP_INFO:   - Abort Power On Auto Provisioning [yes - continue with normal setup, skip - bypass password and basic configuration, no - continue with Power On Auto Provisioning] (yes/skip/no)[no]: yes
Disabling POAP.......Disabling POAP
2019 Apr 10 00:36:17 switch %$ VDC-1 %$ poap: Rolling back, please wait... (This may take 5-15 minutes)

---- System Admin Account Setup ----
----
. 輸入* y*以強制執行安全密碼標準：
+
[listing]
----
Do you want to enforce secure password standard (yes/no) [y]: y
----
. 輸入並確認使用者管理的密碼：
+
[listing]
----
Enter the password for "admin":
Confirm the password for "admin":
----
. 進入「基本系統組態」對話方塊：
+
[listing]
----
This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus9000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus9000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.

Would you like to enter the basic configuration dialog (yes/no):
----
. 建立另一個登入帳戶：
+
[listing]
----
Create another login account (yes/no) [n]:
----
. 設定唯讀和讀寫SNMP社群字串：
+
[listing]
----
Configure read-only SNMP community string (yes/no) [n]:

Configure read-write SNMP community string (yes/no) [n]:
----
. 設定叢集交換器名稱：
+
[listing]
----
Enter the switch name : cs2
----
. 設定頻外管理介面：
+
[listing]
----

Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]: y

Mgmt0 IPv4 address : 172.22.133.216

Mgmt0 IPv4 netmask : 255.255.224.0

Configure the default gateway? (yes/no) [y]: y

IPv4 address of the default gateway : 172.22.128.1
----
. 設定進階IP選項：
+
[listing]
----
Configure advanced IP options? (yes/no) [n]: n
----
. 設定遠端登入服務：
+
[listing]
----
Enable the telnet service? (yes/no) [n]: n
----
. 設定SSH服務和SSH金鑰：
+
[listing]
----
Enable the ssh service? (yes/no) [y]: y

Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa

Number of rsa key bits <1024-2048> [1024]: 2048
----
. 設定其他設定：
+
[listing]
----
Configure the ntp server? (yes/no) [n]: n

  Configure default interface layer (L3/L2) [L2]: L2

  Configure default switchport interface state (shut/noshut) [noshut]: noshut

  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]: strict
----
. 確認交換器資訊並儲存組態：
+
[listing]
----
Would you like to edit the configuration? (yes/no) [n]: n

Use this configuration and save it? (yes/no) [y]: y

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 針對《支援乙太網路》9.8及更新版本、請使用下列命令啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔：「系統交換器乙太網路記錄設定密碼」及「系統交換器乙太網路記錄啟用-收集」ONTAP
+
[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system  switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。

. 對於9.5P16、9.6P12和9.7P10及更新版本的修補程式、請使用「系統叢集交換器記錄設定密碼」和「系統叢集交換器記錄啟用收集」命令、啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔ONTAP
+
[listing]
----
cluster1::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
+

NOTE: 如果這些命令中有任何一個出現錯誤、請聯絡NetApp支援部門。


