---
permalink: switch-cisco-9336c-fx2/setup-required-documentation.html 
sidebar: sidebar 
keywords: controller, documentation, ontap, cluster, required documentation - cisco nexus 9336c-fx2 
summary: 您需要特定的交換器和控制器文件來設定ONTAP 您的叢集。 
---
= 必要文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要特定的交換器和控制器文件來設定ONTAP 您的叢集。

.叢集網路交換器的必要文件
若要設定Cisco Nexus 9336C-FX2和92300YC交換器、您需要取得的下列文件 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000系列交換器支援"^] 頁面：

[cols="1,2"]
|===
| 文件標題 | 說明 


 a| 
_Nexus 9000系列硬體安裝指南_
 a| 
提供有關站台需求、交換器硬體詳細資料及安裝選項的詳細資訊。



 a| 
_Cisco Nexus 9000系列交換器軟體組態指南_（請選擇您交換器上安裝的NX-OS版本指南）
 a| 
提供您需要的初始交換器組態資訊、然後才能設定交換器ONTAP 以供執行故障操作。



 a| 
_Cisco Nexus 9000系列NX-OS軟體升級與降級指南_（請針對安裝在交換器上的NX-OS版本選擇指南）
 a| 
如ONTAP 有必要、提供如何將交換器降級至支援的交換器軟體的相關資訊。



 a| 
_Cisco Nexus 9000系列NX-OS命令參考主索引_
 a| 
提供Cisco所提供之各種命令參考資料的連結。



 a| 
_Cisco Nexus 9000 MIBs參考資料_
 a| 
說明Nexus 9000交換器的管理資訊庫（MIB）檔案。



 a| 
_Nexus 9000系列NX-OS系統訊息參考_
 a| 
說明Cisco Nexus 9000系列交換器的系統訊息、資訊訊息、以及其他可能有助於診斷連結、內部硬體或系統軟體問題的訊息。



 a| 
_Cisco Nexus 9000系列NX-OS版本資訊（請選擇安裝在交換器上的NX-OS版本附註）_
 a| 
說明Cisco Nexus 9000系列的功能、錯誤和限制。



 a| 
Cisco Nexus 9000系列的法規遵循與安全資訊
 a| 
提供Nexus 9000系列交換器的國際機構法規遵循、安全及法規資訊。

|===
若要設定Cisco Nexus 3232C和3132Q-V交換器、您需要取得的下列文件 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000系列交換器支援"^] 頁面：

[cols="1,2"]
|===
| 文件標題 | 說明 


 a| 
_Nexus 3000系列硬體安裝指南_
 a| 
提供有關站台需求、交換器硬體詳細資料及安裝選項的詳細資訊。



 a| 
_Cisco Nexus 3000系列交換器軟體組態指南_（請選擇您交換器上安裝的NX-OS版本指南）
 a| 
提供您需要的初始交換器組態資訊、然後才能設定交換器ONTAP 以供執行故障操作。



 a| 
_Cisco Nexus 3000系列NX-OS軟體升級與降級指南_（請針對安裝在交換器上的NX-OS版本選擇指南）
 a| 
如ONTAP 有必要、提供如何將交換器降級至支援的交換器軟體的相關資訊。



 a| 
_Cisco Nexus 3000系列NX-OS命令參考主索引_
 a| 
提供Cisco所提供之各種命令參考資料的連結。



 a| 
_Cisco Nexus 3000 MIBs參考資料_
 a| 
說明Nexus 3000交換器的管理資訊庫（MIB）檔案。



 a| 
_Nexus 3000系列NX-OS系統訊息參考_
 a| 
說明Cisco Nexus 3000系列交換器的系統訊息、資訊訊息、以及其他可能有助於診斷連結、內部硬體或系統軟體問題的訊息。



 a| 
_Cisco Nexus 3000系列NX-OS版本資訊（請選擇安裝在交換器上的NX-OS版本附註）_
 a| 
說明Cisco Nexus 3000系列的功能、錯誤和限制。



 a| 
Cisco Nexus 6000、Cisco Nexus 5000系列、Cisco Nexus 3000系列和Cisco Nexus 2000系列的法規、法規遵循與安全資訊
 a| 
提供Nexus 3000系列交換器的國際機構法規遵循、安全及法規資訊。

|===
若要設定Cisco Nexus 5596交換器、您需要提供下列文件 https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/series.html["Cisco Nexus 5000系列交換器支援"^] 頁面：

[cols="1,2"]
|===
| 文件標題 | 說明 


 a| 
_Nexus 5000系列硬體安裝指南_
 a| 
提供有關站台需求、交換器硬體詳細資料及安裝選項的詳細資訊。



 a| 
_Cisco Nexus 5000系列交換器軟體組態指南_（請針對您使用的軟體選擇指南）
 a| 
提供您需要的初始交換器組態資訊、然後才能設定交換器ONTAP 以供執行故障操作。



 a| 
_Cisco Nexus 5000系列NX-OS軟體升級與降級指南_
 a| 
如ONTAP 有必要、提供如何將交換器降級至支援的功能性交換器軟體的相關資訊。



 a| 
_Cisco Nexus 5000系列NX-OS命令參考主索引_
 a| 
提供特定NX-OS版本所支援的所有命令的字母順序清單。



 a| 
_Cisco Nexus 5000與Nexus 2000 MIBs參考資料_
 a| 
說明Nexus 5000交換器的管理資訊庫（MIB）檔案。



 a| 
_Nexus 5000系列NX-OS系統訊息參考_
 a| 
說明疑難排解資訊。



 a| 
_ Cisco Nexus 6000系列、Cisco Nexus 5000系列、Cisco Nexus 3000系列和Cisco Nexus 2000系列的法規、法規遵循與安全資訊_
 a| 
提供Nexus 5000系列交換器的國際機構法規遵循、安全及法規資訊。

|===
.支援ONTAP 的支援的支援的資訊系統所需的文件
若要設定ONTAP 一套作業系統、您需要從取得下列作業系統版本的文件 https://docs.netapp.com/ontap-9/index.jsp["供應說明文件中心 ONTAP"^]。

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
控制器專屬的安裝與設定指示_
 a| 
說明如何安裝NetApp硬體。



 a| 
本文檔 ONTAP
 a| 
提供ONTAP 有關這些版本的所有方面的詳細資訊。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
提供NetApp硬體組態與相容性資訊。

|===
.軌道套件與機櫃文件
若要在NetApp機櫃中安裝Cisco交換器、請參閱下列硬體文件：

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U系統機櫃、深度指南"^]
 a| 
說明與42U系統機櫃相關的FRU、並提供維護與FRU更換指示。



 a| 
https://library.netapp.com/ecm/ecm_get_file/ECMLP2843148["在NetApp機櫃中安裝Cisco Nexus 3232C叢集交換器和傳遞面板"^]
 a| 
說明如何在四柱NetApp機櫃中安裝Cisco Nexus 3232C交換器。



 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMLP2518305["在NetApp機櫃中安裝Cisco Nexus 3132Q-V交換器和傳遞面板"^]
 a| 
說明如何在四柱NetApp機櫃中安裝Cisco Nexus 3132Q-V交換器。



 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMP1141864["在NetApp機櫃中安裝Cisco Nexus 5596交換器和傳遞面板"^]
 a| 
說明如何在NetApp機櫃中安裝Cisco Nexus 5596交換器。

|===