---
permalink: switch-cisco-9336c-fx2/setup-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 請依照下列步驟設定和設定Cisco Nexus 9336C-FX2 交換器。 
---
= 配置 9336C-FX2 和 9336C-FX2-T 叢集交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟設定Cisco Nexus 9336C-FX2 和 9336C-FX2-T 交換器。

.開始之前
請確保您擁有以下物品：

* 在安裝現場存取 HTTP、FTP 或 TFTP 伺服器，以下載適用的 NX-OS 和參考設定檔 (RCF) 版本。
* 適用的NX-OS版本，可從以下網址下載： https://software.cisco.com/download/home["Cisco軟體下載"^]頁。
* 適用的許可證、網路和設定資訊以及線纜。
* 完全的link:setup-worksheet-9336c-cluster.html["佈線工作表"]。
* 可從NetApp支援網站下載適用的NetApp叢集網路和管理網路 RCF。 http://mysupport.netapp.com/["mysupport.netapp.com"^] 。所有Cisco集群網路和管理網路交換器均採用Cisco標準出廠預設設定。這些交換器也具有目前版本的 NX-OS 軟體，但未載入 RCF。
* link:required-documentation-9336c-cluster.html["所需的交換器和ONTAP文檔"]。


.步驟
. 對叢集網路交換器進行初始設定。
+
首次啟動交換器時，請對以下初始設定問題提供相應的答案。您網站的安全性原則定義了要啟用的回應和服務。

+
[cols="1,2"]
|===
| 迅速的 | 回覆 


 a| 
中止自動配置並繼續進行正常設定？  （是/否）
 a| 
請回答「是」。預設值為否。



 a| 
您是否希望強制執行安全密碼標準？  （是/否）
 a| 
請回答「是」。預設值為“是”。



 a| 
請輸入管理者密碼。
 a| 
預設密碼為「`admin`」；您必須建立一個新的、強密碼。弱密碼可能會被拒絕。



 a| 
您想進入基本設定對話框嗎？  （是/否）
 a| 
在交換器的初始設定階段，請回答「是」。



 a| 
建立另一個登入帳戶？  （是/否）
 a| 
答案取決於您網站關於備用管理員的政策。預設值為*否*。



 a| 
配置唯讀 SNMP 團體字串？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
配置讀寫 SNMP 團體字串？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
請輸入交換器名稱。
 a| 
請輸入交換器名稱，字數限制為 63 個字母數字字元。



 a| 
繼續進行帶外（mgmt0）管理配置？  （是/否）
 a| 
在該提示出現時，請回答「是」（預設值）。在 mgmt0 IPv4 位址提示字元處，輸入您的 IP 位址：ip_address。



 a| 
配置預設網關？  （是/否）
 a| 
請回答「是」。在預設閘道的 IPv4 位址提示字元處，輸入您的預設閘道。



 a| 
配置進階 IP 選項？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
啟用 Telnet 服務？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
已啟用 SSH 服務？  （是/否）
 a| 
請回答「是」。預設值為“是”。


NOTE: 使用乙太網路交換器健康監視器 (CSHM) 時，建議使用 SSH 進行日誌收集。為了提高安全性，建議使用 SSHv2。



 a| 
請輸入要產生的 SSH 金鑰類型（dsa/rsa/rsa1）。
 a| 
預設值為 *rsa*。



 a| 
請輸入密鑰位數（1024-2048）。
 a| 
請輸入1024到2048之間的密鑰位數。



 a| 
配置NTP伺服器？  （是/否）
 a| 
回答“不”。預設值為否。



 a| 
配置預設介面層（L3/L2）
 a| 
請用*L2*回覆。預設值為 L2。



 a| 
配置交換器連接埠介面的預設狀態（關閉/不關閉）
 a| 
回覆 *noshut*。預設為 noshut。



 a| 
設定 CoPP 系統設定檔（嚴格/中/寬鬆/嚴格）
 a| 
回覆時請使用 *strict*。預設為嚴格。



 a| 
您想修改配置嗎？  （是/否）
 a| 
此時您應該可以看到新的配置。請檢查並對您剛剛輸入的配置進行必要的更改。如果對配置滿意，請在提示時回答「否」。如果要編輯配置設置，請回覆「是」。



 a| 
使用此配置並儲存？  （是/否）
 a| 
回覆“是”以儲存配置。這會自動更新啟動鏡像和系統鏡像。


NOTE: 如果此時不儲存配置，下次重新啟動交換器時，所有變更都會失效。

|===
. 在設定結束時顯示的介面中，確認您所做的配置選擇，並確保儲存配置。
. 檢查叢集網路交換器上的軟體版本，如有必要，請從 NetApp 官網下載NetApp支援的軟體版本到交換器。 https://software.cisco.com/download/home["Cisco軟體下載"^]頁。


.下一步是什麼？
配置好交換器後，您可以… link:install-nxos-overview-9336c-cluster.html["準備安裝NX-OS軟體和RCF"]。
