---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: 您可以使用此程序來安裝適用於 Nexus 92300YC 叢集交換器叢集交換器健全狀況監控的組態檔。 
---
= 安裝叢集交換器健全狀況監視器（ SHM ）組態檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請遵循此程序、安裝適用於 Nexus 9336C-FX2 叢集交換器叢集交換器健全狀況監控（ SHM ）的組態檔。

.您需要的產品
在設定 9336C-FX2 叢集交換器的 SHM 之前、請確定 ONTAP 叢集已啟動並正在執行。


NOTE: 您也應該啟用 SSH 、以使用 SHM 中的所有可用功能。

.步驟
. 根據對應的 ONTAP 版本、下載叢集 SHM 組態 zip 檔案。此檔案可從取得 https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp軟體下載"^] 頁面。
+
.. 在「軟體」下載頁面上、選取*「交換器健全狀況監視器組態檔案」*
.. 選取平台 = * ONTAP * 、然後選取 * 執行！ *
.. 在 Switch Health Monitor Configuration Files for ONTAP 頁面上、選取 * 檢視與下載 *
.. 在 Switch Health Monitor Configuration Files for ONTAP > Description 頁面上、針對適用的叢集交換器機型選取 * Download* 、例如： * Cisco Nexus 9336C-FX2*
.. 在「終端使用者授權合約」頁面上、選取 * 接受 *
.. 在交換器健全狀況監視器的 ONTAP 組態檔案 > 下載頁面上、選取適用的組態檔、例如 * Cisco_Nexus 9336C-FX2.zip*


. 將適用的Zip檔案上傳至內部Web伺服器、其中IP位址為X.X.X.X
+
如果內部Web伺服器IP位址為192．168．2、假設存在/usr/downloads目錄、您可以使用scp將壓縮檔上傳至Web伺服器：

+
[listing]
----
% scp Cisco_Nexus_9336C-FX2.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. 從叢集中的其中一個 ONTAP 系統存取進階模式設定：
+
`set-privilege advanced`

+
[listing]
----
cluster1::> set -privilege advanced
----
. 執行交換器健全狀況監視器組態命令 `system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file`：
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. 確認命令輸出包含文字字串「已成功處理下載的套件」。如果發生錯誤、請聯絡NetApp支援部門。
. 執行命令 `system cluster-switch show` 在 ONTAP 系統上、請確定叢集交換器是在監控欄位設定為「 True 」的情況下探索到的。
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: 如果您隨時恢復至舊版 ONTAP 、則需要再次安裝 SHM 組態檔、以啟用 9336C-FX2 叢集交換器的 SHM 。


