---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: 您可以使用「Bes - 53248叢集交換器連接埠指派表」作為設定叢集的指南。 
---
= BS-53248叢集交換器的組態需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若為 BS-53248 交換器安裝與維護、請務必檢閱 EFOS 和 ONTAP 支援與組態需求。



== EFOS 和 ONTAP 支援

請參閱 https://["NetApp Hardware Universe"^] 和 https://["Broadcom 交換器相容性對照表"^] 適用於 EFOS 和 ONTAP 與 BS-53248 交換器的相容性資訊。EFOS 和 ONTAP 支援可能會因特定機器類型的 BS-53248 交換器而異。如需所有 BS-52348 交換器機型的詳細資訊、請參閱 link:components-bes53248.html["BS-53248叢集交換器的元件和零件編號"]。



== 組態需求

若要設定叢集、您需要叢集交換器適當的纜線數量和類型、以及纜線連接器。視您初始設定的叢集交換器類型而定、您需要使用隨附的主控台纜線連接至交換器主控台連接埠。



=== 叢集交換器連接埠指派

您可以使用Broadcom支援的Bes - 53248叢集交換器連接埠指派表、作為設定叢集的指南。

[cols="1,2"]
|===
| 交換器連接埠 | 連接埠使用量 


 a| 
2016年1月16日
 a| 
10/25GbE叢集連接埠節點、基礎組態



 a| 
17-48
 a| 
10/25GbE叢集連接埠節點、含授權



 a| 
49至54歲
 a| 
40/100GbE 叢集連接埠節點、含授權、由右至左新增



 a| 
55-56
 a| 
100GbE叢集交換器間連結（ISL）連接埠、基礎組態

|===
請參閱 https://["Hardware Universe"] 如需交換器連接埠的詳細資訊、



=== 連接埠群組速度限制

* 在BES-53248叢集交換器上、48個10/25GbE（SFP28/SFP+）連接埠會結合成12個4埠群組、如下所示：連接埠1-4、5-8、9-12、13-16、17-20、21至24、25至28、29至32、33至36、37至40、41至44及45至48。
* 在4埠群組的所有連接埠之間、SFP28/SFP+連接埠速度必須相同（10GbE或25GbE）。




=== 其他需求

* 如果您購買額外授權、請參閱 link:configure-licenses.html["啟動新授權連接埠"] 如需如何啟動的詳細資訊、請參閱。
* 如果 SSH 是作用中的、則必須在執行命令後手動重新啟用 SSH `erase startup-config` 然後重新啟動交換器。

