---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: B16-53248叢集交換器基礎模式已獲得16個10GbE或25GbE連接埠和2個100GbE連接埠的授權。您可以購買更多授權來新增連接埠。 
---
= 安裝適用於B3作業 叢集交換器的授權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
B16-53248叢集交換器基礎模式已獲得16個10GbE或25GbE連接埠和2個100GbE連接埠的授權。您可以購買更多授權來新增連接埠。



== 檢閱可用的授權

下列授權可在B3交互 式叢集交換器上使用：

[cols="1,2,3"]
|===
| 授權類型 | 授權詳細資料 | 支援的韌體版本 


 a| 
SW-BS-53248A2-8P-2P
 a| 
Broadcom 8Pt - 10G25G + 2pt-40G100G 授權金鑰、 X190005/R
 a| 
EFOS 3.4.4.6及更新版本



 a| 
SW-BS-53248A2-8P-1025G
 a| 
Broadcom 8 連接埠 10G25G 授權金鑰、 X190005/R
 a| 
EFOS 3.4.4.6及更新版本



 a| 
SW-BES53248A2-6P-40-100g
 a| 
Broadcom 6 連接埠 40G100G 授權金鑰、 X190005/R
 a| 
EFOS 3.4.4.6及更新版本

|===


== 舊版授權

下表列出可在 BS-53248 叢集交換器上使用的舊版授權：

[cols="1,2,3"]
|===
| 授權類型 | 授權詳細資料 | 支援的韌體版本 


 a| 
SW-BE-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25、2P40至100授權金鑰、X190005/R
 a| 
EFOS 3.4.3.3及更新版本



 a| 
SW-BE-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25、4P40-100授權金鑰、X190005/R
 a| 
EFOS 3.4.3.3及更新版本



 a| 
SW-BE-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-256P40-100授權金鑰、X190005/R
 a| 
EFOS 3.4.3.3及更新版本



 a| 
SW-BES54248-40-100G授權
 a| 
Broadcom 6port 40G100G授權金鑰、X190005/R
 a| 
EFOS 3.4.4.6及更新版本



 a| 
SW-BES53248-8P-10G25G授權
 a| 
Broadcom 8Port 10G25G授權金鑰、X190005/R
 a| 
EFOS 3.4.4.6及更新版本



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Broadcom 16Port 10G25G授權金鑰、X190005/R
 a| 
EFOS 3.4.4.6及更新版本



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Broadcom 24Port 10G25G授權金鑰、X190005/R
 a| 
EFOS 3.4.4.6及更新版本

|===

NOTE: 基礎組態不需要授權。



== 安裝授權檔案

請依照下列步驟安裝BS-53248叢集交換器的授權。

.步驟
. 將叢集交換器連接至管理網路。
. 使用「ping」命令來驗證與裝載EFOS、授權和RCF檔案的伺服器之間的連線。
+
.顯示範例
[%collapsible]
====
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 檢查交換器CS2目前的授權使用量：
+
「如何授權」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. 安裝授權檔案。
+
重複此步驟以載入更多授權、並使用不同的金鑰索引編號。

+
.顯示範例
[%collapsible]
====
下列範例使用SFTP將授權檔案複製到金鑰索引1。

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. 顯示所有目前的授權資訊、並在重新啟動交換器CS2之前記下授權狀態：
+
「如何授權」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. 顯示所有授權連接埠：
+
「How port all | exclude Detach」

+
交換器重新開機後、才會顯示其他授權檔的連接埠。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. 重新啟動交換器：
+
"重裝"

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. 請檢查新授權是否已啟用、並注意已套用授權：
+
「如何授權」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. 檢查所有新連接埠是否可用：
+
「How port all | exclude Detach」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: 安裝額外授權時、您必須手動設定新介面。請勿將RCF重新套用至現有運作中的正式作業交換器。



== 疑難排解安裝問題

如果安裝授權時發生問題、請在執行之前執行下列偵錯命令 `copy` 命令。

要使用的除錯命令：「Debuger transfer」和「debugs license」

.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
當您執行時 `copy` 命令 `debug transfer` 和 `debug license` 選項已啟用、會傳回記錄輸出。

.顯示範例
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
在偵錯輸出中檢查下列項目：

* 請檢查序號是否符合：「序號QTFC38290012相符」
* 檢查交換器機型是否符合「model Bes - 53248 matched」
* 檢查之前是否未使用指定的授權索引。如果已使用授權索引、則會傳回下列錯誤：「License file /mnt/download//license．dat.1 already exists（授權檔案/mnt/download//license．dat.1已存在）」
* 連接埠授權並非功能授權。因此、預期會有下列陳述：「在索引= 1的授權檔案中找不到功能。」


使用 `copy` 將連接埠授權備份到伺服器的命令：

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: 如果您需要將交換器軟體從3.4.4.6版降級、則會移除授權。這是預期的行為。

您必須先安裝適當的舊版授權、才能還原至舊版軟體。



== 啟動新授權的連接埠

若要啟動新授權的連接埠、您必須編輯最新版的RCF、然後取消註釋適用的連接埠詳細資料。

預設授權會啟動連接埠0/1到0/16和0/55到0/56、而新授權的連接埠則會在連接埠0/17到0/54之間、視可用授權的類型和數量而定。例如、若要啟動SW-BES54248-40-100g-LIC授權、您必須取消註解RCF中的下列章節：

.顯示範例
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: 對於0/49到0/54（含）之間的高速連接埠、請針對每個連接埠取消註解、但在RCF中只取消註釋一條*速度*線路、例如*速度100g全雙工*或*速度40G全雙工*、如範例所示。對於0/17到0/48（含）之間的低速度連接埠、請在啟用適當授權後、取消註釋整個8埠區段。

.接下來呢？
link:configure-install-rcf.html["安裝參考組態檔（RCF）"] 或 link:upgrade-rcf.html["升級 RCF"]。
