---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: B16-53248叢集交換器基礎模式已獲得16個10GbE或25GbE連接埠和2個100GbE連接埠的授權。您可以購買更多授權來新增連接埠。 
---
= 安裝適用於B3作業 叢集交換器的授權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
B16-53248叢集交換器基礎模式已獲得16個10GbE或25GbE連接埠和2個100GbE連接埠的授權。您可以購買更多授權來新增連接埠。

下列授權可在B3交互 式叢集交換器上使用：

[cols="1,2"]
|===
| 授權類型 | 授權詳細資料 


| 支援的韌體版本  a| 
SW-BE-53248A1-G1-8P-LIC



 a| 
Broadcom 8P 10-25、2P40至100授權金鑰、X190005/R
 a| 
EFOS 3.4.3.3及更新版本



 a| 
SW-BE-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25、4P40-100授權金鑰、X190005/R



 a| 
EFOS 3.4.3.3及更新版本
 a| 
SW-BE-53248A1-G1-24P-LIC



 a| 
Broadcom 24P 10-256P40-100授權金鑰、X190005/R
 a| 
EFOS 3.4.3.3及更新版本



 a| 
SW-BES54248-40-100G授權
 a| 
Broadcom 6port 40G100G授權金鑰、X190005/R



 a| 
EFOS 3.4.4.6及更新版本
 a| 
SW-BES53248-8P-10G25G授權



 a| 
Broadcom 8Port 10G25G授權金鑰、X190005/R
 a| 
EFOS 3.4.4.6及更新版本



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Broadcom 16Port 10G25G授權金鑰、X190005/R



 a| 
EFOS 3.4.4.6及更新版本
 a| 
SW-BES53248-24P-1025G-LIC



 a| 
Broadcom 24Port 10G25G授權金鑰、X190005/R
 a| 
EFOS 3.4.4.6及更新版本

|===
.步驟
. 將叢集交換器連接至管理網路。
. 使用「ping」命令來驗證與裝載EFOS、授權和RCF檔案的伺服器之間的連線。
+
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 檢查交換器CS2目前的授權使用量：
+
「如何授權」

+
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
. 安裝授權檔案。下列範例使用SFTP將授權檔案複製到金鑰索引1。
+
重複此步驟以載入更多授權、並使用不同的金鑰索引編號。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
. 顯示所有目前的授權資訊、並在重新啟動交換器CS2之前記下授權狀態：
+
「如何授權」

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
. 顯示所有授權連接埠：
+
「How port all | exclude Detach」

+
交換器重新開機後、才會顯示其他授權檔的連接埠。

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
. 重新啟動交換器：
+
"重裝"

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
. 請檢查新授權是否已啟用、並注意已套用授權：
+
「如何授權」

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
. 檢查所有新連接埠是否可用：
+
「How port all | exclude Detach」

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----



CAUTION: 安裝額外授權時、您必須手動設定新介面。不建議將RCF重新套用至現有的運作中正式作業交換器。
