---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 請依照下列步驟、在BS-53248叢集交換器上安裝乙太網路架構作業系統（EFOS）軟體。 
---
= 安裝EFOS軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟、在BS-53248叢集交換器上安裝乙太網路架構作業系統（EFOS）軟體。

EFOS軟體包含一組進階網路功能和傳輸協定、可用於開發乙太網路和IP基礎架構系統。此軟體架構適用於使用需要徹底封包檢查或分離的應用程式的任何網路組織裝置。



== 準備安裝

.開始之前
* 此程序僅適用於新安裝。
* 從下載適用於叢集交換器的Broadcom EFOS軟體 https://www.broadcom.com/support/bes-switch["Broadcom乙太網路交換器支援"^] 網站。
* 確保 link:configure-install-initial.html["設定了 BS-53248 叢集交換器"]。




== 安裝軟體

請使用下列其中一種方法來安裝 EFOS 軟體：

* <<方法1：安裝EFOS>>。適用於大多數情況。
* <<方法 2 ：在 ONIE 模式下安裝 EFOS>>。如果其中一個EFOS版本符合FIPS標準、而另一個EFOS版本不符合FIPS標準、請使用。




=== 方法1：安裝EFOS

請執行下列步驟來安裝 EFOS 軟體。

.步驟
. 登入交換器序列主控台連接埠或使用 SSH 連線。
. 使用「ping」命令來驗證與裝載EFOS、授權和RCF檔案的伺服器之間的連線。
+
.顯示範例
[%collapsible]
====
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 將映像檔下載到交換器。
+
請查看下表、以取得支援的複製協定資訊：

+
|===


| *傳輸協定* | * 先決條件 * 


 a| 
簡易檔案傳輸協定（ TFTP ）
 a| 
無



 a| 
SSH 檔案傳輸協定（ SFTP ）
 a| 
您的軟體套件必須支援安全管理



 a| 
FTP
 a| 
需要密碼



 a| 
Xmodem
 a| 
無



 a| 
Ymodem
 a| 
無



 a| 
ZMODEM-
 a| 
無



 a| 
安全複製傳輸協定（ SCP ）
 a| 
您的軟體套件必須支援安全管理



 a| 
HTTP
 a| 
當有原生 wGet 公用程式可用時、所選平台支援 CLI 型檔案傳輸



 a| 
HTTPS
 a| 
當有原生 wGet 公用程式可用時、所選平台支援 CLI 型檔案傳輸

|===
+
將映像檔複製到作用中映像、表示當您重新開機時、該映像會建立執行中的EFOS版本。上一個映像仍可作為備份使用。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 顯示使用中和備份組態的開機映像：
+
「如何啟動bootvar

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. 重新啟動交換器：
+
"重裝"

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. 再次登入並驗證EFOS軟體的新版本：
+
《如何版本》

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 完成安裝。
請依照下列五個步驟重新設定交換器：
+
.. link:configure-licenses.html["安裝授權"]
.. link:configure-install-rcf.html["安裝 RCF 檔案"]
.. link:configure-ssh.html["啟用SSH"]
.. link:CSHM_log_collection.html["啟用記錄收集"]
.. link:CSHM_snmpv3.html["設定用於監控的 SNMPv3"]


. 在合作夥伴交換器上重複步驟 1 至 7 。




=== 方法 2 ：在 ONIE 模式下安裝 EFOS

如果其中一個EFOS版本符合FIPS標準、而另一個EFOS版本不符合FIPS標準、您可以執行下列步驟。這些步驟可用於在交換器無法開機時、從ONIE安裝非FIPS或FIPS相容的EFOS 3.7.x.x映像。

.步驟
. 連接至連接至交換器序列連接埠的主控台。
. 將交換器開機至ONIE安裝模式。
+
在開機期間、當您看到提示時、請選取ONIE。

+
.顯示範例
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
選擇* ONIE*之後、交換器會載入並顯示多個選項。選擇*安裝OS*。

+
.顯示範例
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
交換器會開機進入ONIE安裝模式。

. 停止ONIE探索並設定乙太網路介面。
+
出現以下訊息時、按* Enter *以叫用ONIE主控台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE會繼續探索、並將訊息列印至主控台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 設定交換器管理連接埠的乙太網路介面、並使用新增路由 `ifconfig eth0 <ipAddress> netmask <netmask> up` 和 `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 確認裝載ONIE安裝檔案的伺服器可連線：
+
`ping`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安裝新的交換器軟體：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
軟體隨即安裝、然後重新啟動交換器。讓交換器正常重新開機至新的EFOS版本。

. 登入並確認已安裝新的交換器軟體：
+
「如何啟動bootvar

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. 完成安裝。
交換器會重新啟動、但不會套用任何組態、並會重設為原廠預設值。請依照下列六個步驟重新設定交換器：
+
.. link:configure-install-initial.html["設定交換器"]
.. link:configure-licenses.html["安裝授權"]
.. link:configure-install-rcf.html["安裝 RCF 檔案"]
.. link:configure-ssh.html["啟用SSH"]
.. link:CSHM_log_collection.html["啟用記錄收集"]
.. link:CSHM_snmpv3.html["設定用於監控的 SNMPv3"]


. 在合作夥伴交換器上重複步驟 1 至 8 。

