---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248 叢集交換器基本型號授權配備 16 個 10GbE 或 25GbE 連接埠和 2 個 100GbE 連接埠。可以透過購買更多許可證來新增連接埠。 
---
= 安裝 BES-53248 叢集交換器的許可證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 叢集交換器基本型號授權配備 16 個 10GbE 或 25GbE 連接埠和 2 個 100GbE 連接埠。您可以透過購買更多許可證來新增連接埠。


CAUTION: 對於 EFOS 3.12 及更高版本，請按照以下安裝步驟進行操作：link:efos-install-rcf-license-file.html["安裝參考設定檔 (RCF) 和授權文件"] 。



== 查看可用許可證

以下許可證可用於 BES-53248 叢集交換器：

[cols="1,2,3"]
|===
| 許可證類型 | 許可證詳情 | 支援的韌體版本 


 a| 
SW-BES-53248A2-8P-2P
 a| 
博通 8PT-10G25G + 2PT-40G100G 許可證密鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES-53248A2-8P-1025G
 a| 
博通8埠10G25G許可證金鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248A2-6P-40-100G
 a| 
博通 6 埠 40G/100G 許可證金鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===

NOTE: 若要使用交易密鑰兌換連接埠許可證密鑰文件，請前往link:https://support.broadcom.com/web/csg/license-generation["博通支援的乙太網路交換器的授權門戶"^]頁。請參閱知識庫文章link:https://kb.netapp.com/on-prem/Switches/Broadcom-KBs/How_to_add_Additional_Port_Licensing_for_the_Broadcom_BES_53248_Switch["如何為博通 BES-53248 交換器添加額外的連接埠許可"^]更多詳情請見下文。



== 舊版許可證

下表列出了可在 BES-53248 叢集交換器上使用的舊版授權：

[cols="1,2,3"]
|===
| 許可證類型 | 許可證詳情 | 支援的韌體版本 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25,2P40-100 許可證金鑰，X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25,4P40-100 許可證金鑰，X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-25,6P40-100 許可證金鑰，X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES54248-40-100G-LIC
 a| 
博通 6 埠 40G/100G 許可證金鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
博通8埠10G25G許可證金鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
博通 16 埠 10G25G 許可證金鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
博通 24 埠 10G/25G 許可證金鑰，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===

NOTE: 基本配置不需要許可證。



== 安裝許可證文件

請依照下列步驟安裝 BES-53248 叢集交換器的授權。

.步驟
. 將集群交換器連接到管理網路。
. 使用 `ping`用於驗證與託管 EFOS、許可證和 RCF 檔案的伺服器的連接性的命令。
+
.顯示範例
[%collapsible]
====
此範例驗證交換器是否已連接到 IP 位址為 172.19.2.1 的伺服器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 檢查交換器 CS2 的目前許可證使用：
+
`show license`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. 安裝許可證文件。
+
重複此步驟以載入更多許可證並使用不同的金鑰索引號。

+
.顯示範例
[%collapsible]
====
以下範例使用 SFTP 將授權檔案複製到金鑰索引 1。

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. 顯示所有目前許可證信息，並在交換機 cs2 重新啟動前記錄許可證狀態：
+
`show license`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. 顯示所有已授權連接埠：
+
`show port all | exclude Detach`

+
交換器重新啟動後才會顯示附加許可證文件中的連接埠。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. 重啟交換器：
+
`reload`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. 請檢查新許可證是否已激活，並確認許可證已應用：
+
`show license`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. 檢查所有新連接埠是否可用：
+
`show port all | exclude Detach`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: 安裝其他許可證時，必須手動設定新介面。不要對現有正在運作的生產交換器重新套用 RCF。



== 排查安裝問題

如果在安裝許可證時出現問題，請在執行以下命令之前執行以下偵錯命令： `copy`再次發出命令。

可使用的調試命令： `debug transfer`和 `debug license`

.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
當你運行 `copy`使用命令 `debug transfer`和 `debug license`啟用這些選項後，將傳回日誌輸出。

.顯示範例
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
請檢查調試輸出中的以下內容：

* 請檢查序號是否匹配： `Serial number QTFCU38290012 matched.`
* 檢查交換器型號是否匹配： `Model BES-53248 matched.`
* 檢查指定的許可證索引是否之前未被使用過。如果許可證索引已被使用，則會傳回下列錯誤： `License file /mnt/download//license.dat.1 already exists.`
* 連接埠許可證並非功能許可證。因此，預期會出現以下語句： `Feature not found in license file with index = 1.`


使用 `copy`將連接埠許可證備份到伺服器的命令：

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: 如果需要將交換器軟體從 3.4.4.6 版本降級，則許可證將被移除。這是預期行為。

在還原到軟體的舊版本之前，您必須先安裝相應的舊版本許可證。



== 啟動新授權的端口

要啟動新授權的端口，您需要編輯最新版本的 RCF 文件，並取消註釋適用的端口詳細資訊。

預設許可證啟動連接埠 0/1 至 0/16 和 0/55 至 0/56，而新授權的連接埠將根據可用許可證的類型和數量在連接埠 0/17 至 0/54 之間。例如，要啟動 SW-BES54248-40-100G-LIC 許可證，您必須取消註釋 RCF 中的以下部分：

.顯示範例
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: 對於 0/49 到 0/54 之間的高速端口（含 0/49 和 0/54），取消註釋每個端口，但每個端口的 RCF 中僅取消註釋一行 *speed*，可以是：*speed 100G 全雙工* 或 *speed 40G 全雙工*，如示例所示。對於 0/17 到 0/48 之間的低速連接埠（含 0/17 和 0/48），當啟動對應的許可證後，請取消註解整個 8 埠部分。

.下一步是什麼？
安裝許可證後，您可以 link:configure-install-rcf.html["安裝參考設定檔（RCF）"] 或者 link:upgrade-rcf.html["升級 RCF"]。
