---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 您可以使用此程序、在Bes - 53248叢集交換器上安裝EFOS軟體。您可以從Broadcom乙太網路交換器支援網站下載適用於叢集交換器的Broadcom EFOS軟體。 
---
= 安裝EFOS軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此程序、在Bes - 53248叢集交換器上安裝EFOS軟體。您可以從Broadcom乙太網路交換器支援網站下載適用於叢集交換器的Broadcom EFOS軟體。



==== 關於這項工作

====
*請注意下列事項：*

* 從EFOS 3.4.x.x升級至EFOS 3.7.x.x或更新版本時、交換器必須執行EFOS 3.4.4.6（或更新版本3.4.x.x）。如果您執行之前的版本、請先將交換器升級至EFOS 3.4.4.6（或更新版本3.4.x.x）、然後將交換器升級至EFOS 3.7.x.x或更新版本。
* EFOS 3.4.x.x和3.7.x.x或更新版本的組態不同。若要將EFOS版本從3.4.x.x變更為3.7.x.x或更新版本、或將其變更為3.7.x.x或更新版本、必須將交換器重設為原廠預設值、並套用對應EFOS版本的RCF檔案（重新）。此程序需要透過序列主控台連接埠存取。
* 從EFOS 3.7.x.x或更新版本開始、我們提供不符合FIPS標準的版本、以及符合FIPS標準的版本。從非FIPS相容的版本移至FIPS相容的版本時、會套用不同的步驟、反之亦然。將EFOS從非FIPS相容的版本變更為FIPS相容的版本、反之亦然、會將交換器重設為原廠預設值。此程序需要透過序列主控台連接埠存取。


====
|===


| *程序* | *目前的EFOS版本* | *全新EFOS版本* | *高階步驟* 


 a| 
在兩個（非）FIPS相容版本之間升級EFOS的步驟
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用方法1安裝新的EFOS映像）會保留組態與授權資訊



 a| 
3.4.4.6（或更新版本3.4.x.x）
 a| 
3.7.x.x或更新版本不符合FIPS標準
 a| 
使用方法1升級EFOS。將交換器重設為原廠預設值、並套用EFOS 3.7.x.x或更新版本的RCF檔案



.2+| 3.7.x.x或更新版本不符合FIPS標準  a| 
3.4.4.6（或更新版本3.4.x.x）
 a| 
使用方法1降級EFOS。將交換器重設為原廠預設值、並套用EFOS 3.4.x.x的RCF檔案



 a| 
3.7.x.x或更新版本不符合FIPS標準
 a| 
使用方法1安裝新的EFOS映像。系統會保留組態與授權資訊



 a| 
3.7.x.x或更新版本符合FIPS標準
 a| 
3.7.x.x或更新版本符合FIPS標準
 a| 
使用方法1安裝新的EFOS映像。系統會保留組態與授權資訊



 a| 
從FIPS相容EFOS版本升級至/升級的步驟
 a| 
不符合FIPS標準
 a| 
符合FIPS標準
 a| 
使用方法2安裝EFOS映像。交換器組態和授權資訊將會遺失。



 a| 
符合FIPS標準
 a| 
不符合FIPS標準

|===

IMPORTANT: 請注意、將BSP-53248叢集交換器從EFOS 3.3.x.x或3.4.x.x升級至EFOS 3.7.0.4或3.8.0.2之後、交換器間連結（ISL）和連接埠通道會標示為「*向下*」狀態。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["知識庫文章"^] 以取得更多詳細資料。

.步驟
. 將B通信 設備叢集交換器連接至管理網路。
. 使用「ping」命令來驗證與裝載EFOS、授權和RCF檔案的伺服器之間的連線。
+
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 在CS2上備份目前使用中的映像：
+
「如何啟動bootvar

+
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     Q.10.22.1     3.4.3.3           3.4.3.3
(cs2) # copy active backup
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2) # show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     3.4.3.3     3.4.3.3           3.4.3.3
(cs2) #
----
. 驗證EFOS軟體的執行版本：
+
《如何版本》

+
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. Quanta IX8-B 48x25GB SFP 8x100GB QSFP, 3.4.3.3, Linux 4.4.117-ceeeb99d, 2016.05.00.04
Machine Type................................... Quanta IX8-B 48x25GB SFP 8x100GB QSFP
Machine Model.................................. IX8-B
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.4.3.3
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
. 將映像檔下載到交換器。
+
將映像檔複製到作用中映像、表示當您重新開機時、該映像會建立執行中的EFOS版本。上一個映像仍可作為備份使用。

+
[listing]
----
(cs2) # copy sftp://root@172.19.2.1//tmp/EFOS-3.4.4.6.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 顯示使用中和備份組態的開機映像：
+
「如何啟動bootvar

+
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     3.4.3.3     3.4.3.3            3.4.3.3            3.4.4.6
----
. 重新啟動交換器：
+
"重裝"

+
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
. 再次登入並驗證EFOS軟體的新版本：
+
《如何版本》

+
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. x86_64-quanta_common_rglbmc-r0, 3.4.4.6, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... x86_64-quanta_common_rglbmc-r0
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.4.4.6
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----




== 使用ONIE OS安裝來升級EFOS

如果其中一個EFOS版本符合FIPS標準、而另一個EFOS版本不符合FIPS標準、您可以執行下列步驟。這些步驟可用於在交換器無法開機時、從ONIE安裝非FIPS或FIPS相容的EFOS 3.7.x.x映像。


NOTE: 此功能僅適用於不符合FIPS標準的EFOS 3.7.x.x或更新版本。

.步驟
. 將交換器開機至ONIE安裝模式。
+
在開機期間、當下列畫面出現時、請選取ONIE：

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
選取「* ONIE」*之後、交換器就會載入並顯示下列選項：

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
現在、交換器將會開機進入ONIE安裝模式。

. 停止ONIE探索並設定乙太網路介面。
+
出現下列訊息後、請按<Enter>以叫用ONIE主控台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE探索將會繼續、訊息將會列印到主控台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 使用「ifconfigeth0 <ipaddress> netmask> up」和「route add Default GW <gatewayAddress>」來設定乙太網路介面並新增路由
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 確認裝載ONIE安裝檔案的伺服器可連線：
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. 安裝新的交換器軟體：
+
[listing]
----
ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
軟體將會安裝、然後重新啟動交換器。讓交換器正常重新開機至新的EFOS版本。

. 驗證是否安裝了新的交換器軟體：「How bootvar
+
[listing, subs="+quotes"]
----
(cs2) # *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	  3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(cs2) #
----
. 完成安裝。
+
交換器將在未套用組態的情況下重新開機、然後重設為原廠預設值。



*相關資訊*

https://www.broadcom.com/support/bes-switch["Broadcom乙太網路交換器支援"^]
