---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: 您可以使用此程式執行 BES-53248 叢集交換器的初始安裝。 
---
= 配置 BES-53248 集群交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟對 BES-53248 叢集交換器進行初步設定。

.開始之前
* 硬體已按所述方式安裝。link:install-hardware-bes53248.html["安裝硬體"] 。
* 您已審閱以下內容：
+
** link:configure-reqs-bes53248.html["配置要求"]
** link:components-bes53248.html["組件和零件編號"]
** link:required-documentation-bes53248.html["文件要求"]




.關於範例
設定過程中的範例使用下列交換器和節點命名規則：

* NetApp交換器的名稱是 `cs1`和 `cs2`。升級從第二個交換器 _cs2 開始。
* 集群 LIF 名稱為 `node1_clus1`和 `node1_clus2`對於節點1，以及 `node2_clus1`和 `node2_clus2`對於節點2。
* IP空間名稱為Cluster。
* 這 `cluster1::>`prompt 指示叢集名稱。
* 每個節點上的叢集連接埠都命名為 `e0a`和 `e0b`。參見 https://hwu.netapp.com/Home/Index["NetAppHardware Universe"^]針對您的平台實際支援的叢集連接埠。
* NetApp交換器支援的交換器間連結 (ISL) 為連接埠 0/55 和 0/56。
* NetApp交換器支援的節點連接為連接埠 0/1 至 0/16，採用預設授權。
* 範例中使用了兩個節點，但叢集中最多可以有 24 個節點。


.步驟
. 將串口連接到主機或串列埠。
. 將管理連接埠（交換器左側的 RJ-45 扳手連接埠）連接到 TFTP 伺服器所在的相同網路。
. 在控制台上，設定主機端串列埠設定：
+
** 115200 波特
** 8 位元數據
** 1 停止位
** 奇偶性：無
** 流量控制：無


. 以管理員身分登入交換器。 `admin`當系統提示輸入密碼時，按 *Enter* 鍵。預設交換器名稱為 *routing*。出現提示時，輸入 `enable`。這樣您就可以存取特權 EXEC 模式以進行交換器設定。
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. 將開關名稱變更為 *cs2*。
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. 若要為交換器的服務連接埠設定靜態 IPv4 或 IPv6 管理位址：


[role="tabbed-block"]
====
.IPv4
--
服務連接埠預設為使用 DHCP。  IP位址、子網路遮罩和預設閘道位址將自動指派。

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
服務連接埠預設為使用 DHCP。  IP位址、子網路遮罩和預設閘道位址將自動指派。

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[步驟7]]使用下列指令驗證結果：
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. 配置網域名稱和名稱伺服器：
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. 配置NTP伺服器。


[role="tabbed-block"]
====
.EFOS 3.10.0.3 及更高版本
--
配置時區和時間同步（NTP）：

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 及更早版本
--
設定時區和時間同步（SNTP）：

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]如果您在上一個步驟中沒有設定 NTP 伺服器，請手動設定時間。


[role="tabbed-block"]
====
.EFOS 3.10.0.3 及更高版本
--
手動設定時間。

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 及更早版本
--
手動設定時間。

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[步驟11]]將運行配置儲存到啟動配置：
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.下一步是什麼？
配置好交換器後，您可以… link:configure-efos-software.html["安裝 EFOS 軟體"]。
