---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: 您可以使用此程序來執行Bes - 53248叢集交換器的初始安裝。 
---
= 設定BS-53248叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟執行BS-53248叢集交換器的初始設定。

.開始之前
* 硬體已安裝、如所述 link:install-hardware-bes53248.html["安裝硬體"]。
* 您已檢閱下列內容：
+
** link:configure-reqs-bes53248.html["組態需求"]
** link:components-bes53248.html["元件與零件編號"]
** link:required-documentation-bes53248.html["文件需求"]




.關於範例
組態程序中的範例使用下列交換器和節點命名法：

* NetApp交換器名稱為 `cs1` 和 `cs2`。升級從第二個交換器（_CS2._）開始
* 叢集LIF名稱為節點1的「node1_clus1」和「node1_clus2」、節點2的「node2_clus1」和「node2_clus2」。
* IPspace名稱為叢集。
* 「cluster1：>」提示會指出叢集的名稱。
* 每個節點上的叢集連接埠都會命名為 `e0a` 和 `e0b`。請參閱 https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^] 以取得平台所支援的實際叢集連接埠。
* NetApp交換器支援的交換器間連結（ISL）為連接埠0/55和0/56。
* NetApp交換器支援的節點連線是連接埠0/1到0/16、並具有預設授權。
* 範例使用兩個節點、但叢集中最多可有24個節點。


.步驟
. 將序列連接埠連接至主機或序列連接埠。
. 將管理連接埠（交換器左側的RJ-45扳手連接埠）連接至您的TFTP伺服器所在的相同網路。
. 在主控台設定主機端的序列設定：
+
** 115200傳輸率
** 8個資料位元
** 1停止位元
** 同位元檢查：無
** 流程控制：無


. 以身分登入交換器 `admin` 並在系統提示輸入密碼時按* Enter鍵。預設的交換器名稱為*路由選擇*。在提示字元下輸入 `enable`。這可讓您存取交換器組態的優先執行模式。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
====
. 將交換器名稱變更為* CS2*。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
====
. 若要設定靜態IP位址、請使用範例所示的「服務連接埠傳輸協定」、「網路傳輸協定」和「服務連接埠IP」命令。
+
ServicePort預設為使用DHCP。系統會自動指派IP位址、子網路遮罩和預設閘道位址。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip ipaddr netmask gateway*
----
====
. 使用命令驗證結果：
+
「How ServicePort」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
====
. 設定網域和名稱伺服器：
+
設定

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *ip domain name company.com*
(cs2) (Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2) (Config)# *exit*
(cs2) (Config)#
----
====
. 設定NTP伺服器。
+
.. 設定時區與時間同步（SNTP）：
+
《NTP》

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)#
(cs2) (Config)# *sntp client mode unicast*
(cs2) (Config)# *sntp server 10.99.99.5*
(cs2) (Config)# *clock timezone -7*
(cs2) (Config)# *exit*
(cs2) (Config)#
----
====
+
對於 EFOS 3.10.0.3 版及更新版本、請使用命令 `ntp`。

+
`ntp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)configure
(cs2)(Config)# *ntp ?*

authenticate             Enables NTP authentication.
authentication-key       Configure NTP authentication key.
broadcast                Enables NTP broadcast mode.
broadcastdelay           Configure NTP broadcast delay in microseconds.
server                   Configure NTP server.
source-interface         Configure the NTP source-interface.
trusted-key              Configure NTP authentication key number for trusted time source.
vrf                      Configure the NTP VRF.

(cs2)(Config)# *ntp server ?*

ip-address|ipv6-address|hostname  Enter a valid IPv4/IPv6 address or hostname.

(cs2)(Config)# *ntp server 10.99.99.5*
----
====
.. 手動設定時間：
+
"時鐘"

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2) (Config)# *no sntp client mode*
(cs2) (Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2) (Config)# *clock timezone -5 zone EST*
(cs2) (Config)# *clock set 07:00:00
(cs2) (Config)# *clock set 10/20/2020*

(cs2) (Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2) (Config)# *exit*

(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====




.接下來呢？
link:configure-efos-software.html["安裝EFOS軟體"]。
