---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: '請依照下列步驟在 BES-53248 叢集交換器上安裝乙太網路結構作業系統 (EFOS) 軟體。' 
---
= 安裝 EFOS 軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟在 BES-53248 叢集交換器上安裝乙太網路結構作業系統 (EFOS) 軟體。

EFOS 軟體包含一套用於開發乙太網路和 IP 基礎架構系統的進階網路功能和協定。這種軟體架構適用於任何使用需要徹底資料包檢查或分離的應用程式的網路組織裝置。



== 準備安裝

.開始之前
* 此方法僅適用於新安裝。
* 從以下位置下載適用於您的叢集交換器的 Broadcom EFOS 軟體： https://www.broadcom.com/support/bes-switch["博通乙太網路交換器支援"^]地點。
* 確保link:configure-install-initial.html["BES-53248 叢集交換器已配置"]。




== 安裝軟體

請使用以下方法之一安裝 EFOS 軟體：

* <<方法一：安裝 EFOS>>。適用於大多數情況。
* <<方法二：在 ONIE 模式下安裝 EFOS>>。如果一個 EFOS 版本符合 FIPS 標準，而另一個 EFOS 版本則不符合 FIPS 標準，則可以使用此方法。




=== 方法一：安裝 EFOS

請依照以下步驟安裝 EFOS 軟體。

.步驟
. 登入交換器串列控制台連接埠或透過 SSH 連線。
. 使用 `ping`用於驗證與託管 EFOS、許可證和 RCF 檔案的伺服器的連接性的命令。
+
.顯示範例
[%collapsible]
====
此範例驗證交換器是否已連接到 IP 位址為 172.19.2.1 的伺服器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 將鏡像檔下載到交換器。
+
請查看下表，了解支援的複製協議資訊：

+
|===


| *協定* | *先決條件* 


 a| 
簡單檔案傳輸協定 (TFTP)
 a| 
沒有任何



 a| 
SSH 檔案傳輸協定 (SFTP)
 a| 
您的軟體包必須支援安全管理



 a| 
FTP
 a| 
需要密碼



 a| 
XMODEM
 a| 
沒有任何



 a| 
YMODEM
 a| 
沒有任何



 a| 
ZMODEM
 a| 
沒有任何



 a| 
安全複製協定（SCP）
 a| 
您的軟體包必須支援安全管理



 a| 
HTTP
 a| 
當某些平台提供原生 WGET 工具時，支援基於 CLI 的檔案傳輸。



 a| 
HTTPS
 a| 
當某些平台提供原生 WGET 工具時，支援基於 CLI 的檔案傳輸。

|===
+
將鏡像檔案複製到活動鏡像意味著，當您重新啟動時，該鏡像將建立正在運行的 EFOS 版本。之前的鏡像檔案仍可作為備份使用。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 顯示活動配置和備份配置的啟動映像：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. 重啟交換器：
+
`reload`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. 請重新登入並驗證EFOS軟體的新版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 完成安裝。請依照以下五個步驟重新設定交換器：
+
.. link:configure-licenses.html["安裝許可證"]
.. link:configure-install-rcf.html["安裝 RCF 文件"]
.. link:configure-ssh.html["啟用 SSH"]
.. link:CSHM_log_collection.html["啟用日誌收集"]
.. link:CSHM_snmpv3.html["設定 SNMPv3 進行監控"]


. 在夥伴交換器上重複步驟 1 至 7。




=== 方法二：在 ONIE 模式下安裝 EFOS

如果一個 EFOS 版本符合 FIPS 標準，而另一個 EFOS 版本則不符合 FIPS 標準，則可以執行下列步驟。如果交換器無法啟動，可以使用下列步驟從 ONIE 安裝非 FIPS 或符合 FIPS 標準的 EFOS 3.7.xx 映像。

.步驟
. 連接到交換器串口的控制台。
. 將交換器啟動到 ONIE 安裝模式。
+
啟動時，看到提示符號後選擇 ONIE。

+
.顯示範例
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
選擇 *ONIE* 後，開關會載入並向您展示幾個選項。選擇“安裝作業系統”。

+
.顯示範例
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
交換器啟動進入 ONIE 安裝模式。

. 停止 ONIE 發現並設定乙太網路介面。
+
當出現以下訊息時，按 *Enter* 鍵開啟 ONIE 控制台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 偵測仍在繼續，訊息會列印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 配置交換器管理連接埠的乙太網路介面並新增路由 `ifconfig eth0 <ipAddress> netmask <netmask> up`和 `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 請確認託管 ONIE 安裝檔案的伺服器可以存取：
+
`ping`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安裝新的交換器軟體：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
軟體安裝完成後，交換器將會重新啟動。讓交換器正常重新啟動進入新的 EFOS 版本。

. 登入並確認新交換器軟體已安裝：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. 完成安裝。交換器重新啟動後未套用任何配置，並重設為出廠預設值。請依照以下六個步驟重新設定交換器：
+
.. link:configure-install-initial.html["配置交換機"]
.. link:configure-licenses.html["安裝許可證"]
.. link:configure-install-rcf.html["安裝 RCF 文件"]
.. link:configure-ssh.html["啟用 SSH"]
.. link:CSHM_log_collection.html["啟用日誌收集"]
.. link:CSHM_snmpv3.html["設定 SNMPv3 進行監控"]


. 在夥伴交換器上重複步驟 1 至 8。


.下一步
安裝 EFOS 軟體後，您可以… link:configure-licenses.html["安裝您的許可證"]。
