---
permalink: switch-bes-53248/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation,BES-53248 Broadcom setup,BES-53248 switches configuration,EFOS 
summary: 'ONTAP中的乙太網路交換器健康監視器 (CSHM) 日誌收集功能用於從叢集或儲存網路交換器收集日誌。' 
---
= 乙太網路交換器健康監控日誌收集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
乙太網路交換器健康監視器 (CSHM) 負責確保叢集和儲存網路交換器的運作健康，並收集交換器日誌以進行偵錯。此程式引導您完成從交換器設定和開始收集詳細*支援*日誌的流程，並開始每小時收集由AutoSupport收集的*定期*資料。

.開始之前
* 若要啟用日誌收集功能，您必須執行ONTAP版本 9.10.1P15、9.11.1P12 或 9.12.1 或更高版本以及 EFOS 3.8.0.2 或更高版本。
* 必須為交換器啟用交換器健康監控功能。透過確保以下方式驗證這一點： `Is Monitored:`輸出中該欄位設定為*true* `system switch ethernet show`命令。


.步驟
. 若要設定日誌收集，請對每個交換器執行以下命令。系統會提示您輸入用於日誌收集的交換器名稱、使用者名稱和密碼。
+
`system switch ethernet log setup-password`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. 若要開始收集日誌，請執行以下命令，將 DEVICE 替換為上一個命令中使用的開關。這將啟動兩種類型的日誌收集：詳細的*支援*日誌和每小時收集的*定期*資料。
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
等待 10 分鐘，然後檢查日誌收集是否完成：

+
`system switch ethernet log show`

+

CAUTION: 如果這些命令中的任何一個回傳錯誤，或日誌收集未完成，請聯絡NetApp支援。



.故障排除
如果您遇到日誌收集功能報告的以下任何錯誤狀態（可在輸出中查看）， `system switch ethernet log show` ），請嘗試對應的調試步驟：

|===


| *日誌收集錯誤狀態* | *解決* 


 a| 
*RSA金鑰不存在*
 a| 
重新產生ONTAP SSH 金鑰。聯繫NetApp支援。



 a| 
*切換密碼錯誤*
 a| 
驗證憑證，測試 SSH 連接，並重新產生ONTAP SSH 金鑰。請查閱交換器文件或聯絡NetApp支援以取得操作說明。



 a| 
*FIPS 系統中不存在 ECDSA 金鑰*
 a| 
如果啟用了 FIPS 模式，則需要在交換器上產生 ECDSA 金鑰，然後再重試。



 a| 
*發現已存在的日誌*
 a| 
刪除交換器上之前的日誌收集檔案。



 a| 
*交換器轉儲日誌錯誤*
 a| 
請確保切換使用者擁有日誌收集權限。請參考以上先決條件。

|===