---
permalink: switch-bes-53248/efos-install-rcf-license-file.html 
sidebar: sidebar 
keywords: install rcf,setup rcf,rcf file, efos, license file 
summary: 您可以在設定BS-53248叢集交換器之後、以及套用新授權之後、安裝參考組態檔（RCF）。 
---
= 安裝參考組態檔案（ RCF ）和授權檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 EFOS 3.12.0.1 開始、您可以在設定 BS-53248 叢集交換器之後、安裝參考組態檔案（ RCF ）和授權檔案。


CAUTION: Sall 連接埠是在您安裝 RCF 時設定的、但您需要安裝授權才能啟動設定的連接埠。



== 檢閱要求

.開始之前
請確認下列各項已就緒：

* 交換器組態的目前備份。
* 完全正常運作的叢集（記錄檔中沒有錯誤或類似問題）。
* 目前的 RCF 、可從 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom叢集交換器"^]頁面取得。
* RCF 中的開機組態、可反映所需的開機映像、如果您只安裝 EFOS 並保留目前的 RCF 版本、則需要此組態。如果您需要變更開機組態以反映目前的開機映像、則必須在重新套用RCF之前執行此動作、以便在未來重新開機時產生正確的版本。
* 從原廠預設狀態安裝 RCF 時、需要主控台連線至交換器。如果您已使用知識庫文件、則此需求為選用項目 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何清除 Broadcom 互連交換器上的組態、同時保持遠端連線"^] 事先清除組態。


.建議的文件
請參閱交換器相容性表、以瞭解支援ONTAP 的功能表和RCF版本。請參閱 https://mysupport.netapp.com/site/info/broadcom-cluster-switch["EFOS 軟體下載"^] 頁面。請注意、 RCF 中的命令語法與 EFOS 版本中的命令語法之間可能存在命令相依性。



== 安裝組態檔

.關於範例
本程序中的範例使用下列交換器和節點命名法：

* 兩台 BS-53248 交換器的名稱分別是 CS1 和 CS2 。
* 節點名稱為cluster1-01、cluster1-02、cluster1-03和cluster1-04。
* 叢集 LIF 名稱為 cluster1-01_clus1 、 cluster1-01_clus2 、 cluster1-02_clus1 、 cluster1-02_clus2 、 cluster1-03_clus1 、 cluster1-03_clus2 、 cluster1-04_clus1 和 cluster1-04_clus2 。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 本程序中的範例使用四個節點。這些節點使用兩個10GbE叢集互連連接埠 `e0a` 和 `e0b`。請參閱 https://hwu.netapp.com/Home/Index["Hardware Universe"^] 驗證平台上的叢集連接埠是否正確。



NOTE: 命令輸出可能會因ONTAP 不同版本的不相同而有所差異。

.關於這項工作
此程序需要同時使用 ONTAP 命令和 Broadcom 交換器命令、除非另有說明、否則會使用 ONTAP 命令。

在此程序期間、不需要運作中的交換器間連結（ISL）。這是因為RCF版本變更可能會暫時影響ISL連線。為了確保叢集作業不中斷、下列程序會在執行目標交換器上的步驟時、將所有叢集生命體移轉至作業夥伴交換器。


CAUTION: 在安裝新的交換器軟體版本和 RCFs 之前，請先參閱知識庫文章 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何清除 Broadcom 互連交換器上的組態、同時保持遠端連線"^]。如果您必須完全清除交換器設定、則需要再次執行基本組態。您必須使用序列主控台連線至交換器、因為完整的組態刪除會重設管理網路的組態。



== 步驟1：準備安裝

. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=xh
----
+
其中_x_是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

+
下列命令會禁止自動建立兩小時的個案：

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
[source, cli]
----
set -privilege advanced
----
+
出現進階提示（*>）。

. 顯示連接至叢集交換器之每個節點上的叢集連接埠：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster1-02/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster1-03/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/3               BES-53248
cluster1::*>
----
====
. 檢查每個叢集連接埠的管理和作業狀態。
+
.. 確認所有叢集連接埠都正常運作：
+
[source, cli]
----
network port show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.

Node: cluster1-03

   Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
.. 確認所有叢集介面（l生命）都位於主連接埠：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            cluster1-01_clus1  up/up     169.254.3.4/23     cluster1-01  e0a     true
            cluster1-01_clus2  up/up     169.254.3.5/23     cluster1-01  e0b     true
            cluster1-02_clus1  up/up     169.254.3.8/23     cluster1-02  e0a     true
            cluster1-02_clus2  up/up     169.254.3.9/23     cluster1-02  e0b     true
            cluster1-03_clus1  up/up     169.254.1.3/23     cluster1-03  e0a     true
            cluster1-03_clus2  up/up     169.254.1.1/23     cluster1-03  e0b     true
            cluster1-04_clus1  up/up     169.254.1.6/23     cluster1-04  e0a     true
            cluster1-04_clus2  up/up     169.254.1.7/23     cluster1-04  e0b     true
----
====


. 驗證叢集是否顯示兩個叢集交換器的資訊。


[role="tabbed-block"]
====
.更新版本ONTAP
--
從 ONTAP 9.8 開始、請使用命令：

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.更新版本ONTAP
--
對於 ONTAP 9.7 及更早版本、請使用命令：

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step6]]停用叢集生命體上的自動還原功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




== 步驟2：設定連接埠

. 在交換器 CS2 上、確認連接到叢集中節點的連接埠清單。
+
[source, cli]
----
show isdp neighbor
----
. 在叢集交換器CS2上、關閉連接至節點叢集連接埠的連接埠。例如、如果連接埠 0/1 到 0/16 連接到 ONTAP 節點：
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)#
----
. 驗證叢集LIF是否已移轉至叢集交換器CS1上裝載的連接埠。這可能需要幾秒鐘的時間。
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1 up/up      169.254.3.4/23     cluster1-01   e0a     true
            cluster1-01_clus2 up/up      169.254.3.5/23     cluster1-01   e0a     false
            cluster1-02_clus1 up/up      169.254.3.8/23     cluster1-02   e0a     true
            cluster1-02_clus2 up/up      169.254.3.9/23     cluster1-02   e0a     false
            cluster1-03_clus1 up/up      169.254.1.3/23     cluster1-03   e0a     true
            cluster1-03_clus2 up/up      169.254.1.1/23     cluster1-03   e0a     false
            cluster1-04_clus1 up/up      169.254.1.6/23     cluster1-04   e0a     true
            cluster1-04_clus2 up/up      169.254.1.7/23     cluster1-04   e0a     false
cluster1::*>
----
====
. 驗證叢集是否正常：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. 如果您尚未這麼做、請將下列命令的輸出複製到記錄檔、以儲存目前的交換器組態：
+
[source, cli]
----
show running-config
----
. 清除交換器CS2上的組態、然後執行基本設定。
+

CAUTION: 更新或套用新的RCF時、您必須清除交換器設定並執行基本組態。您必須使用序列主控台連線至交換器、才能清除交換器設定。如果您已使用知識庫文件、則此需求為選用項目 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何清除 Broadcom 互連交換器上的組態、同時保持遠端連線"] 事先清除組態。

+

NOTE: 清除組態不會刪除授權。

+
.. SSH 進入交換器。
+
只有當從交換器的連接埠移除所有叢集生命期、且交換器已準備好清除組態時、才能繼續進行。

.. 進入權限模式：
+
[listing]
----
(cs2)> enable
(cs2)#
----
.. 複製並貼上下列命令以移除先前的 RCF 組態（視先前使用的 RCF 版本而定、如果沒有特定設定、某些命令可能會產生錯誤）：
+
[source, cli]
----
clear config interface 0/1-0/56
y
clear config interface lag 1
y
configure
deleteport 1/1 all
no policy-map CLUSTER
no policy-map WRED_25G
no policy-map WRED_100G
no class-map CLUSTER
no class-map HA
no class-map RDMA
no classofservice dot1p-mapping
no random-detect queue-parms 0
no random-detect queue-parms 1
no random-detect queue-parms 2
no random-detect queue-parms 3
no random-detect queue-parms 4
no random-detect queue-parms 5
no random-detect queue-parms 6
no random-detect queue-parms 7
no cos-queue min-bandwidth
no cos-queue random-detect 0
no cos-queue random-detect 1
no cos-queue random-detect 2
no cos-queue random-detect 3
no cos-queue random-detect 4
no cos-queue random-detect 5
no cos-queue random-detect 6
no cos-queue random-detect 7
exit
vlan database
no vlan 17
no vlan 18
exit
----
.. 將執行組態儲存至啟動組態：
+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
.. 重新啟動交換器：
+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*
----
.. 使用 SSH 再次登入交換器以完成 RCF 安裝。




. 記錄在先前 RCF 中所做的任何自訂項目、並將這些項目套用至新的 RCF 。例如、設定連接埠速度或硬編碼 FEC 模式。
. 使用下列傳輸協定之一、將 RCF 複製到交換器 CS2 的 bootflash ： FTP 、 HTTP 、 TFTP 、 SFTP 或 SCP 。
+
本範例顯示使用HTTP將RCF複製到交換器CS2上的bootFlash：

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy http://<ip-to-webserver>/path/to/BES-53248-RCF-v1.12-Cluster-HA.txt nvram:reference-config*

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... <ip-to-webserver>/path/to/
Filename....................................... BES-53248-RCF-v1.12-Cluster-HA.txt
Data Type...................................... Unknown

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
File transfer in progress.
Management access will be blocked for the duration of the transfer.
Please wait...
HTTP Unknown file type transfer starting...
Validating configuration script
.....
....
Configuration script validated.
File transfer operation completed successfully.
----
====
. 確認指令碼已下載並儲存在您指定的檔案名稱下：
+
《記錄清單》

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
Reference-config.scr                       2680         2024 05 31 21:54:22
1 configuration script(s) found.
2045 Kbytes free.
----
. 將指令碼套用至交換器：
+
適用記錄

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *script apply reference-config.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!
...
...
Configuration script 'reference-config.scr' applied.
----
====
. 安裝授權檔案。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy http://<ip-to-webserver>/path/to/BES-53248-LIC.dat nvram:license-key 1*
Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... <ip-to-webserver>/path/to/
Filename....................................... BES-53248-LIC.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer.

Please wait...

License Key transfer operation completed successfully.

System reboot is required.
(cs2)# *write memory*

This operation may take a few minutes.

Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!

(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
...
...
----
====
. 檢查命令的橫幅輸出 `show clibanner`。您必須閱讀並遵循這些指示、以驗證交換器的正確組態和操作。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show clibanner*

Banner Message configured :
=========================
BES-53248 Reference Configuration File v1.12 for Cluster/HA/RDMA

Switch   : BES-53248
Filename : BES-53248-RCF-v1.12-Cluster.txt
Date     : 11-04-2024
Version  : v1.12
Port Usage:
Ports 01 - 16: 10/25GbE Cluster Node Ports, base config
Ports 17 - 48: 10/25GbE Cluster Node Ports, with licenses
Ports 49 - 54: 40/100GbE Cluster Node Ports, with licenses, added right to left
Ports 55 - 56: 100GbE Cluster ISL Ports, base config
NOTE:
- The 48 SFP28/SFP+ ports are organized into 4-port groups in terms of port speed:
  Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, 45-48
  The port speed should be the same (10GbE or 25GbE) across all ports in a 4-port group
- If additional licenses are purchased, follow the 'Additional Node Ports
  activated with Licenses' section for instructions
- If SSH is active, it will have to be re-enabled manually after 'erase startup-config'
  command has been executed and the switch rebooted"
----
====
. 在交換器上、確認附加授權連接埠在應用 RCF 之後出現：
+
[source, cli]
----
show port all | exclude Detach
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ------------ ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
====
. 在交換器上、確認您的變更已完成：
+
[source, cli]
----
show running-config
----
+
[listing, subs="+quotes"]
----
(cs2)# *show running-config*
----
. 儲存執行中的組態、以便在您重新啟動交換器時將其變成啟動組態：
+
寫入記憶體

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 重新啟動交換器、並驗證執行中的組態是否正確：
+
"重裝"

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*

System will now restart!
----
. 在叢集交換器 CS2 上、開啟連接至節點叢集連接埠的連接埠。例如、如果連接埠 0/1 到 0/16 連接到 ONTAP 節點：
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)#
----
. 驗證交換器 CS2 上的連接埠：
+
[source, cli]
----
show interfaces status all | exclude Detach
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# show interfaces status all | exclude Detach

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. 驗證叢集上叢集連接埠的健全狀況。
+
.. 驗證叢集中所有節點的 e0b 連接埠是否正常運作：
+
[source, cli]
----
network port show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*

Node: cluster1-01
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-02

                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-03
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-04
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====
.. 從叢集驗證交換器健全狀況：
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster01-2/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster01-3/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====


. 驗證叢集是否顯示兩個叢集交換器的資訊。


[role="tabbed-block"]
====
.更新版本ONTAP
--
從 ONTAP 9.8 開始、請使用命令：

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.更新版本ONTAP
--
對於 ONTAP 9.7 及更早版本、請使用命令：

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step21]] 在叢集交換器 CS1 上、關閉連接至節點叢集連接埠的連接埠。
+
以下範例使用介面範例輸出：

+
[listing, subs="+quotes"]
----
(cs1)> *enable*
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
----
. 驗證叢集LIF是否已移轉至交換器CS2上裝載的連接埠。這可能需要幾秒鐘的時間。
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current            Current  Is
Vserver     Interface          Admin/Oper Address/Mask       Node               Port     Home
----------- ------------------ ---------- ------------------ ------------------ -------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01        e0a      false
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01        e0b      true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02        e0a      false
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02        e0b      true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03        e0a      false
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03        e0b      true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04        e0a      false
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04        e0b      true
cluster1::*>
----
====
. 驗證叢集是否正常：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health   Eligibility   Epsilon
-------------------- -------- ------------- -------
cluster1-01          true     true          false
cluster1-02          true     true          false
cluster1-03          true     true          true
cluster1-04          true     true          false
----
====
. 在交換器 CS1 上重複步驟 4 至 19 。
. 在叢集生命體上啟用自動還原：
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 重新開機交換器CS1。這會觸發叢集生命體還原至其主連接埠。您可以在交換器重新開機時忽略節點上報告的「叢集連接埠當機」事件。
+
[listing, subs="+quotes"]
----
(cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved! System will now restart!
----




== 步驟3：驗證組態

. 在交換器 CS1 上、確認連接至叢集連接埠的交換器連接埠為 * 開啟 * ：
+
[source, cli]
----
show interfaces status all | exclude Detach
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# show interfaces status all | exclude Detach

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. 驗證交換器 CS1 和 CS2 之間的 ISL 是否正常運作：
+
[source, cli]
----
show port-channel 1/1
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)
Mbr     Device/       Port      Port
Ports   Timeout       Speed     Active
------- ------------- --------- -------
0/55    actor/long    Auto      True
        partner/long
0/56    actor/long    Auto      True
        partner/long
----
====
. 驗證叢集生命區是否已還原至其主連接埠：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network interface show -role cluster
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0a     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0b     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0a     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0b     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0a     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0a     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
----
====
. 驗證叢集是否正常：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. 驗證遠端叢集介面的連線能力：


[role="tabbed-block"]
====
.更新版本ONTAP
--
您可以使用 `network interface check cluster-connectivity` 命令以啟動叢集連線的存取檢查、然後顯示詳細資料：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 注意： * 請等待數秒後再執行 `show`命令以顯示詳細資料。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster01-02_clus1  none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster01-02_clus2  none

cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-02_clus2   none
----
--
.所有 ONTAP 版本
--
對於所有 ONTAP 版本、您也可以使用 `cluster ping-cluster -node <name>` 檢查連線能力的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e0a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e0b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e0a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e0b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e0a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0b
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e0a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0b
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8
169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
  Local 169.254.1.3 to Remote 169.254.1.6
  Local 169.254.1.3 to Remote 169.254.1.7
  Local 169.254.1.3 to Remote 169.254.3.4
  Local 169.254.1.3 to Remote 169.254.3.5
  Local 169.254.1.3 to Remote 169.254.3.8
  Local 169.254.1.3 to Remote 169.254.3.9
  Local 169.254.1.1 to Remote 169.254.1.6
  Local 169.254.1.1 to Remote 169.254.1.7
  Local 169.254.1.1 to Remote 169.254.3.4
  Local 169.254.1.1 to Remote 169.254.3.5
  Local 169.254.1.1 to Remote 169.254.3.8
  Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
--
====
. 將權限層級變更回管理：
+
[source, cli]
----
set -privilege admin
----
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=END
----


.接下來呢？
link:configure-ssh.html["啟用SSH"]。
