---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: 若要將叢集中現有的 CN1610 叢集交換器替換為 Broadcom 支援的 BES-53248 叢集交換機，必須執行一系列特定的任務。 
---
= 將 CN1610 叢集交換器遷移到 BES-53248 叢集交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將叢集中的 CN1610 叢集交換器移轉到 Broadcom 支援的 BES-53248 叢集交換機，請先查看遷移需求，然後依照遷移程序進行操作。

支援以下集群交換器：

* CN1610
* BES-53248




== 審查要求

請確認您的配置符合以下要求：

* BES-53248 交換器上的某些連接埠配置為以 10GbE 運作。
* 節點到 BES-53248 叢集交換器的 10GbE 連線已規劃、遷移和記錄。
* 叢集運作正常（日誌中不應有任何錯誤或類似問題）。
* BES-53248 交換器的初始客製化工作已完成，具體如下：
+
** BES-53248 交換器運作的是最新推薦版本的 EFOS 軟體。
** 交換器已套用參考設定檔（RCF）。
** 任何網站定制，如 DNS、NTP、SMTP、SNMP 和 SSH，都在新交換器上進行設定。






=== 節點連接

叢集交換器支援以下節點連線：

* NetApp CN1610：連接埠 0/1 至 0/12 (10GbE)
* BES-53248：連接埠 0/1-0/16（10GbE/25GbE）
+

NOTE: 可透過購買連接埠許可證啟動其他連接埠。





=== ISL 連接埠

叢集交換器使用下列交換器間鏈路（ISL）連接埠：

* NetApp CN1610：連接埠 0/13 至 0/16 (10GbE)
* BES-53248：連接埠 0/55-0/56 (100GbE)


這 link:https://hwu.netapp.com/Home/Index["NetApp硬體世界"^] 包含有關ONTAP相容性、支援的 EFOS 韌體以及與 BES-53248 叢集交換器的佈線的資訊。看 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["安裝HWU中沒有的設備還需要哪些額外資訊？"^] 有關交換器安裝要求的詳細資訊。



=== ISL佈線

適用的ISL佈線如下：

* *起始：*對於 CN1610 到 CN1610（SFP+ 到 SFP+），四條 SFP+ 光纖或銅纜直連接線。
* *最終：*對於 BES-53248 到 BES-53248（QSFP28 到 QSFP28），兩個 QSFP28 光收發器/光纖或銅纜直接連接纜線。




== 遷移交換機

請依照下列步驟將 CN1610 叢集交換器遷移到 BES-53248 叢集交換器。

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 範例使用了兩個節點，每個節點部署了兩個 10 GbE 叢集互連連接埠： `e0a`和 `e0b`。
* 命令輸出可能因ONTAP軟體版本不同而有所差異。
* 需要更換的CN1610交換器有： `CL1`和 `CL2`。
* 用於替代 CN1610 交換器的 BES-53248 交換器是 `cs1`和 `cs2`。
* 節點是 `node1`和 `node2`。
* 首先將開關 CL2 替換為 cs2，然後將 CL1 替換為 cs1。
* BES-53248 交換器預先安裝了支援的參考設定檔 (RCF) 和乙太網路交換矩陣作業系統 (EFOS) 版本，ISL 纜線連接在連接埠 55 和 56 上。
* 集群 LIF 名稱為 `node1_clus1`和 `node1_clus2`對於節點1，以及 `node2_clus1`和 `node2_clus2`對於節點2。


.關於此任務
本流程涵蓋以下情況：

* 叢集由兩個節點組成，這兩個節點連接到兩個 CN1610 叢集交換器。
* CN1610 交換器 CL2 被 BES-53248 交換器 cs2 取代：
+
** 關閉叢集節點的連接埠。為避免叢集不穩定，所有連接埠必須同時關閉。
** 斷開連接到 CL2 的所有節點上所有叢集連接埠的電纜，然後使用支援的電纜將連接埠重新連接到新的叢集交換器 cs2。


* CN1610 交換器 CL1 被 BES-53248 交換器 cs1 取代：
+
** 關閉叢集節點的連接埠。為避免叢集不穩定，所有連接埠必須同時關閉。
** 斷開連接到 CL1 的所有節點上所有叢集連接埠的電纜，然後使用支援的電纜將連接埠重新連接到新的叢集交換器 cs1。





NOTE: 在此過程中不需要任何可操作的交換器間連結 (ISL)。這是設計使然，因為 RCF 版本的變更可能會暫時影響 ISL 連線。為確保叢集運作不會中斷，以下步驟將所有叢集 LIF 遷移到運作夥伴交換機，同時在目標交換器上執行對應步驟。



=== 步驟 1：準備遷移

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 為維護窗口的持續時間（小時）。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

+
以下命令可抑制自動建立案件兩小時：

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。





=== 步驟二：設定埠和線纜

. 在新交換器上，確認交換器 cs1 和 cs2 之間的 ISL 線纜連接正常且運作良好：
+
`show port-channel`

+
.顯示範例
[%collapsible]
====
以下範例表示交換器 cs1 上的 ISL 連接埠已啟用：

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
以下範例表示交換器 cs2 上的 ISL 連接埠已啟用：

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 顯示連接到現有叢集交換器的每個節點上的叢集連接埠：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
以下範例顯示了每個節點上每個叢集互連交換器配置的叢集互連連接口數量：

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. 確定每個叢集介面的管理或運作狀態。
+
.. 確認所有叢集連接埠都已連接 `up`與一個 `healthy`地位：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. 確認所有叢集介面（LIF）都已連接到其所屬連接埠：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. 確認集群顯示兩個集群交換器的資訊：


[role="tabbed-block"]
====
.ONTAP 9.8 及更高版本
--
從ONTAP 9.8 開始，使用以下指令： `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 及更早版本
--
對於ONTAP 9.7 及更早版本，請使用以下指令： `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]停用叢集 LIF 的自動還原功能。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. 在叢集交換器 CL2 上，關閉連接到節點叢集連接埠的端口，以便進行叢集 LIF 的故障轉移：
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. 確認叢集 LIF 已故障轉移到叢集交換器 CL1 上託管的連接埠。這可能需要幾秒鐘。
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. 將所有叢集節點連接電纜從舊的 CL2 交換器移至新的 cs2 交換器。
. 確認遷移到 cs2 的網路連線狀況：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
所有已遷移的叢集連接埠都應該是 `up`。

. 檢查叢集連接埠的鄰居資訊：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. 從交換器 CS2 的角度確認交換器連接埠連接是否正常：
+
[listing, subs="+quotes"]
----
cs2# *show interface all*
cs2# *show isdp neighbors*
----
. 在叢集交換器 CL1 上，關閉連接到節點叢集連接埠的端口，以便進行叢集 LIF 的故障轉移：
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
所有群集 LIF 故障轉移到 cs2 交換器。

. 驗證叢集 LIF 是否已故障轉移到交換器 cs2 上託管的連接埠。這可能需要幾秒鐘：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. 將叢集節點連接電纜從 CL1 移至新的 cs1 交換器。
. 確認已遷移至 cs1 的網路連線的健康狀況：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
所有已遷移的叢集連接埠都應該是 `up`。

. 檢查叢集連接埠的鄰居資訊：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. 從交換器 CS1 的角度確認交換器連接埠連接是否正常：
+
[listing, subs="+quotes"]
----
cs1# *show interface all*
cs1# *show isdp neighbors*
----
. 確認 cs1 和 cs2 之間的 ISL 連線仍然正常運作：
+
`show port-channel`

+
.顯示範例
[%collapsible]
====
以下範例表示交換器 cs1 上的 ISL 連接埠已啟用：

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
以下範例表示交換器 cs2 上的 ISL 連接埠已啟用：

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 如果被取代的 CN1610 交換器沒有自動刪除，則將其從叢集的交換器表中刪除：


[role="tabbed-block"]
====
.ONTAP 9.8 及更高版本
--
從ONTAP 9.8 開始，使用以下指令： `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 及更早版本
--
對於ONTAP 9.7 及更早版本，請使用以下指令： `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== 步驟 3：驗證配置

. 啟用叢集 LIF 的自動回滾功能。
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. 在交換器 cs2 上，關閉並重新啟動所有叢集端口，以觸發所有不在它們所屬端口上的集群 LIF 的自動恢復。
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. 驗證叢集 LIF 是否已恢復到其原始連接埠（這可能需要一分鐘）：
+
`network interface show -vserver Cluster`

+
如果叢集中的任何 LIF 尚未恢復到其主端口，請手動將其復原。您必須連接到擁有該 LIF 的本機節點的每個節點管理 LIF 或SP/ BMC系統控制台：

+
`network interface revert -vserver Cluster -lif *`

. 驗證叢集是否運作正常：
+
`cluster show`

. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]]如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用此功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.下一步是什麼？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
