---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: 如果您有一個雙節點無交換器集群，您可以無中斷地遷移到包含博通支援的 BES-53248 集群交換器的雙節點有交換器集群。 
---
= 遷移到交換式NetApp叢集環境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您已經擁有一個雙節點無交換器叢集環境，則可以使用博通支援的 BES-53248 叢集交換器遷移到雙節點有交換器叢集環境，從而使叢集能夠擴展到兩個以上的節點。

遷移過程適用於所有使用光纖或 Twinax 連接埠的叢集節點端口，但如果節點使用板載 10GBASE-T RJ45 連接埠作為叢集網路端口，則此交換器不支援此遷移過程。



== 審查要求

請查看以下叢集環境要求。

* 請注意，大多數系統需要在每個控制器上設定兩個專用的叢集網路連接埠。
* 請確保按照說明設定 BES-53248 集群開關。link:replace-switch-reqs.html["替換要求"]在開始遷移過程之前。
* 對於雙節點無交換器配置，請確保：
+
** 雙節點無交換器配置已正確設定並運作正常。
** 這些節點運行的是ONTAP 9.5P8 及更高版本。從 EFOS 韌體版本 3.4.4.6 及更高版本開始支援 40/100 GbE 叢集連接埠。
** 叢集所有連接埠均處於*開啟*狀態。
** 所有群集邏輯介面（LIF）均處於 *up* 狀態，並位於其主連接埠上。


* 對於博通支援的 BES-53248 叢集交換器配置，請確保：
+
** 兩台交換器上的 BES-53248 群集開關功能完全正常。
** 兩台交換器都具備管理網路連線功能。
** 可以透過控制台存取叢集交換器。
** BES-53248 節點到節點交換器和交換器到交換器的連接使用 Twinax 或光纖電纜。
+
這 https://hwu.netapp.com/Home/Index["NetApp硬體世界"^]包含有關ONTAP相容性、支援的 EFOS 韌體以及與 BES-53248 交換器的佈線的資訊。



* 交換器間連結 (ISL) 電纜連接到兩個 BES-53248 交換器上的連接埠 0/55 和 0/56。
* 兩台 BES-53248 交換器的初始客製化工作已完成，具體如下：
+
** BES-53248 交換器運作的是最新版本的軟體。
** BES-53248 交換器如果購買，則已安裝選用連接埠許可證。
** 參考設定檔（RCF）應用於交換器。


* 所有站點自訂（SMTP、SNMP 和 SSH）均在新交換器上設定。


.連接埠組速度限制
* 48 個 10/25GbE (SFP28/SFP+) 連接埠組合成 12 個 4 埠組，如下：連接埠 1-4、5-8、9-12、13-16、17-20、21-24、25-28、29-32、33-36、37、4-132、47-413
* 4 連接埠組中所有連接埠的 SFP28/SFP+ 連接埠速度必須相同（10GbE 或 25GbE）。
* 如果 4 個連接埠群組中的速度不同，交換器連接埠將無法正常運作。




== 遷移到叢集環境

.關於範例
本流程中的範例使用下列叢集交換器和節點命名規則：

* BES-53248交換器的名稱是 `cs1`和 `cs2`。
* 聚類SVM的名稱是 `node1`和 `node2`。
* LIF的名稱是 `node1_clus1`和 `node1_clus2`在節點 1 上，並且 `node2_clus1`和 `node2_clus2`分別在節點 2 上。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 此過程中使用的集群連接埠為： `e0a`和 `e0b`。
+
這 https://hwu.netapp.com/Home/Index["NetApp硬體世界"^]包含您平台實際集群連接埠的最新資訊。





=== 步驟 1：準備遷移

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 為維護窗口的持續時間（小時）。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

+
以下命令可抑制自動建立案件兩小時：

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
進階提示(`*>`出現。





=== 步驟二：設定埠和線纜

. 停用新叢集交換器 cs1 *和* cs2 上所有已啟動的面向節點的連接埠（不是 ISL 連接埠）。
+

NOTE: 您不得禁用 ISL 連接埠。

+
以下範例顯示交換器 cs1 上面向節點的連接埠 1 到 16 已停用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 確認兩台 BES-53248 交換器 cs1 和 cs2 之間的 ISL 以及 ISL 上的實體連接埠均已啟動：
+
`show port-channel`

+
.顯示範例
[%collapsible]
====
以下範例表示交換器 cs1 上的 ISL 連接埠已啟動：

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
以下範例表示交換器 cs2 上的 ISL 連接埠已啟動：

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 顯示相鄰設備清單：
+
`show isdp neighbors`

+
此命令提供有關連接到系統的設備的資訊。

+
.顯示範例
[%collapsible]
====
以下範例列出了交換器 cs1 上的相鄰設備：

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
以下範例列出了交換器 cs2 上的相鄰設備：

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. 請確認叢集所有連接埠均已啟動：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. 確認所有叢集 LIF 都已啟動並正常運作：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. 停用群集 LIF 的自動回滾功能。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. 斷開節點 1 上的叢集連接埠 e0a 的電纜，然後使用 BES-53248 交換器支援的適當電纜將 e0a 連接到叢集交換器 cs1 上的連接埠 1。
+
這 https://hwu.netapp.com/Home/Index["NetApp硬體世界"^]包含更多關於佈線的資訊。

. 斷開節點 2 上的叢集連接埠 e0a 的電纜，然後使用 BES-53248 交換器支援的適當電纜將 e0a 連接到叢集交換器 cs1 上的連接埠 2。
. 啟用叢集交換器 cs1 上所有面向節點的連接埠。
+
以下範例顯示交換器 cs1 上的連接埠 1 到 16 已啟用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 請確認叢集所有連接埠均已啟動：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 確認所有叢集 LIF 都已啟動並正常運作：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. 顯示叢集中節點的狀態資訊：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集中節點的健康狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 斷開節點 1 上的叢集連接埠 e0b 的電纜，然後使用 BES-53248 交換器支援的適當電纜將 e0b 連接到叢集交換器 cs2 上的連接埠 1。
. 斷開節點 2 上的叢集連接埠 e0b 的電纜，然後使用 BES-53248 交換器支援的適當電纜將 e0b 連接到叢集交換器 cs2 上的連接埠 2。
. 啟用叢集交換器 cs2 上所有面向節點的連接埠。
+
以下範例顯示交換器 cs2 上的連接埠 1 到 16 已啟用：

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. 請確認叢集所有連接埠均已啟動：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== 步驟 3：驗證配置

. 啟用叢集 LIF 的自動回滾功能。
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. 在交換器 cs2 上，關閉並重新啟動所有叢集端口，以觸發所有不在它們所屬端口上的集群 LIF 的自動恢復。
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. 驗證叢集 LIF 是否已恢復到其原始連接埠（這可能需要一分鐘）：
+
`network interface show -vserver Cluster`

+
如果叢集中的任何 LIF 尚未恢復到其主端口，請手動將其復原。您必須連接到擁有該 LIF 的本機節點的每個節點管理 LIF 或SP/ BMC系統控制台：

+
`network interface revert -vserver Cluster -lif *`

. 確認所有介面均顯示 `true`為了 `Is Home`：
+
`network interface show -vserver Cluster`

+

NOTE: 這可能需要幾分鐘才能完成。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. 確認兩個節點都分別與每個交換器建立了一個連線：
+
`show isdp neighbors`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩種開關的正確結果：

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. 顯示集群中已發現的網路設備資訊：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. 請確認這些設定已停用：
+
`network options switchless-cluster show`

+

NOTE: 命令可能需要幾分鐘才能完成。等待「3分鐘生命即將結束」的公告。

+
這 `false`以下範例的輸出表示組態設定已停用：

+
[listing, subs="+quotes"]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: *false*
----
. 驗證叢集中節點成員的狀態：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集中節點的健康狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. 步驟10：將權限等級改回管理員：
+
`set -privilege admin`

. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
+
更多資訊請見： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp知識庫文章：如何在規劃維護視窗期間禁止自動建立案例"^]



.下一步是什麼？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
