---
permalink: switch-bes-53248/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched BES-53248 cluster environment,switchless cluster environments,tnsc,TNSC,2-node 
summary: 如果您有現有的雙節點無交換式叢集環境、可以使用Broadcom支援的Bsc-53248叢集交換器、移轉至雙節點交換式叢集環境、使您能夠擴充至叢集中的兩個節點之外。 
---
= 使用Broadcom支援的Bes - 53248叢集交換器移轉至交換式NetApp叢集環境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有現有的雙節點無交換式叢集環境、可以使用Broadcom支援的Bsc-53248叢集交換器、移轉至雙節點交換式叢集環境、使您能夠擴充至叢集中的兩個節點之外。

雙節點無交換器組態：

* 雙節點無交換器組態必須正確設定並正常運作。
* 節點必須執行ONTAP 的是功能不正常的9.5P8及更新版本。支援40/100 GbE叢集連接埠、從EFOS韌體版本3.4.4.6及更新版本開始。
* 所有叢集連接埠都必須處於「up」（開機）狀態。
* 所有叢集邏輯介面（LIF）都必須處於「up」（開機）狀態、並位於其主連接埠上。


Broadcom支援的Bes - 53248叢集交換器組態：

* B予53248叢集交換器必須在兩個交換器上都能完全正常運作。
* 兩台交換器都必須具備管理網路連線能力。
* 叢集交換器必須有主控台存取權。
* BES至53248節點對節點交換器和交換器對交換器連線必須使用雙軸纜線或光纖纜線。
+
。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe SUR__"^] 包含ONTAP 有關支援功能的資訊、支援的EFOS韌體、以及連接至B作業 環境與53248交換器的纜線。

* 交換器間連結（ISL）纜線必須連接至兩個B2-53248交換器上的連接埠0/55和0/56。
* 兩個B予53248交換器的初始自訂必須完成。因此：
+
** Bes - 53248交換器正在執行最新版本的軟體
** 如果購買的是Bes - 53248交換器、則會安裝選用的連接埠授權
** 參考組態檔（RCT）已套用至交換器
+
必須在新交換器上設定任何站台自訂、例如：SMTP、SNMP和SSH。





本程序中的範例使用下列叢集交換器和節點命名法：

* BS-53248交換器的名稱為「CS1」和「CS2」。
* 叢集SVM的名稱為「node1」和「node2」。
* lifs的名稱分別是節點1上的「node1_clus1」和「node1_clus2」、節點2上的「node2_clus1」和「node2_clus2」。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 此程序中使用的叢集連接埠為「e0a」和「e0b」。
+
。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe SUR__"^] 包含平台實際叢集連接埠的最新資訊。



.步驟
. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -Message MAn=xh」

+
其中x是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

+
下列命令會禁止自動建立兩小時的個案：

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
"進階權限"

+
出現進階提示（「*>」）。

. 在新的叢集交換器CS1 *和* CS2上停用所有啟動的面向節點的連接埠（非ISL連接埠）。
+

NOTE: 您不得停用ISL連接埠。

+
以下範例顯示、交換器CS1上的節點對向連接埠1至16已停用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 驗證兩台BS-53248交換器CS1和CS2之間的ISL和ISL實體連接埠是否為「up（正常）：
+
「How port-channel」

+
下列範例顯示交換器CS1上的ISL連接埠已開啟：

+
[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
+
以下範例顯示交換器CS2上的ISL連接埠已開啟：

+
[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
. 顯示鄰近裝置的清單：
+
「我的鄰居」

+
此命令提供有關連線至系統之裝置的資訊。

+
下列範例列出交換器CS1上的鄰近裝置：

+
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
+
下列範例列出交換器CS2上的鄰近裝置：

+
[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
. 確認所有叢集連接埠均為「up（正常））：
+
「網路連接埠show -IPSpace Cluster」

+
每個連接埠應顯示「Link」（連結）和「Healthy」（健康狀態）。

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
. 驗證所有叢集生命體是否均為「up」（正常運作）：「network interface show -vserver cluster」（網路介面show -vserver叢集）
+
每個叢集LIF都應該顯示「true」、表示「is Home」、並顯示「tatus admin/Opper」為「up / up」

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
. 驗證是否已在所有叢集生命體上啟用「自動還原」：「網路介面show -vserver叢集-功能 變數自動還原」
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
. 從節點1上的叢集連接埠e0a拔下纜線、然後使用BES-53248交換器支援的適當纜線、將e0a連接至叢集交換器CS1上的連接埠1。
+
。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe SUR__"^] 包含纜線的詳細資訊。

. 從節點2上的叢集連接埠e0a拔下纜線、然後使用BES-53248交換器支援的適當纜線、將e0a連接至叢集交換器CS1上的連接埠2。
. 在叢集交換器CS1上啟用所有面向節點的連接埠。
+
下列範例顯示交換器CS1上已啟用連接埠1到16：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 驗證所有叢集生命體是否都正常運作、並顯示為「真實」、表示「是家」：
+
「網路介面show -vserver叢集」

+
以下範例顯示、節點1和節點2上的所有生命都在運作中、而且「原為主目錄」結果為「真」：

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
. 顯示叢集中節點狀態的相關資訊：
+
「叢集展示」

+
下列範例顯示叢集中節點的健全狀況和資格資訊：

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. 從節點1上的叢集連接埠e0b拔下纜線、然後使用BES-53248交換器支援的適當纜線、將e0b連接至叢集交換器CS2上的連接埠1。
. 從節點2上的叢集連接埠e0b拔下纜線、然後使用BES-53248交換器支援的適當纜線、將e0b連接至叢集交換器CS2上的連接埠2。
. 在叢集交換器CS2上啟用所有面向節點的連接埠。
+
下列範例顯示交換器CS2上已啟用連接埠1到16：

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. 確認所有叢集連接埠均為「up（正常））：
+
「網路連接埠show -IPSpace Cluster」

+
以下範例顯示節點1和節點2上的所有叢集連接埠都已啟動：

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
. 驗證所有介面是否都顯示「true」表示「is Home」：
+
「網路介面show -vserver叢集」

+

NOTE: 這可能需要幾分鐘的時間才能完成。

+
以下範例顯示、節點1和節點2上的所有l生命 都已啟動、而且「原為主目錄」結果為「真」：

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
. 驗證兩個節點各自與每個交換器都有一個連線：
+
「我的鄰居」

+
以下範例顯示兩個交換器的適當結果：

+
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
. 顯示叢集中探索到的網路裝置相關資訊：
+
「network device-dDiscovery show -protocol cup」

+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
. 確認設定已停用：
+
「網路選項、無交換式叢集展示」

+

NOTE: 命令可能需要幾分鐘的時間才能完成。等待「3分鐘壽命即將到期」公告。

+
以下範例中的「假」輸出顯示組態設定已停用：

+
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
. 驗證叢集中節點成員的狀態：
+
「叢集展示」

+
下列範例顯示叢集中節點的健全狀況和資格資訊：

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. 請使用下列命令、確保叢集網路具備完整連線能力：
+
「叢集ping叢集-node-node-name_」

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 192.168.168.26 node1 e0a
Cluster node1_clus2 192.168.168.27 node1 e0b
Cluster node2_clus1 192.168.168.28 node2 e0a
Cluster node2_clus2 192.168.168.29 node2 e0b
Local = 192.168.168.28 192.168.168.29
Remote = 192.168.168.26 192.168.168.27
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 4 path(s):
    Local 192.168.168.28 to Remote 192.168.168.26
    Local 192.168.168.28 to Remote 192.168.168.27
    Local 192.168.168.29 to Remote 192.168.168.26
    Local 192.168.168.29 to Remote 192.168.168.27
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. 將權限層級變更回管理：
+
「et -priv. admin」

. 如果您禁止自動建立個案、請叫用AutoSupport 下列消息來重新啟用此功能：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=END
----


請參閱 link:configure-health-monitor.html["安裝叢集交換器健全狀況監視器（CSHM）組態檔"] 和 link:configure-log-collection.html["設定叢集交換器記錄收集功能"] 以瞭解啟用叢集健全狀況交換器記錄收集以收集交換器相關記錄檔所需的步驟。

*相關資訊*

https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]

link:replace-requirements.html["Broadcom支援的Bes - 53248交換器設定與組態"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp知識庫文章：如何在排定的維護時間內禁止自動建立案例"^]
