---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: 您可以在首次設定BS-53248叢集交換器之後、以及在套用新的授權或授權之後、安裝RCF。如果您要從舊版升級RCF、檔案會有效地合併在一起、並完成此處詳述的步驟。 
---
= 安裝參考組態檔（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在首次設定BS-53248叢集交換器之後、以及在套用新的授權或授權之後、安裝RCF。如果您要從舊版升級RCF、則必須重設Broadcom交換器設定並執行基本組態、才能重新套用RCF。每次您想要升級或變更RCF時、都必須執行此作業。請參閱下列內容 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["知識庫文章"^] 以取得詳細資料。



== 將Broadcom IP交換器重設為原廠預設值

在安裝新的交換器軟體版本和RCFs之前、您必須清除Broadcom交換器設定並執行基本組態。

.關於這項工作
* 您必須在每個叢集交換器上重複這些步驟。
* 您必須使用序列主控台連線至交換器。
* 此工作會重設管理網路的組態。


.步驟
. 變更為提升命令提示字元（`#'）：「enable」
+
[listing]
----
(cs2)> enable
(cs2) #
----
. 清除啟動組態並移除橫幅
+
.. 清除啟動組態：
+
*「erase啟動組態」*

+
[listing]
----
(cs2) #erase startup-config
Are you sure you want to clear the configuration? (y/n) y
(cs2) #
----
+
此命令不會清除橫幅。

.. 移除橫幅：
+
*「no set clibanner」*

+
[listing]
----
(cs2) #configure
(cs2)(Config) # no set clibanner
(cs2)(Config) #
----


. 重新啟動交換器：*（CS2）#relev*
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: 如果系統在重新載入交換器之前詢問是否要儲存未儲存或變更的組態、請選取*否*。

. 等待交換器重新載入、然後登入交換器。
+
預設使用者為「admin」、未設定密碼。畫面會顯示類似下列的提示：

+
[listing]
----
(Routing)>
----
. 變更為提高權限的命令提示字元：
+
「啟用」

+
[listing]
----
Routing)> enable
(Routing) #
----
. 將服務連接埠傳輸協定設為「無」：
+
'無服務傳輸協定'

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. 將IP位址指派給服務連接埠：
+
「erviceport ip _ip-address__netask__gateway_」

+
以下範例顯示指派IP位址「10.10.10.10」的服務連接埠、子網路為「255．255．255．0」、閘道為「10．10．10」：

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. 確認服務連接埠設定正確：
+
「How ServicePort」

+
下列範例顯示連接埠已啟動、且已指派正確的位址：

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 如有需要、請設定SSH伺服器。
+

NOTE: RCF檔案會停用Telnet傳輸協定。如果您未設定SSH伺服器、則只能使用序列連接埠連線存取橋接器。

+
.. 產生RSA金鑰。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. 產生DSA金鑰（選用）
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. 如果您使用的是FIPS相容版本的EFOS、請產生ECDSA金鑰。下列範例會建立長度為256的金鑰。有效值為256、384或521。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. 啟用SSH伺服器。
+
如有必要、請結束組態內容。

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: 如果金鑰已經存在、系統可能會要求您覆寫金鑰。



. 如有需要、請設定網域和名稱伺服器：
+
設定

+
以下範例顯示「IP網域」和「IP名稱伺服器」命令：

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 如有需要、請設定時區和時間同步（SNTP）。
+
以下範例顯示「shntp」命令、指定SNTP伺服器的IP位址和相對時區。

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. 設定交換器名稱：
+
主機名稱CS2

+
交換器提示會顯示新名稱：

+
[listing]
----
(Routing) # hostname cs2

(cs2) #
----
. 儲存組態：
+
寫入記憶體

+
您會收到類似下列範例的提示和輸出：

+
[listing]
----
(cs2) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(cs2) #
----
. 在其他叢集交換器上重複上述步驟。




== 安裝參考組態檔（RCF）

.步驟
. 將叢集交換器連接至管理網路。
. 使用ping命令來驗證與裝載EFOS、授權和RCF之伺服器的連線。
+
如果連線有問題、請使用非路由網路、並使用IP位址192.168.x或172.19.x來設定服務連接埠您可以稍後將服務連接埠重新設定為正式作業管理IP位址。

+
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 使用copy命令在BS-53248叢集交換器上安裝RCF。
+
[listing]
----
(cs2) # copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: 視您的環境而定、您可能需要在copy命令中使用雙斜槓、例如：`+copy http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM：指令碼BS-53248_RCF-v1.6-Cluster-HA.scr+。

+

NOTE: 在啟動指令碼之前、必須先將「.scr」副檔名設定為檔案名稱的一部分。此擴充是EFOS作業系統的延伸。當指令碼下載到交換器時、交換器會自動驗證指令碼、並將輸出傳送到主控台。此外、您也可以變更「.scr」的名稱、使其符合主控台螢幕的大小、以便更容易閱讀、例如：「+ copy」 http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM：指令碼RCF-v1.6-Cluster-HA.scr+。

. 確認已下載指令碼並儲存至您指定的檔案名稱：
+
《記錄清單》

+
[listing]
----
(cs2) # script list

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. 將指令碼套用至交換器。
+
適用記錄

+
[listing]
----
(cs2) # script apply BES-53248_RCF_v1.6-Cluster-HA.scr

Are you sure you want to apply the configuration script? (y/n) y

The system has unsaved changes.
Would you like to save them now? (y/n) y
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. 在套用RCF之後、驗證連接埠是否有額外授權：
+
「How port all | exclude Detach」

+
[listing]
----
(cs2) # show port all \| exclude Detach

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. 在交換器上確認您已進行變更：
+
「如何執行設定」

+
[listing]
----
(cs2) # show running-config
----
. 儲存執行中的組態、以便在您重新啟動交換器時將其變成啟動組態：
+
寫入記憶體

+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 重新啟動交換器、並驗證執行中的組態是否正確：
+
"重裝"

+
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n) y

System will now restart!
----

