---
permalink: switch-bes-53248/replace-prepare-controller.html 
sidebar: sidebar 
keywords: BES-53248 switches,preparing for upgrade,upgrade bes-53248 switch 
summary: 您可以使用此程序來準備控制器以進行BES-53248叢集交換器升級。 
---
= 準備控制器以進行叢集交換器升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此程序來準備控制器以進行BES-53248叢集交換器升級。

.步驟
. 將叢集交換器連接至管理網路。
. 使用ping命令來驗證與裝載EFOS、授權和RCF之伺服器的連線。
+
如果發生此問題、請使用非路由網路、並使用IP位址192.168.x或172.19.x來設定服務連接埠您可以稍後將服務連接埠重新設定為正式作業管理IP位址。

+
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 使用以下命令確認叢集連接埠正常運作、並有連結：
+
「網路連接埠show -IPSpace Cluster」

+
以下範例顯示所有連接埠的輸出類型、其「連結」值為up、「健全狀態」為healthy：

+
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
. 使用以下命令、確認叢集生命體在管理和操作上均已啟動、並位於其主連接埠上：
+
「網路介面show -vserver叢集」

+
在此範例中、「-vserver」參數會顯示與叢集連接埠相關聯的lifs資訊。「狀態管理/操作者」必須為開機、「IS主頁」必須為真：

+
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----

