---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 升級BS-53248叢集交換器時、首先要準備好控制器以進行升級、安裝EFOS軟體、授權、以及參考組態檔（RCF）。安裝完成後、您可以在不中斷營運的升級（NDU）和不中斷營運環境（NDU）環境中還原控制器組態。 
---
= 升級BS-53248叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟升級BS-53248叢集交換器。

此程序適用於正常運作的叢集、並允許不中斷營運的升級（NDU）和不中斷營運（NDO）環境。



== 檢閱要求

在現有NetApp BS-53248叢集交換器上安裝EFOS軟體、授權和RCF檔案之前、請確定：

* 叢集是功能完整的叢集（沒有錯誤記錄訊息或其他問題）。
* 叢集不含任何故障的叢集網路介面卡（NIC）。
* 兩個叢集交換器上所有連接的連接埠均正常運作。
* 所有叢集連接埠均已啟動。
* 所有的叢集生命都在管理和作業上、並在其主連接埠上。
* 每個節點上的前兩個叢集l生命 量是在個別的NIC上設定、並連接至個別的叢集交換器連接埠。
* The The ONTAP `cluster ping-cluster -node node1` 進階權限命令會指出這一點 `larger than PMTU communication` 在所有路徑上都成功。



NOTE: RCF和EFOS版本中的命令語法可能會有命令相依性。


NOTE: 如需交換器相容性、請參閱上的相容性表 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom叢集交換器"^] 支援的EFOS、RCF和ONTAP 版本的頁面。



== 準備控制器

請遵循此程序、為控制器做好升級BES-53248叢集交換器的準備。

.步驟
. 將叢集交換器連接至管理網路。
. 使用ping命令來驗證與裝載EFOS、授權和RCF之伺服器的連線。
+
如果發生此問題、請使用非路由網路、並使用IP位址192.168.x或172.19.x來設定服務連接埠您可以稍後將服務連接埠重新設定為正式作業管理IP位址。

+
.顯示範例
[%collapsible]
====
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 使用以下命令確認叢集連接埠正常運作、並有連結：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
以下範例顯示所有連接埠的輸出類型、其「連結」值為up、「健全狀態」為healthy：

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 使用以下命令、確認叢集生命體在管理和操作上均已啟動、並位於其主連接埠上：
+
「網路介面show -vserver叢集」

+
.顯示範例
[%collapsible]
====
在此範例中、「-vserver」參數會顯示與叢集連接埠相關聯的lifs資訊。「狀態管理/操作者」必須為開機、「IS主頁」必須為真：

[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====




== 安裝軟體

請依照下列指示安裝軟體。

. link:configure-efos-software.html["安裝EFOS軟體"]。在BS-53248叢集交換器上下載並安裝乙太網路架構作業系統（EFOS）軟體。
. link:configure-licenses.html["安裝適用於B3作業 叢集交換器的授權"]。或者、您也可以購買及安裝更多授權來新增連接埠。交換器基礎模式已獲得16個10GbE或25GbE連接埠及2個100GbE連接埠的授權。
. link:configure-install-rcf.html["安裝參考組態檔（RCF）"]。在BS-53248叢集交換器上安裝或升級RCF、然後在套用RCF之後驗證連接埠是否有額外授權。
. link:configure-health-monitor.html["安裝叢集交換器健全狀況監視器（CSHM）組態檔"]。安裝適用的組態檔以監控叢集交換器健全狀況。
. link:configure-ssh.html["在BS-53248叢集交換器上啟用SSH"]。如果您使用叢集交換器健全狀況監視器（CSHM）和記錄收集功能、請在交換器上啟用SSH。
. link:configure-log-collection.html["啟用記錄收集功能"]。使用此功能可收集ONTAP 有關交換器的記錄檔、以供參考。

