---
permalink: switch-bes-53248/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: BES-53248 switches,initial installation,new install 
summary: 您可以完成本章中詳細說明的步驟、設定新的Bes - 53248叢集交換器。 
---
= 設定新的Bes - 53248叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以完成本章中詳細說明的步驟、設定新的Bes - 53248叢集交換器。

在執行ONTAP 指示燈介面的系統上安裝Bes - 53248叢集交換器、首先要設定IP位址和組態、讓交換器能夠透過管理介面進行通訊。然後您可以視需要安裝乙太網路架構作業系統（EFOS）軟體、參考組態檔（RCF）及其他授權。此程序旨在在新增控制器之前、先準備B3交互 式交換器。此外、您可能需要安裝所需的組態檔、以支援適用於BS-53248叢集交換器的叢集交換器健全狀況監視器（CSHealth Monitor、CSHM）。請參閱 link:replace_install_cshm_file.md#GUID-53ED7CFF-35AD-4D01-BDAF-CA17ABF3AD4E["安裝叢集交換器健全狀況監視器（CSHM）組態檔"] 以取得更多詳細資料。

本程序中的範例使用下列交換器和節點命名法：

* NetApp交換器名稱為CS1和CS2。
* 此程序中使用的範例會在第二個交換器_CS2._上開始升級
* 叢集LIF名稱為node1_clus1、node1_clus2為node1、node2_clus1為node2_clus2、node2_clus2為node2。
* IPspace名稱為叢集。
* 「cluster1：>」提示會指出叢集的名稱。
* 每個節點上的叢集連接埠名稱為e0a和e0b。
+
如Hardware Universe 需平台上支援的實際叢集連接埠、請參閱_SUR__。

+
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]

* NetApp交換器支援的交換器間連結（ISL）為連接埠0/55和0/56。
* NetApp交換器支援的節點連線是連接埠0/1到0/16、並具有預設授權。
* 本程序中的範例使用兩個節點、但叢集中最多可有24個節點。

