---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: 您需要特定的交換器與控制器文件、才能設定叢集模式組態。 
---
= BS-53248叢集交換器的文件需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於BES-53248交換器的安裝與維護、請務必檢閱特定的交換器與控制器文件。



== Broadcom文件

若要設定Bes - 53248叢集交換器、您需要Broadcom支援網站上提供的下列文件： https://["Broadcom乙太網路交換器產品線"^]

[cols="1,2"]
|===
| 文件標題 | 說明 


 a| 
_EFOS系統管理員指南v3.4.3_
 a| 
提供範例、說明如何在一般網路中使用B怎麼 使用B怎麼53248交換器。



 a| 
_EFOS CLI命令參考v3.4.3_
 a| 
說明用於檢視和設定Bs-53248軟體的命令列介面（CLI）命令。



 a| 
_EFOS入門指南v3.4.3_
 a| 
提供關於B3作業 與53248交換器的詳細資訊。



 a| 
_EFOS SNMP參考指南v3.4.3_
 a| 
提供範例、說明如何在一般網路中使用B怎麼 使用B怎麼53248交換器。



 a| 
_EFOS Scaling參數字與值v3.4.3_
 a| 
說明EFOS軟體在支援平台上的交付與驗證預設擴充參數。



 a| 
_EFOS功能規格v3.4.3_
 a| 
說明EFOS軟體在支援平台上的規格。



 a| 
_EFOS發行說明v3.4.3_
 a| 
提供關於B3作業 軟體的版本專屬資訊。



 a| 
_叢集網路與管理網路相容性對照表_
 a| 
提供網路相容性的相關資訊。您可從BS-53248交換器下載網站取得此對照表 https://["Broadcom叢集交換器"^]。

|===


== 系統文件與知識庫文章ONTAP

若要設定 ONTAP 系統，您需要 NetApp 支援網站上的下列文件： http://["mysupport.netapp.com"^] 或是位於的知識庫（KB）網站 https://["kb.netapp.com"^]。

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
https://["NetApp Hardware Universe"^]
 a| 
說明所有NetApp硬體（包括系統機櫃）的電源和站台需求、並提供相關連接器和纜線選項的相關資訊及其零件編號。



 a| 
控制器專屬的安裝與設定指示_
 a| 
說明如何安裝NetApp硬體。



 a| 
功能9. ONTAP
 a| 
提供ONTAP 有關支援功能的詳細資訊。



 a| 
_如何為Broadcom支援的BS-53248交換器新增額外的連接埠授權_
 a| 
提供新增連接埠授權的詳細資訊。前往 https://["知識庫文章"^]。

|===