---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 請依照下列步驟升級 BS-53248 叢集交換器上的乙太網路光纖 OS （ EFOS ）軟體。 
---
= 升級 EFOS 軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟升級 BS-53248 叢集交換器上的 EFOS 軟體。

EFOS軟體包含一組進階網路功能和傳輸協定、可用於開發乙太網路和IP基礎架構系統。此軟體架構適用於使用需要徹底封包檢查或分離的應用程式的任何網路組織裝置。



== 準備升級

.開始之前
* 從下載適用於叢集交換器的Broadcom EFOS軟體 https://www.broadcom.com/support/bes-switch["Broadcom乙太網路交換器支援"^] 網站。
* 請檢閱下列EFOS版本的相關附註。


[]
====
*請注意下列事項：*

* 從EFOS 3.4.x.x升級至EFOS 3.7.x.x或更新版本時、交換器必須執行EFOS 3.4.4.6（或更新版本3.4.x.x）。如果您執行之前的版本、請先將交換器升級至EFOS 3.4.4.6（或更新版本3.4.x.x）、然後將交換器升級至EFOS 3.7.x.x或更新版本。
* EFOS 3.4.x.x和3.7.x.x或更新版本的組態不同。若要將EFOS版本從3.4.x.x變更為3.7.x.x或更新版本、或將其變更為3.7.x.x或更新版本、必須將交換器重設為原廠預設值、並套用對應EFOS版本的RCF檔案（重新）。此程序需要透過序列主控台連接埠存取。
* 從EFOS 3.7.x.x或更新版本開始、我們提供不符合FIPS標準的版本、以及符合FIPS標準的版本。從非FIPS相容的版本移至FIPS相容的版本時、適用不同的步驟、反之亦然。將EFOS從非FIPS相容的版本變更為FIPS相容的版本、反之亦然、會將交換器重設為原廠預設值。此程序需要透過序列主控台連接埠存取。


====
|===


| *程序* | *目前的EFOS版本* | *全新EFOS版本* | *高階步驟* 


 a| 
在兩個（非）FIPS相容版本之間升級EFOS的步驟
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用升級新的 EFOS 映像 <<方法 1 ：升級 EFOS>>。
系統會保留組態與授權資訊。



 a| 
3.4.4.6（或更新版本3.4.x.x）
 a| 
3.7.x.x或更新版本不符合FIPS標準
 a| 
使用升級EFOS <<方法 1 ：升級 EFOS>>。
將交換器重設為原廠預設值、並套用EFOS 3.7.x.x或更新版本的RCF檔案。



.2+| 3.7.x.x或更新版本不符合FIPS標準  a| 
3.4.4.6（或更新版本3.4.x.x）
 a| 
使用降級EFOS <<方法 1 ：升級 EFOS>>。
將交換器重設為原廠預設值、並套用EFOS 3.4.x.x的RCF檔案



 a| 
3.7.x.x或更新版本不符合FIPS標準
 a| 
使用升級新的 EFOS 映像 <<方法 1 ：升級 EFOS>>。系統會保留組態與授權資訊。



 a| 
3.7.x.x或更新版本符合FIPS標準
 a| 
3.7.x.x或更新版本符合FIPS標準
 a| 
使用升級新的 EFOS 映像 <<方法 1 ：升級 EFOS>>。
系統會保留組態與授權資訊。



 a| 
從FIPS相容EFOS版本升級至/升級的步驟
 a| 
不符合FIPS標準
 a| 
符合FIPS標準
 a| 
使用升級 EFOS 映像 <<方法2：使用ONIE OS安裝來升級EFOS>>。交換器組態和授權資訊將會遺失。



 a| 
符合FIPS標準
 a| 
不符合FIPS標準

|===
[IMPORTANT]
====
若要檢查您的 EFOS 版本是否符合 FIPS 標準或不符合 FIPS 標準、請使用 `show fips status` 命令。在下列範例中、 *IP_switch_A1* 使用 FIPS 相容的 EFOS 、而 *IP_switch_A2* 則使用非 FIPS 相容的 EFOS 。

* 在交換器 IP_switch_A1 （符合 FIPS 標準的 EFOS ）上：
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* 在交換器 IP_switch_A2 上（不符合 FIPS 標準的 EFOS ）：
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== 升級軟體

請使用下列其中一種方法：

* <<方法 1 ：升級 EFOS>>。適用於大多數情況（請參閱上表）。
* <<方法2：使用ONIE OS安裝來升級EFOS>>。如果其中一個EFOS版本符合FIPS標準、而另一個EFOS版本不符合FIPS標準、請使用。



NOTE: 一次在一台交換器上升級 EFOS 、以確保叢集網路持續運作。



=== 方法 1 ：升級 EFOS

執行下列步驟以升級 EFOS 軟體。


IMPORTANT: 請注意、將BSP-53248叢集交換器從EFOS 3.3.x.x或3.4.x.x升級至EFOS 3.7.0.4或3.8.0.2之後、交換器間連結（ISL）和連接埠通道會標示為「*向下*」狀態。請參閱以下知識庫文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BS-53248叢集交換器NDU無法升級至EFOS 3.7.0.4及更新版本"^] 以取得更多詳細資料。

.步驟
. 將B通信 設備叢集交換器連接至管理網路。
. 使用「ping」命令來驗證與裝載EFOS、授權和RCF檔案的伺服器之間的連線。
+
此範例可驗證交換器是否連接至IP位址為172.19.2.1的伺服器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 停用叢集生命體上的自動還原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 顯示使用中和備份組態的開機映像：
+
「如何啟動bootvar

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4

----
====
. 在CS2上備份目前使用中的映像：
+
[source, cli]
----
copy active backup
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy active backup*
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :
 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4
(cs2)#
----
====
. 驗證EFOS軟體的執行版本：
+
《如何版本》

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.7.0.4, Linux 4.4.117-ceeeb99d, 2016.05.00.05
Machine Type................................... BES-53248A1
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.7.0.4
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
+

NOTE: 如果您已安裝任何授權、請檢閱其狀態。

. 將映像檔下載到交換器。
+
將映像檔複製到作用中映像、表示當您重新開機時、該映像會建立執行中的EFOS版本。上一個映像仍可作為備份使用。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 顯示使用中和備份組態的開機映像：
+
「如何啟動bootvar

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. 重新啟動交換器：
+
"重裝"

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 再次登入並驗證EFOS軟體的新版本：
+
《如何版本》

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 在交換器 CS1 上重複步驟 5 到 10 。
. 在叢集生命體上啟用自動還原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 驗證叢集生命區是否已還原至其主連接埠：
+
[source, cli]
----
network interface show -role Cluster
----
+
如需詳細資料、請參閱 link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["將LIF還原至其主連接埠"]。





=== 方法2：使用ONIE OS安裝來升級EFOS

如果其中一個EFOS版本符合FIPS標準、而另一個EFOS版本不符合FIPS標準、您可以執行下列步驟。如果交換器無法開機、這些步驟可用於從 ONIE 升級非 FIPS 或 FIPS 相容的 EFOS 3.7.x.x 映像。


NOTE: 此功能僅適用於不符合FIPS標準的EFOS 3.7.x.x或更新版本。


CAUTION: 如果您使用 ONIE OS 安裝來升級 EFOS 、組態會重設為原廠預設值、並刪除授權。您必須設定交換器並安裝授權和支援的 RCF 、才能讓交換器恢復正常運作。

.步驟
. 停用叢集生命體上的自動還原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 將交換器開機至ONIE安裝模式。
+
在開機期間、當您看到提示時、請選取 ONIE ：

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
選擇* ONIE*之後、交換器會載入並顯示多個選項。選擇*安裝OS*。

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
交換器會開機進入ONIE安裝模式。

. 停止ONIE探索並設定乙太網路介面。
+
出現以下訊息時、按* Enter *以叫用ONIE主控台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE會繼續探索、並將訊息列印至主控台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 使用「ifconfigeth0 <ipaddress> netmask> up」和「route add Default GW <gatewayAddress>」來設定乙太網路介面並新增路由
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 確認裝載ONIE安裝檔案的伺服器可連線：
+
`ping`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安裝新的交換器軟體：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
軟體隨即安裝、然後重新啟動交換器。讓交換器正常重新開機至新的EFOS版本。

. 驗證是否安裝了新的交換器軟體：
+
「如何啟動bootvar

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. 完成安裝。交換器會重新啟動、但不會套用任何組態、並會重設為原廠預設值。完成下列步驟以重新設定交換器：
+
.. link:configure-licenses.html["安裝授權"]
.. link:configure-install-rcf.html["安裝RCF"]
.. link:configure-ssh.html["啟用SSH"]
.. link:CSHM_log_collection.html["啟用記錄收集"]
.. link:CSHM_snmpv3.html["設定用於監控的 SNMPv3"]


. 在交換器 CS1 上重複步驟 2 到 8 。
. 在叢集生命體上啟用自動還原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 驗證叢集生命區是否已還原至其主連接埠：
+
[source, cli]
----
network interface show -role Cluster
----
+
如需詳細資料、請參閱 link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["將LIF還原至其主連接埠"]。


