---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: '請依照以下步驟升級 BES-53248 叢集交換器上的乙太網路結構作業系統 (EFOS) 軟體。' 
---
= 升級 EFOS 軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照以下步驟升級 BES-53248 叢集交換器上的 EFOS 軟體。

EFOS 軟體包含一套用於開發乙太網路和 IP 基礎架構系統的進階網路功能和協定。這種軟體架構適用於任何使用需要徹底資料包檢查或分離的應用程式的網路組織裝置。



== 準備升級

.開始之前
* 從以下位置下載適用於您的叢集交換器的 Broadcom EFOS 軟體： https://www.broadcom.com/support/bes-switch["博通乙太網路交換器支援"^]地點。
* 請查看以下有關 EFOS 版本的說明。


[]
====
*請注意以下事項：*

* 從 EFOS 3.4.xx 升級到 EFOS 3.7.xx 或更高版本時，交換器必須執行 EFOS 3.4.4.6（或更高版本的 3.4.xx）。如果您使用的是先前的版本，請先將交換器升級到 EFOS 3.4.4.6（或更高版本的 3.4.xx），然後再將交換器升級到 EFOS 3.7.xx 或更高版本。
* EFOS 3.4.xx 和 3.7.xx 或更高版本的配置有所不同。將 EFOS 版本從 3.4.xx 更改為 3.7.xx 或更高版本，反之亦然，需要將交換器重置為出廠預設設置，並（重新）套用相應 EFOS 版本的 RCF 檔案。此過程需要透過序列控制台連接埠進行存取。
* 從 EFOS 版本 3.7.xx 或更高版本開始，提供不符合 FIPS 標準的版本和符合 FIPS 標準的版本。從不符合 FIPS 標準的版本過渡到符合 FIPS 標準的版本或反之亦然時，需要採取不同的步驟。將 EFOS 從不符合 FIPS 標準的版本變更為符合 FIPS 標準的版本，反之亦然，會將交換器重設為原廠預設值。此過程需要透過序列控制台連接埠進行存取。


====
|===


| *程式* | *當前EFOS版本* | *全新EFOS版本* | *進階步驟* 


 a| 
在兩個（非）符合 FIPS 標準的版本之間升級 EFOS 的步驟
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用以下方式升級新的 EFOS 映像<<方法一：升級EFOS>>。配置和許可證資訊將被保留。



 a| 
3.4.4.6（或更高版本的 3.4.xx）
 a| 
3.7.xx 或更高版本不符合 FIPS 標準
 a| 
使用以下方式升級 EFOS<<方法一：升級EFOS>> 。將交換器重設為出廠預設設置，並套用適用於 EFOS 3.7.xx 或更高版本的 RCF 檔案。



.2+| 3.7.xx 或更高版本不符合 FIPS 標準  a| 
3.4.4.6（或更高版本的 3.4.xx）
 a| 
使用降級 EFOS<<方法一：升級EFOS>> 。將交換器重設為出廠預設設置，並套用適用於 EFOS 3.4.xx 的 RCF 檔案。



 a| 
3.7.xx 或更高版本不符合 FIPS 標準
 a| 
使用以下方式升級新的 EFOS 映像<<方法一：升級EFOS>>。配置和許可證資訊將被保留。



 a| 
3.7.xx 或更高版本符合 FIPS 標準
 a| 
3.7.xx 或更高版本符合 FIPS 標準
 a| 
使用以下方式升級新的 EFOS 映像<<方法一：升級EFOS>>。配置和許可證資訊將被保留。



 a| 
從符合 FIPS 標準的 EFOS 版本升級到/從符合 FIPS 標準的 EFOS 版本升級的步驟
 a| 
不符合FIPS標準
 a| 
符合FIPS標準
 a| 
使用以下方式升級 EFOS 映像<<方法二：使用 ONIE OS 安裝程式升級 EFOS>>。交換器配置和許可證資訊將會遺失。



 a| 
符合FIPS標準
 a| 
不符合FIPS標準

|===
[IMPORTANT]
====
若要檢查您的 EFOS 版本是否符合 FIPS 標準，請使用以下方法： `show fips status`命令。在以下範例中，*IP_switch_a1* 使用的是符合 FIPS 標準的 EFOS，而 *IP_switch_a2* 使用的是不符合 FIPS 標準的 EFOS。

* 在交換器 IP_switch_a1（符合 FIPS 標準的 EFOS）上：
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* 在交換器 IP_switch_a2（非 FIPS 合規 EFOS）上：
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== 升級軟體

請使用以下方法之一：

* <<方法一：升級EFOS>>。適用於大多數情況（見上表）。
* <<方法二：使用 ONIE OS 安裝程式升級 EFOS>>。如果一個 EFOS 版本符合 FIPS 標準，而另一個 EFOS 版本則不符合 FIPS 標準，則可以使用此方法。



NOTE: 一次升級一台交換器上的 EFOS，以確保叢集網路持續運作。



=== 方法一：升級EFOS

請依照以下步驟升級 EFOS 軟體。


IMPORTANT: 請注意，將 BES-53248 叢集交換器從 EFOS 3.3.xx 或 3.4.xx 升級至 EFOS 3.7.0.4 或 3.8.0.2 後，交換器間連結 (ISL) 和連接埠通道將標示為 *Down* 狀態。這是預期行為，除非您在自動還原 LIF 時遇到問題，否則可以安全地繼續升級。請參閱知識庫文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248 叢集交換器 NDU 升級到 EFOS 3.7.0.4 及更高版本失敗"^]更多詳情請見下文。

.步驟
. 將 BES-53248 叢集交換器連接到管理網路。
. 使用 `ping`用於驗證與託管 EFOS、許可證和 RCF 檔案的伺服器的連接性的命令。
+
此範例驗證交換器是否已連接到 IP 位址為 172.19.2.1 的伺服器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 停用群集 LIF 的自動回滾功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 顯示活動配置和備份配置的啟動映像：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. 將鏡像檔下載到交換器。
+
將映像檔複製到備份映像意味著當您重新啟動時，該映像將建立正在執行的 EFOS 版本，從而完成更新。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 顯示活動配置和備份配置的啟動映像：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. 從備份配置啟動系統：
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. 顯示活動配置和備份配置的啟動映像：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. 將運行配置儲存到啟動配置：
+
`write memory`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. 重啟交換器：
+
`reload`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 請重新登入並驗證EFOS軟體的新版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 在交換器 cs1 上重複步驟 5 到 11。
. 啟用叢集 LIF 的自動回滾功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -vserver Cluster
----
+
更多詳情請參見link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["將 LIF 恢復到其母端口"]。





=== 方法二：使用 ONIE OS 安裝程式升級 EFOS

如果一個 EFOS 版本符合 FIPS 標準，而另一個 EFOS 版本則不符合 FIPS 標準，則可以執行下列步驟。如果交換器無法啟動，可以使用下列步驟從 ONIE 升級非 FIPS 或符合 FIPS 標準的 EFOS 3.7.xx 映像。


NOTE: 此功能僅適用於不符合 FIPS 標準的 EFOS 3.7.xx 或更高版本。


CAUTION: 如果使用 ONIE OS 安裝程式升級 EFOS，則設定將重設為原廠預設設置，許可證將被刪除。您必須設定交換器並安裝許可證和受支援的 RCF，才能使交換器恢復正常運作。

.步驟
. 停用群集 LIF 的自動回滾功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 將交換器啟動到 ONIE 安裝模式。
+
啟動過程中，看到提示時選擇 ONIE：

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
選擇 *ONIE* 後，開關會載入並向您展示幾個選項。選擇“安裝作業系統”。

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
交換器啟動進入 ONIE 安裝模式。

. 停止 ONIE 發現並設定乙太網路介面。
+
當出現以下訊息時，按 *Enter* 鍵開啟 ONIE 控制台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 偵測仍在繼續，訊息會列印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 設定乙太網路介面並新增路由 `ifconfig eth0 <ipAddress> netmask <netmask> up`和 `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 請確認託管 ONIE 安裝檔案的伺服器可以存取：
+
`ping`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安裝新的交換器軟體：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.顯示範例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
軟體安裝完成後，交換器將會重新啟動。讓交換器正常重新啟動進入新的 EFOS 版本。

. 確認新交換器軟體已安裝：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. 完成安裝。交換器重新啟動後未套用任何配置，並重設為出廠預設值。請依照以下步驟重新設定交換器：
+
.. link:configure-licenses.html["安裝許可證"]
.. link:configure-install-rcf.html["安裝 RCF"]
.. link:configure-ssh.html["啟用 SSH"]
.. link:CSHM_log_collection.html["啟用日誌收集"]
.. link:CSHM_snmpv3.html["設定 SNMPv3 進行監控"]


. 在交換器 cs1 上重複步驟 2 至 8。
. 啟用叢集 LIF 的自動回滾功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -vserver Cluster
----
+
更多詳情請參見link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["將 LIF 恢復到其母端口"]。


