---
permalink: switch-bes-53248/upgrade-rcf.html 
sidebar: sidebar 
keywords: upgrade rcf,setup rcf,rcf file 
summary: '設定 BES-53248 叢集交換器並套用任何新授權後，您可以升級參考設定檔 (RCF)。' 
---
= 升級參考設定檔（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升級 BES-53248 叢集交換器 EFOS 並套用任何新授權後，您可以升級參考設定檔 (RCF)。

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* 當前 RCF 檔案可從以下位置取得： https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["博通集群交換機"^]頁。
* RCF 中的啟動配置反映了所需的啟動映像，如果您僅安裝 EFOS 並保留目前的RCF 版本，則需要此配置。如果需要更改啟動配置以反映目前的啟動映像，則必須在重新套用 RCF 之前進行更改，以便在以後的重新啟動中實例化正確的版本。
* 從出廠預設狀態安裝 RCF 時，需要透過控制台連接到交換器。如果您已使用知識庫文章，則此要求為可選。 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除博通互連交換器上的配置"^]事先清除配置。


.建議的文檔
* 請查閱交換器相容性列表，以了解支援的ONTAP和 RCF 版本。參見 https://mysupport.netapp.com/site/info/broadcom-cluster-switch["EFOS軟體下載"^]頁。請注意，RCF 中的指令語法與 EFOS 版本中的指令語法之間可能存在指令依賴關係。
* 請參閱網站上提供的相應軟體和升級指南。 https://www.broadcom.com/support/bes-switch["博通"^]本網站提供有關 BES-53248 交換器升級和降級程序的完整文件。


.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩台 BES-53248 交換器的名稱分別是 cs1 和 cs2。
* 節點名稱為cluster1-01、cluster1-02、cluster1-03和cluster1-04。
* 群集 LIF 名稱稱為 cluster1-01_clus1、cluster1-01_clus2、cluster1-02_clus1、cluster1-02_clus2、cluster1-03_clus1、cluster1-03_clus2、cluster1-04_clus1 和 cluster1-04_clus2。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 本流程中的範例使用了四個節點。這些節點使用兩個 10GbE 叢集互連端口 `e0a`和 `e0b`。參見 https://hwu.netapp.com/Home/Index["Hardware Universe"^]驗證平台上的叢集連接埠是否正確。



NOTE: 命令輸出可能因ONTAP版本不同而有所差異。

.關於此任務
該程式需要同時使用ONTAP命令和 Broadcom 交換器命令；除非另有說明，否則使用ONTAP命令。

在此過程中不需要任何可操作的交換器間連結 (ISL)。這是設計使然，因為 RCF 版本的變更可能會暫時影響 ISL 連線。為確保叢集運作不會中斷，以下步驟會將所有叢集 LIF 遷移到運作夥伴交換機，同時在目標交換器上執行對應步驟。


CAUTION: 在安裝新的交換器軟體版本和 RCF 之前，請先閱讀知識庫文章。 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除博通互連交換器上的配置"^] 。如果必須完全清除交換器設置，則需要重新進行基本配置。您必須使用序列控制台連接到交換機，因為完全清除設定會重設管理網路的設定。



== 第一步：準備升級

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 為維護視窗的持續時間（小時）。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

+
以下命令可抑制自動建立案件兩小時：

+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=2h
----
. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
[source, cli]
----
set -privilege advanced
----
+
出現高階提示符號（*>）。

. 顯示每個節點上連接到叢集交換器的叢集連接埠：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster1-02/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster1-03/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/3               BES-53248
cluster1::*>
----
====
. 檢查每個叢集連接埠的管理和運作狀態。
+
.. 確認叢集所有連接埠均已啟動且狀態正常：
+
[source, cli]
----
network port show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.

Node: cluster1-03

   Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
.. 確認所有叢集介面（LIF）都位於主連接埠上：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            cluster1-01_clus1  up/up     169.254.3.4/23     cluster1-01  e0a     true
            cluster1-01_clus2  up/up     169.254.3.5/23     cluster1-01  e0b     true
            cluster1-02_clus1  up/up     169.254.3.8/23     cluster1-02  e0a     true
            cluster1-02_clus2  up/up     169.254.3.9/23     cluster1-02  e0b     true
            cluster1-03_clus1  up/up     169.254.1.3/23     cluster1-03  e0a     true
            cluster1-03_clus2  up/up     169.254.1.1/23     cluster1-03  e0b     true
            cluster1-04_clus1  up/up     169.254.1.6/23     cluster1-04  e0a     true
            cluster1-04_clus2  up/up     169.254.1.7/23     cluster1-04  e0b     true
----
====


. 確認集群顯示兩個集群交換器的資訊。


[role="tabbed-block"]
====
.ONTAP 9.8 及更高版本
--
從ONTAP 9.8 開始，使用以下指令：

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 及更早版本
--
對於ONTAP 9.7 及更早版本，請使用以下指令：

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step6]]停用叢集 LIF 的自動還原功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




== 步驟 2：設定埠

. 在交換器 cs2 上，確認連接到叢集中節點的連接埠清單。
+
[source, cli]
----
show isdp neighbor
----
. 在交換器 cs2 上，關閉連接到節點叢集連接埠的連接埠。例如，如果連接埠 0/1 到 0/16 連接到ONTAP節點：
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)#
----
. 驗證叢集 LIF 是否已遷移到叢集交換器 cs1 上託管的連接埠。這可能需要幾秒鐘。
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1 up/up      169.254.3.4/23     cluster1-01   e0a     true
            cluster1-01_clus2 up/up      169.254.3.5/23     cluster1-01   e0a     false
            cluster1-02_clus1 up/up      169.254.3.8/23     cluster1-02   e0a     true
            cluster1-02_clus2 up/up      169.254.3.9/23     cluster1-02   e0a     false
            cluster1-03_clus1 up/up      169.254.1.3/23     cluster1-03   e0a     true
            cluster1-03_clus2 up/up      169.254.1.1/23     cluster1-03   e0a     false
            cluster1-04_clus1 up/up      169.254.1.6/23     cluster1-04   e0a     true
            cluster1-04_clus2 up/up      169.254.1.7/23     cluster1-04   e0a     false
cluster1::*>
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. 如果您尚未儲存目前交換器配置，請將以下命令的輸出複製到日誌檔案中：
+
[source, cli]
----
show running-config
----
. 清除交換器 cs2 上的配置並執行基本設定。
+

CAUTION: 更新或套用新的 RCF 時，必須清除交換器設定並執行基本配置。必須使用串列埠控制台連接到交換器才能清除交換器設定。如果您已使用知識庫文章，則此要求為可選。 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除博通互連交換器上的配置"]事先清除配置。

+

NOTE: 清除配置不會刪除許可證。

+
.. 透過SSH連接到交換器。
+
只有當交換器連接埠上的所有叢集 LIF 都被移除，且交換器準備好清除配置時，才能繼續執行此操作。

.. 進入特權模式：
+
[listing]
----
(cs2)> enable
(cs2)#
----
.. 複製並貼上以下命令以刪除先前的 RCF 配置（根據先前使用的 RCF 版本，如果缺少特定設置，某些命令可能會出錯）：
+
[source, cli]
----
clear config interface 0/1-0/56
y
clear config interface lag 1
y
configure
deleteport 1/1 all
no policy-map CLUSTER
no policy-map WRED_25G
no policy-map WRED_100G
no policy-map InShared
no policy-map InMetroCluster
no policy-map InCluster
no policy-map InClusterRdma
no class-map CLUSTER
no class-map HA
no class-map RDMA
no class-map c5
no class-map c4
no class-map CLUSTER
no class-map CLUSTER_RDMA
no class-map StorageSrc
no class-map StorageDst
no class-map RdmaSrc
no class-map RdmaDstA
no classofservice dot1p-mapping
no random-detect queue-parms 0
no random-detect queue-parms 1
no random-detect queue-parms 2
no random-detect queue-parms 3
no random-detect queue-parms 4
no random-detect queue-parms 5
no random-detect queue-parms 6
no random-detect queue-parms 7
no cos-queue min-bandwidth
no cos-queue random-detect 0
no cos-queue random-detect 1
no cos-queue random-detect 2
no cos-queue random-detect 3
no cos-queue random-detect 4
no cos-queue random-detect 5
no cos-queue random-detect 6
no cos-queue random-detect 7
exit
vlan database
no vlan 17
no vlan 18
exit
show running-config
----
.. 將運行配置儲存到啟動配置：
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
.. 重啟交換器：
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
----
.. 使用 SSH 再次登入交換器以完成 RCF 安裝。


. 請注意以下事項：
+
.. 如果交換器上安裝了額外的連接埠許可證，則必須修改 RCF 以設定額外的許可證連接埠。看link:configure-licenses.html#activate-newly-licensed-ports["啟動新授權的端口"]了解詳情。
.. 記錄先前 RCF 中所做的任何自訂設置，並將這些設定套用到新的 RCF 中。例如，設定連接埠速度或硬編碼 FEC 模式。




[role="tabbed-block"]
====
.EFOS 版本 3.12.x 及更高版本
--
. 使用下列傳輸協定之一將 RCF 複製到交換器 cs2 的 bootflash：HTTP、HTTPS、FTP、TFTP、SFTP 或 SCP。
+
此範例展示如何使用 SFTP 將 RCF 檔案複製到交換器 cs2 的啟動快閃記憶體中：



[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/BES-53248-RCF-v1.9-Cluster-HA.txt nvram:reference-config*
Remote Password:**
Mode........................................... TFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /
Filename....................................... BES-53248_RCF_v1.9-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... reference-config.scr
Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
TFTP Code transfer starting...
File transfer operation completed successfully.
----
. 請確認腳本已下載並以您指定的檔案名稱儲存：
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
reference-config.scr                       2680         2024 05 31 21:54:22
2 configuration script(s) found.
2042 Kbytes free.
----
. 將腳本應用到交換器：
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply reference-config.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'reference-config.scr' applied.
----


--
.所有其他 EFOS 版本
--
. 使用下列傳輸協定之一將 RCF 複製到交換器 cs2 的 bootflash：HTTP、HTTPS、FTP、TFTP、SFTP 或 SCP。
+
此範例展示如何使用 SFTP 將 RCF 檔案複製到交換器 cs2 的啟動快閃記憶體中：



[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.9-Cluster-HA.txt
nvram:script BES-53248_RCF_v1.9-Cluster-HA.scr*
Remote Password:**
Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.9-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.9-Cluster-HA.scr
Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...
File transfer operation completed successfully.
----
. 請確認腳本已下載並儲存到您指定的檔案名稱：
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.9-Cluster-HA.scr          2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. 將腳本應用到交換器：
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.9-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.9-Cluster-HA.scr' applied.
----


--
====
. 步驟11：檢查橫幅輸出。 `show clibanner`命令。您必須閱讀並遵循這些說明以確保交換器的正確配置和操作。
+
`show clibanner`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show clibanner*

Banner Message configured :
=========================
BES-53248 Reference Configuration File v1.9 for Cluster/HA/RDMA

Switch   : BES-53248
Filename : BES-53248-RCF-v1.9-Cluster.txt
Date     : 10-26-2022
Version  : v1.9
Port Usage:
Ports 01 - 16: 10/25GbE Cluster Node Ports, base config
Ports 17 - 48: 10/25GbE Cluster Node Ports, with licenses
Ports 49 - 54: 40/100GbE Cluster Node Ports, with licenses, added right to left
Ports 55 - 56: 100GbE Cluster ISL Ports, base config
NOTE:
- The 48 SFP28/SFP+ ports are organized into 4-port groups in terms of port
speed:
Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44,
45-48
The port speed should be the same (10GbE or 25GbE) across all ports in a 4-port
group
- If additional licenses are purchased, follow the 'Additional Node Ports
activated with Licenses' section for instructions
- If SSH is active, it will have to be re-enabled manually after 'erase
startup-config'
command has been executed and the switch rebooted
----
====
. 在交換器上，驗證應用 RCF 後是否出現了新增的授權連接埠：
+
[source, cli]
----
show port all | exclude Detach
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ------------ ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
====
. 請在交換器上確認您的變更已生效。
+
[source, cli]
----
show running-config
----
. 儲存運作配置，以便重新啟動交換器時將其作為啟動配置：
+
`write memory`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. 重新啟動交換器並驗證運轉配置是否正確。
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
System will now restart!
----
. 在叢集交換器 cs2 上，啟動連接到節點叢集連接埠的連接埠。
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Config)# *exit*
----
. 將運行配置儲存到啟動配置：
+
`write memory`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. 請檢查交換器 cs2 上的連接埠：
+
[source, cli]
----
show interfaces status all | exclude Detach
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show interfaces status all | exclude Detach*

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. 檢查叢集上叢集連接埠的運作狀況。
+
.. 驗證叢集中所有節點的 e0b 連接埠是否已啟動且運作狀況良好：
+
[source, cli]
----
network port show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*

Node: cluster1-01
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-02

                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-03
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-04
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====
.. 從叢集驗證交換器運作狀況：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster01-2/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster01-3/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====


. 確認集群顯示兩個集群交換器的資訊。


[role="tabbed-block"]
====
.ONTAP 9.8 及更高版本
--
從ONTAP 9.8 開始，使用以下指令：

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 及更早版本
--
對於ONTAP 9.7 及更早版本，請使用以下指令：

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step21]]在交換器 cs1 上重複步驟 1 到 20。
. 啟用叢集 LIF 的自動回滾功能：
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 。確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -role Cluster
----
+
更多詳情請參見link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["將 LIF 恢復到其母端口"]。





== 步驟 3：驗證配置

. 在交換器 cs1 上，確認連接到叢集連接埠的交換器連接埠是否已啟動：
+
[source, cli]
----
show interfaces status all
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# show interfaces status all | exclude Detach

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. 驗證交換器 cs1 和 cs2 之間的 ISL 是否正常運作：
+
[source, cli]
----
show port-channel 1/1
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)
Mbr     Device/       Port      Port
Ports   Timeout       Speed     Active
------- ------------- --------- -------
0/55    actor/long    Auto      True
        partner/long
0/56    actor/long    Auto      True
        partner/long
----
====
. 確認叢集 LIF 已恢復到其原始連接埠：
+
[source, cli]
----
network interface show -role cluster
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network interface show -role cluster
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0a     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0b     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0a     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0b     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0a     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0a     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster01-02_clus1  none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster01-02_clus2  none

cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-02_clus2   none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e0a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e0b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e0a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e0b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e0a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0b
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e0a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0b
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8
169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
  Local 169.254.1.3 to Remote 169.254.1.6
  Local 169.254.1.3 to Remote 169.254.1.7
  Local 169.254.1.3 to Remote 169.254.3.4
  Local 169.254.1.3 to Remote 169.254.3.5
  Local 169.254.1.3 to Remote 169.254.3.8
  Local 169.254.1.3 to Remote 169.254.3.9
  Local 169.254.1.1 to Remote 169.254.1.6
  Local 169.254.1.1 to Remote 169.254.1.7
  Local 169.254.1.1 to Remote 169.254.3.4
  Local 169.254.1.1 to Remote 169.254.3.5
  Local 169.254.1.1 to Remote 169.254.3.8
  Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
--
====
. 將權限等級改回管理員：
+
[source, cli]
----
set -privilege admin
----
. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=END
----

