---
permalink: switch-cisco-3132q-v/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html 
sidebar: sidebar 
keywords: replace, cisco nexus 5596 cluster switch, 3132q-v 
summary: 當您將Cisco Nexus 5596叢集交換器更換為Cisco Nexus 3132Q-V叢集交換器時、必須注意特定的組態資訊、連接埠連線和纜線需求。 
---
= 將Cisco Nexus 5596叢集交換器更換為Cisco Nexus 3132Q-V叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您將Cisco Nexus 5596叢集交換器更換為Cisco Nexus 3132Q-V叢集交換器時、必須注意特定的組態資訊、連接埠連線和纜線需求。

* 支援下列叢集交換器：
+
** Nexus 5596
** Nexus 3132Q-V


* 10 GbE和40/100 GbE連接埠的數量是在上可用的參考組態檔（RCFs）中定義 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco®叢集網路交換器參考組態檔案下載"^] 頁面。
* 叢集交換器使用下列連接埠來連線至節點：
+
** 連接埠E1/1-40（10 GbE）：Nexus 5596
** 連接埠E1/1-30（40/100 GbE）：Nexus 3132Q-V


* 叢集交換器使用下列交換器間連結（ISL）連接埠：
+
** 連接埠E1/41至48（10 GbE）：Nexus 5596
** 連接埠E1/31-32（40/100 GbE）：Nexus 3132Q-V


* 。 link:https://hwu.netapp.com/["Hardware Universe"^] 包含有關支援的Nexus 3132Q-V交換器纜線連接資訊：
+
** 具有10 GbE叢集連線的節點需要QSFP至SFP+光纖中斷纜線、或QSFP至SFP+銅線中斷纜線。
** 具有40/100 GbE叢集連線的節點、需要使用光纖纜線或QSFP/QSFP28銅線直接連接纜線來支援QSFP/QSFP28光纖模組。


* 叢集交換器使用適當的ISL纜線：
+
** 開始：Nexus 5596至Nexus 5596（SFP+至SFP+）
+
*** 8條SFP+光纖或銅線直接連接纜線


** 過渡：Nexus 5596至Nexus 3132Q-V（QSFP至4xSFP+中斷）
+
*** 1條QSFP至SFP+光纖中斷或銅線中斷纜線


** 最終版本：Nexus 3132Q-V至Nexus 3132Q-V（QSFP28至QSFP28）
+
*** 2條QSFP28光纖或銅線直接連接纜線




* 在Nexus 3132Q-V交換器上、您可以將QSFP/QSFP28連接埠作為40/100 Gigabit乙太網路或4 x 10 Gigabit乙太網路模式來操作。
+
依預設、40/100 Gigabit乙太網路模式有32個連接埠。這40個Gigabit乙太網路連接埠均以2元組命名慣例編號。例如、第二個40 Gigabit乙太網路連接埠編號為1/2。將組態從40 Gigabit乙太網路變更為10 Gigabit乙太網路的過程稱為_中斷_、將組態從10 Gigabit乙太網路變更為40 Gigabit乙太網路的過程稱為_breakin _。當您將40/100 Gigabit乙太網路連接埠分成10 Gigabit乙太網路連接埠時、所產生的連接埠會使用3元命名慣例進行編號。例如、第二個40 Gigabit乙太網路連接埠的中斷連接埠編號為1/2/1、1/2/2、1/2/3和1/2/4。

* Nexus 3132Q-V交換器左側是一組4個SFP+連接埠、可多工複用至該QSFP28連接埠。
+
根據預設、RCF結構化為使用QSFP28連接埠。

+

NOTE: 您可以使用「硬體設定檔前端連接埠模式SFP-PLUS」命令、讓4個SFP+連接埠變成作用中狀態、而非Nexus 3132Q-V交換器的QSFP連接埠。同樣地、您也可以使用「硬體設定檔前端連接埠模式qsfp'命令、將Nexus 3138S-V交換器重設為使用QSFP連接埠、而非4個SFP+連接埠。

* 您已將Nexus 3132Q-V交換器上的部分連接埠設定為以10 GbE或40/100 GbE執行。
+

NOTE: 您可以使用「介面中斷模組1連接埠1-6 MAP 10ge-4x」命令、將前六個連接埠分割成4x10 GbE模式。同樣地、您也可以使用「無介面中斷模組1連接埠1-6 MAP 10g-4x」命令、從中斷組態重新分組前六個QSFP+連接埠。

* 您已完成規劃、移轉、並閱讀10 GbE和40/100 GbE連線的必要文件、從節點連接至Nexus 3132Q-V叢集交換器。
* 本程序所支援的支援的支援版本包括ONTAP link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco乙太網路交換器"^] 頁面。

