---
permalink: switch-cisco-3132q-v/install-rcf-3132q-v.html 
sidebar: sidebar 
keywords: install rcf 
summary: 首次設定 Nexus 3132Q-V 交換器後，您可以安裝 RCF。您也可以使用此程序升級您的 RCF 版本。 
---
= 安裝或升級參考設定檔 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次設定 Nexus 3132Q-V 交換器後，請依照下列步驟安裝 RCF。您也可以使用此程序升級您的 RCF 版本。



== 審查要求

.開始之前
* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* 目前參考設定檔（RCF）。
* 安裝 RCF 時需要將控制台連接到交換器。如果您已使用知識庫文章，則此要求為可選。 https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除Cisco互連交換器上的配置"^]事先清除配置。
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]。請查閱交換器相容性列表，以了解支援的ONTAP和 RCF 版本。請注意，RCF 中的命令語法與 NX-OS 版本中的命令語法之間可能存在命令依賴關係。
* https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["CiscoNexus 3000 系列交換機"^]。有關Cisco交換器升級和降級程序的完整文檔，請參閱Cisco網站上提供的相應軟體和升級指南。




== 安裝檔案

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩台Cisco交換器的名稱是： `cs1`和 `cs2`。
* 節點名稱是 `cluster1-01`， `cluster1-02` ， `cluster1-03` ， 和 `cluster1-04`。
* 集群 LIF 名稱為 `cluster1-01_clus1`， `cluster1-01_clus2` ， `cluster1-02_clus1` ， `cluster1-02_clus2` ， `cluster1-03_clus1` ， `cluster1-03_clus2` ， `cluster1-04_clus1` ， 和 `cluster1-04_clus2`。
* 這 `cluster1::*>`prompt 指示叢集名稱。


.關於此任務
流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

在此過程中不需要任何可操作的交換器間連結 (ISL)。這是設計使然，因為 RCF 版本的變更可能會暫時影響 ISL 連線。為確保叢集運作不會中斷，以下步驟將所有叢集 LIF 遷移到運作夥伴交換機，同時在目標交換器上執行對應步驟。

務必完成以下步驟link:prepare-install-cisco-nexus-3132q.html["準備安裝 NX-OS 軟體和參考設定文件"]然後按照以下步驟操作。



=== 步驟 1：檢查連接埠狀態

. 顯示每個節點上連接到叢集交換器的叢集連接埠：
+
`network device-discovery show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ------------
cluster1-01/cdp
            e0a    cs1                       Ethernet1/7       N3K-C3132Q-V
            e0d    cs2                       Ethernet1/7       N3K-C3132Q-V
cluster1-02/cdp
            e0a    cs1                       Ethernet1/8       N3K-C3132Q-V
            e0d    cs2                       Ethernet1/8       N3K-C3132Q-V
cluster1-03/cdp
            e0a    cs1                       Ethernet1/1/1     N3K-C3132Q-V
            e0b    cs2                       Ethernet1/1/1     N3K-C3132Q-V
cluster1-04/cdp
            e0a    cs1                       Ethernet1/1/2     N3K-C3132Q-V
            e0b    cs2                       Ethernet1/1/2     N3K-C3132Q-V
cluster1::*>
----
====
. 檢查每個叢集連接埠的管理和運作狀態。
+
.. 確認叢集所有連接埠均已啟動且狀態正常：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.

Node: cluster1-03

   Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
.. 確認所有叢集介面（LIF）都位於主連接埠上：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            cluster1-01_clus1  up/up     169.254.3.4/23     cluster1-01  e0a     true
            cluster1-01_clus2  up/up     169.254.3.5/23     cluster1-01  e0d     true
            cluster1-02_clus1  up/up     169.254.3.8/23     cluster1-02  e0a     true
            cluster1-02_clus2  up/up     169.254.3.9/23     cluster1-02  e0d     true
            cluster1-03_clus1  up/up     169.254.1.3/23     cluster1-03  e0a     true
            cluster1-03_clus2  up/up     169.254.1.1/23     cluster1-03  e0b     true
            cluster1-04_clus1  up/up     169.254.1.6/23     cluster1-04  e0a     true
            cluster1-04_clus2  up/up     169.254.1.7/23     cluster1-04  e0b     true
cluster1::*>
----
====
.. 確認集群顯示兩個集群交換器的資訊：
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.0.0.1         NX3132QV
     Serial Number: FOXXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

cs2                         cluster-network    10.0.0.2         NX3132QV
     Serial Number: FOXXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
----
====


+

NOTE: 對於ONTAP 9.8 及更高版本，請使用以下指令 `system switch ethernet show -is-monitoring-enabled-operational true`。

. 停用群集 LIF 的自動回滾功能。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
+
執行此命令後，請確保已停用自動還原功能。

. 在叢集交換器 cs2 上，關閉連接到節點叢集連接埠的連接埠。
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface eth1/1/1-2,eth1/7-8*
cs2(config-if-range)# *shutdown*
cs2(config-if-range)# *exit*
cs2# *exit*
----
+

NOTE: 顯示的連接埠數量取決於叢集中的節點數量。

. 確認叢集連接埠已遷移到叢集交換器 cs1 上託管的連接埠。這可能需要幾秒鐘。
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1 up/up      169.254.3.4/23     cluster1-01   e0a     true
            cluster1-01_clus2 up/up      169.254.3.5/23     cluster1-01   e0a     false
            cluster1-02_clus1 up/up      169.254.3.8/23     cluster1-02   e0a     true
            cluster1-02_clus2 up/up      169.254.3.9/23     cluster1-02   e0a     false
            cluster1-03_clus1 up/up      169.254.1.3/23     cluster1-03   e0a     true
            cluster1-03_clus2 up/up      169.254.1.1/23     cluster1-03   e0a     false
            cluster1-04_clus1 up/up      169.254.1.6/23     cluster1-04   e0a     true
            cluster1-04_clus2 up/up      169.254.1.7/23     cluster1-04   e0a     false
cluster1::*>
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
cluster1::*>
----
====




=== 步驟 2：配置並驗證設定

. 如果您尚未儲存目前交換器配置，請將以下命令的輸出複製到文字檔案中：
+
`show running-config`

. 記錄目前運行配置和正在使用的 RCF 檔案之間的任何自訂新增。
. 儲存基本配置詳細信息 `write_erase.cfg`啟動閃存上的檔案。
+

NOTE: 升級或套用新的 RCF 時，必須清除交換器設定並執行基本配置。您必須連接到交換器序列控制台連接埠才能重新設定交換器。

+
`cs2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`cs2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`cs2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

. 對於 RCF 版本 1.12 及更高版本，請執行以下命令：
+
`cs2# echo "hardware access-list tcam region vpc-convergence 256" >> bootflash:write_erase.cfg`

+
`cs2# echo "hardware access-list tcam region racl 256" >> bootflash:write_erase.cfg`

+
`cs2# echo "hardware access-list tcam region e-racl 256" >> bootflash:write_erase.cfg`

+
`cs2# echo "hardware access-list tcam region qos 256" >> bootflash:write_erase.cfg`

+
請參閱知識庫文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除Cisco互連交換器上的配置"^]更多詳情請見下文。

. 確認 `write_erase.cfg`文件已如預期填入：
+
`show file bootflash:write_erase.cfg`

. 問題 `write erase`清除目前已儲存配置的命令：
+
`cs2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 將先前儲存的基本配置複製到啟動配置中。
+
`cs2# *copy bootflash:write_erase.cfg startup-config*`

. 重啟交換器：
+
`cs2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 使用下列傳輸協定之一將 RCF 複製到交換器 cs2 的 bootflash：FTP、TFTP、SFTP 或 SCP。有關Cisco命令的更多信息，請參閱相應的指南。link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^]指南。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_3132QV_RCF_v1.6-Cluster-HA-Breakout.txt*
Enter hostname for the tftp server: 172.22.201.50
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 將先前下載的 RCF 檔案套用到啟動快閃記憶體。
+
有關Cisco命令的更多信息，請參閱相應的指南。link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^]指南。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *copy Nexus_3132QV_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands*
----
====
. 檢查橫幅輸出 `show banner motd`命令。您必須閱讀並遵循「重要提示」下的說明，以確保交換器的正確配置和運作。
+
.顯示範例
[%collapsible]
====
[listing]
----
cs2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3132Q-V
* Filename : Nexus_3132QV_RCF_v1.6-Cluster-HA-Breakout.txt
* Date     : Nov-02-2020
* Version  : v1.6
*
* Port Usage : Breakout configuration
* Ports  1- 6: Breakout mode (4x10GbE) Intra-Cluster Ports, int e1/1/1-4,
* e1/2/1-4, e1/3/1-4,int e1/4/1-4, e1/5/1-4, e1/6/1-4
* Ports  7-30: 40GbE Intra-Cluster/HA Ports, int e1/7-30
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* - Load Nexus_3132QV_RCF_v1.6-Cluster-HA.txt for non breakout config
*
* - This RCF utilizes QoS and requires specific TCAM configuration, requiring
*   cluster switch to be rebooted before the cluster becomes operational.
*
* - Perform the following steps to ensure proper RCF installation:
*
*   (1) Apply RCF, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*
*   (4) Save running-configuration again
*
* - If running NX-OS versions 9.3(5) 9.3(6), 9.3(7), or 9.3(8)
*    - Downgrade the NX-OS firmware to version 9.3(5) or earlier if
*      NX-OS using a version later than 9.3(5).
*    - Do not upgrade NX-OS prior to applying v1.9 RCF file.
*    - After the RCF is applied and switch rebooted, then proceed to upgrade
*      NX-OS to version 9.3(5) or later.
*
* - If running 9.3(9) 10.2(2) or later the RCF can be applied to the switch
*      after the upgrade.
*
* - Port 1 multiplexed H/W configuration options:
*     hardware profile front portmode qsfp      (40G H/W port 1/1 is active - default)
*     hardware profile front portmode sfp-plus  (10G H/W ports 1/1/1 - 1/1/4 are active)
*     hardware profile front portmode qsfp      (To reset to QSFP)
*
******************************************************************************
----
====
. 請確認 RCF 檔案是否為最新版本：
+
`show running-config`

+
檢查輸出結果以驗證是否擁有正確的 RCF 時，請確保以下資訊正確：

+
** RCF橫幅
** 節點和連接埠設置
** 客製化
+
輸出結果會根據您的網站配置而有所不同。檢查連接埠設置，並參考發行說明，以了解您安裝的 RCF 版本是否有任何特定變更。

+

NOTE: 有關 RCF 升級後如何將 10GbE 連接埠上線的步驟，請參閱知識庫文章。 https://kb.netapp.com/onprem%2FSwitches%2FCisco%2F10GbE_ports_on_Cisco_3132Q_cluster_switch_do_not_come_online["Cisco 3132Q 叢集交換器上的 10GbE 連接埠無法連線"^] 。



. 確認 RCF 版本和交換器設定正確後，將運行設定檔複製到啟動設定檔。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^]指南。

+
.顯示範例
[%collapsible]
====
[listing]
----
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
====
. 重啟交換器cs2。您可以忽略交換器重新啟動期間節點上報告的「叢集連接埠關閉」事件和錯誤。 `% Invalid command at '^' marker`輸出。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
====
. 應用相同的 RCF 並再次儲存運行配置。這是必要的，因為 RCF 利用 QoS，需要重新配置 TCAM，這涉及到對 RCF 進行兩次加載，中間需要重新啟動交換器。
+
.顯示範例
[%collapsible]
====
[listing]
----
cs2# copy Nexus_3132QV_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
====
. 將先前對交換器配置所做的任何自訂設定重新套用。請參閱link:cabling-considerations-3132q-v.html["審查佈線和配置注意事項"]有關任何後續變更的詳細資訊。
. 檢查叢集上叢集連接埠的運作狀況。
+
.. 確認叢集中所有節點的叢集連接埠均已啟動且運作狀況良好：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====
.. 從叢集中驗證交換器的運作狀況。
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e0a    cs1                       Ethernet1/7       N3K-C3132Q-V
            e0d    cs2                       Ethernet1/7       N3K-C3132Q-V
cluster01-2/cdp
            e0a    cs1                       Ethernet1/8       N3K-C3132Q-V
            e0d    cs2                       Ethernet1/8       N3K-C3132Q-V
cluster01-3/cdp
            e0a    cs1                       Ethernet1/1/1     N3K-C3132Q-V
            e0b    cs2                       Ethernet1/1/1     N3K-C3132Q-V
cluster1-04/cdp
            e0a    cs1                       Ethernet1/1/2     N3K-C3132Q-V
            e0b    cs2                       Ethernet1/1/2     N3K-C3132Q-V

cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1                         cluster-network    10.233.205.90    N3K-C3132Q-V
     Serial Number: FOXXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

cs2                         cluster-network    10.233.205.91    N3K-C3132Q-V
     Serial Number: FOXXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
----
====
+

NOTE: 對於ONTAP 9.8 及更高版本，請使用以下指令 `system switch ethernet show -is-monitoring-enabled-operational true`。

+
[NOTE]
====
根據交換器上先前載入的 RCF 版本，您可能會在 cs1 交換器控制台上看到以下輸出：

[source]
----
2020 Nov 17 16:07:18 cs1 %$ VDC-1 %$ %STP-2-UNBLOCK_CONSIST_PORT: Unblocking port port-channel1 on VLAN0092. Port consistency restored.
2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_PEER: Blocking port-channel1 on VLAN0001. Inconsistent peer vlan.
2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_LOCAL: Blocking port-channel1 on VLAN0092. Inconsistent local vlan.
----
====
+

NOTE: 叢集節點最多可能需要 5 分鐘才能報告為健康狀態。



. 在叢集交換器 cs1 上，關閉連接到節點叢集連接埠的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1> *enable*
cs1# *configure*
cs1(config)# *interface eth1/1/1-2,eth1/7-8*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1# *exit*
----
====
+

NOTE: 顯示的連接埠數量取決於叢集中的節點數量。

. 確認叢集 LIF 已遷移到交換器 cs2 上託管的連接埠。這可能需要幾秒鐘。
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0d     false
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0d     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0d     false
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0d     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0b     false
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0b     false
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
cluster1::*>
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health   Eligibility   Epsilon
-------------------- -------- ------------- -------
cluster1-01          true     true          false
cluster1-02          true     true          false
cluster1-03          true     true          true
cluster1-04          true     true          false
4 entries were displayed.
cluster1::*>
----
====
. 在交換器 cs1 上重複步驟 1 至 17。
. 啟用叢集 LIF 的自動回滾功能。
+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert True
----
====
. 重啟交換器cs1。這樣做是為了觸發叢集 LIF 恢復到它們的來源連接埠。交換器重新啟動期間，您可以忽略節點上報告的「叢集連接埠關閉」事件。
+
[listing, subs="+quotes"]
----
cs1# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----




=== 步驟 3：驗證配置

. 確認連接到叢集連接埠的交換器連接埠已開啟。
+
`show interface brief | grep up`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/1/1      1       eth  access up      none                    10G(D) --
Eth1/1/2      1       eth  access up      none                    10G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
====
. 驗證 cs1 和 cs2 之間的 ISL 連線是否正常：
+
`show port-channel summary`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
cs1#
----
====
. 確認叢集 LIF 已恢復到其原始連接埠：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0d     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0d     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0d     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0d     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0b     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0b     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
cluster1::*>
----
====
. 驗證叢集是否運作正常：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
cluster1::*>
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*在執行 show 命令顯示詳細資訊之前，請等待幾秒鐘。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -----------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster1-02_clus2   none

cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-01_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-01_clus2   none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
.下一步是什麼？
link:configure-ssh-keys.html["驗證 SSH 配置"]。
