---
permalink: switch-cisco-3132q-v/migrate-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: 您可以在 AFF 或 FAS 叢集中使用 Cisco Nexus 3132q-v 交換器作為叢集交換器。 
---
= 設定連接埠，以便從無交換器叢集移轉至交換式叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟設定連接埠，以便從雙節點無交換器叢集移轉至雙節點交換式叢集。

.步驟
. 在Nexus 3132Q-V交換器C1和C2上、停用所有面向節點的連接埠C1和C2、但不要停用ISL連接埠。
+
.顯示範例
[%collapsible]
====
下列範例顯示使用RCF支援的組態、在Nexus 3132Q-V叢集交換器C1和C2上停用連接埠1到30 `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 使用支援的纜線、將C1上的連接埠1/31和1/32連接至C2上的相同連接埠。
. 確認ISL連接埠在C1和C2上正常運作：
+
「How port-channel Summary」

+
.顯示範例
[%collapsible]
====
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 顯示交換器上的鄰近裝置清單：
+
「How cup neighbor」

+
.顯示範例
[%collapsible]
====
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
====
. 顯示每個節點上的叢集連接埠連線能力：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
下列範例顯示雙節點無交換器叢集組態。

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. 將clus1介面移轉至裝載clus2的實體連接埠：
+
網路介面移轉

+
從每個本機節點執行此命令。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e
----
====
. 驗證叢集介面移轉：
+
「網路介面展示」

+
.顯示範例
[%collapsible]
====
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 關閉兩個節點上的叢集連接埠clus1 LIF：
+
網路連接埠修改

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. 驗證遠端叢集介面的連線能力：


[role="tabbed-block"]
====
.更新版本ONTAP
--
您可以使用 `network interface check cluster-connectivity` 命令以啟動叢集連線的存取檢查、然後顯示詳細資料：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 注意： * 在執行 show 命令之前、請等待數秒以顯示詳細資料。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.所有 ONTAP 版本
--
對於所有 ONTAP 版本、您也可以使用 `cluster ping-cluster -node <name>` 檢查連線能力的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step10]] 從節點 n1 上的 E4A 拔下纜線。
+
您可以參考執行中的組態、並使用Nexus 3132Q-V上支援的纜線、將交換器C1（本範例中為連接埠1/7）上的前40 GbE連接埠連接至n1上的E4A

+

NOTE: 將任何纜線重新連接至新的Cisco叢集交換器時、所使用的纜線必須是Cisco支援的光纖或纜線。

. 從節點n2上的E4A拔下纜線。
+
您可以參考執行中的組態、並使用支援的纜線、將E4A連接至C1連接埠1/8上的下一個可用40 GbE連接埠。

. 啟用C1上的所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
下列範例顯示使用RCF支援的組態、在Nexus 3132Q-V叢集交換器C1和C2上啟用連接埠1到30 `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. 在每個節點上啟用第一個叢集連接埠E4A：
+
網路連接埠修改

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. 驗證兩個節點上的叢集是否均已啟動：
+
「網路連接埠展示」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
. 針對每個節點、還原所有移轉的叢集互連生命生命、如下所示：
+
網路介面回復

+
.顯示範例
[%collapsible]
====
以下範例顯示移轉的LIF正還原至其主連接埠。

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
====
. 確認所有的叢集互連連接埠現在都已還原至其主連接埠：
+
「網路介面展示」

+
對於「目前連接埠」欄中所列的所有連接埠、「is Home」欄位應顯示「true」。如果顯示的值為「假」、表示連接埠尚未還原。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 顯示每個節點上的叢集連接埠連線能力：
+
「網路裝置探索秀」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
====
. 在每個節點的主控台上、將clus2移轉至連接埠E4A：
+
網路介面移轉

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a
----
====
. 關閉兩個節點上的叢集連接埠clus2 LIF：
+
網路連接埠修改

+
以下範例顯示兩個節點上要關閉的指定連接埠：

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. 驗證叢集LIF狀態：
+
「網路介面展示」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 從節點n1上的e4e拔下纜線。
+
您可以參考執行中的組態、並使用Nexus 3132Q-V上支援的纜線、將交換器C2上的前40 GbE連接埠（本範例中為連接埠1/7）連接至n1上的e4e

. 從節點n2上的e4e拔下纜線。
+
您可以參考執行中的組態、並使用支援的纜線、將e4e連接至C2連接埠1/8上的下一個可用40 GbE連接埠。

. 在C2上啟用所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
下列範例顯示使用RCF支援的組態、在Nexus 3132Q-V叢集交換器C1和C2上啟用連接埠1到30 `NX3132_RCF_v1.1_24p10g_26p40g.txt`：

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 在每個節點上啟用第二個叢集連接埠e4e：
+
網路連接埠修改

+
下列範例顯示正在啟動的指定連接埠：

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 針對每個節點、還原所有移轉的叢集互連生命生命、如下所示：
+
網路介面回復

+
以下範例顯示移轉的LIF正還原至其主連接埠。

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. 確認所有的叢集互連連接埠現在都已還原至其主連接埠：
+
「網路介面展示」

+
對於「目前連接埠」欄中所列的所有連接埠、「is Home」欄位應顯示「true」。如果顯示的值為「假」、表示連接埠尚未還原。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 驗證所有的叢集互連連接埠是否都處於「up」狀態。
+
「網路連接埠show -role cluster」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====


.接下來呢？
link:migrate-switchless-complete-migration.html["完成移轉"]。
