---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: 在設定 Cisco Nexus 3132Q-V 交換器之前，請先審查流程總覽和命名慣例。 
---
= 移轉需求
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
如果您有雙節點無交換器式叢集，請審查此程序，以了解移轉至雙節點交換器式叢集的適用要求。

[NOTE]
====
流程需要同時使用 ONTAP 命令和 Cisco Nexus 3000 系列交換器命令；除非另有說明，否則使用 ONTAP 命令。

====
如需更多資訊，請參閱

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 乙太網路交換器"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.連接埠和節點連接
當您移轉到使用 Cisco Nexus 3132Q-V 叢集交換器的雙節點交換叢集時，請務必了解連接埠和節點連線以及佈線需求。

* 叢集交換器使用交換器間連結 (ISL) 連接埠 e1/31-32。
* link:https://hwu.netapp.com/["Hardware Universe"^]包含有關 Nexus 3132Q-V 交換器支援佈線的資訊：
+
** 具有 10 GbE 叢集連接的節點需要 QSFP 光模組搭配分支光纖纜線，或 QSFP 轉 SFP+ 銅分支纜線。
** 具有 40 GbE 叢集連接的節點需要支援的 QSFP/QSFP28 光模組搭配光纖纜線，或 QSFP/QSFP28 銅直連線。
** 叢集交換器使用適當的 ISL 佈線：2x QSFP28 光纖或銅直連接纜線。


* 在 Nexus 3132Q-V 上，您可以將 QSFP 連接埠用作 40 Gb 乙太網路或 4x10 Gb 乙太網路模式。
+
預設情況下，40 Gb 乙太網路模式下有 32 個連接埠。這些 40 Gb 乙太網路連接埠採用二元組命名慣例進行編號。例如，第二個 40 Gb 乙太網路連接埠的編號為 1/2。將組態從 40 Gb 乙太網路改為 10 Gb 乙太網路的過程稱為 _breakout_，將組態從 10 Gb 乙太網路改為 40 Gb 乙太網路的過程稱為 _breakin_。當您將一個 40 Gb 乙太網路連接埠分線為 10 Gb 乙太網路連接埠時，分線後的連接埠會採用三元組命名慣例進行編號。例如，第二個 40 Gb 乙太網路連接埠分線後的連接埠編號為 1/2/1、1/2/2、1/2/3 和 1/2/4。

* Nexus 3132Q-V 的左側有一組四個 SFP+ 連接埠，多工傳輸至第一個 QSFP 連接埠。
+
預設情況下，RCF 結構為使用第一個 QSFP 連接埠。

+
您可以使用 `hardware profile front portmode sfp-plus`命令，將 Nexus 3132Q-V 的四個 SFP+ 連接埠設定為作用中狀態，而非使用 QSFP 連接埠。同樣地，您可以使用 `hardware profile front portmode qsfp`命令，將 Nexus 3132Q-V 重設為使用 QSFP 連接埠，而非使用四個 SFP+ 連接埠。

* 請確保已將 Nexus 3132Q-V 上的某些連接埠設定為以 10 GbE 或 40 GbE 運作。
+
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x`命令將前六個連接埠拆分為 4x10 GbE 模式。同樣，您可以使用 `no interface breakout module 1 port 1-6 map 10g-4x`命令將前六個 QSFP+ 連接埠從拆分組態中重新組合。

* 10 GbE 和 40 GbE 連接埠的數量在參考組態檔 (RCF) 中定義，可在 link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 叢集網路交換器參考組態檔下載"^] 取得。


.開始之前
* 組態已正確設定並正常運作。
* 執行 ONTAP 9.4 或更新版本的節點。
* 所有叢集連接埠均處於 `up`狀態。
* 支援 Cisco Nexus 3132Q-V 叢集交換器。
* 現有叢集網路組態具有：
+
** Nexus 3132 叢集基礎架構在兩台交換器上均具備援功能且運作正常。
** 交換器上已安裝最新的 RCF 和 NX-OS 版本。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 包含有關此程序中支援的 ONTAP 和 NX-OS 版本的資訊。

** 兩台交換器均具備管理連線功能。
** 可透過控制台存取兩台交換器。
** 所有叢集邏輯介面（LIF）處於 `up`狀態，且未移轉。
** 交換器的初始自訂。
** 所有 ISL 連接埠均已啟用並連接線纜。




此外，您還必須規劃、移轉並讀取有關從節點到 Nexus 3132Q-V 叢集交換器的 10 GbE 和 40 GbE 連線的必要文件。

.關於所使用的範例
本流程中的範例使用以下開關和節點命名規則：

* Nexus 3132Q-V 叢集交換器，C1 和 C2。
* 節點分別為 n1 和 n2。


[NOTE]
====
本流程中的範例使用兩個節點，每個節點使用兩個 40 GbE 叢集互連埠 *e4a* 和 *e4e*。其中link:https://hwu.netapp.com/["Hardware Universe"^]包含有關您平台上叢集連接埠的詳細資訊。

====
本流程涵蓋以下幾種情況：

* *n1_clus1* 是連接到叢集交換器 C1 的節點 *n1* 的第一個叢集邏輯介面（LIF）。
* *n1_clus2* 是第一個連接到節點 *n1* 的叢集交換器 C2 的叢集 LIF。
* *n2_clus1* 是第一個連接到叢集交換器 C1 的叢集 LIF，用於節點 *n2*。
* *n2_clus2* 是第二個要連接到叢集交換器 C2 的叢集 LIF，用於節點 *n2*。
* 10 GbE 和 40 GbE 連接埠的數量在參考組態檔 (RCF) 中定義，可在 link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 叢集網路交換器參考組態檔下載"^] 取得。


[NOTE]
====
流程需要同時使用 ONTAP 命令和 Cisco Nexus 3000 系列交換器命令；除非另有說明，否則使用 ONTAP 命令。

====
* 叢集由兩個連接並運作的節點組成，採用雙節點無交換器式叢集設定。
* 第一個叢集連接埠移至 C1。
* 第二個叢集連接埠已移至 C2。
* 雙節點無交換器式叢集選項已停用。


.下一步是什麼？
在您審查移轉需求後，您可以link:migrate-switchless-prepare-to-migrate.html["準備移轉交換器"]。
