---
permalink: switch-cisco-3132q-v/migrate-switchless-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: 準備從雙節點無交換器式叢集移轉至 Cisco Nexus 3132Q-V 叢集交換器。 
---
= 準備從無交換器式叢集移轉到 Cisco Nexus 3132Q-V 叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
準備好將您的雙節點無交換器式叢集移轉到使用 Cisco Nexus 3132Q-V 叢集交換器的交換式叢集。

.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 確定每個叢集介面的管理或運作狀態：
+
.. 顯示網路連接埠屬性：
+
`network port show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
.. 顯示邏輯介面資訊：
+
`network interface show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====


. 確認已根據您的要求在新 3132Q-V 交換器上安裝了相應的 RCF 和映像，並進行任何必要的站台自訂，例如使用者和密碼、網路位址等。
+
此時您必須準備好兩台交換器。如果需要升級 RCF 和映像軟體，請依照以下步驟操作：

+
.. 請前往 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 造訪 NetApp 支援網站。
.. 請記下您交換器的型號以及該頁表格中所需的軟體版本。
.. 下載適當版本的 RCF。
.. 在 *Description* 頁面上選擇 *CONTINUE*，接受授權合約，然後依照 *Download* 頁面上的說明下載 RCF。
.. 下載對應版本的映像軟體。


. 在 *Description* 頁面上選擇 *CONTINUE*，接受授權合約，然後依照 *Download* 頁面上的說明下載 RCF。


.下一步是什麼？
準備好移轉交換器後，您可以link:migrate-switchless-configure-ports.html["設定您的連接埠"]。
