---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: 更換Cisco Nexus 3132Q-V 叢集交換器時，您必須了解某些設定資訊、連接埠連線和佈線需求。 
---
= 更換Cisco Nexus 3132Q-V 群集交換器的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更換叢集交換器時，請務必了解設定需求、連接埠連接和佈線要求。



== Cisco Nexus 3132Q-V 要求

* 支援Cisco Nexus 3132Q-V 集群交換器。
* 10 GbE 和 40 GbE 連接埠的數量在參考設定檔 (RCF) 中定義，這些檔案可在以下位置取得：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集網路交換器參考設定檔下載"^] 。
* 叢集交換器使用交換器間連結 (ISL) 連接埠 e1/31-32。
* 這link:https://hwu.netapp.com["Hardware Universe"^]包含有關 Nexus 3132Q-V 交換器支援的佈線資訊：
+
** 具有 10 GbE 叢集連接的節點需要 QSFP 光模組和分支光纖纜線或 QSFP 轉 SFP+ 銅纜分支纜線。
** 具有 40 GbE 叢集連接的節點需要支援 QSFP/QSFP28 光模組，並配備光纖電纜或 QSFP/QSFP28 銅纜直連接纜線。
** 叢集交換器使用適當的 ISL 佈線：2x QSFP28 光纖或銅纜直連接纜線。


* 在 Nexus 3132Q-V 上，您可以將 QSFP 連接埠用作 40 Gb 乙太網路或 4x10 Gb 乙太網路模式。
+
預設情況下，40Gb乙太網路模式下有32個連接埠。這些 40 Gb 乙太網路連接埠採用二元組命名規則進行編號。例如，第二個 40 Gb 乙太網路連接埠編號為 1/2。將配置從 40 Gb 乙太網路變更為 10 Gb 乙太網路的過程稱為 _breakout_，將設定從 10 Gb 乙太網路變更為 40 Gb 乙太網路的過程稱為 _breakin_。當您將 40 Gb 乙太網路連接埠分割為 10 Gb 乙太網路連接埠時，產生的連接埠將使用三元組命名約定進行編號。例如，第二個 40 Gb 乙太網路連接埠的分線連接埠編號為 1/2/1、1/2/2、1/2/3 和 1/2/4。

* Nexus 3132Q-V 的左側有一組四個 SFP+ 端口，重複使用到第一個 QSFP 連接埠。
+
預設情況下，RCF 結構為使用第一個 QSFP 連接埠。

+
您可以使用以下方法將 Nexus 3132Q-V 的四個 SFP+ 連接埠設定為活動狀態，而不是一個 QSFP 連接埠： `hardware profile front portmode sfp-plus`命令。同樣，您可以使用以下方法將 Nexus 3132Q-V 重設為使用 QSFP 連接埠而不是四個 SFP+ 連接埠： `hardware profile front portmode qsfp`命令。

* 您必須將 Nexus 3132Q-V 上的某些連接埠配置為以 10 GbE 或 40 GbE 運作。
+
您可以使用下列方法將前六個連接埠分接成 4x10 GbE 模式： `interface breakout module 1 port 1-6 map 10g-4x`命令。同樣，您可以使用下列方法將前六個 QSFP+ 連接埠從分支配置中重新分組： `no interface breakout module 1 port 1-6 map 10g-4x`命令。

* 您必須已經完成了規劃、遷移，並閱讀了有關從節點到 Nexus 3132Q-V 叢集交換器的 10 GbE 和 40 GbE 連接的必要文件。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^]包含有關此過程中支援的ONTAP和 NX-OS 版本的資訊。





== Cisco Nexus 5596 要求

* 支援以下集群交換器：
+
** Nexus 5596
** Nexus 3132Q-V


* 10 GbE 和 40 GbE 連接埠的數量在參考設定檔 (RCF) 中定義，這些檔案可在以下位置取得：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco叢集網路交換器參考設定檔下載"^] 。
* 叢集交換器使用下列連接埠連接到節點：
+
** 埠 e1/1-40 (10 GbE)：Nexus 5596
** 埠 e1/1-30 (40 GbE)：Nexus 3132Q-V


* 叢集交換器使用下列交換器間連結 (ISL) 連接埠：
+
** 埠 e1/41-48 (10 GbE)：Nexus 5596
** 連接埠 e1/31-32 (40 GbE)：Nexus 3132Q-V


* 這link:https://hwu.netapp.com/["Hardware Universe"^]包含有關 Nexus 3132Q-V 交換器支援的佈線資訊：
+
** 具有 10 GbE 叢集連接的節點需要 QSFP 轉 SFP+ 光纖分支電纜或 QSFP 轉 SFP+ 銅纜分支纜線。
** 具有 40 GbE 叢集連接的節點需要支援 QSFP/QSFP28 光模組，並配備光纖電纜或 QSFP/QSFP28 銅纜直連接纜線。


* 叢集交換器使用對應的ISL電纜：
+
** 起始端：Nexus 5596 至 Nexus 5596（SFP+ 至 SFP+）
+
*** 8條SFP+光纖或銅纜直連接纜


** 中期調整：Nexus 5596 至 Nexus 3132Q-V（QSFP 至 4xSFP+ 突破）
+
*** 1條QSFP轉SFP+光纖分支線或銅纜分支線


** 最終版：Nexus 3132Q-V 至 Nexus 3132Q-V（QSFP28 至 QSFP28）
+
*** 2條QSFP28光纖或銅纜直連接電纜




* 在 Nexus 3132Q-V 交換器上，您可以將 QSFP/QSFP28 連接埠用作 40 千兆乙太網路或 4 x 10 千兆乙太網路模式。
+
預設情況下，40千兆乙太網路模式下有32個連接埠。這 40 個千兆乙太網路連接埠採用二元組命名規則進行編號。例如，第二個 40 千兆乙太網路連接埠編號為 1/2。將 40 千兆乙太網路配置更改為 10 千兆乙太網路的過程稱為 _breakout_，將 10 千兆乙太網路配置更改為 40 千兆乙太網路的過程稱為 _breakin_。當您將一個 40 千兆乙太網路連接埠分割為 10 千兆乙太網路連接埠時，產生的連接埠將使用三元組命名規則進行編號。例如，第二個 40 千兆乙太網路連接埠的分線連接埠編號為 1/2/1、1/2/2、1/2/3 和 1/2/4。

* Nexus 3132Q-V 交換器的左側有一組 4 個 SFP+ 端口，重複使用到該 QSFP28 連接埠。
+
預設情況下，RCF 結構設計為使用 QSFP28 連接埠。

+

NOTE: 您可以使用下列方法將 Nexus 3132Q-V 交換器的 4 個 SFP+ 連接埠設定為活動狀態，而不是使用一個 QSFP 連接埠： `hardware profile front portmode sfp-plus`命令。同樣，您可以使用以下方法將 Nexus 3132Q-V 交換器重設為使用 QSFP 連接埠而不是 4 個 SFP+ 連接埠： `hardware profile front portmode qsfp`命令。

* 您已將 Nexus 3132Q-V 交換器上的一些連接埠配置為以 10 GbE 或 40 GbE 運作。
+

NOTE: 您可以使用下列方法將前六個連接埠配置為 4x10 GbE 模式： `interface breakout module 1 port 1-6 map 10g-4x`命令。同樣，您可以使用下列方法將前六個 QSFP+ 連接埠從分支配置中重新分組： `no interface breakout module 1 port 1-6 map 10g-4x`命令。

* 您已完成規劃、遷移，並閱讀了有關從節點到 Nexus 3132Q-V 叢集交換器的 10 GbE 和 40 GbE 連接的必要文件。
* 此流程支援的ONTAP和 NX-OS 版本為：link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 。




== NetApp CN1610 要求

* 支援以下集群交換器：
+
** NetApp CN1610
** CiscoNexus 3132Q-V


* 叢集交換器支援以下節點連線：
+
** NetApp CN1610：連接埠 0/1 至 0/12 (10 GbE)
** Cisco Nexus 3132Q-V：連接埠 e1/1-30 (40 GbE)


* 叢集交換器使用下列交換器間鏈路（ISL）連接埠：
+
** NetApp CN1610：連接埠 0/13 至 0/16 (10 GbE)
** Cisco Nexus 3132Q-V：連接埠 e1/31-32 (40 GbE)


* 這link:https://hwu.netapp.com/["Hardware Universe"^]包含有關 Nexus 3132Q-V 交換器支援的佈線資訊：
+
** 具有 10 GbE 叢集連接的節點需要 QSFP 轉 SFP+ 光纖分支電纜或 QSFP 轉 SFP+ 銅纜分支纜線。
** 具有 40 GbE 叢集連接的節點需要支援 QSFP/QSFP28 的光模組，並配備光纖電纜或 QSFP/QSFP28 銅纜直連接纜線。


* 適用的ISL佈線如下：
+
** 起始端：對於 CN1610 到 CN1610（SFP+ 到 SFP+），四條 SFP+ 光纖或銅纜直連電纜
** 臨時方案：對於 CN1610 到 Nexus 3132Q-V（QSFP 轉四個 SFP+ 分支），使用一條 QSFP 轉 SFP+ 光纖或銅纜分支電纜
** 最後：對於 Nexus 3132Q-V 到 Nexus 3132Q-V（QSFP28 到 QSFP28）的連接，需要兩條 QSFP28 光纖或銅纜直連接線。


* NetApp雙絞線電纜與Cisco Nexus 3132Q-V 交換器不相容。
+
如果您目前的 CN1610 設定使用NetApp雙絞線電纜進行叢集節點到交換器的連接或 ISL 連接，並且您想要繼續在您的環境中使用雙絞線，則需要購買Cisco雙絞線電纜。或者，您可以使用光纖電纜同時進行 ISL 連線和叢集節點到交換器的連線。

* 在 Nexus 3132Q-V 交換器上，您可以將 QSFP/QSFP28 連接埠用作 40 Gb 乙太網路或 4x 10 Gb 乙太網路模式。
+
預設情況下，40Gb乙太網路模式下有32個連接埠。這些 40 Gb 乙太網路連接埠採用二元組命名規則進行編號。例如，第二個 40 Gb 乙太網路連接埠編號為 1/2。將配置從 40 Gb 乙太網路變更為 10 Gb 乙太網路的過程稱為 _breakout_，將設定從 10 Gb 乙太網路變更為 40 Gb 乙太網路的過程稱為 _breakin_。當您將 40 Gb 乙太網路連接埠分割為 10 Gb 乙太網路連接埠時，產生的連接埠將使用三元組命名約定進行編號。例如，第二個 40 Gb 乙太網路連接埠的分線連接埠編號為 1/2/1、1/2/2、1/2/3 和 1/2/4。

* Nexus 3132Q-V 交換器的左側有一組四個 SFP+ 端口，重複使用到第一個 QSFP 端口。
+
預設情況下，參考設定檔 (RCF) 的結構是使用第一個 QSFP 連接埠。

+
對於 Nexus 3132Q-V 交換機，您可以使用以下方法啟動四個 SFP+ 端口，而不是一個 QSFP 連接埠： `hardware profile front portmode sfp-plus`命令。同樣，您可以使用以下方法將 Nexus 3132Q-V 交換器重設為使用 QSFP 連接埠而不是四個 SFP+ 連接埠： `hardware profile front portmode qsfp`命令。

+

NOTE: 當您使用前四個 SFP+ 連接埠時，第一個 40GbE QSFP 連接埠將被停用。

* 您一定將 Nexus 3132Q-V 交換器上的某些連接埠配置為以 10 GbE 或 40 GbE 運作。
+
您可以使用以下方法將前六個連接埠分割為 4x10 GbE 模式： `interface breakout module 1 port 1-6 map 10g-4x`命令。同樣，您可以使用以下方法將_breakout_配置中的前六個QSFP+連接埠重新分組： `no interface breakout module 1 port 1-6 map 10g-4x`命令。

* 您必須已經完成了規劃、遷移，並閱讀了有關從節點到 Nexus 3132Q-V 叢集交換器的 10 GbE 和 40 GbE 連接的必要文件。
* 此流程支援的ONTAP和 NX-OS 版本列於此。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換機"^] 。
* 此流程支援的ONTAP和 FASTPATH 版本列於此。link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 交換機"^] 。

