---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: '使用群集交換器健康監視器 (CSHM) 和日誌收集功能時需要 SSH。若要在Cisco 3232c 叢集交換器上啟用 SSH，您需要先生成 SSH 金鑰，然後啟用 SSH。' 
---
= 安裝參考設定檔（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次設定 Nexus 3232C 交換器後，安裝參考設定檔 (RCF)。

.開始之前
請核實以下安裝和連接：

* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* 當前的RCF。
* 與交換器的主控台連線，安裝 RCF 時需要此連線。


.關於此任務
流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

完成 link:prepare-install-cisco-nexus-3232c-storage.html["準備安裝 NX-OS 和 RCF"] 中的程序，然後依照以下步驟操作。



== 步驟 1：在交換器上安裝 RCF

. 使用 SSH 或透過序列主控台登入交換器 s2。
. 使用下列傳輸協定之一將 RCF 複製到交換器 s2 的 bootflash：FTP、TFTP、SFTP 或 SCP。如需 Cisco 命令的詳細資訊，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^]中的適當指南。
+
.顯示範例
[%collapsible]
====
此範例展示如何使用 TFTP 將 RCF 複製到交換器 s2 的 bootflash 上：

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 將先前下載的 RCF 檔案套用到啟動快閃記憶體。
+
有關Cisco命令的更多信息，請參閱 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 指令參考"^]。

+
.顯示範例
[%collapsible]
====
此範例顯示在交換器 s2 上安裝 RCF 檔案 `NX9336C-FX2-RCF-v1.13-1-Storage.txt`：

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
請務必仔細閱讀 RCF 中的 *Installation notes*、*Important Notes* 和 *banner* 部分。您必須閱讀並遵循這些說明，以確保交換器的配置和運作正確。

====
. 檢查橫幅輸出 `show banner motd`命令。您必須閱讀並遵循「重要提示」下的說明，以確保交換器的正確配置和操作。
. 請確認 RCF 是否為正確的最新版本：
+
`show running-config`

+
檢查輸出結果以驗證是否擁有正確的 RCF 時，請確保以下資訊正確：

+
** RCF橫幅
** 節點和連接埠設置
** 客製化
+
輸出結果會根據您的網站配置而有所不同。檢查連接埠設置，並參考發行說明，以了解您安裝的 RCF 版本是否有任何特定變更。



. 將先前對交換器配置所做的任何自訂設定重新套用。
. 確認 RCF 版本和交換器設定正確後，複製以下內容： `running-config`文件到 `startup-config`文件。
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. 重新啟動交換器 s2：
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 在交換器 s1 上重複步驟 1 至 8。
. 將 ONTAP 叢集中所有節點的節點儲存連接埠和儲存架連接埠連接至交換器 s1 和 s2 。




== 步驟 2：驗證交換器連接

. 確認交換器連接埠為 *up* 狀態。
+
`show interface brief`

. 使用下列命令驗證節點儲存連接埠和儲存架連接埠是否位於正確的 VLAN 中：
+
`show vlan brief`

+
`show interface trunk`





== 步驟 3：設定ONTAP集群

NetApp建議您使用系統管理員來設定新的叢集。

系統管理器為叢集設定和配置提供了簡單易行的工作流程，包括分配節點管理 IP 位址、初始化叢集、建立本機層、設定協定和配置初始儲存。

參考 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["使用 System Manager 在新叢集上設定ONTAP"]了解設定說明。

.下一步是什麼？
安裝 RCF 後，您可以… link:configure-ssh-keys.html["驗證 SSH 配置"]。
