---
permalink: switch-cisco-3232c-storage/install-nx-os-software-3232c-storage.html 
sidebar: sidebar 
keywords: install, nx-os software 
summary: 您可以使用此程序在 Nexus 3232C 儲存交換器上安裝 NX-OS 軟體。 
---
= 安裝或升級 NX-OS 軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此程序在 Nexus 3232C 儲存交換器上安裝 NX-OS 軟體。

.開始之前
請確認您已具備以下條件：

* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco乙太網路交換器頁面"^]。請查閱交換器相容性表格，以了解支援的ONTAP和 NX-OS 版本。
* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["CiscoNexus 3000 系列交換機"^]。有關Cisco交換器升級和降級程序的完整文檔，請參閱Cisco網站上提供的相應軟體和升級指南。




== 安裝或升級軟體

流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

完成 link:prepare-install-cisco-nexus-3232c-storage.html["準備安裝 NX-OS 和 RCF"] 中的程序，然後依照以下步驟操作。

.步驟
. 將交換器連接到管理網路。
. 使用 `ping`用於驗證與託管 NX-OS 軟體和 RCF 的伺服器的連接性的命令。
+
.顯示範例
[%collapsible]
====
此範例驗證交換器可以存取 IP 位址為 172.19.2.1 的伺服器：

[listing, subs="+quotes"]
----
s2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 如果您是第一次設定交換器，請跳至步驟 5。如果您要升級交換器，請繼續執行下一步。
. 檢查每個節點儲存連接埠和儲存架連接埠的管理或運作狀態。
+
.. 顯示節點儲存連接埠屬性：
+
`storage port show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. 顯示儲存櫃連接埠屬性：+
`storage shelf port show`
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 確認交換器已啟用交換器健全狀況監控（CSHM）功能，以便對其進行監控：
+
`system switch ethernet show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. 使用 SSH 或透過序列主控台登入交換器。
. 將 NX-OS 軟體和 EPLD 映像複製到 Nexus 3232C 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.


s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: user1

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 請確認NX-OS軟體的運作版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2019, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.37
  NXOS: version 9.3(3)
  BIOS compile time:  01/28/2020
  NXOS image file is: bootflash:///nxos.9.3.3.bin
  NXOS compile time:  12/22/2019 2:00:00 [12/22/2019 14:00:37]

Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOCXXXXXXGD

  Device name: s2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 36 second(s)

Last reset at 74117 usecs after Tue Nov 24 06:24:23 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. 安裝 NX-OS 鏡像。
+
安裝鏡像檔案後，每次交換器重新啟動時都會載入該檔案。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS

Compatibility check is done:
Module  bootable          Impact              Install-type  Reason
------- ----------------- ------------------- ------------- ----------
     1     Yes            Disruptive          Reset         Default upgrade is not hitless

Images will be upgraded according to following table:
Module       Image       Running-Version(pri:alt)                New-Version          Upg-Required
------------ ----------- --------------------------------------- -------------------- ------------
     1       nxos        9.3(3)                                  9.3(4)               yes
     1       bios        v08.37(01/28/2020):v08.32(10/18/2016)   v08.37(01/28/2020)   no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 交換器重新啟動後，請先驗證NX-OS軟體的新版本：
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.37
  NXOS: version 9.3(4)
  BIOS compile time:  01/28/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 06:28:31]

Hardware
 cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOCXXXXXXGS

  Device name: rtpnpi-mcc01-8200-ms-A1
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 14 second(s)

Last reset at 196755 usecs after Tue Nov 24 06:37:36 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. 升級EPLD鏡像並重新啟動交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                       0x12
IO   FPGA                       0x11

s2# *install epld bootflash:n9000-epld.9.3.4.img module 1*
Compatibility check:
Module        Type         Upgradable    Impact      Reason
------  -----------------  ----------    ----------  -----------------
     1         SUP         Yes           Disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------  ----  -----------------  ---------------   -----------  ------------
     1   SUP   MI FPGA                0x12         0x12         No
     1   SUP   IO FPGA                0x11         0x12         Yes
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module        Type  Upgrade-Result
------  ------------------  --------------
     1         SUP         Success

Module 1 EPLD upgrade is successful.
----
====
. 如果您要升級至 NX-OS 版本 9.3(11)，則必須升級 EPLD。 `golden`鏡像並再次重新啟動交換器。否則，跳至步驟 12。
+
看 https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/epld-rn/nxos_n9K_epldRN_9311.html["EPLD 升級版本說明，版本 9.3(11)"^]更多詳情請見下文。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install epld bootflash:n9000-epld.9.3.11.img module 1 golden*
Digital signature verification is successful
Compatibility check:
Module        Type         Upgradable     Impact      Reason
------  -----------------  -------------  ----------  -----------------
     1        SUP          Yes            Disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

 Starting Module 1 EPLD Upgrade

Module 1 : MI FPGA [Programming] : 100.00% (     64 of      64 sect)
Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sect)
Module 1 EPLD upgrade is successful.
Module        Type          Upgrade-Result
------  ------------------  --------------
     1         SUP          Success

EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. 交換器重新啟動後，登入以驗證新版本的 EPLD 是否已成功載入。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x12
IO   FPGA                        0x12
----
====
. 如果您是第一次設定交換器，請跳至步驟 15。如果您要升級交換器，請繼續下一步。
. 驗證每個節點儲存連接埠和儲存架連接埠的健全狀況狀態。
+
.. 顯示節點儲存連接埠屬性：
+
`storage port show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
----
====
.. 顯示儲存櫃連接埠屬性：+
`storage shelf port show`
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 確認交換器已啟用交換器健全狀況監控（CSHM）功能，以便對其進行監控：
+
`system switch ethernet show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP  false
----
====


. 重複步驟 5 至 13 ，在交換器 s1 上安裝 NX-OS 軟體。


.下一步是什麼？
安裝 NX-OS 軟體後，您可以link:install-rcf-software-3232c-storage.html["安裝或升級參考設定檔（RCF）"]。
