---
permalink: switch-cisco-3232c-storage/prepare-install-cisco-nexus-3232c-storage.html 
sidebar: sidebar 
keywords: nx-os software, install, cisco nexus storage switches, 3232c, rcfs 
summary: Cisco Nexus 3232C 儲存交換器上必須安裝 Cisco NX-OS 軟體和參考設定檔（RCF）。 
---
= 準備安裝 NX-OS 軟體和參考設定檔 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安裝 NX-OS 軟體和參考設定檔 (RCF) 之前，請依照下列步驟操作。

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩個 Cisco 交換器的名稱分別是 s1 和 s2。
* 節點名稱為 cluster1-01 和 cluster1-02。


請參閱 link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 以驗證平台上的正確網路連接埠。如需交換器安裝需求的詳細資訊，請參閱 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["安裝HWU中沒有的設備還需要哪些額外資訊？"^]。

.關於此任務
流程需要同時使用ONTAP指令和Cisco Nexus 3000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

.步驟
. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
`system node autosupport invoke -node * -type all -message MAINT=x h`
+
其中 _x_ 為維護視窗的持續時間（小時）。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
進階提示(`*>`出現。

. 顯示每個節點中為每個交換器設定的介面數量：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e5a    s1                        Eth1/2            N3K-C3232C
            e3b    s2                        Eth1/2            N3K-C3232C
cluster1-01/cdp
            e5a    s1                        Eth1/1            N3K-C3232C
            e3b    s2                        Eth1/1            N3K-C3232C
.
.
----
====
. 檢查每個節點儲存連接埠和儲存架連接埠的管理或運作狀態。
+
.. 顯示節點儲存連接埠屬性：
+
`storage port show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. 顯示儲存櫃連接埠屬性：+
`storage shelf port show`
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 確認交換器已啟用交換器健全狀況監控（CSHM）功能，以便對其進行監控：
+
`system switch ethernet show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch             Type               Address          Model
  ------------------ ------------------ ---------------- ---------------
  s1                 storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                 storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.下一步是什麼？
準備好安裝 NX-OS 軟體和 RCF 後，您可以link:install-nx-os-software-3232c-storage.html["安裝 NX-OS 軟體"]。
