---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 您可以使用此程序升級您的 RCF 版本。 
---
= 升級您的參考設定檔 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您的運行交換器上已安裝了現有版本的 RCF 檔案時，您需要升級 RCF 版本。

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的群集（日誌中沒有錯誤或類似問題）。
* 當前的RCF。
* 如果您要更新 RCF 版本，則需要在 RCF 中進行啟動配置，以反映所需的啟動映像。
+
如果需要更改啟動配置以反映目前的啟動映像，則必須在重新套用 RCF 之前進行更改，以便在以後的重新啟動中包含正確的版本。




CAUTION: 在安裝新的交換器軟體版本和 RCF 之前，必須清除交換器設定並執行基本設定。在清除交換器設定之前，您必須使用序列控制台連接到交換機，或保留基本設定資訊。



== 第一步：準備升級

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 為維護視窗的持續時間（小時）。

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 顯示每個節點上連接到交換器的連接埠：
+
[source, cli]
----
network device-discovery show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====
. 檢查每個節點儲存連接埠和儲存架連接埠的管理或運作狀態。
+
.. 確認所有節點儲存連接埠均已啟動且狀態正常：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. 驗證所有儲存架連接埠是否處於正常狀態：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 確認交換器是否處於監控狀態。
+
[source, cli]
----
system switch ethernet show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== 步驟 2：升級 RCF

. 使用 SSH 或透過序列主控台登入交換器 s2。
. 關閉與節點所有連接埠相連的連接埠。
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-32*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: 確保關閉所有連接的連接埠以避免任何網路連線問題。請參閱知識庫文章 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["在切換作業系統升級期間遷移叢集 LIF 時，節點脫離仲裁。"^]更多詳情請見下文。

. 如果您尚未儲存目前交換器配置，請將以下命令的輸出複製到文字檔案中：
+
`show running-config`

+
.. 記錄目前版本與目前版本之間的任何自訂新增內容。 `running-config`以及正在使用的 RCF 檔案（例如貴組織的 SNMP 配置）。
.. 對於 NX-OS 10.2 及更高版本，請使用 `show diff running-config`用於與 bootflash 中儲存的 RCF 檔案進行比較的命令。否則，請使用第三方差異比較工具。


. 儲存基本配置詳細信息 `write_erase.cfg`啟動閃存上的檔案。
+
[NOTE]
====
確保配置以下內容：

** 使用者名稱和密碼
** 管理 IP 位址
** 預設網關
** 交換器名稱


====
+
`s2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`s2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`s2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
請參閱知識庫文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持遠端連線的情況下清除Cisco互連交換器上的配置"^]更多詳情請見下文。

. 確認 `write_erase.cfg`文件已如預期填入：
+
`*show file bootflash:write_erase.cfg*`

. 問題 `write erase`清除目前已儲存配置的命令：
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 將先前儲存的基本配置複製到啟動配置中。
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. 重啟交換器：
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP 位址恢復正常後，透過 SSH 登入交換器。
+
您可能需要更新與 SSH 金鑰相關的 hosts 檔案項目。

. 使用下列傳輸協定之一將 RCF 複製到交換器 s2 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有關 Cisco 命令的更多資訊，請參閱  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html#CommandReferences["Cisco Nexus 3000 系列 NX-OS 文件"^] 中的相應指南。

+
.顯示範例
[%collapsible]
====
此範例展示如何使用 TFTP 將 RCF 複製到交換器 s2 的 bootflash 上：

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 將先前下載的 RCF 檔案套用到啟動快閃記憶體。
+
有關 Cisco 命令的更多資訊，請參閱  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 系列文件"^] 中的相應指南。

+
此範例顯示在交換器 s2 上安裝 RCF 檔案 `NX3232C-RCF-v1.13-1-Storage.txt`：

+
[listing, subs="+quotes"]
----
s2# *copy NX3232C-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
確保仔細閱讀 RCF 的 *安裝說明*、*重要說明* 和 *橫幅* 部分。您必須閱讀並遵循這些說明以確保交換器的正確配置和操作。

====
. 請確認 RCF 檔案是否為最新版本：
+
`show running-config`

+
檢查輸出結果以驗證是否擁有正確的 RCF 時，請確保以下資訊正確：

+
** RCF橫幅
** 節點和連接埠設置
** 客製化
+
輸出結果會根據您的網站配置而有所不同。檢查連接埠設置，並參考發行說明，以了解您安裝的 RCF 版本是否有任何特定變更。



. 將先前對交換器配置所做的任何自訂設定重新套用。
. 確認 RCF 版本、自訂新增項目和交換器設定正確後，複製以下內容： `running-config`文件到 `startup-config`文件。
+
有關 Cisco 命令的更多資訊，請參閱  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 9000 系列文件"^] 中的相應指南。

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. 重新啟動交換器 s2。在交換器重新啟動期間、您可以忽略節點上報告的「`cluster switch health monitor`」警示和「`cluster ports down`」事件。
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 檢查每個節點儲存連接埠和儲存架連接埠的管理或運作狀態。
+
.. 驗證所有儲存連接埠均處於正常狀態：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. 驗證所有儲存架連接埠是否處於正常狀態：
+
[source, cli]
----
storage shelf port show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 確認交換器是否正在被監控：
+
[source, cli]
----
system switch ethernet show
----
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. 在交換器 s1 上重複步驟 1 至 16。




== 步驟 3：驗證儲存網路

在每個儲存交換器上完成以下步驟，以驗證 RCF 升級後儲存網路是否正常運作。

. 確認交換器連接埠為 *up* 狀態。
+
[source, cli]
----
show interface brief
----
. 請確認預期的節點儲存連接埠仍處於連線狀態：
+
[source, cli]
----
show cdp neighbors
----
. 確認預期的儲存櫃連接埠是否仍保持連線：
+
[source, cli]
----
show lldp neighbors
----
. 使用下列命令驗證節點儲存連接埠和儲存架連接埠是否位於正確的 VLAN 中：
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.下一步是什麼？
升級 RCF 後，您可以link:configure-ssh-keys.html["驗證 SSH 配置"]。
