---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: 當您在NetApp交換器上安裝FastPath軟體時、必須先從第二個交換器CS2開始升級。 
---
= 安裝FastPath軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在NetApp交換器上安裝FastPath軟體時、必須先從第二個交換器_CS2_開始升級。



== 檢閱要求

.開始之前
請確定您擁有下列項目：

* 交換器組態的目前備份。
* 完全正常運作的叢集（記錄中沒有錯誤、也沒有故障的叢集網路介面卡（NIC）或類似問題）。
* 叢集交換器上的完整功能連接埠連線。
* 設定所有叢集連接埠。
* 所有已設定的叢集邏輯介面（lifs）（不得已移轉）。
* 成功的溝通途徑：ONTAP The es執行（權限：進階） `cluster ping-cluster -node node1` 命令必須指出這一點 `larger than PMTU communication` 在所有路徑上都成功。
* 受支援版本的FastPath和ONTAP 支援的功能。
+
請務必參閱上的交換器相容性表 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601與CN1610交換器"^] 頁面、以取得支援的FastPath和ONTAP 支援的版本。





== 安裝FastPath

下列程序使用叢集Data ONTAP 式的循環8.2語法。因此、叢集Vserver、LIF名稱和CLI輸出與Data ONTAP 《Sv3 8.3》中的不同。

RCF和FastPath版本中的命令語法之間可能存在命令相依性。

.關於範例
本程序中的範例使用下列交換器和節點命名法：

* 兩個NetApp交換器分別是CS1和CS2。
* 這兩個叢集l生命 區是clus1和clus2。
* Vserver是VS1和VS2。
* 「cluster：*>」提示會指出叢集的名稱。
* 每個節點上的叢集連接埠名稱為e1a和E2A。
+
https://hwu.netapp.com/["Hardware Universe"^] 有更多有關平台所支援的實際叢集連接埠資訊。

* 支援的交換器間連結（ISL）是連接埠0/13到0/16。
* 支援的節點連線是連接埠0/1到0/12。




=== 步驟1：移轉叢集

. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -訊息MAn=xh」

+
_x_是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

. 以admin身分登入交換器。預設沒有密碼。在「（CS2）#」提示字元中、輸入「enable」命令。同樣地、預設也沒有密碼。這可讓您存取「優先執行」模式、以便設定網路介面。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 在每個節點的主控台上、將clus2移轉至連接埠e1a：
+
網路介面移轉

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 在每個節點的主控台上、確認移轉發生：
+
「網路介面展示」

+
以下範例顯示、clus2已移轉至兩個節點上的連接埠e1a：

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== 步驟2：安裝FastPath軟體

. 關閉兩個節點上的叢集連接埠E2A：
+
網路連接埠修改

+
.顯示範例
[%collapsible]
====
以下範例顯示兩個節點上的連接埠E2A正在關機：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 確認兩個節點上的連接埠E2A均已關機：
+
「網路連接埠展示」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. 關閉CS1上的交換器間連結（ISL）連接埠、即作用中的NetApp交換器：
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. 在CS2上備份目前使用中的映像。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. 將映像檔下載到交換器。
+
將映像檔複製到作用中映像、表示當您重新開機時、該映像會建立執行中的FastPath版本。上一個映像仍可作為備份使用。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 驗證FastPath軟體的執行版本。
+
《如何版本》

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. 檢視使用中和備份組態的開機映像。
+
「如何啟動bootvar

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. 重新啟動交換器。
+
"重裝"

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== 步驟3：驗證安裝

. 再次登入、並驗證FastPath軟體的新版本。
+
《如何版本》

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. 啟動使用中交換器CS1上的ISL連接埠。
+
設定

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. 驗證ISL是否正常運作：
+
「How port-channel 3/1」

+
「Link State（連結狀態）」欄位應顯示「Up（啟動）」。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 如果您對軟體版本和交換器設定滿意、請將「執行組態」檔案複製到「儲存組態」檔案。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 在每個節點上啟用第二個叢集連接埠E2A：
+
網路連接埠修改

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. 還原與連接埠E2A相關的clus2：
+
網路介面回復

+
LIF可能會自動回復、視ONTAP 您使用的版本而定。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. 確認LIF現在位於兩個節點上的主節點（「true」）：
+
「網路介面show -_role叢集_」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 檢視節點狀態：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 重複上述步驟、在另一台交換器CS1上安裝FastPath軟體。
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」


