---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 當您安裝參考組態檔（RCF）時、必須先將叢集l生命 從交換器CS2移除。安裝並驗證RCF之後、便可將LIF移回。 
---
= 在CN1610交換器上安裝參考組態檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請遵循此程序來安裝參考組態檔（RCF）。

在安裝RCF之前、您必須先將叢集LIF從交換器CS2移轉。安裝並驗證RCF之後、便可將LIF移回。



== 檢閱要求

.開始之前
請確定您擁有下列項目：

* 交換器組態的目前備份。
* 完全正常運作的叢集（記錄中沒有錯誤、也沒有故障的叢集網路介面卡（NIC）或類似問題）。
* 叢集交換器上的完整功能連接埠連線。
* 設定所有叢集連接埠。
* 設定所有叢集邏輯介面（lifs）。
* 成功的溝通途徑：ONTAP The es執行（權限：進階） `cluster ping-cluster -node node1` 命令必須指出這一點 `larger than PMTU communication` 在所有路徑上都成功。
* 支援版本的RCF和ONTAP 不支援。
+
請務必參閱上的交換器相容性表 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601與CN1610交換器"^] 頁面、以取得支援的RCF和ONTAP 版本。





== 安裝RCF

下列程序使用叢集Data ONTAP 式的循環8.2語法。因此、叢集Vserver、LIF名稱和CLI輸出與Data ONTAP 《Sv3 8.3》中的不同。

RCF和FastPath版本中的命令語法之間可能存在命令相依性。


NOTE: 在RCF 1.2版中、由於安全考量、已明確停用對Telnet的支援。若要避免安裝RCF 1.2時發生連線問題、請確認已啟用Secure Shell（SSH）。。 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610交換器管理員指南"^] 有更多關於SSH的資訊。

.關於範例
本程序中的範例使用下列交換器和節點命名法：

* 兩個NetApp交換器分別是CS1和CS2。
* 這兩個叢集l生命 區是clus1和clus2。
* Vserver是VS1和VS2。
* 「cluster：*>」提示會指出叢集的名稱。
* 每個節點上的叢集連接埠名稱為e1a和E2A。
+
https://hwu.netapp.com/["Hardware Universe"^] 有更多有關平台所支援的實際叢集連接埠資訊。

* 支援的交換器間連結（ISL）是連接埠0/13到0/16。
* 支援的節點連線是連接埠0/1到0/12。
* 受支援版本的FastPath、RCF和ONTAP RESZ.
+
請務必參閱上的交換器相容性表 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601與CN1610交換器"^] 頁面、以取得所支援的FastPath、RCF及ONTAP 支援的版本。





=== 步驟1：移轉叢集

. 儲存您目前的交換器組態資訊：
+
寫入記憶體

+
.顯示範例
[%collapsible]
====
以下範例顯示目前交換器組態儲存至交換器CS2上的啟動組態（「startup組態」）檔案：

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 在每個節點的主控台上、將clus2移轉至連接埠e1a：
+
網路介面移轉

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 在每個節點的主控台上、確認移轉是否發生：
+
「網路介面show -role cluster」

+
.顯示範例
[%collapsible]
====
以下範例顯示、clus2已移轉至兩個節點上的連接埠e1a：

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 關閉兩個節點上的連接埠E2A：
+
網路連接埠修改

+
.顯示範例
[%collapsible]
====
以下範例顯示兩個節點上的連接埠E2A正在關機：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 確認兩個節點上的連接埠E2A均已關機：
+
「網路連接埠展示」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. 關閉使用中NetApp交換器CS1上的ISL連接埠。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== 步驟2：安裝RCF

. 將RCF複製到交換器。
+

NOTE: 您必須先將「.scr」副檔名設定為檔案名稱的一部分、才能叫用指令碼。此副檔名是FastPath作業系統的副檔名。

+
交換器會在下載指令碼到交換器時自動驗證指令碼、然後輸出會移至主控台。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. 確認已下載指令碼、並以您指定的檔案名稱儲存。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. 驗證指令碼。
+

NOTE: 指令碼會在下載期間驗證、以驗證每一行是否為有效的交換器命令列。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. 將指令碼套用至交換器。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 確認交換器已實作您的變更。
+
[listing]
----
(cs2) # show running-config
----
+
此範例顯示交換器上的「執行組態」檔案。您必須將檔案與RCF進行比較、以驗證您設定的參數是否符合預期。

. 儲存變更。
. 將「執行組態」檔案設為標準檔案。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. 重新啟動交換器、確認「執行組態」檔案正確無誤。
+
重新開機完成後、您必須登入、檢視「執行組態」檔案、然後在介面3/64上尋找說明、該介面是RCF的版本標籤。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 啟動使用中交換器CS1上的ISL連接埠。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. 驗證ISL是否正常運作：
+
「How port-channel 3/1」

+
「Link State（連結狀態）」欄位應顯示「Up（啟動）」。

+
.顯示範例
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 在兩個節點上啟動叢集連接埠E2A：
+
網路連接埠修改

+
.顯示範例
[%collapsible]
====
以下範例顯示節點1和節點2上正在啟動的連接埠E2A：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== 步驟3：驗證安裝

. 驗證兩個節點上的連接埠E2A是否都已開啟：
+
`network port show -_role cluster_`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 在兩個節點上、還原與連接埠E2A相關的clus2：
+
網路介面回復

+
LIF可能會自動回復、視ONTAP 您的版本而定。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. 確認LIF現在位於兩個節點上的主節點（「true」）：
+
「網路介面show -_role叢集_」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 檢視節點成員的狀態：
+
「叢集展示」

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. 如果您對軟體版本和交換器設定滿意、請將「執行組態」檔案複製到「儲存組態」檔案。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 重複上述步驟、在另一台交換器CS1上安裝RCF。


.接下來呢？
link:../switch-cshm/config-overview.html["設定交換器健全狀況監控"]
