---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: '在 NetApp CN1610 叢集交換器上安裝 FASTPATH 軟體和參考組態檔 (RCF)，以支援 ONTAP 8.3.1 及更新版本。' 
---
= 在 NetApp CN1610 叢集交換器上安裝適用於 ONTAP 8.3.1 及更新版本的 FASTPATH 軟體和 RCF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 NetApp CN1610 叢集交換器上安裝 FASTPATH 軟體和參考組態檔 (RCF)，以支援 ONTAP 8.3.1 及更新版本。

對於執行 ONTAP 8.3.1 或更新版本的 NetApp CN1601 管理交換器和 CN1610 叢集交換器，安裝步驟相同。但是，這兩種型號需要不同的軟體和 RCF。



[[review-requirements]]
== 審查要求

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的叢集（日誌中沒有錯誤，叢集網路介面卡（NIC）也沒有缺陷或類似問題）。
* 叢集交換器上的連接埠連線功能齊全。
* 所有叢集連接埠均已設定。
* 所有叢集邏輯介面（LIF）均已設定（必須尚未移轉）。
* 成功的通訊路徑：ONTAP （權限：進階） `cluster ping-cluster -node node1` 命令必須指示 `larger than PMTU communication`在所有路徑上均成功。
* 支援的 FASTPATH、RCF 和 ONTAP 版本。
+
請務必查閱 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交換器"^]頁面上的交換器相容性表格，以了解支援的 FASTPATH、RCF 和 ONTAP 版本。





[[install-the-fastpath-software]]
== 安裝 FASTPATH 軟體

以下步驟使用叢集式 Data ONTAP 8.2 語法。因此，叢集 Vserver、LIF 名稱和 CLI 輸出與 Data ONTAP 8.3 中的有所不同。

RCF 和 FASTPATH 版本中的命令語法之間可能存在命令相依性。


NOTE: 出於安全性考慮，RCF 1.2 版本已明確停用 Telnet 支援。為避免安裝 RCF 1.2 時出現連線問題，請確認已啟用 Secure Shell （SSH）。 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 交換器管理員指南"^]有關 SSH 的詳細資訊。

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩個 NetApp 交換器的名稱分別是 cs1 和 cs2。
* 叢集邏輯介面 （LIF） 名稱分別為：節點 1 的 node1_clus1 和 node1_clus2，節點 2 的 node2_clus1 和 node2_clus2。（一個叢集最多可以包含 24 個節點。）
* 儲存設備虛擬機器（SVM）名稱為 Cluster。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 每個節點上的叢集連接埠分別命名為 e0a 和 e0b。
+
link:https://hwu.netapp.com/["Hardware Universe"^]提供有關您平台支援的實際叢集連接埠的詳細資訊。

* 支援的交換器間連結 (ISL) 為連接埠 0/13 至 0/16。
* 支援的節點連接為連接埠 0/1 至 0/12。




[[step-1-migrate-cluster]]
=== 步驟 1：移轉叢集

. 顯示叢集上的網路連接埠資訊：
+
`network port show -_ipspace cluster_`

+
.顯示範例
[%collapsible]
====
以下範例顯示了該命令的輸出類型：

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. 顯示叢集上 LIF 的相關資訊：
+
`network interface show -_role cluster_`

+
.顯示範例
[%collapsible]
====
以下範例展示了叢集上的邏輯介面。在本例中，此 `-role`參數顯示了與叢集連接埠關聯的 LIF 相關資訊：

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. 在每個節點上，使用節點管理 LIF，將 node1_clus2 移轉到 node1 上的 e0a，將 node2_clus2 移轉到 node2 上的 e0a：
+
`network interface migrate`

+
您必須在擁有對應叢集 LIF 的控制器主控台上輸入命令。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: 此命令中，叢集名稱區分大小寫，且需要在每個節點上執行此命令。無法在通用叢集 LIF 中執行此命令。

. 在節點上使用 `network interface show`命令，驗證移轉是否已完成。
+
.顯示範例
[%collapsible]
====
以下範例顯示 clus2 已移轉至節點 node1 和 node2 上的連接埠 e0a：

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. 將權限層級變更為進階，並在提示繼續時輸入 y：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 關閉兩個節點上的叢集連接埠 e0b：
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
您必須在擁有對應叢集 LIF 的控制器主控台上輸入命令。

+
.顯示範例
[%collapsible]
====
以下範例展示了關閉所有節點上 e0b 連接埠的命令：

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. 請確認兩個節點上的 e0b 連接埠都已關閉：
+
`network port show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. 關閉 cs1 上的交換器間連結 (ISL) 連接埠。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. 備份 cs2 上目前作用中的映像。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




[[step-2-install-the-fastpath-software-and-rcf]]
=== 步驟 2：安裝 FASTPATH 軟體和 RCF

. 請確認 FASTPATH 軟體的運作版本。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. 將鏡像檔下載到交換器。
+
將映像檔案複製到作用中映像，表示重新開機後，該映像將建立執行中的 FASTPATH 版本。先前的映像仍可作為備份使用。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 確認目前和下一個活動的開機映像版本：
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. 將與新映像版本相容的 RCF 安裝到交換器上。
+
如果 RCF 版本已正確，則啟動 ISL 連接埠。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: The `.scr` 副檔名必須在呼叫指令碼之前設定為檔案名稱的一部分。此副檔名適用於 FASTPATH 作業系統。

+
交換器在指令碼下載到交換器時會自動驗證指令碼。輸出結果會顯示在主控台上。

. 請確認指令碼已下載並儲存為您指定的檔案名稱。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. 將指令碼應用於交換器。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. 確認變更已套用至交換器，然後儲存：
+
`show running-config`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. 儲存執行中的組態，以便重新開機交換器時將其作為啟動組態。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 重啟交換器。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




[[step-3-validate-installation]]
=== 步驟 3：驗證安裝

. 再次登入，然後驗證交換器是否正在執行新版本的 FASTPATH 軟體。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
重新開機完成後，您必須登入以驗證映像版本、檢視執行中的組態，並尋找介面 3/64 上的執行摘要，這是 RCF 的版本標籤。

. 在作用中交換器 cs1 上啟用 ISL 連接埠。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. 確認ISL是否正常運作：
+
`show port-channel 3/1`

+
連結狀態欄位應指示 `Up`。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 在所有節點上啟用叢集連接埠 e0b：
+
`network port modify`

+
您必須在擁有對應叢集 LIF 的控制器主控台上輸入命令。

+
.顯示範例
[%collapsible]
====
以下範例展示如何在節點 1 和節點 2 上啟動連接埠 e0b：

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. 確認所有節點上的 e0b 連接埠均已啟用：
+
`network port show -ipspace cluster`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. 確認 LIF 現在在兩個節點上都處於主目錄（(`true`）狀態：
+
`network interface show -_role cluster_`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. 顯示節點成員的狀態：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. 返回管理員權限層級：
+
`set -privilege admin`

. 重複上述步驟，在另一台交換器 cs1 上安裝 FASTPATH 軟體和 RCF。

