---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: '安裝參考設定檔 (RCF) 時，必須先將叢集 LIF 從交換器 cs2 遷移出去。  RCF 安裝並驗證完成後，LIF 即可遷移回去。' 
---
= 在 CN1610 交換器上安裝參考設定檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照以下步驟安裝參考設定檔 (RCF)。

在安裝 RCF 之前，必須先將叢集 LIF 從交換器 cs2 遷移出去。  RCF 安裝並驗證完成後，LIF 即可遷移回去。



== 審查要求

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的叢集（日誌中沒有錯誤，叢集網路介面卡（NIC）也沒有缺陷或類似問題）。
* 集群交換器上的連接埠連線功能齊全。
* 所有群集連接埠均已設定。
* 所有群集邏輯介面（LIF）均已設定。
* 一條成功的溝通路徑： ONTAP （權限：進階） `cluster ping-cluster -node node1`命令必須表明 `larger than PMTU communication`在所有路徑上都取得了成功。
* 受支援的 RCF 和ONTAP版本。
+
請務必查閱交換器相容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交換機"^]本頁列出了支援的 RCF 和ONTAP版本。





== 安裝 RCF

下列程序使用叢集式Data ONTAP 8.2 語法。因此，叢集 Vserver、LIF 名稱和 CLI 輸出與Data ONTAP 8.3 中的不同。

RCF 和 FASTPATH 版本中的指令語法可能存在指令依賴關係。


NOTE: 由於安全性問題，RCF 版本 1.2 中已明確停用對 Telnet 的支援。為避免安裝 RCF 1.2 時出現連線問題，請確認安全殼層 (SSH) 已啟用。這 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 交換器管理員指南"^]包含更多關於 SSH 的資訊。

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩台NetApp交換器分別是 cs1 和 cs2。
* 這兩個簇 LIF 分別是 clus1 和 clus2。
* 虛擬伺服器為 vs1 和 vs2。
* 這 `cluster::*>`prompt 指示叢集名稱。
* 每個節點上的叢集連接埠分別命名為 e1a 和 e2a。
+
https://hwu.netapp.com/["Hardware Universe"^]包含有關您的平台支援的實際集群連接埠的更多資訊。

* 支援的交換器間連結 (ISL) 為連接埠 0/13 至 0/16。
* 支援的節點連接為連接埠 0/1 至 0/12。
* 支援的 FASTPATH、RCF 和ONTAP版本。
+
請務必查閱交換器相容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交換機"^]此頁面列出了支援的 FASTPATH、RCF 和ONTAP版本。





=== 步驟 1：遷移集群

. 儲存您目前的交換器設定資訊：
+
`write memory`

+
.顯示範例
[%collapsible]
====
以下範例展示如何將目前交換器組態儲存到啟動組態中。(`startup-config` ) 文件在交換器 cs2 上：

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 在每個節點的控制台上，將 clus2 遷移到連接埠 e1a：
+
`network interface migrate`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 在每個節點的控制台上，驗證遷移是否已完成：
+
`network interface show -role cluster`

+
.顯示範例
[%collapsible]
====
以下範例顯示 clus2 已遷移到兩個節點上的 e1a 連接埠：

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 關閉兩個節點上的 e2a 連接埠：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩個節點上的 e2a 連接埠都已關閉：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 請確認兩個節點上的 e2a 連接埠均已關閉：
+
`network port show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. 關閉活動NetApp交換器 cs1 上的 ISL 連接埠。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== 步驟 2：安裝 RCF

. 將 RCF 複製到交換器。
+

NOTE: 你必須設定 `.scr`在呼叫腳本之前，將檔案副檔名作為檔案名稱的一部分。此擴充功能是適用於 FASTPATH 作業系統的擴充功能。

+
交換機會在腳本下載到交換器時自動驗證，並將輸出結果輸出到控制台。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. 請確認腳本已下載並以您指定的檔案名稱儲存。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. 驗證腳本。
+

NOTE: 下載過程中會對腳本進行驗證，以確保每一行都是有效的交換器命令列。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. 將腳本應用到交換器上。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 請確認您的變更已在交換器上生效。
+
[listing]
----
(cs2) # show running-config
----
+
該範例展示了 `running-config`文件在交換器上。您必須將該檔案與 RCF 進行比較，以驗證您設定的參數是否符合預期。

. 儲存更改。
. 設定 `running-config`文件將成為標準文件。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. 重新啟動交換器並驗證 `running-config`文件正確。
+
重新啟動完成後，您必須登入並查看 `running-config`然後尋找文件，並在介面 3/64 上尋找描述，這是 RCF 的版本標籤。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 在活動交換器 cs1 上啟用 ISL 連接埠。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. 確認ISL是否正常運作：
+
`show port-channel 3/1`

+
“鏈路狀態”欄位應指示 `Up`。

+
.顯示範例
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 在兩個節點上啟動叢集連接埠 e2a：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例展示如何在節點 1 和節點 2 上啟動連接埠 e2a：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== 步驟 3：驗證安裝

. 請確認兩個節點上的 e2a 連接埠都已啟動：
+
`network port show -_role cluster_`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 在兩個節點上，還原與連接埠 e2a 關聯的 clus2：
+
`network interface revert`

+
LIF 可能會自動恢復，具體取決於您的ONTAP版本。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. 確認 LIF 現在已歸位(`true`）在兩個節點上：
+
`network interface show -_role cluster_`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看節點成員的狀態：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. 複製 `running-config`文件到 `startup-config`當您對軟體版本和開關設定滿意後，請提交文件。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 重複上述步驟，在另一台交換器 cs1 上安裝 RCF。


.下一步是什麼？
link:../switch-cshm/config-overview.html["配置交換器健康監控"]
