---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: 在NetApp交換器上安裝 FASTPATH 軟體時，必須從第二個交換器 cs2 開始升級。 
---
= 安裝 FASTPATH 軟體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在NetApp交換器上安裝 FASTPATH 軟體時，必須從第二個交換器 _cs2_ 開始升級。



== 審查要求

.開始之前
請確保您擁有以下物品：

* 交換器配置的目前備份。
* 一個功能齊全的叢集（日誌中沒有錯誤，叢集網路介面卡（NIC）也沒有缺陷或類似問題）。
* 集群交換器上的連接埠連線功能齊全。
* 所有群集連接埠均已設定。
* 所有群集邏輯介面（LIF）均已設定（必須尚未遷移）。
* 一條成功的溝通路徑： ONTAP （權限：進階） `cluster ping-cluster -node node1`命令必須表明 `larger than PMTU communication`在所有路徑上都取得了成功。
* 支援的 FASTPATH 和ONTAP版本。
+
請務必查閱交換器相容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交換機"^]本頁列出了支援的 FASTPATH 和ONTAP版本。





== 安裝 FASTPATH

下列程序使用叢集式Data ONTAP 8.2 語法。因此，叢集 Vserver、LIF 名稱和 CLI 輸出與Data ONTAP 8.3 中的不同。

RCF 和 FASTPATH 版本中的指令語法可能存在指令依賴關係。

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 這兩台NetApp交換器分別是 cs1 和 cs2。
* 這兩個簇 LIF 分別是 clus1 和 clus2。
* 虛擬伺服器為 vs1 和 vs2。
* 這 `cluster::*>`prompt 指示叢集名稱。
* 每個節點上的叢集連接埠分別命名為 e1a 和 e2a。
+
https://hwu.netapp.com/["Hardware Universe"^]包含有關您的平台支援的實際集群連接埠的更多資訊。

* 支援的交換器間連結 (ISL) 為連接埠 0/13 至 0/16。
* 支援的節點連接為連接埠 0/1 至 0/12。




=== 步驟 1：遷移集群

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是維護視窗的持續時間，單位為小時。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

. 以管理員身分登入交換器。預設沒有密碼。在 `(cs2) #`提示，輸入 `enable`命令。再次強調，預設沒有密碼。這樣您就可以存取特權 EXEC 模式，從而設定網路介面。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 在每個節點的控制台上，將 clus2 遷移到連接埠 e1a：
+
`network interface migrate`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 在每個節點的控制台上，驗證遷移是否已完成：
+
`network interface show`

+
以下範例顯示 clus2 已遷移到兩個節點上的 e1a 連接埠：

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== 步驟 2：安裝 FASTPATH 軟體

. 關閉兩個節點上的叢集連接埠 e2a：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩個節點上的 e2a 連接埠都已關閉：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 請確認兩個節點上的 e2a 連接埠均已關閉：
+
`network port show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. 關閉活動NetApp交換器 cs1 上的交換器間連結 (ISL) 連接埠：
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. 備份 CS2 上目前活動的影像。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. 將鏡像檔下載到交換器。
+
將鏡像檔案複製到活動鏡像意味著，當您重新啟動時，該鏡像將建立正在運行的 FASTPATH 版本。之前的鏡像檔案仍可作為備份使用。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 請確認FASTPATH軟體的運作版本。
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. 查看活動配置和備份配置的啟動映像。
+
`show bootvar`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. 重啟交換器。
+
`reload`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== 步驟 3：驗證安裝

. 重新登錄，並驗證 FASTPATH 軟體的新版本。
+
`show version`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. 在活動交換器 cs1 上啟用 ISL 連接埠。
+
`configure`

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. 確認ISL是否正常運作：
+
`show port-channel 3/1`

+
“鏈路狀態”欄位應指示 `Up`。

+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 複製 `running-config`文件到 `startup-config`當您對軟體版本和開關設定滿意後，請提交文件。
+
.顯示範例
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 在每個節點上啟用第二個叢集連接埠 e2a：
+
`network port modify`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. 還原與連接埠 e2a 關聯的 clus2：
+
`network interface revert`

+
LIF 可能會自動恢復，具體取決於您的ONTAP軟體版本。

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. 確認 LIF 現在已歸位(`true`）在兩個節點上：
+
`network interface show -_role cluster_`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看節點狀態：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 重複上述步驟，在另一台交換器 cs1 上安裝 FASTPATH 軟體。
. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


