---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: '您必須在NetApp CN1610 叢集交換器上安裝 FASTPATH 軟體和參考設定檔 (RCF)。' 
---
= 準備在NetApp叢集交換器上安裝 FASTPATH 軟體和 RCF。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須在NetApp CN1610 叢集交換器上安裝 FASTPATH 軟體和參考設定檔 (RCF)。

.開始之前
* 此集群必須是功能齊全的集群。
* 叢集網路介面卡（NIC）不得有任何缺陷，叢集交換器上的所有連接連接埠必須功能正常。
* 叢集所有連接埠必須處於啟用狀態。
* 所有叢集邏輯介面（LIF）必須處於啟用狀態，且不得已遷移。
* ONTAP （權限：進階） `cluster ping-cluster -node node1`命令必須表明 `larger than PMTU communication`在所有路徑上都取得了成功。
* 您必須查閱交換器相容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交換機"^]此頁面列出了支援的 FASTPATH、RCF 和ONTAP版本。
+
RCF 和 FASTPATH 版本中的指令語法可能存在指令依賴關係。




NOTE: 由於安全性問題，RCF 版本 1.2 中已明確停用對 Telnet 的支援。為避免安裝 RCF 1.2 時出現連線問題，必須確認安全殼層 (SSH) 已啟用。這 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 交換器管理員指南"^]包含更多關於 SSH 的資訊。

.關於此任務
本流程中的範例使用以下開關和節點命名規則：

* 本文檔中的程式使用叢集式Data ONTAP 8.2 語法。因此，叢集 Vserver、LIF 名稱和 CLI 輸出將與Data ONTAP 8.3 中的不同。
* 這兩台NetApp交換器分別是 cs1 和 cs2。
* 這兩個簇 LIF 分別是 clus1 和 clus2。
* 虛擬伺服器為 vs1 和 vs2。
* 這 `cluster::*>`prompt 指示叢集名稱。
* 每個節點上的叢集連接埠分別命名為 e1a 和 e2a。
+
這 https://hwu.netapp.com/["Hardware Universe"^]包含有關您的平台支援的實際集群連接埠的更多資訊。

* NetApp叢集交換器支援的交換器間連結 (ISL) 為連接埠 0/13 至 0/16。
* NetApp叢集交換器支援的節點連接埠為 0/1 至 0/12。


程式分為兩部分：

* link:install-fastpath-software.html["安裝 FASTPATH 軟體"]介紹如何安裝 FASTPATH 軟體。
* link:install-rcf-file.html["在 CN1610 交換器上安裝 RCF"]描述如何安裝 RCF。

