---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: 您可以透過執行特定​​步驟序列，在不中斷業務的情況下更換有缺陷的NetApp CN1610 叢集交換器。 
---
= 更換NetApp CN1610 叢集交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請依照下列步驟更換叢集網路中發生故障的NetApp CN1610 交換器。這是一個非侵入性手術（NDU）。



== 審查要求

.開始之前
在進行交換器更換之前，必須滿足以下條件：在目前環境和待更換交換器上，現有叢集和網路基礎設施均需滿足這些條件：

* 必須驗證現有叢集是否完全功能正常，至少有一個完全連接的叢集交換器。
* 叢集中的所有連接埠必須處於啟用狀態。
* 叢集中的所有邏輯介面（LIF）必須處於啟用狀態，且不得已被遷移。
* ONTAP叢集 `ping-cluster -node node1`命令必須表示所有路徑上的基本連接和大於 PMTU 的通訊均已成功。




== 啟用控制台日誌記錄

NetApp強烈建議您在使用的裝置上啟用控制台日誌記錄，並在更換交換器時執行以下操作：

* 維護期間請保持AutoSupport功能啟用。
* 在維護前後觸發維護AutoSupport，以在維護期間停用案例建立。請參考這篇知識庫文章 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92：如何在計劃維護視窗期間抑制自動建立案例"^]更多詳情請見下文。
* 啟用所有 CLI 會話​​的會話日誌記錄。有關如何啟用會話日誌記錄的說明，請查看此知識庫文章中的「記錄會話輸出」部分。 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何配置 PuTTY 以獲得與ONTAP系統的最佳連接"^] 。




== 更換開關

.關於此任務
您必須從叢集 LIF 所在的節點執行遷移叢集 LIF 的命令。

本流程中的範例使用下列叢集交換器和節點命名規則：

* 這兩個 CN1610 叢集交換器的名稱是 `cs1`和 `cs2`。
* 待更換的CN1610交換器（故障交換器）的名稱是 `old_cs1`。
* 新型CN1610交換器（替代交換器）的名稱是 `new_cs1`。
* 未被替換的夥伴交換器的名稱是 `cs2`。


.步驟
. 確認啟動設定檔與運行設定檔一致。您必須將這些文件保存到本地，以便在替換過程中使用。
+
以下範例中的設定指令適用於 FASTPATH 1.2.0.7：

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. 建立運行設定檔副本。
+
以下範例中的指令適用於 FASTPATH 1.2.0.7：

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: 您可以使用除以下任何檔案名稱之外的任何檔案名稱。 `CN1610_CS_RCF_v1.2.scr` 。檔案名稱必須帶有 *.scr* 副檔名。

. [[step3]]將交換器的運作設定檔儲存到外部主機，以便進行更換。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. 請核對交換器和ONTAP版本是否在相容性矩陣中匹配。參見 https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601 和 CN1610 交換機"^]詳情請見頁面。
. 從 https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["軟體下載頁面"^]在NetApp支援網站上，選擇NetApp叢集交換機，下載對應的 RCF 和 FASTPATH 版本。
. 使用 FASTPATH、RCF 和已儲存的設定簡單檔案傳輸協定 (TFTP) 伺服器 `.scr`用於新交換器的文件。
. 將序列埠（交換器右側標示為「IOIOI」的 RJ-45 連接器）連接至具有終端模擬功能的可用主機。
. 在主機上，設定串口終端連線：
+
.. 9600波特
.. 8 位元數據
.. 1 停止位
.. 奇偶性：無
.. 流量控制：無


. 將管理連接埠（交換器左側的 RJ-45 扳手連接埠）連接到 TFTP 伺服器所在的相同網路。
. 準備連接到網路和 TFTP 伺服器。
+
如果您使用的是動態主機設定協定 (DHCP)，目前無需為交換器設定 IP 位址。服務連接埠預設為使用 DHCP。 IPv4 和 IPv6 協定設定中的網路管理連接埠皆設定為「無」。如果您的扳手連接埠連接到具有 DHCP 伺服器的網絡，則伺服器設定將自動配置。

+
要設定靜態 IP 位址，您應該使用 serviceport protocol、network protocol 和 serviceport ip 命令。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. 如果 TFTP 伺服器位於筆記型電腦上，則可以選擇使用標準乙太網路線將 CN1610 交換器連接到筆記型電腦，然後使用備用 IP 位址在同一網路中設定其網路連接埠。
+
你可以使用 `ping`用於驗證地址的命令。如果無法建立連接，則應使用非路由網絡，並使用 IP 192.168.x 或 172.16.x 設定服務連接埠。稍後您可以將服務連接埠重新設定為生產管理 IP 位址。

. （選用）驗證並安裝適用於新交換器的 RCF 和 FASTPATH 軟體的相應版本。如果您已確認新交換器已正確設置，且不需要更新 RCF 和 FASTPATH 軟體，則應前往步驟 13。
+
.. 請驗證新的交換器設定。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. 將 RCF 檔案下載到新交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. 確認 RCF 已下載到交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. 將 RCF 應用於 CN1610 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. 儲存運作設定文件，以便重新啟動交換器時將其設為啟動設定檔。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 將鏡像下載到 CN1610 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. 透過重新啟動交換器來執行新的活動啟動映像。
+
必須重新啟動交換機，步驟 6 的指令才能反映新的映像。輸入重新載入指令後，可能會看到兩種不同的回應視圖。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. 將舊交換器上儲存的設定檔複製到新交換器上。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. 將先前儲存的設定套用到新交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 將運行設定檔儲存到啟動設定檔。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ 是維護視窗的持續時間，單位為小時。

+
[NOTE]
====
AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

====
. 在新交換器 new_cs1 上，以管理員使用者身分登錄，並關閉所有連接到節點叢集介面的連接埠（連接埠 1 到 12）。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. 將叢集 LIF 從連接到 old_cs1 交換器的連接埠遷移。
+
您必須從目前節點的管理介面遷移每個叢集 LIF。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. 確認所有叢集 LIF 都已移動到每個節點上的對應叢集連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. 關閉連接到您更換的交換器的集群連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. 驗證集群的健康狀況。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 請確認連接埠已關閉。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. 在交換器 cs2 上，關閉 ISL 連接埠 13 至 16。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. 確認儲存管理員是否已準備好更換交換器。
. 從 old_cs1 交換器上拆下所有電纜，然後將電纜連接到 new_cs1 交換器上的相同連接埠。
. 在 cs2 交換器上，啟用 ISL 連接埠 13 至 16。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. 啟用新交換器上與叢集節點關聯的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. 在單一節點上，啟動連接到被替換交換器的叢集節點端口，然後確認鏈路已建立。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. 還原與步驟 25 中連接埠關聯的叢集 LIF。
+
在本例中，如果「Is Home」列為真，則節點 1 上的 LIF 將會成功還原。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. 如果第一個節點的叢集 LIF 已啟動並恢復到其主端口，則重複步驟 25 和 26 以啟動叢集連接埠並恢復叢集中其他節點的叢集 LIF。
. 顯示叢集中節點的相關資訊。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 確認更換後的交換器上的啟動設定檔和運作設定檔是否正確。此設定檔應與步驟 1 中的輸出相符。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


