---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: 您可以執行特定的工作順序、以不中斷營運的方式更換有瑕疵的 NetApp CN1610 叢集交換器。 
---
= 更換 NetApp CN1610 叢集交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請遵循下列步驟、在叢集網路中更換有瑕疵的 NetApp CN1610 交換器。這是一項不中斷營運的程序（ NDU ）。



== 檢閱要求

.開始之前
在執行交換器更換之前、在目前環境中以及在現有叢集和網路基礎架構的更換交換器上執行交換器更換之前、必須先存在下列條件：

* 必須使用至少一個完全連接的叢集交換器、驗證現有叢集是否完全正常運作。
* 所有叢集連接埠都必須為 * 上 * 。
* 所有叢集邏輯介面（生命）都必須啟動、而且不得移轉。
* ONTAP 叢集 `ping-cluster -node node1` 命令必須指出所有路徑上的基本連線能力和大於 PMTU 的通訊均已成功。




== 啟用主控台記錄

NetApp 強烈建議您在使用的裝置上啟用主控台記錄功能、並在更換交換器時採取下列動作：

* 在維護期間保持啟用 AutoSupport 。
* 在維護前後觸發維護 AutoSupport 、以在維護期間停用案例建立。請參閱本知識庫文件 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92 ：如何在排程的維護期間內、禁止自動建立案例"^] 以取得更多詳細資料。
* 啟用任何 CLI 工作階段的工作階段記錄。如需如何啟用工作階段記錄的說明、請參閱本知識庫文件中的「記錄工作階段輸出」一節 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何設定 Putty 以最佳化連線至 ONTAP 系統"^]。




== 更換交換器

.關於這項工作
您必須執行命令、從裝載叢集LIF的節點移轉叢集LIF。

本程序中的範例使用下列叢集交換器和節點命名法：

* 兩台 CN1610 叢集交換器的名稱為 `cs1` 和 `cs2`。
* 要更換的 CN1610 交換器（故障交換器）名稱為 `old_cs1`。
* 新的 CN1610 交換器（替換交換器）名稱為 `new_cs1`。
* 未被取代的合作夥伴交換器名稱為 `cs2`。


.步驟
. 確認啟動組態檔案符合執行中組態檔案。您必須將這些檔案儲存在本機、以便在更換期間使用。
+
下列範例中的組態命令適用於 FastPath 1.2.0.7 ：

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. 建立執行中組態檔案的複本。
+
下列範例中的命令適用於 FastPath 1.2.0.7 ：

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: 您可以使用任何檔案名稱、但不包括 `CN1610_CS_RCF_v1.2.scr`。檔案名稱的副檔名必須是 * 。 scr* 。

. [[step3]] 將交換器的執行組態檔案儲存至外部主機、以準備更換。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. 確認交換器和 ONTAP 版本符合相容性對照表。請參閱 https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601與CN1610交換器"^] 頁面以取得詳細資料。
. 從 https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["軟體下載頁面"^] 在 NetApp 支援網站 上、選取 NetApp 叢集交換器以下載適當的 RCF 和 FastPath 版本。
. 使用 FastPath 、 RCF 和儲存的組態設定簡單檔案傳輸協定（ TFTP ）伺服器 `.scr` 用於新交換器的檔案。
. 將序列連接埠（交換器右側標示為「 IOIOIOI 」的 RJ-45 連接器）連接至具有終端機模擬的可用主機。
. 在主機上、設定序列終端連線設定：
+
.. 9600傳輸速率
.. 8個資料位元
.. 1停止位元
.. 同位元檢查：無
.. 流程控制：無


. 將管理連接埠（交換器左側的RJ-45扳手連接埠）連接至您的TFTP伺服器所在的相同網路。
. 準備使用 TFTP 伺服器連線至網路。
+
如果您使用動態主機組態傳輸協定（ DHCP ）、此時不需要為交換器設定 IP 位址。預設會將服務連接埠設定為使用 DHCP 。對於 IPv4 和 IPv6 通訊協定設定、網路管理連接埠設為「無」。如果您的扳手連接埠已連線至具有 DHCP 伺服器的網路、則會自動設定伺服器設定。

+
若要設定靜態 IP 位址、您應該使用 ServicePort 傳輸協定、網路傳輸協定和 ServicePort IP 命令。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. 或者、如果 TFTP 伺服器位於筆記型電腦上、則使用標準乙太網路纜線將 CN1610 交換器連接至筆記型電腦、然後在同一個網路中以替代 IP 位址設定其網路連接埠。
+
您可以使用 `ping` 用於驗證位址的命令。如果無法建立連線、則應使用非路由網路、並使用 IP 192.168.8.x 或 172.16.x 設定服務連接埠您可以稍後將服務連接埠重新設定為正式作業管理 IP 位址。

. 您也可以針對新交換器、驗證並安裝適當版本的 RCF 和 FastPath 軟體。如果您已確認新交換器已正確設定、且不需要更新 RCF 和 FastPath 軟體、請前往步驟 13 。
+
.. 驗證新的交換器設定。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. 將 RCF 下載至新的交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. 確認 RCF 已下載至交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. 將 RCF 套用至 CN1610 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. 儲存執行中的組態檔、以便在重新開機時成為啟動組態檔。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 將映像下載到 CN1610 交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. 重新啟動交換器以執行新的作用中開機映像。
+
必須重新啟動交換器、步驟 6 中的命令才能反映新映像。輸入 reload 命令後可能會看到兩種回應檢視。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. 將保存的配置文件從舊交換機複製到新交換機。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. 將先前儲存的組態套用至新交換器。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 將執行中的組態檔儲存至啟動組態檔。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 下列訊息來抑制自動建立案例：「System Node AutoSupport 支援功能叫用節點*-type all - Message MAn=xh」
+
_x_是維護時段的持續時間（以小時為單位）。

+
[NOTE]
====
此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

====
. 在新的交換器 new_CS1 上、以管理員使用者身分登入、並關閉所有連接至節點叢集介面的連接埠（連接埠 1 到 12 ）。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. 從連接至 old_CS1 交換器的連接埠移轉叢集生命。
+
您必須從目前節點的管理介面移轉每個叢集 LIF 。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. 確認所有叢集生命體已移至每個節點上適當的叢集連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. 關閉連接至您所更換之交換器的叢集連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. 驗證叢集的健全狀況。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 確認連接埠已關閉。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. 在交換器 CS2 上、關閉 ISL 連接埠 13 到 16 。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. 驗證儲存管理員是否已準備好更換交換器。
. 從 old_CS1 交換器拔下所有纜線、然後將纜線連接至 new_CS1 交換器上的相同連接埠。
. 在 CS2 交換器上、開啟 ISL 連接埠 13 到 16 。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. 打開與叢集節點相關聯的新交換器連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. 在單一節點上、開啟連接至更換交換器的叢集節點連接埠、然後確認連結已開啟。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. 在同一個節點上還原步驟 25 中與連接埠相關聯的叢集生命週期。
+
在此範例中、如果「是首頁」欄為真、則節點 1 上的生命將成功還原。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. 如果第一個節點的叢集 LIF 已啟動並還原至其主連接埠、請重複步驟 25 和 26 、以啟動叢集連接埠、並在叢集中的其他節點上還原叢集生命週期。
. 顯示叢集中節點的相關資訊。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 確認更換的交換器上的啟動組態檔和執行組態檔正確無誤。此組態檔應符合步驟 1 中的輸出。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」


