---
permalink: switch-netapp-cn1610/task-install-an-rcf-on-a-cn1610-switch.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 當您安裝參考組態檔（RCF）時、必須先將叢集l生命 從交換器CS2移除。安裝並驗證RCF之後、便可將LIF移回。 
---
= 在CN1610交換器上安裝參考組態檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您安裝參考組態檔（RCF）時、必須先將叢集l生命 從交換器CS2移除。安裝並驗證RCF之後、便可將LIF移回。

.開始之前
您必須已儲存目前在交換器上執行的組態。

.步驟
. 儲存您目前的交換器組態資訊：「寫入記憶體」
+
以下範例顯示目前交換器組態儲存至交換器CS2上的啟動組態（「startup組態」）檔案：

+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 在每個節點的主控台上、將clus2移轉至連接埠e1a：「網路介面移轉」
+
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
. 在每個節點的主控台上、確認移轉發生：「network interface show -role cluster」（網路介面顯示角色叢集）
+
以下範例顯示、clus2已移轉至兩個節點上的連接埠e1a：

+
[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
. 關閉兩個節點上的連接埠E2A：「網路連接埠修改」
+
以下範例顯示兩個節點上的連接埠E2A正在關機：

+
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
. 確認兩個節點上的連接埠E2A均已關機：「network port show」（網路連接埠顯示）
+
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
. 關閉使用中NetApp交換器CS1上的ISL連接埠。
+
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
. 將RCF複製到交換器。
+

NOTE: 您必須先將「.scr」副檔名設定為檔案名稱的一部分、才能叫用指令碼。此副檔名是FastPath作業系統的副檔名。

+
交換器會在下載指令碼到交換器時自動驗證指令碼、然後輸出會移至主控台。

+
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
. 確認已下載指令碼、並以您指定的檔案名稱儲存。
+
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
. 驗證指令碼。
+

NOTE: 指令碼會在下載期間驗證、以驗證每一行是否為有效的交換器命令列。

+
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
. 將指令碼套用至交換器。
+
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
. 確認交換器已實作您的變更。
+
[listing]
----
(cs2) # show running-config
----
+
此範例顯示交換器上的「執行組態」檔案。您必須將檔案與RCF進行比較、以驗證您設定的參數是否符合預期。

. 儲存變更。
. 將「執行組態」檔案設為標準檔案。
+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
. 重新啟動交換器、確認「執行組態」檔案正確無誤。
+
重新開機完成後、您必須登入、檢視「執行組態」檔案、然後在介面3/64上尋找說明、該介面是RCF的版本標籤。

+
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
. 啟動使用中交換器CS1上的ISL連接埠。
+
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
. 驗證ISL是否正常運作：「How port-channel 3/1」
+
「Link State（連結狀態）」欄位應顯示「Up（啟動）」。

+
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. 在兩個節點上都顯示叢集連接埠E2A：「網路連接埠修改」
+
以下範例顯示節點1和節點2上正在啟動的連接埠E2A：

+
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
. 驗證兩個節點上的端口E2A是否均已打開：「network port show -_role cluster」（網路連接埠show -_role叢集）
+
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
. 在兩個節點上、回復與連接埠E2A相關的clus2：「網路介面回復」
+
LIF可能會自動回復、視ONTAP 您的版本而定。

+
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
. 驗證LIF現在位於兩個節點上的主節點（'true'）：「network interface show -_role cluster _」（網路介面顯示-_role叢集_）
+
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
. 查看節點成員的狀態：「叢集顯示」
+
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
. 如果您對軟體版本和交換器設定滿意、請將「執行組態」檔案複製到「儲存組態」檔案。
+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 重複步驟1到步驟22、升級另一臺交換器CS1上的RCF。


*相關資訊*

https://support.netapp.com/["NetApp支援"^]
