---
permalink: switch-netapp-cn1610/task-install-fastpath-software-and-rcf-files-on-netapp-cluster-switches.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: 安裝步驟與執行ONTAP 本版本的NetApp CN1601管理交換器和CN1610叢集交換器相同。不過、這兩種機型需要不同的軟體和RCT。 
---
= 在執行ONTAP NetApp的叢集交換器上安裝FastPath軟體和RCV、這些交換器執行的是NetApp 8.3.1及更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝步驟與執行ONTAP 本版本的NetApp CN1601管理交換器和CN1610叢集交換器相同。不過、這兩種機型需要不同的軟體和RCT。

.開始之前
* 叢集必須是運作正常的叢集。
* 叢集NIC必須無故障、而且兩個叢集交換器上的所有連接埠都必須正常運作。
* 所有叢集連接埠都必須正常運作。
* 所有叢集邏輯介面（LIF）都必須正常運作、而且不得移轉。
* 這個指令（權限：進階）「叢集ping叢集節點節點節點1」必須指出、所有路徑上的「大於PMTU通訊」都會成功。ONTAP
* 您必須使用受支援的FastPath、RCF及ONTAP 支援的版本。
+
RCF和FastPath版本中的命令語法之間可能存在命令相依性。交換器相容性頁面會列出支援的版本。請參閱 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601與CN1610交換器"^] 以取得詳細資料。



本程序中的範例使用下列交換器和節點命名法：

* 兩個NetApp交換器名稱分別是CS1和CS2。
* 叢集邏輯介面（LIF）名稱為node1_clus1、node1_clus2為node1、node2_clus1為node2_clus1、node2_clus2為node2。
* 儲存虛擬機器（SVM）名稱為叢集。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 每個節點上的叢集連接埠名稱為e0a和e0b。
+
。 https://hwu.netapp.com/["Hardware Universe"^] 包含平台所支援的實際叢集連接埠。

* NetApp叢集交換器支援的交換器間連結（ISL）是0/13到0/16的連接埠。
* NetApp叢集交換器支援的節點連線是連接埠0/1到0/12。
* 此程序的範例會在第二個交換器_CS2_上開始升級。
* 本程序中的範例使用兩個節點、但叢集中最多可有24個節點。
* 範例和輸出可能會因FastPath、RCF和ONTAP 其他版本的不同而有所差異。


.步驟
. 顯示叢集上網路連接埠的相關資訊：
+
「網路連接埠show -_IPSpace叢集_」

+
下列範例顯示命令的輸出類型：

+
[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
. 顯示叢集上有關生命的資訊：
+
「網路介面show -_role叢集_」

+
以下範例顯示叢集上的邏輯介面。在此範例中、「-role」參數會顯示與叢集連接埠相關聯的lifs資訊：

+
[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
. 在每個節點上、使用節點管理LIF、將節點1上的節點1_clus2移轉至e0a、並將節點2上的節點2_clus2移轉至節點2上的e0a：
+
網路介面移轉

+
您必須在控制器主控台上輸入擁有各自叢集生命的命令。

+
[listing]
----

cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
+

NOTE: 對於此命令、叢集名稱區分大小寫、命令應在每個節點上執行。無法在一般叢集LIF中執行此命令。

. 在節點上使用「network interface show」命令來驗證是否已進行移轉。
+
以下範例顯示clus2已移轉至節點node1和node2上的連接埠e0a：

+
[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
. 將權限層級變更為進階、並在系統提示您繼續時輸入y：
+
"進階權限"

+
出現進階提示（*>）。

. 關閉兩個節點上的叢集連接埠e0b：
+
「網路連接埠修改-node_node_name_-port _port_name_-up管理假」

+
您必須在控制器主控台上輸入擁有各自叢集生命的命令。

+
下列範例顯示在所有節點上關閉連接埠e0b的命令：

+
[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
. 確認兩個節點上的連接埠e0b均已關機：
+
「網路連接埠展示」

+
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
. 關閉CS1上的交換器間連結（ISL）連接埠。
+
[listing]
----

(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
. 在CS2上備份目前使用中的映像。
+
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
. 驗證FastPath軟體的執行版本。
+
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
. 將映像檔下載到交換器。
+
將映像檔複製到作用中映像、表示當您重新開機時、該映像會建立執行中的FastPath版本。上一個映像仍可作為備份使用。

+
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 確認目前和下一個作用中的開機映像版本：
+
「如何啟動bootvar

+
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
. 將新映像版本的相容RCF安裝至交換器。
+
如果RCF版本已正確、請跳至步驟18以啟動ISL連接埠。

+
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: 在啟動指令碼之前、必須先將「.scr」副檔名設定為檔案名稱的一部分。此副檔名適用於FastPath作業系統。

+
交換器會在指令碼下載到交換器時自動驗證該指令碼。輸出會移至主控台。

. 確認已下載指令碼並儲存至您指定的檔案名稱。
+
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
. 將指令碼套用至交換器。
+
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
. 確認變更已套用至交換器、然後儲存：
+
「如何執行設定」

+
[listing]
----
(cs2) #show running-config
----
. 儲存執行中的組態、使其成為重新啟動交換器時的啟動組態。
+
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 重新啟動交換器。
+
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
. 再次登入、然後確認交換器正在執行新版本的FastPath軟體。
+
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
+
重新開機完成後、您必須登入以驗證映像版本、檢視執行中的組態、並在介面3/64（RCF的版本標籤）上尋找說明。

. 啟動使用中交換器CS1上的ISL連接埠。
+
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
. 驗證ISL是否正常運作：
+
「How port-channel 3/1」

+
「Link State（連結狀態）」欄位應顯示「Up（啟動）」。

+
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. 在所有節點上啟動叢集連接埠e0b：
+
網路連接埠修改

+
您必須在控制器主控台上輸入擁有各自叢集生命的命令。

+
以下範例顯示節點1和節點2上正在啟動的連接埠e0b：

+
[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
. 確認所有節點上的連接埠e0b都已開啟：
+
「網路連接埠show -IPSpace叢集」

+
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
. 確認LIF現在位於兩個節點上的主節點（「true」）：
+
「網路介面show -_role叢集_」

+
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
. 顯示節點成員的狀態：
+
「叢集展示」

+
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. 返回管理權限層級：
+
「et -priv. admin」

. 重複步驟1到18、升級另一台交換器CS1上的FastPath軟體和RCF。
+
|===
| 如果您... | 然後... 


 a| 
不需要安裝RCF
 a| 
請移至步驟18完成安裝。



 a| 
需要安裝RCF
 a| 
請前往步驟13。

|===

