---
permalink: switch-netapp-cn1610/task-migrate-from-a-switchless-cluster-to-a-switched-netapp-cn1610-cluster-environment.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: 如果您有現有的雙節點無交換式叢集環境、則可使用CN1610叢集網路交換器移轉至雙節點交換式叢集環境、以便擴充至兩個節點以外的環境。 
---
= 從無交換器叢集環境移轉至交換式NetApp CN1610叢集環境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有現有的雙節點無交換式叢集環境、則可使用CN1610叢集網路交換器移轉至雙節點交換式叢集環境、以便擴充至兩個節點以外的環境。

.開始之前
雙節點無交換器組態：

* 雙節點無交換器組態必須正確設定並正常運作。
* 節點必須執行ONTAP 的是版本8.2或更新版本。
* 所有叢集連接埠都必須處於「up」狀態。
* 所有叢集邏輯介面（LIF）都必須處於「up」（開機）狀態、而且必須位於主連接埠上。


CN1610叢集交換器組態：

* CN1610叢集交換器基礎架構必須在兩台交換器上都具備完整功能。
* 兩台交換器都必須具備管理網路連線能力。
* 叢集交換器必須有主控台存取權。
* CN1610節點對節點交換器和交換器對交換器連線必須使用雙軸纜線或光纖纜線。
+
。 https://hwu.netapp.com/["Hardware Universe"^] 包含纜線的詳細資訊。

* 交換器間連結（ISL）纜線必須連接至兩個CN1610交換器上的連接埠13至16。
* 必須完成兩個CN1610交換器的初始自訂。
+
任何先前的站台自訂（例如、SMTP、SNMP和SSH）都應該複製到新的交換器。



.關於這項工作
本程序中的範例使用下列叢集交換器和節點命名法：

* CN1610交換器的名稱為CS1和CS2。
* lifs的名稱為clus1和clus2。
* 節點名稱為node1和node2。
* 「cluster：*>」提示會指出叢集的名稱。
* 此程序中使用的叢集連接埠為e1a和E2A。
+
。 https://hwu.netapp.com/["Hardware Universe"^] 包含平台實際叢集連接埠的最新資訊。



.步驟
. 請將權限等級變更為進階、並在系統提示您繼續時輸入「y」：「et -priv榮幸 進階」
+
出現進階提示（*>）。

. 如果AutoSupport 此叢集啟用了「支援功能」、請叫用AutoSupport 「系統節點AutoSupport 支援功能叫用節點*-type all -most MAn=xh」訊息來禁止自動建立案例
+
_x_是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

+
下列命令會禁止自動建立兩小時的個案：

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 停用新叢集交換器CS1和CS2上的所有面向節點的連接埠（非ISL連接埠）。
+
您不得停用ISL連接埠。

+
以下範例顯示、交換器CS1上的節點對向連接埠1至12已停用：

+
[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
+
以下範例顯示、交換器CS2上的節點對向連接埠1到12已停用：

+
[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
. 驗證兩個CN1610叢集交換器CS1和CS2之間的ISL和ISL實體連接埠是否為「up」：「How port-channel」
+
以下範例顯示交換器CS1上的ISL連接埠為「up」（開啟）：

+
[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
+
以下範例顯示交換器CS2上的ISL連接埠為「up」（開啟）：

+
[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
. 顯示鄰近裝置的清單：「How isdp neighbors」
+
此命令提供有關連線至系統之裝置的資訊。

+
下列範例列出交換器CS1上的鄰近裝置：

+
[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
+
下列範例列出交換器CS2上的鄰近裝置：

+
[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
. 顯示叢集連接埠清單：「network port show」
+
下列範例顯示可用的叢集連接埠：

+
[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
. 確認每個叢集連接埠都已連接至其合作夥伴叢集節點上的對應連接埠：「RUN * CDPD show-neighbors」（執行* CDPD show -neighbors）
+
下列範例顯示叢集連接埠e1a和E2A已連接至其叢集合作夥伴節點上的相同連接埠：

+
[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
. 驗證所有的叢集生命體都是「up」（正常）且正常運作：「network interface show -vserver Cluster」（網路介面show -vserver叢集）
+
每個叢集LIF都應該在「is Home」欄位中顯示「true」。

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
+

NOTE: 必須從本機節點執行步驟10到13中的下列修改和移轉命令。

. 確認所有叢集連接埠均為「up」（正常）：「network port show -IPSpace Cluster」（網路連接埠顯示-IPSpace叢集）
+
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. 在兩個節點上的叢集lust1和clus2上、將「-aut-revert」參數設為「假」：「網路介面修改」
+
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
+

NOTE: 對於8.3版及更新版本、請使用下列命令：「network interface modify -vserver cluster -lIF *-auto-revert假」

. Ping叢集連接埠以驗證叢集連線能力：「叢集ping叢集local」
+
命令輸出顯示所有叢集連接埠之間的連線能力。

. 將clus1移轉至每個節點主控台的連接埠E2A：「網路介面移轉」
+
以下範例顯示將clus1移轉至節點1和節點2上的連接埠E2A的程序：

+
[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
+

NOTE: 對於8.3版及更新版本、請使用下列命令：「network interface mIGRADE -vserver cluster -lIF clus1 -dest-Node node1 -dest-port E2A」

. 驗證是否進行了移轉：「network interface show -vserver Cluster」（網路介面show -vserver叢集）
+
以下範例驗證clus1是否已移轉至節點1和節點2上的連接埠E2A：

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
. 關閉兩個節點上的叢集連接埠e1a：「網路連接埠修改」
+
以下範例說明如何關閉節點1和節點2上的連接埠e1a：

+
[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
. 驗證連接埠狀態：「network port show」（網路連接埠顯示）
+
以下範例顯示節點1和節點2上的連接埠e1a為「自己的」：

+
[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. 從節點1上的叢集連接埠e1a拔下纜線、然後使用CN1610交換器支援的適當纜線、將e1a連接至叢集交換器CS1上的連接埠1。
+
。 link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] 包含纜線的詳細資訊。

. 從節點2上的叢集連接埠e1a拔下纜線、然後使用CN1610交換器支援的適當纜線、將e1a連接至叢集交換器CS1上的連接埠2。
. 在叢集交換器CS1上啟用所有面向節點的連接埠。
+
下列範例顯示交換器CS1上已啟用連接埠1到12：

+
[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
. 在每個節點上啟用第一個叢集連接埠e1a：「網路連接埠修改」
+
以下範例說明如何在節點1和節點2上啟用連接埠e1a：

+
[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
. 驗證所有的叢集連接埠是否均為「up」：「network port show -IPSpace Cluster」
+
以下範例顯示節點1和節點2上的所有叢集連接埠均為「up」：

+
[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. 將兩個節點上的clus1（先前已移轉）還原為e1a：「網路介面回復」
+
以下範例說明如何將clus1還原為節點1和節點2上的連接埠e1a：

+
[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
+

NOTE: 對於8.3版及更新版本、請使用下列命令：「network interface revert -vserver cluster -lIF <nodename_clus<N>>'

. 驗證所有的叢集生命體都是「up」（正常運作）、並在「is Home」（原為首頁）欄中顯示為「true」（真）：「network interface show -vserver Cluster」（網路介面show -vserver叢集）
+
以下範例顯示、節點1和節點2上的所有lifs均為「up」、且「is Home」欄位結果為「true」：

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
. 顯示叢集中節點狀態的相關資訊：「叢集顯示」
+
下列範例顯示叢集中節點的健全狀況和資格資訊：

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. 將clus2移轉至每個節點主控台的連接埠e1a：「網路介面移轉」
+
以下範例顯示將clus2移轉至節點1和節點2上的連接埠e1a的程序：

+
[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
+

NOTE: 對於8.3版及更新版本、請使用下列命令：「network interface mIGRADE -vserver cluster -lIF node1_clus2 -dest-Node node1 -dest-port e1a」

. 驗證是否進行了移轉：「network interface show -vserver Cluster」（網路介面show -vserver叢集）
+
以下範例驗證clus2是否已移轉至節點1和節點2上的連接埠e1a：

+
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
. 關閉兩個節點上的叢集連接埠E2A：「網路連接埠修改」
+
以下範例說明如何關閉節點1和節點2上的連接埠E2A：

+
[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
. 驗證連接埠狀態：「network port show」（網路連接埠顯示）
+
以下範例顯示、節點1和節點2上的連接埠E2A是「自己」：

+
[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. 從節點1上的叢集連接埠E2A拔下纜線、然後使用CN1610交換器所支援的適當纜線、將E2A連接至叢集交換器CS2上的連接埠1。
. 從節點2上的叢集連接埠E2A拔下纜線、然後使用CN1610交換器所支援的適當纜線、將E2A連接至叢集交換器CS2上的連接埠2。
. 在叢集交換器CS2上啟用所有面向節點的連接埠。
+
下列範例顯示交換器CS2上已啟用連接埠1到12：

+
[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
. 在每個節點上啟用第二個叢集連接埠E2A：
+
以下範例說明如何在節點1和節點2上啟用連接埠E2A：

+
[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
. 驗證所有的叢集連接埠是否均為「up」：「network port show -IPSpace Cluster」
+
以下範例顯示節點1和節點2上的所有叢集連接埠均為「up」：

+
[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
. 將兩個節點上的clus2（先前已移轉）回復為E2A：「網路介面回復」
+
以下範例說明如何將clus2還原為節點1和節點2上的連接埠E2A：

+
[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
+

NOTE: 對於8.3版及更新版本、命令為：「cluster::*> network interface revert -vserver cluster -lIF node1_clus2」及「cluster:*> network interface revert -vserver cluster -lIF node2_clus2」

. 驗證所有介面在「is Home」欄位中是否顯示「true」：「network interface show -vserver Cluster」
+
以下範例顯示、節點1和節點2上的所有lifs均為「up」、且「is Home」欄位結果為「true」：

+
[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
. Ping叢集連接埠以驗證叢集連線能力：「叢集ping叢集local」
+
命令輸出顯示所有叢集連接埠之間的連線能力。

. 驗證兩個節點是否都有兩個連接到每個交換器：「How isdp neighbors」
+
以下範例顯示兩個交換器的適當結果：

+
[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
. 顯示組態中裝置的相關資訊：「網路裝置探索秀」
. 使用進階權限命令「network options detect-switchless modify」停用兩個節點上的無交換器組態設定
+
下列範例顯示如何停用無交換器組態設定：

+
[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
+

NOTE: 若為9.2版及更新版本、請跳過此步驟、因為組態會自動轉換。

. 確認設定已停用：「網路選項detect-switchless cluster show」
+
以下範例中的「假」輸出顯示組態設定已停用：

+
[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
+

NOTE: 對於9.2版及更新版本、請等待「啟用無交換器叢集」設定為假。這可能需要三分鐘的時間。

. 將叢集clus1和clus2設定為在每個節點上自動還原、並確認：
+
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
+

NOTE: 對於8.3版及更新版本、請使用下列命令：「network interface modify -vserver cluster -lIF *-auta-f還原true」、以在叢集中的所有節點上啟用自動還原功能。

. 驗證叢集中節點成員的狀態：「cluster show」（叢集顯示）
+
下列範例顯示叢集中節點的健全狀況和資格資訊：

+
[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
. 如果您禁止自動建立個案、請叫用AutoSupport 下列消息來重新啟用此功能：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
. 將權限等級變更回admin：「et -priv. admin」


*相關資訊*

http://hwu.netapp.com["Hardware Universe"^]

http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601與CN1610說明頁面"^]

https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["CN1601與CN1610交換器設定與組態指南"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp知識庫文件編號1010449：如何在排程的維護期間、抑制自動建立案例"^]
