---
permalink: switch-cisco-92300/install-nxos-rcf.html 
sidebar: sidebar 
keywords: install rcf,rcf configure 
summary: 您可以在初次設定Nexus 2300YC交換器之後安裝RCF。 
---
= 安裝參考組態檔（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在初次設定Nexus 2300YC交換器之後安裝RCF。

.交換器和節點命名法
本程序中的範例使用下列交換器和節點命名法：

* 兩個Cisco交換器的名稱分別為「CS1」和「CS2」。
* 節點名稱是「node1」和「node2」。
* 叢集LIF的名稱為節點1的「node1_clus1」和「node1_clus2」、節點2的「node2_clus1」和「node2_clus2」。
* 「cluster1：*：>」提示會指出叢集的名稱。
* 每個節點上的叢集連接埠名稱為「e0a」和「e0b」。
+
請參閱 link:https://hwu.netapp.com/Home/Index["_SUR1__ Hardware Universe"] 以取得平台所支援的實際叢集連接埠。



.支援的連接埠和節點連線
* Nexus 2300YC交換器支援的交換器間連結（ISL）為連接埠1/65和1/66。
* Nexus 2300YC交換器支援的節點連線為連接埠1/1到1/66。
* 本程序中的範例使用兩個節點。這些節點使用兩個10GbE叢集互連連接埠 `e0a` 和 `e0b`。請參閱 https://["Hardware Universe"^] 驗證平台上的叢集連接埠是否正確。


.開始之前
* 您必須擁有目前的RCF。
* 叢集必須完全正常運作（記錄中不應有錯誤或類似問題）。
* 如果您只安裝NX-OS並保留目前的RCF版本、則必須在RCF中檢查或設定所需的開機組態、以反映所需的開機映像。
* 如果您需要變更開機組態以反映目前的開機映像、則必須在重新套用RCF之前執行此動作、以便在未來重新開機時產生正確的版本。
* 您必須查閱上的交換器相容性表 https://["Cisco乙太網路交換器"^] 頁面、以取得支援ONTAP 的功能表、NX-OS和RCF版本。
* RCF中的命令語法與NX-OS版本中的命令語法之間可能存在相依性。


.關於這項工作
此程序需要同時使用ONTAP 支援指令和Cisco Nexus 9000系列交換器的指令；ONTAP 除非另有說明、否則會使用支援指令。

命令輸出可能會因ONTAP 不同版本的不相同而有所差異。

.步驟
. 將叢集交換器連接至管理網路。
. 使用ping命令來驗證與裝載RCF的伺服器的連線能力。
+
此範例可驗證交換器是否能以IP位址172.19.2.1連至伺服器：

+
[listing, subs="+quotes"]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 將RCF複製到Nexus 2300YC交換器：
+
[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/Nexus_92300YC_RCF_v1.0.2.txt*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/Nexus_92300YC_RCF_v1.0.2.txt  /bootflash/nxos.9.2.2.bin
/code/Nexus_92300YC_R  100% 9687   530.2KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 將RCF與交換器的執行組態合併：
+
[listing, subs="+quotes"]
----
cs2# *copy bootflash:Nexus_92300YC_RCF_v1.0.2.txt running-config*

Disabling ssh: as its enabled right now:
 generating ecdsa key(521 bits)......
generated ecdsa key

Enabling ssh: as it has been disabled
 this command enables edge port type (portfast) by default on all interfaces. You
 should now disable edge port type (portfast) explicitly on switched ports leading to hubs,
 switches and bridges as they may create temporary bridging loops.

Edge port type (portfast) should only be enabled on ports connected to a single
 host. Connecting hubs, concentrators, switches, bridges, etc...  to this
 interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
 Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet1/1 but will only
 have effect when the interface is in a non-trunking mode.

...

Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 在交換器上確認RCF已成功合併：
+
「如何執行設定」

+
[listing, subs="+quotes"]
----
cs2# *show running-config*
!Command: show running-config
!Running configuration last done at: Wed Apr 10 06:32:27 2019
!Time: Wed Apr 10 06:36:00 2019

version 9.2(2) Bios:version 05.33
switchname cs2
vdc cs2 id 1
  limit-resource vlan minimum 16 maximum 4094
  limit-resource vrf minimum 2 maximum 4096
  limit-resource port-channel minimum 0 maximum 511
  limit-resource u4route-mem minimum 248 maximum 248
  limit-resource u6route-mem minimum 96 maximum 96
  limit-resource m4route-mem minimum 58 maximum 58
  limit-resource m6route-mem minimum 8 maximum 8

feature lacp

no password strength-check
username admin password 5 $5$HY9Kk3F9$YdCZ8iQJ1RtoiEFa0sKP5IO/LNG1k9C4lSJfi5kesl
6  role network-admin
ssh key ecdsa 521

banner motd #
********************************************************************************
*                                                                              *
*  Nexus 92300YC Reference Configuration File (RCF) v1.0.2 (10-19-2018)        *
*                                                                              *
*  Ports 1/1  - 1/48: 10GbE Intra-Cluster Node Ports                           *
*  Ports 1/49 - 1/64: 40/100GbE Intra-Cluster Node Ports                       *
*  Ports 1/65 - 1/66: 40/100GbE Intra-Cluster ISL Ports                        *
*                                                                              *
********************************************************************************
----
. 儲存執行中的組態、以便在您重新啟動交換器時將其變成啟動組態：
+
[listing, subs="+quotes"]
----
cs2# *copy running-config startup-config*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 如需ONTAP 使用《系統叢集-交換器記錄設定密碼》和《系統叢集-交換器記錄啟用-收集》命令、請啟用乙太網路交換器健全狀況監視器記錄收集功能、以收集交換器相關的記錄檔
+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
. 重新啟動交換器、並驗證執行中的組態是否正確：
+
"重裝"

+
[listing, subs="+quotes"]
----
cs2# *reload*

This command will reboot the system. (y/n)?  [n] *y*
----

