---
permalink: switch-cisco-92300/install-nxos-rcf.html 
sidebar: sidebar 
keywords: install rcf,rcf configure 
summary: 首次設定 Nexus 92300YC 交換器後，您可以安裝 RCF。 
---
= 安裝參考設定檔（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次設定 Nexus 92300YC 交換器後，您可以安裝 RCF。

.交換器和節點命名法
本流程中的範例使用以下開關和節點命名規則：

* 這兩台Cisco交換器的名稱是： `cs1`和 `cs2`。
* 節點名稱是 `node1`和 `node2`。
* 集群 LIF 名稱為 `node1_clus1`和 `node1_clus2`對於節點1和 `node2_clus1`和 `node2_clus2`對於節點2。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 每個節點上的叢集連接埠都命名為 `e0a`和 `e0b`。
+
參見link:https://hwu.netapp.com/Home/Index["硬體宇宙"]針對您的平台實際支援的叢集連接埠。看 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["安裝HWU中沒有的設備還需要哪些額外資訊？"^] 有關交換器安裝要求的詳細資訊。



.支援的連接埠和節點連接
* Nexus 92300YC 交換器支援的交換器間連結 (ISL) 為連接埠 1/65 和 1/66。
* Nexus 92300YC 交換器支援的節點連接為連接埠 1/1 至 1/66。
* 本流程中的範例使用了兩個節點。這些節點使用兩個 10GbE 叢集互連端口 `e0a`和 `e0b`。參見 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]驗證平台上的叢集連接埠是否正確。


.開始之前
* 您必須持有最新的RCF。
* 叢集必須完全正常運作（日誌中不應有任何錯誤或類似問題）。
* 如果您僅安裝 NX-OS 並保留目前的RCF 版本，則必須已在 RCF 中檢查或設定所需的啟動配置，以反映所需的啟動映像。
* 如果需要更改啟動配置以反映目前的啟動映像，則必須在重新套用 RCF 之前進行更改，以便在以後的重新啟動中實例化正確的版本。
* 您一定查閱過交換器相容性表格。 https://support.netapp.com/NOW/download/software/cm_switches/["Cisco乙太網路交換機"^]支援的ONTAP、NX-OS 和 RCF 版本頁面。
* RCF 中的指令語法與 NX-OS 版本中的指令語法之間可能存在指令依賴關係。


.關於此任務
流程需要同時使用ONTAP指令和Cisco Nexus 9000 系列交換器指令；除非另有說明，否則使用ONTAP指令。

命令輸出可能因ONTAP版本不同而有所差異。

.步驟
. 將集群交換器連接到管理網路。
. 使用 ping 指令驗證與託管 RCF 的伺服器的連線性。
+
此範例驗證交換器可以存取 IP 位址為 172.19.2.1 的伺服器：

+
[listing, subs="+quotes"]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 將 RCF 檔案複製到 Nexus 92300YC 交換器：
+
[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/Nexus_92300YC_RCF_v1.0.2.txt*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/Nexus_92300YC_RCF_v1.0.2.txt  /bootflash/nxos.9.2.2.bin
/code/Nexus_92300YC_R  100% 9687   530.2KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 將 RCF 與交換器的運作配置合併：
+
[listing, subs="+quotes"]
----
cs2# *copy bootflash:Nexus_92300YC_RCF_v1.0.2.txt running-config*

Disabling ssh: as its enabled right now:
 generating ecdsa key(521 bits)......
generated ecdsa key

Enabling ssh: as it has been disabled
 this command enables edge port type (portfast) by default on all interfaces. You
 should now disable edge port type (portfast) explicitly on switched ports leading to hubs,
 switches and bridges as they may create temporary bridging loops.

Edge port type (portfast) should only be enabled on ports connected to a single
 host. Connecting hubs, concentrators, switches, bridges, etc...  to this
 interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
 Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet1/1 but will only
 have effect when the interface is in a non-trunking mode.

...

Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 在交換器上驗證 RCF 是否已成功合併：
+
`show running-config`

+
[listing, subs="+quotes"]
----
cs2# *show running-config*
!Command: show running-config
!Running configuration last done at: Wed Apr 10 06:32:27 2019
!Time: Wed Apr 10 06:36:00 2019

version 9.2(2) Bios:version 05.33
switchname cs2
vdc cs2 id 1
  limit-resource vlan minimum 16 maximum 4094
  limit-resource vrf minimum 2 maximum 4096
  limit-resource port-channel minimum 0 maximum 511
  limit-resource u4route-mem minimum 248 maximum 248
  limit-resource u6route-mem minimum 96 maximum 96
  limit-resource m4route-mem minimum 58 maximum 58
  limit-resource m6route-mem minimum 8 maximum 8

feature lacp

no password strength-check
username admin password 5 $5$HY9Kk3F9$YdCZ8iQJ1RtoiEFa0sKP5IO/LNG1k9C4lSJfi5kesl
6  role network-admin
ssh key ecdsa 521

banner motd #
********************************************************************************
*                                                                              *
*  Nexus 92300YC Reference Configuration File (RCF) v1.0.2 (10-19-2018)        *
*                                                                              *
*  Ports 1/1  - 1/48: 10GbE Intra-Cluster Node Ports                           *
*  Ports 1/49 - 1/64: 40/100GbE Intra-Cluster Node Ports                       *
*  Ports 1/65 - 1/66: 40/100GbE Intra-Cluster ISL Ports                        *
*                                                                              *
********************************************************************************
----
. 儲存運作配置，以便重新啟動交換器時將其作為啟動配置：
+
[listing, subs="+quotes"]
----
cs2# *copy running-config startup-config*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 對於ONTAP 9.6P8 及更高版本，請使用以下命令啟用乙太網路交換器運行狀況監視器日誌收集功能，以收集與交換器相關的日誌檔案： `system cluster-switch log setup-password`和 `system cluster-switch log enable-collection`
+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
. 重新啟動交換器並驗證運作設定是否正確：
+
`reload`

+
[listing, subs="+quotes"]
----
cs2# *reload*

This command will reboot the system. (y/n)?  [n] *y*
----

