---
permalink: switch-cisco-92300/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: 2-node switched Cisco 92300YC cluster switch migration 
summary: 如果您已有雙節點無交換器叢集環境，則可以使用Cisco Nexus 92300YC 交換器遷移到雙節點有交換器叢集環境，以便能夠將叢集擴展到兩個以上節點。 
---
= 遷移到使用Cisco Nexus 92300YC 交換器的雙節點交換集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您已經擁有一個雙節點無交換器叢集環境，則可以使用Cisco Nexus 92300YC 交換器遷移到雙節點有交換器叢集環境，從而使叢集能夠擴展到兩個節點以上。

具體操作步驟取決於每個控制器上是有兩個專用叢集網路連接埠還是只有一個叢集連接埠。記錄的過程適用於所有使用光纖或雙絞線端口的節點，但如果節點使用板載 10Gb BASE-T RJ45 端口作為集群網路端口，則此交換機不支援此過程。

大多數系統需要在每個控制器上設定兩個專用的叢集網路連接埠。


NOTE: 遷移完成後，您可能需要安裝所需的設定文件，以支援 92300YC 叢集交換器的叢集交換器健康監視器 (CSHM)。看link:../switch-cshm/cshm-overview.html["交換器健康監測 (CSHM)"]。



== 審查要求

.開始之前
請確保您擁有以下物品：

對於雙節點無交換器配置，請確保：

* 雙節點無交換器配置已正確設定並運作正常。
* 這些節點運行的是ONTAP 9.6 及更高版本。
* 叢集所有連接埠均處於*開啟*狀態。
* 所有群集邏輯介面（LIF）均處於 *up* 狀態，並位於其主連接埠上。


對於Cisco Nexus 92300YC 交換器配置：

* 兩台交換器都具備管理網路連線功能。
* 可以透過控制台存取叢集交換器。
* Nexus 92300YC 節點到節點交換器和交換器到交換器的連接使用雙絞線或光纖電纜。
+
https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe- 交換機"^]包含更多關於佈線的資訊。

* 交換器間連結 (ISL) 電纜連接到兩個 92300YC 交換器上的連接埠 1/65 和 1/66。
* 兩台 92300YC 交換器的初始客製化工作已完成。因此：
+
** 92300YC交換器運作的是最新版本的軟體。
** 參考設定檔 (RCF) 應用於交換器。任何站點自訂，如 SMTP、SNMP 和 SSH，均在新交換器上進行設定。






== 遷移交換機

.關於範例
本流程中的範例使用下列叢集交換器和節點命名規則：

* 92300YC 交換器的名稱是 cs1 和 cs2。
* 聚類SVM的名稱分別為node1和node2。
* 節點 1 上的 LIF 名稱分別為 node1_clus1 和 node1_clus2，節點 2 上的 LIF 名稱分別為 node2_clus1 和 node2_clus2。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 此過程中使用的叢集連接埠為 e0a 和 e0b。
+
https://hwu.netapp.com["Hardware Universe"^]包含您平台實際集群連接埠的最新資訊。





=== 步驟 1：準備遷移

. 將權限級別變更為高級，輸入 `y`當系統提示繼續：
+
`set -privilege advanced`

+
進階提示(`*>`出現。

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 為維護窗口的持續時間（小時）。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

+
.顯示範例
[%collapsible]
====
以下命令可抑制自動建立案件兩小時：

[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=2h*
----
====




=== 步驟 2：設定線纜和連接埠

. 停用新叢集交換器 cs1 和 cs2 上所有面向節點的連接埠（非 ISL 連接埠）。
+
您不得禁用 ISL 連接埠。

+
.顯示範例
[%collapsible]
====
以下範例顯示交換器 cs1 上面向節點的連接埠 1 到 64 已停用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e/1-64*
cs1(config-if-range)# *shutdown*
----
====
. 驗證兩個 92300YC 交換器 cs1 和 cs2 之間的 ISL 以及 ISL 上的實體連接埠在連接埠 1/65 和 1/66 上是否處於啟動狀態：
+
`show port-channel summary`

+
.顯示範例
[%collapsible]
====
以下範例表示交換器 cs1 上的 ISL 連接埠已啟動：

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
----
以下範例表示交換器 cs2 上的 ISL 連接埠已啟動：

+

[listing, subs="+quotes"]
----
(cs2)# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
----
====
. 顯示相鄰設備清單：
+
`show cdp neighbors`

+
此命令提供有關連接到系統的設備的資訊。

+
.顯示範例
[%collapsible]
====
以下範例列出了交換器 cs1 上的相鄰設備：

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2(FDO220329V5)    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 2
----
以下範例列出了交換器 cs2 上的相鄰設備：

+

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1(FDO220329KU)    Eth1/65        177    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)    Eth1/66        177    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 2
----
====
. 請確認叢集所有連接埠均已啟動：
+
`network port show -ipspace Cluster`

+
每個連接埠都應該顯示出來。 `Link`而且對身體有益 `Health Status`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. 確認所有叢集 LIF 都已啟動並正常運作：
+
`network interface show -vserver Cluster`

+
每個聚類 LIF 都應該顯示為 true `Is Home`並且擁有 `Status Admin/Oper`向上/向上

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 確認所有叢集 LIF 都已啟用自動回滾功能：
+
`network interface show -vserver Cluster -fields auto-revert`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 斷開節點 1 上的叢集連接埠 e0a 的電纜，然後使用 92300YC 交換器支援的適當電纜將 e0a 連接到叢集交換器 cs1 上的連接埠 1。
+
這 https://hwu.netapp.com/SWITCH/INDEX["硬體宇宙 - 交換機"^]包含更多關於佈線的資訊。

. 斷開節點 2 上的叢集連接埠 e0a 的電纜，然後使用 92300YC 交換器支援的適當電纜將 e0a 連接到叢集交換器 cs1 上的連接埠 2。
. 啟用叢集交換器 cs1 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示交換器 cs1 上的連接埠 1/1 到 1/64 已啟用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-64*
cs1(config-if-range)# *no shutdown*
----
====
. 驗證所有叢集 LIF 是否都已啟動、運作正常，並且顯示為 true。 `Is Home` ：
+
`network interface show -vserver Cluster`

+
.顯示範例
[%collapsible]
====
以下範例表明，節點 1 和節點 2 上的所有 LIF 都已啟動。 `Is Home`結果屬實：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. 顯示叢集中節點的狀態資訊：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集中節點的健康狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 斷開節點 1 上的叢集連接埠 e0b 的電纜，然後使用 92300YC 交換器支援的適當電纜將 e0b 連接到叢集交換器 cs2 上的連接埠 1。
. 斷開節點 2 上的叢集連接埠 e0b 的電纜，然後使用 92300YC 交換器支援的適當電纜將 e0b 連接到叢集交換器 cs2 上的連接埠 2。
. 啟用叢集交換器 cs2 上所有面向節點的連接埠。
+
.顯示範例
[%collapsible]
====
以下範例顯示交換器 cs2 上的連接埠 1/1 到 1/64 已啟用：

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-64*
cs2(config-if-range)# *no shutdown*
----
====




=== 步驟 3：驗證配置

. 請確認叢集所有連接埠均已啟動：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
以下範例顯示節點 1 和節點 2 上的所有叢集連接埠均已啟動：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====
. 驗證所有介面是否都顯示為 true `Is Home` ：
+
`network interface show -vserver Cluster`

+

NOTE: 這可能需要幾分鐘才能完成。

+
.顯示範例
[%collapsible]
====
以下範例顯示節點 1 和節點 2 上的所有 LIF 都已啟動，並且 `Is Home`結果屬實：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. 確認兩個節點都分別與每個交換器建立了一個連線：
+
`show cdp neighbors`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩種開關的正確結果：

[listing, subs="+quotes"]
----
(cs1)# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         133    H         FAS2980       e0a
node2               Eth1/2         133    H         FAS2980       e0a
cs2(FDO220329V5)    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4


(cs2)# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         133    H         FAS2980       e0b
node2               Eth1/2         133    H         FAS2980       e0b
cs1(FDO220329KU)
                    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)
                    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
====
. 顯示集群中已發現的網路設備資訊：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.
----
====
. 請確認這些設定已停用：
+
`network options switchless-cluster show`

+

NOTE: 命令可能需要幾分鐘才能完成。等待「3分鐘生命即將結束」的公告。

+
.顯示範例
[%collapsible]
====
以下範例中的錯誤輸出表示組態設定已停用：

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====
. 驗證叢集中節點成員的狀態：
+
`cluster show`

+
.顯示範例
[%collapsible]
====
以下範例顯示了叢集中節點的健康狀況和資格資訊：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[步驟8]] 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用此功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=END*
----
====
. 將權限等級改回管理員：
+
`set -privilege admin`



.下一步是什麼？
驗證完 SSH 配置後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
