---
permalink: switch-cisco-92300/migrate-to-92300yc.html 
sidebar: sidebar 
keywords: migration steps for cisco nexus 92300yc cluster switch 
summary: 您可以將ONTAP叢集的舊Cisco叢集交換器無中斷地遷移到Cisco Nexus 92300YC 叢集網路交換器。 
---
= 將Cisco交換器遷移到Cisco Nexus 92300YC 交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將ONTAP叢集的舊Cisco叢集交換器無中斷地遷移到Cisco Nexus 92300YC 叢集網路交換器。


NOTE: 遷移完成後，您可能需要安裝所需的設定文件，以支援 92300YC 叢集交換器的叢集交換器健康監視器 (CSHM)。看link:../switch-cshm/cshm-overview.html["交換器健康監測 (CSHM)"]。



== 審查要求

.開始之前
請確保您擁有以下物品：

* 一個功能齊全的現有集群。
* 節點到 Nexus 92300YC 叢集交換器的 10 GbE 和 40 GbE 連接。
* 叢集所有連接埠均處於啟用狀態，以確保運作不中斷。
* Nexus 92300YC 叢集交換器上安裝了正確版本的 NX-OS 和參考設定檔 (RCF)。
* 使用較舊的Cisco交換機構建立冗餘且功能齊全的NetApp叢集。
* 舊款Cisco交換器和新交換器的管理連線和控制台存取。
* 所有處於啟動狀態的叢集 LIF 都位於其主連接埠上。
* ISL 連接埠已啟用，並已在舊款Cisco交換器和新款交換器之間連接了線纜。




== 遷移交換機

.關於範例
本流程中的範例使用以下開關和節點命名規則：

* 現有的Cisco Nexus 5596UP 叢集交換器為 c1 和 c2。
* 新的 Nexus 92300YC 叢集交換器是 cs1 和 cs2。
* 節點分別為 node1 和 node2。
* 節點 1 上的叢集 LIF 分別為 node1_clus1 和 node1_clus2，節點 2 上的叢集 LIF 分別為 node2_clus1 和 node2_clus2。
* 首先將交換器 c2 替換為交換器 cs2，然後將交換器 c1 替換為交換器 cs1。
+
** 在 cs1 上建立臨時 ISL，將 c1 連接到 cs1。
** 然後斷開節點與 c2 之間的電纜與 c2 的連接，並重新連接到 cs2。
** 然後斷開節點與 c1 之間的電纜與 c1 的連接，並重新連接到 cs1。
** 然後移除 c1 和 cs1 之間的暫存 ISL。




.用於連接的連接埠
* Nexus 92300YC 交換器上的某些連接埠配置為以 10 GbE 或 40 GbE 運作。
* 叢集交換器使用下列連接埠連接到節點：
+
** 埠 e1/1-48 (10/25 GbE)、e1/49-64 (40/100 GbE)：Nexus 92300YC
** 埠 e1/1-40 (10 GbE)：Nexus 5596UP
** 埠 e1/1-32 (10 GbE)：Nexus 5020
** 連接埠 e1/1-12、e2/1-6 (10 GbE)：附擴充模組的 Nexus 5010


* 叢集交換器使用下列交換器間連結 (ISL) 連接埠：
+
** 埠 e1/65-66 (100 GbE)：Nexus 92300YC
** 埠 e1/41-48 (10 GbE)：Nexus 5596UP
** 埠 e1/33-40 (10 GbE)：Nexus 5020
** 埠 e1/13-20 (10 GbE)：Nexus 5010


* https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe- 交換機"^]包含所有群集交換器支援的佈線資訊。
* 本流程支援的ONTAP和 NX-OS 版本如下： https://support.netapp.com/NOW/download/software/cm_switches/["Cisco乙太網路交換機"^]頁。




=== 步驟 1：準備遷移

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 如果此叢集上啟用了AutoSupport ，則透過呼叫AutoSupport訊息來抑制自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 為維護窗口的持續時間（小時）。

+

NOTE: AutoSupport訊息會通知技術支援此維護任務，以便在維護視窗期間抑制自動建立案例。

+
.顯示範例
[%collapsible]
====
以下命令可抑制自動建立案件兩小時：

[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=2h*
----
====
. 確認所有叢集 LIF 都已啟用自動回滾功能：
+
`network interface show -vserver Cluster -fields auto-revert`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 確定每個叢集介面的管理或運作狀態：
+
每個連接埠都應該顯示出來。 `Link`而且對身體有益 `Health Status`。

+
.. 顯示網路連接埠屬性：
+
`network port show -ipspace Cluster`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====
.. 顯示有​​關邏輯介面及其指定歸屬節點的資訊：
+
`network interface show -vserver Cluster`

+
每個 LIF 都應該顯示 up/up。 `Status Admin/Oper`確實如此 `Is Home`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- -----------  ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true

4 entries were displayed.
----
====


. 使用下列命令（從節點角度）驗證每個節點上的叢集連接埠是否已以下列方式連接到現有的叢集交換器：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    c2                        0/2               N5K-C5596UP
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    c2                        0/1               N5K-C5596UP

4 entries were displayed.
----
====
. 使用以下命令驗證叢集連接埠和交換器是否以下列方式連接（從交換器的角度來看）：
+
`show cdp neighbors`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1               Eth1/1         124    H         FAS2750            e0a
node2               Eth1/2         124    H         FAS2750            e0a
c2(FOX2025GEFC)     Eth1/41        179    S I s     N5K-C5596UP        Eth1/41

c2(FOX2025GEFC)     Eth1/42        175    S I s     N5K-C5596UP        Eth1/42

c2(FOX2025GEFC)     Eth1/43        179    S I s     N5K-C5596UP        Eth1/43

c2(FOX2025GEFC)     Eth1/44        175    S I s     N5K-C5596UP        Eth1/44

c2(FOX2025GEFC)     Eth1/45        179    S I s     N5K-C5596UP        Eth1/45

c2(FOX2025GEFC)     Eth1/46        179    S I s     N5K-C5596UP        Eth1/46

c2(FOX2025GEFC)     Eth1/47        175    S I s     N5K-C5596UP        Eth1/47

c2(FOX2025GEFC)     Eth1/48        179    S I s     N5K-C5596UP        Eth1/48

Total entries displayed: 10


c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1               Eth1/1         124    H         FAS2750            e0b
node2               Eth1/2         124    H         FAS2750            e0b
c1(FOX2025GEEX)     Eth1/41        175    S I s     N5K-C5596UP        Eth1/41

c1(FOX2025GEEX)     Eth1/42        175    S I s     N5K-C5596UP        Eth1/42

c1(FOX2025GEEX)     Eth1/43        175    S I s     N5K-C5596UP        Eth1/43

c1(FOX2025GEEX)     Eth1/44        175    S I s     N5K-C5596UP        Eth1/44

c1(FOX2025GEEX)     Eth1/45        175    S I s     N5K-C5596UP        Eth1/45

c1(FOX2025GEEX)     Eth1/46        175    S I s     N5K-C5596UP        Eth1/46

c1(FOX2025GEEX)     Eth1/47        176    S I s     N5K-C5596UP        Eth1/47

c1(FOX2025GEEX)     Eth1/48        176    S I s     N5K-C5596UP        Eth1/48
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== 步驟 2：設定線纜和連接埠

. 在 c1 和 cs1 之間的連接埠 e1/41-48 上設定 cs1 上的臨時 ISL。
+
.顯示範例
[%collapsible]
====
以下範例展示如何在 c1 和 cs1 上設定新的 ISL：

[listing, subs="+quotes"]
----
cs1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/41-48*
cs1(config-if-range)# *description temporary ISL between Nexus 5596UP and Nexus 92300YC*
cs1(config-if-range)# *no lldp transmit*
cs1(config-if-range)# *no lldp receive*
cs1(config-if-range)# *switchport mode trunk*
cs1(config-if-range)# *no spanning-tree bpduguard enable*
cs1(config-if-range)# *channel-group 101 mode active*
cs1(config-if-range)# *exit*
cs1(config)# *interface port-channel 101*
cs1(config-if)# *switchport mode trunk*
cs1(config-if)# *spanning-tree port type network*
cs1(config-if)# *exit*
cs1(config)# *exit*
----
====
. 從 c2 的 e1/41-48 連接埠移除 ISL 電纜，並將電纜連接到 cs1 的 e1/41-48 連接埠。
. 驗證 ISL 連接埠和連接埠通道是否正常運作，連接 c1 和 cs1：
+
`show port-channel summary`

+
.顯示範例
[%collapsible]
====
以下範例顯示如何使用Cisco show port-channel summary 指令來驗證 c1 和 cs1 上的 ISL 連接埠是否正常運作：

[listing, subs="+quotes"]
----
c1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)


cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
101   Po101(SU)   Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)
----
====
. 對於節點 1，斷開 c2 上的 e1/1 電纜，然後使用 Nexus 92300YC 支援的適當電纜將電纜連接到 cs2 上的 e1/1。
. 對於節點 2，斷開 c2 上的 e1/2 電纜，然後使用 Nexus 92300YC 支援的適當電纜將電纜連接到 cs2 上的 e1/2。
. 從節點的角度來看，每個節點上的叢集連接埠現在會以以下方式連接到叢集交換器：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.
----
====
. 對於節點 1，斷開 c1 上的 e1/1 電纜，然後使用 Nexus 92300YC 支援的適當電纜將電纜連接到 cs1 上的 e1/1。
. 對於節點 2，斷開 c1 上的 e1/2 的電纜，然後使用 Nexus 92300YC 支援的適當電纜將電纜連接到 cs1 上的 e1/2。
. 從節點的角度來看，每個節點上的叢集連接埠現在會以以下方式連接到叢集交換器：
+
`network device-discovery show -protocol cdp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC
4 entries were displayed.
----
====
. 刪除 cs1 和 c1 之間的暫存 ISL。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1(config)# *no interface port-channel 10*
cs1(config)# *interface e1/41-48*
cs1(config-if-range)# *lldp transmit*
cs1(config-if-range)# *lldp receive*
cs1(config-if-range)# *no switchport mode trunk*
cs1(config-if-range)# *no channel-group*
cs1(config-if-range)# *description 10GbE Node Port*
cs1(config-if-range)# *spanning-tree bpduguard enable*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
====




=== 步驟 3：完成遷移

. 驗證叢集的最終配置：
+
`network port show -ipspace Cluster`

+
每個連接埠都應該顯示出來。 `Link`而且對身體有益 `Health Status`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.


cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.


cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         124    H         FAS2750            e0a
node2               Eth1/2         124    H         FAS2750            e0a
cs2(FDO220329V5)    Eth1/65        179    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        179    R S I s   N9K-C92300YC  Eth1/66


cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         124    H         FAS2750            e0b
node2               Eth1/2         124    H         FAS2750            e0b
cs1(FDO220329KU)
                    Eth1/65        179    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)
                    Eth1/66        179    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
====
. 驗證遠端集群介面的連接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`執行命令以啟動叢集連接性檢查，然後顯示詳細資訊：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*運行程式前請等待幾秒鐘 `show`顯示詳細資訊的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
對於所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`檢查連接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[步驟3]] 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用此功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=END*
----
====
. 將權限等級改回管理員：
+
`set -privilege admin`



.下一步是什麼？
link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
