---
permalink: switch-cisco-92300/migrate-to-92300yc.html 
sidebar: sidebar 
keywords: migration steps for cisco nexus 92300yc cluster switch 
summary: 您可以將不中斷營運的舊Cisco叢集交換器移轉至ONTAP Cisco Nexus 92300YC叢集網路交換器、以供支援使用。 
---
= 從Cisco交換器移轉至Cisco Nexus 2300YC交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將不中斷營運的舊Cisco叢集交換器移轉至ONTAP Cisco Nexus 92300YC叢集網路交換器、以供支援使用。


NOTE: 移轉完成後、您可能需要安裝所需的組態檔、以支援適用於92300YC叢集交換器的叢集交換器健全狀況監視器（CSHM）。請參閱link:setup-install-cshm-file.html["安裝叢集交換器健全狀況監視器（CSHM）"]。



== 檢閱要求

.您需要的產品
* 完整功能的現有叢集。
* 從節點到Nexus 2300YC叢集交換器的10 GbE和40 GbE連線能力。
* 所有叢集連接埠都處於「up」狀態、以確保不中斷營運。
* Nexus 2300YC叢集交換器上安裝的NX-OS適當版本和參考組態檔（RCF）。
* 使用兩個舊Cisco交換器的備援且功能完整的NetApp叢集。
* 管理連線能力、以及對舊Cisco交換器和新交換器的主控台存取。
* 使用叢集生命區的所有叢集生命區都位於主連接埠上。
* 在舊的Cisco交換器之間以及新交換器之間啟用或連接ISL連接埠。




== 移轉交換器

.關於範例
本程序中的範例使用下列交換器和節點命名法：

* 現有的Cisco Nexus 5596UP叢集交換器為C1和C2。
* 新的Nexus 2300YC叢集交換器為CS1和CS2。
* 節點是node1和node2。
* 叢集lIF分別是節點1上的node1_clus1和node1_clus2、以及節點2上的node2_clus1和node2_clus2。
* 交換器C2先由交換器CS2取代、然後由交換器CS1取代交換器C1。
+
** 將C1連接至CS1的CS1上建置了暫時ISL。
** 然後從C2中斷連接節點與C2之間的纜線、並重新連接至CS2。
** 然後、節點與C1之間的纜線會從C1中斷連線、然後重新連線至CS1。
** 然後移除C1與CS1之間的暫用ISL。




.用於連線的連接埠
* 有些連接埠是在Nexus 2300YC交換器上設定、以10 GbE或40 GbE執行。
* 叢集交換器使用下列連接埠來連線至節點：
+
** 連接埠E1/1-48（10/25 GbE）、E1/49-64（40/100 GbE）：Nexus 2300YC
** 連接埠E1/1-40（10 GbE）：Nexus 5596UP
** 連接埠E1/1-32（10 GbE）：Nexus 5020
** 連接埠E1/1-12、2/1-6（10 GbE）：Nexus 5010、含擴充模組


* 叢集交換器使用下列交換器間連結（ISL）連接埠：
+
** 連接埠E1/65-66（100 GbE）：Nexus 92300YC
** 連接埠E1/41至48（10 GbE）：Nexus 5596UP
** 連接埠E1/33-40（10 GbE）：Nexus 5020
** 連接埠E1/13-20（10 GbE）：Nexus 5010


* https://hwu.netapp.com/SWITCH/INDEX["交換器Hardware Universe"^] 包含所有叢集交換器支援的纜線連接資訊。
* 本程序所支援的支援的支援版本包括ONTAP https://support.netapp.com/NOW/download/software/cm_switches/["Cisco乙太網路交換器"^] 頁面。




=== 步驟1：準備移轉

. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
"進階權限"

+
出現進階提示（*>）。

. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -Message MAn=xh」

+
其中x是維護時段的持續時間（以小時為單位）。

+

NOTE: 此資訊可通知技術支援人員執行此維護工作、以便在維護期間抑制自動建立案例。AutoSupport

+
.顯示範例
[%collapsible]
====
下列命令會禁止自動建立兩小時的個案：

[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=2h*
----
====
. 驗證是否已在所有叢集生命體上啟用自動還原：
+
「網路介面show -vserver叢集-功能 變數自動回復」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 判斷每個叢集介面的管理或作業狀態：
+
每個連接埠應顯示「Link」（連結）、「Health Status」（健全狀況狀態）則顯示為「Healthy」（健全狀況）。

+
.. 顯示網路連接埠屬性：
+
「網路連接埠show -IPSpace Cluster」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====
.. 顯示有關邏輯介面及其指定主節點的資訊：
+
「網路介面show -vserver叢集」

+
每個LIF都應顯示為「狀態管理/作業者」、而「IS主頁」則顯示為「真」。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- -----------  ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true

4 entries were displayed.
----
====


. 使用命令、驗證每個節點上的叢集連接埠是否以下列方式（從節點的觀點）連接至現有的叢集交換器：
+
「network device-dDiscovery show -protocol cup」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    c2                        0/2               N5K-C5596UP
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    c2                        0/1               N5K-C5596UP

4 entries were displayed.
----
====
. 使用命令確認叢集連接埠和交換器的連線方式如下（從交換器的觀點來看）：
+
「How cup neighbor」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1               Eth1/1         124    H         FAS2750            e0a
node2               Eth1/2         124    H         FAS2750            e0a
c2(FOX2025GEFC)     Eth1/41        179    S I s     N5K-C5596UP        Eth1/41

c2(FOX2025GEFC)     Eth1/42        175    S I s     N5K-C5596UP        Eth1/42

c2(FOX2025GEFC)     Eth1/43        179    S I s     N5K-C5596UP        Eth1/43

c2(FOX2025GEFC)     Eth1/44        175    S I s     N5K-C5596UP        Eth1/44

c2(FOX2025GEFC)     Eth1/45        179    S I s     N5K-C5596UP        Eth1/45

c2(FOX2025GEFC)     Eth1/46        179    S I s     N5K-C5596UP        Eth1/46

c2(FOX2025GEFC)     Eth1/47        175    S I s     N5K-C5596UP        Eth1/47

c2(FOX2025GEFC)     Eth1/48        179    S I s     N5K-C5596UP        Eth1/48

Total entries displayed: 10


c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1               Eth1/1         124    H         FAS2750            e0b
node2               Eth1/2         124    H         FAS2750            e0b
c1(FOX2025GEEX)     Eth1/41        175    S I s     N5K-C5596UP        Eth1/41

c1(FOX2025GEEX)     Eth1/42        175    S I s     N5K-C5596UP        Eth1/42

c1(FOX2025GEEX)     Eth1/43        175    S I s     N5K-C5596UP        Eth1/43

c1(FOX2025GEEX)     Eth1/44        175    S I s     N5K-C5596UP        Eth1/44

c1(FOX2025GEEX)     Eth1/45        175    S I s     N5K-C5596UP        Eth1/45

c1(FOX2025GEEX)     Eth1/46        175    S I s     N5K-C5596UP        Eth1/46

c1(FOX2025GEEX)     Eth1/47        176    S I s     N5K-C5596UP        Eth1/47

c1(FOX2025GEEX)     Eth1/48        176    S I s     N5K-C5596UP        Eth1/48
----
====
. 使用以下命令驗證叢集網路是否具備完整連線能力：
+
「叢集ping叢集節點節點名稱」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====




=== 步驟2：設定纜線和連接埠

. 在連接埠E1/41-48（C1與CS1之間）的cs1on上設定暫用ISL。
+
.顯示範例
[%collapsible]
====
下列範例顯示如何在C1和CS1上設定新的ISL：

[listing, subs="+quotes"]
----
cs1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/41-48*
cs1(config-if-range)# *description temporary ISL between Nexus 5596UP and Nexus 92300YC*
cs1(config-if-range)# *no lldp transmit*
cs1(config-if-range)# *no lldp receive*
cs1(config-if-range)# *switchport mode trunk*
cs1(config-if-range)# *no spanning-tree bpduguard enable*
cs1(config-if-range)# *channel-group 101 mode active*
cs1(config-if-range)# *exit*
cs1(config)# *interface port-channel 101*
cs1(config-if)# *switchport mode trunk*
cs1(config-if)# *spanning-tree port type network*
cs1(config-if)# *exit*
cs1(config)# *exit*
----
====
. 從C2的連接埠E1/41至48拔下ISL纜線、並將纜線連接至CS1的連接埠E1/41至48。
. 確認ISL連接埠和連接埠通道可正常運作、連接C1和CS1：
+
「How port-channel Summary」

+
.顯示範例
[%collapsible]
====
下列範例顯示Cisco show port-channel摘要命令、用於驗證C1和CS1上的ISL連接埠是否正常運作：

[listing, subs="+quotes"]
----
c1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)


cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
101   Po101(SU)   Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)
----
====
. 對於節點1、請從C2上的E1/1拔下纜線、然後使用Nexus 2300YC支援的適當纜線、將纜線連接至CS2上的E1/1。
. 對於節點2、請從C2上的E1/2拔下纜線、然後使用Nexus 2300YC支援的適當纜線、將纜線連接至CS2上的E1/2。
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：
+
「network device-dDiscovery show -protocol cup」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.
----
====
. 對於節點1、請從C1上的E1/1拔下纜線、然後使用Nexus 2300YC支援的適當纜線、將纜線連接至CS1上的E1/1。
. 對於節點2、請從C1上的E1/2拔下纜線、然後使用Nexus 2300YC支援的適當纜線、將纜線連接至CS1上的E1/2。
. 從節點的觀點來看、每個節點上的叢集連接埠現在都以下列方式連接至叢集交換器：
+
「network device-dDiscovery show -protocol cup」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC
4 entries were displayed.
----
====
. 刪除CS1和C1之間的暫用ISL。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1(config)# *no interface port-channel 10*
cs1(config)# *interface e1/41-48*
cs1(config-if-range)# *lldp transmit*
cs1(config-if-range)# *lldp receive*
cs1(config-if-range)# *no switchport mode trunk*
cs1(config-if-range)# *no channel-group*
cs1(config-if-range)# *description 10GbE Node Port*
cs1(config-if-range)# *spanning-tree bpduguard enable*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
====




=== 步驟3：完成移轉

. 驗證叢集的最終組態：
+
「網路連接埠show -IPSpace Cluster」

+
每個連接埠應顯示「Link」（連結）、「Health Status」（健全狀況狀態）則顯示為「Healthy」（健全狀況）。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.


cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.


cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         124    H         FAS2750            e0a
node2               Eth1/2         124    H         FAS2750            e0a
cs2(FDO220329V5)    Eth1/65        179    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        179    R S I s   N9K-C92300YC  Eth1/66


cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         124    H         FAS2750            e0b
node2               Eth1/2         124    H         FAS2750            e0b
cs1(FDO220329KU)
                    Eth1/65        179    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)
                    Eth1/66        179    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
====
. 驗證叢集網路是否具備完整連線能力：
+
「叢集ping叢集節點節點名稱」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *set -priv advanced*

Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by NetApp personnel.
Do you want to continue? {y|n}: *y*

cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)


cluster1::*> *set -privilege admin*
cluster1::*>
----
====


.接下來呢？
link:../switch-cshm/config-overview.html["設定交換器健全狀況監控"]
