---
permalink: switch-cisco-92300/required-documentation-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 對於Cisco Nexus 2300YC交換器的安裝與維護、請務必檢閱所有建議的文件。 
---
= Cisco Nexus 2300YC交換器的文件需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於Cisco Nexus 2300YC交換器的安裝與維護、請務必檢閱所有建議的文件。



== 交換器文件

若要設定Cisco Nexus 2300YC交換器、您需要提供下列文件 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000系列交換器支援"^] 頁面：

[cols="1,2"]
|===
| 文件標題 | 說明 


 a| 
_Nexus 9000系列硬體安裝指南_
 a| 
提供有關站台需求、交換器硬體詳細資料及安裝選項的詳細資訊。



 a| 
_Cisco Nexus 9000系列交換器軟體組態指南_（請選擇您交換器上安裝的NX-OS版本指南）
 a| 
提供您需要的初始交換器組態資訊、然後才能設定交換器ONTAP 以供執行故障操作。



 a| 
_Cisco Nexus 9000系列NX-OS軟體升級與降級指南_（請針對安裝在交換器上的NX-OS版本選擇指南）
 a| 
如ONTAP 有必要、提供如何將交換器降級至支援的交換器軟體的相關資訊。



 a| 
_Cisco Nexus 9000系列NX-OS命令參考主索引_
 a| 
提供Cisco所提供之各種命令參考資料的連結。



 a| 
_Cisco Nexus 9000 MIBs參考資料_
 a| 
說明Nexus 9000交換器的管理資訊庫（MIB）檔案。



 a| 
_Nexus 9000系列NX-OS系統訊息參考_
 a| 
說明Cisco Nexus 9000系列交換器的系統訊息、資訊訊息、以及其他可能有助於診斷連結、內部硬體或系統軟體問題的訊息。



 a| 
_Cisco Nexus 9000系列NX-OS版本資訊（請選擇安裝在交換器上的NX-OS版本附註）_
 a| 
說明Cisco Nexus 9000系列的功能、錯誤和限制。



 a| 
Cisco Nexus 9000系列的法規遵循與安全資訊
 a| 
提供Nexus 9000系列交換器的國際機構法規遵循、安全及法規資訊。

|===


== 系統文件ONTAP

要設定 ONTAP 系統，您需要以下適用於您的作業系統版本的文檔 https://docs.netapp.com/ontap-9/index.jsp["功能9. ONTAP"^] 。

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
控制器專屬的安裝與設定指示_
 a| 
說明如何安裝NetApp硬體。



 a| 
本文檔 ONTAP
 a| 
提供ONTAP 有關這些版本的所有方面的詳細資訊。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
提供NetApp硬體組態與相容性資訊。

|===


== 軌道套件與機櫃文件

若要在NetApp機櫃中安裝Cisco Nexus 2300YC交換器、請參閱下列硬體文件。

[cols="1,2"]
|===
| 名稱 | 說明 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U系統機櫃、深度指南"^]
 a| 
說明與42U系統機櫃相關的FRU、並提供維護與FRU更換指示。



 a| 
link:install-cisco-nexus-3132qv.html["[在NetApp機櫃中安裝Cisco Nexus 2300YC交換器"]
 a| 
說明如何在四柱NetApp機櫃中安裝Cisco Nexus 2300YC交換器。

|===