---
permalink: switch-cshm/config-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 設定日誌收集，使 CSHM 能夠從叢集和儲存網路交換器收集交換器日誌和診斷資料。 
---
= 設定乙太網路交換器健全狀況監控的日誌收集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定乙太網路交換器的日誌收集功能，使乙太網路交換器健全狀況監視器 （CSHM） 能夠收集交換器日誌以進行偵錯和 AutoSupport 報告。此程序將在 ONTAP 中設定按需支援日誌收集和每小時定期資料收集。

.開始之前
* 如果使用 FIPS 模式，請在設定日誌收集之前完成以下步驟：
+
.. 依照廠商提供的說明，在交換器上重新產生 SSH 金鑰。
.. 使用  `debug system regenerate-systemshell-key-pair` 在 ONTAP 中重新產生 SSH 金鑰。
.. 使用 `system switch ethernet log setup-password`命令重新執行日誌收集設定。


* 您必須擁有交換器 `show`命令的存取權限。如果沒有，請建立新的交換器使用者並授予其必要的權限。
* 必須為交換器啟用交換器健全狀況監控。透過檢查 `Is Monitored:`欄位在 `system switch ethernet show`輸出中是否設為 *true* 來驗證。
* 用於收集博通和Cisco交換器的日誌：
+
** 本機使用者必須具有網路管理員權限。
** 為每個啟用日誌收集的叢集建立一個新的交換器使用者。這些交換器不支援相同使用者使用多個 SSH 金鑰，再次執行設定會覆寫現有的 SSH 金鑰。


* 為了支援使用 NVIDIA 交換器進行日誌收集，日誌收集使用者必須能夠在不需要密碼的情況下執行 `cl-support`命令。若要允許此操作，請執行：
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`



.步驟
依照適用於您的 ONTAP 版本的步驟設定日誌收集、啟用定期資料收集，並可選擇性地要求隨需支援日誌。

[role="tabbed-block"]
====
.ONTAP 9.15.1 及更高版本
--
. 若要設定日誌收集，請對每個交換器執行以下命令。系統會提示您輸入用於日誌收集的交換器名稱、使用者名稱和密碼。
+
*注意：* 如果對使用者規範提示回答 *y*，請確保使用者擁有必要的權限，如下所述：<<開始之前>> 。

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: 對於 CL 5.11.1，建立使用者 *cumulus* 並對以下提示回答 *y*：您是否要指定 admin 以外的使用者進行日誌收集？  {y|n}: *y*

. 步驟2：啟用定期日誌收集。
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. 請求支援日誌收集：
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. 要查看日誌收集的所有詳細信息，包括定期收集的啟用情況、狀態訊息、上一個時間戳和文件名，以及支援收集的請求狀態、狀態訊息、上一個時間戳和文件名，請使用以下命令：
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 及更早版本
--
. 若要設定日誌收集，請對每個交換器執行以下命令。系統會提示您輸入用於日誌收集的交換器名稱、使用者名稱和密碼。
+
*注意：* 如果回答 `y`根據使用者規格提示，確保使用者擁有必要的權限，具體權限要求請參閱相關文件。<<開始之前>> 。

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: 對於 CL 5.11.1，建立使用者 *cumulus* 並對以下提示回答 *y*：您是否要指定 admin 以外的使用者進行日誌收集？  {y|n}: *y*

. [[step2]] 若要要求支援日誌收集並啟用定期收集，請執行下列命令。這將啟動兩種類型的日誌收集：詳細日誌收集和詳細日誌收集。 `Support`日誌和每小時收集的數據 `Periodic`數據。
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
等待 10 分鐘，然後檢查日誌收集是否完成：

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: 如果日誌收集功能報告任何錯誤狀態（在 `system switch ethernet log show`的輸出中可見），請參閱link:log-collection-troubleshoot.html["排查日誌收集問題"]以取得更多詳細資訊。

.下一步是什麼？
link:config-snmpv3.html["配置 SNMPv3（可選）"]。
