---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: 瞭解如何手動建立，變更預設監控設定，以及從監控中刪除乙太網路交換器。 
---
= 管理乙太網路交換器的監控
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在大多數情況下， ONTAP 會自動探索乙太網路交換器，並由 CSHM 監控。套用至交換器的參考組態檔（ RCF ），除其他外，可啟用 Cisco 探索傳輸協定（ CDP ）和 / 或連結層探索傳輸協定（ LLDP ）。不過，您可能需要手動新增未發現的交換器，或移除不再使用的交換器。您也可以停止主動監控，同時將交換器保留在組態中，例如在維護期間。



== 建立交換器項目，讓 ONTAP 能夠監控

使用 `system switch ethernet create`命令手動設定及啟用指定乙太網路交換器的監控。如果 ONTAP 未自動新增交換器，或您先前已移除交換器並想要重新新增交換器，這項功能就很實用。

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
典型的例子是新增一個名為 [DeviceName] 的交換器， IP 位址為 1.2.3.4 ，而 SNMPv2c 認證設定為 *cshm1!* 。如果您正在設定儲存交換器，請改 `-type cluster-network`用 `-type storage-network`。



== 停用監控，但不刪除交換器

如果您想要暫停或停止監控某個交換器，但仍保留它以供未來監控，請修改其 `is-monitoring-enabled-admim`參數而非刪除它。

例如：

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
這可讓您保留交換器的詳細資料和組態，而無需產生新警示或重新探索。



== 移除不再需要的交換器

用於 `system switch ethernet delete`刪除已中斷連線或不再需要的交換器：

[source, cli]
----
system switch ethernet delete -device DeviceName
----
根據預設，只有在 ONTAP 目前未透過 CDP 或 LLDP 偵測到交換器時，此命令才會成功。若要移除探索到的交換器，請使用 `-force`參數：

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
 `-force`使用時，如果 ONTAP 再次偵測到交換器，可能會自動重新新增交換器。
