---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: 您可以將ONTAP叢集中較舊的Cisco交換器無中斷地遷移到NVIDIA SN2100 儲存交換器。 
---
= 將儲存交換器從Cisco)移轉到NVIDIA) SN2100 儲存交換機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將ONTAP叢集中較舊的Cisco交換器遷移到NVIDIA SN2100 儲存交換器。這是一個非破壞性的過程。



== 審查要求

支援以下儲存交換器：

* CiscoNexus 9336C-FX2
* CiscoNexus 3232C
* 參見 https://hwu.netapp.com/["Hardware Universe"^]有關支援的連接埠及其配置的完整詳細資訊。


.開始之前
確保您具有以下各項：

* 現有叢集已正確設定並正常運作。
* 所有儲存連接埠均處於開啟狀態，以確保運作不會中斷。
* NVIDIA SN2100 儲存交換器已設定並運行在正確版本的 Cumulus Linux 下，並應用了參考設定檔 (RCF)。
* 現有儲存網路配置如下：
+
** 使用較舊的Cisco交換機構建立冗餘且功能齊全的NetApp叢集。
** 舊款Cisco交換器和新交換器的管理連線和控制台存取。
** 所有處於啟動狀態的叢集 LIF 都位於其主連接埠上。
** ISL 連接埠已啟用，並已在舊款Cisco交換器和新款交換器之間連接了線纜。


* 參見 https://hwu.netapp.com/["Hardware Universe"^]有關支援的連接埠及其配置的完整詳細資訊。
* NVIDIA SN2100 交換器上的一些連接埠配置為以 100 GbE 運作。
* 您已規劃、遷移並記錄了從節點到NVIDIA SN2100 儲存交換器的 100 GbE 連線。




== 遷移交換機

.關於範例
在此過程中，使用Cisco Nexus 9336C-FX2 儲存交換器作為範例指令和輸出。

本流程中的範例使用以下開關和節點命名規則：

* 現有的Cisco Nexus 9336C-FX2 儲存交換器型號為 _S1_ 和 _S2_。
* 新的NVIDIA SN2100 儲存交換器型號為 _sw1_ 和 _sw2_。
* 節點分別為 _node1_ 和 _node2_。
* 節點 1 上的叢集 LIF 分別為 _node1_clus1_ 和 _node1_clus2_，節點 2 上的叢集 LIF 分別為 _node2_clus1_ 和 _node2_clus2_。
* 這 `cluster1::*>`prompt 指示叢集名稱。
* 此過程中使用的網路連接埠為_e5a_和_e5b_。
* 分支端口採用以下格式：swp1s0-3。例如，swp1 上的四個分支連接埠分別是 _swp1s0_、_swp1s1_、_swp1s2_ 和 _swp1s3_。
* 首先將交換器 S2 替換為交換器 sw2，然後將交換器 S1 替換為交換器 sw1。
+
** 然後斷開節點與 S2 之間的電纜與 S2 的連接，並重新連接到 sw2。
** 然後斷開節點與 S1 之間的電纜與 S1 的連接，並重新連接到 sw1。






=== 步驟 1：準備遷移

. 如果啟用了AutoSupport，則透過呼叫AutoSupport訊息來阻止自動建立案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 為維護視窗的持續時間（小時）。

. 將權限級別變更為高級，並在提示繼續時輸入 *y*：
+
`set -privilege advanced`

+
出現高階提示符號（*>）。

. 確定每個儲存介面的管理或運作狀態：
+
每個連接埠都應顯示為已啟用。 `Status` 。





=== 步驟 2：設定線纜和連接埠

. 顯示網路連接埠屬性：
+
`storage port show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 使用下列命令（從節點角度）驗證每個節點上的儲存連接埠是否已以下列方式連接到現有儲存交換器：
+
`network device-discovery show -protocol lldp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. 在交換器 S1 和 S2 上，使用下列命令確保儲存連接埠和交換器以下列方式連接（從交換器的角度來看）：
+
`show lldp neighbors`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. 在交換器 sw2 上，關閉連接到磁碟櫃儲存連接埠和節點的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 將控制器和磁碟機櫃的節點儲存連接埠從舊交換器 S2 移至新交換器 sw2，使用NVIDIA SN2100 支援的適當電纜。
. 在交換器 sw2 上，啟動連接到節點儲存連接埠和磁碟櫃的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 從節點的角度來看，請確認每個節點上的儲存連接埠現在是否以下列方式連接到交換器：
+
`network device-discovery show -protocol lldp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. 請驗證網路連接埠屬性：
+
`storage port show`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 在交換器 sw2 上，確認所有節點儲存連接埠均已啟動：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 在交換器 sw1 上，關閉連接到節點和磁碟機儲存連接埠的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 使用NVIDIA SN2100 支援的適當線纜，將控制器的節點儲存連接埠和磁碟機櫃從舊交換器 S1 移至新交換器 sw1。
. 在交換器 sw1 上，啟動連接到節點儲存連接埠和磁碟櫃的連接埠。
+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 從節點的角度來看，請確認每個節點上的儲存連接埠現在是否以下列方式連接到交換器：
+
`network device-discovery show -protocol lldp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== 步驟 3：驗證配置

. 驗證最終配置：
+
`storage port show`

+
每個連接埠都應顯示為已啟用。 `State`並已啟用 `Status`。

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 在交換器 sw2 上，確認所有節點儲存連接埠均已啟動：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 確認兩個節點都分別與每個交換器建立了一個連線：
+
`net show lldp`

+
.顯示範例
[%collapsible]
====
以下範例顯示了兩種開關的正確結果：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. 將權限等級改回管理員：
+
`set -privilege admin`

. 如果您已停用自動建立案例功能，請透過呼叫AutoSupport訊息重新啟用該功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什麼？
交換器遷移完成後，您可以… link:../switch-cshm/config-overview.html["配置交換器健康監控"]。
