---
permalink: switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia sn2100 cluster switch - nvidia SN2100 
summary: 在不中斷營運的程序中更換有瑕疵的NVIDIA SN2100儲存交換器（NDU）。 
---
= 更換NVIDIA SN2100儲存交換器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更換有瑕疵的NVIDIA SN2100儲存交換器。這是不中斷營運的程序。

.開始之前
在NVIDIA SN2100儲存交換器上安裝Cummulos軟體和RCFs之前、請確保：

* 您的系統可支援NVIDIA SN2100儲存交換器。
* 您已下載適用的RCT。


。 http://hwu.netapp.com["Hardware Universe"^] 提供支援連接埠及其組態的完整詳細資料。

現有的網路組態必須具有下列特性：

* 請確定已完成所有疑難排解步驟、以確認您的交換器需要更換。
* 兩台交換器都必須具備管理連線能力。
+

NOTE: 請確定已完成所有疑難排解步驟、以確認您的交換器需要更換。



替換的NVIDIA SN2100交換器必須具備下列特性：

* 管理網路連線功能正常。
* 更換交換器的主控台存取已就緒。
* 適當的RCF和Cummulis作業系統映像會載入交換器。
* 交換器的初始自訂已完成。


.程序摘要
此程序將第二個NVIDIA SN2100儲存交換器SW2取代為新的NVIDIA SN2100交換器nsw2。這兩個節點分別是node1和node2。

完成步驟：

* 確認要更換的交換器為SW2。
* 從交換器SW2拔下纜線。
* 將纜線重新連接至交換器nsw2。
* 確認交換器nsw2上的所有裝置組態。


.步驟
. 如果AutoSupport 此叢集啟用了「支援」功能、請叫用AutoSupport 下列訊息來禁止自動建立案例：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -訊息MAn=xh」

+
_x_是維護時段的持續時間（以小時為單位）。

. 將權限等級變更為進階、並在系統提示您繼續時輸入* y*：
+
"進階權限"

. 檢查儲存節點連接埠的健全狀況、確定已連線至儲存交換器S1：
+
「torage port show -port-type ENET」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. 確認儲存交換器sw1可用：
+
`network device-discovery show -protocol lldp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. 執行 `net show interface` 在工作交換器上執行命令、確認您可以同時看到節點和所有磁碟櫃：
+
`net show interface`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----

cumulus@sw1:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e3a)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e3a)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 驗證儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device, remote-port`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   swp3          sw1
3.20    1   -             -
3.20    2   swp4          sw1
3.20    3   -             -
3.30    0   swp5          sw1
3.20    1   -             -
3.30    2   swp6          sw1
3.20    3   -             -
cluster1::*>
----
====
. 拔下連接至儲存交換器SW2的所有纜線。
. 將所有纜線重新連接至更換的交換器nsw2。
. 重新檢查儲存節點連接埠的健全狀況：
+
「torage port show -port-type ENET」

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage 100    enabled  online      30
cluster1::*>
----
====
. 確認兩個交換器都可用：
+
`net device-discovery show -protocol lldp`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----

cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1/lldp
            e0M    sw1 (00:ea:bd:68:6a:e8)   Eth1/46           -
            e0b    sw2 (6c:b2:ae:5f:a5:b2)   Ethernet1/16      -
            e0c    SHFFG1827000286 (d0:39:ea:1c:16:92)
                                             e0a               -
            e0e    sw3 (6c:b2:ae:5f:a5:ba)   Ethernet1/18      -
            e0f    SHFFG1827000286 (00:a0:98:fd:e4:a9)
                                             e0b               -
            e0g    sw4 (28:ac:9e:d5:4a:9c)   Ethernet1/11      -
            e0h    sw5 (6c:b2:ae:5f:a5:ca)   Ethernet1/22      -
            e1a    sw6 (00:f6:63:10:be:7c)   Ethernet1/33      -
            e1b    sw7 (00:f6:63:10:be:7d)   Ethernet1/34      -
            e2a    sw8 (b8:ce:f6:91:3d:88)   Ethernet1/35      -
Press <space> to page down, <return> for next line, or 'q' to quit...
10 entries were displayed.
----
====
. 驗證儲存系統中的機櫃連接埠：
+
`storage shelf port show -fields remote-device, remote-port`

+
.顯示範例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device, remote-port*
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     swp3            sw1
3.20    1     swp3            nsw2
3.20    2     swp4            sw1
3.20    3     swp4            nsw2
3.30    0     swp5            sw1
3.20    1     swp5            nsw2
3.30    2     swp6            sw1
3.20    3     swp6            nsw2
cluster1::*>
----
====
. 將權限層級變更回管理：
+
「et -priv. admin」

. 如果您禁止自動建立個案、請叫用AutoSupport 下列訊息來重新啟用：
+
「系統節點AutoSupport 不完整地叫用節點*-type all -most MAn=end」



.接下來呢？
link:../switch-cshm/config-overview.html["設定交換器健全狀況監控"]。
